### ISSUE TITLE
Tax_glom different result than get_taxa_unique

### ISSUE THREAD

**Issue by TaylerChicoine** [joey711/phyloseq#1003]
Hello, 

I am trying to refine my taxonomic resolution to genus level, e.g. combining all species that are into the same genus into one taxa. 

When I use get_taxa_unique, it reports that I have 715 unique genra: (uniqueGenra <- get_taxa_unique(rhizo.rfy_nosingles, taxonomic.rank = "Genus", errorIfNULL = FALSE)

However, when I try to use tax_glom to merge all of these unique genera, I end up with a different final number, 869:  (rhizo.rfy_nosingles_genra = tax_glom(rhizo.rfy_nosingles, "Genus"). 

Can someone explain why this might be? 

Thank you!

**Comment by waleadebayo** [comment]
Am not an expert, but it may not be surprising to me when I see this. 
In  > get taxa_unique, you never get unclassified genera such as where it was not identified up to actual genus level, as in the hierarchy is still as family level for instance f , 
whereas  >tax_glom picks up anybody at the rank you want in the data.

Did you inspect the list?
