### ISSUE TITLE
Prune tree by node labels

### ISSUE THREAD

**Issue by claireonthecouch** [joey711/phyloseq#1007]
We have used the ClaaTu workflow (https://github.com/chrisgaulke/Claatu) to identify conserved nodes across our sample set. We are interested in applying downstream analyses in phyloseq using only taxa that belong to the conserved nodes. I have a list of the conserved nodes that corresponds to the node labels in the phylogenetic tree. How can I prune a phyloseq tree by node label?

**Comment by cjfields** [comment]
By node label, do you mean leaves (e.g. OTU IDs)?  If so look into `prune_taxa`.

**Comment by claireonthecouch** [comment]
No, I mean the nodes as in the branch points on the tree.
Claire E. Couch
NSF Graduate Fellow
Department of Integrative Biology
Oregon State University

**Comment by joey711** [comment]
@claireonthecouch This feature is not explicitly supported in phyloseq. You will need to use tools that manipulate phylogenetic trees in this way, and then `merge_phyloseq()` or `phyloseq()` them with your other data objects. See the ape, treeio, or ggtree packages for examples.
