### ISSUE TITLE
Issue with removing low abundance taxa

### ISSUE THREAD

**Issue by jsan4christ** [joey711/phyloseq#1008]
Hi,

I'm just going through https://f1000research.com/articles/5-1492/v2 again,

_Deinococcus-Thermus appeared in just over one percent of samples,_ and Fusobacteria appeared in just 2 samples total. 

Deinococcus-Thermus has the values below for mean and sum of prevalence, 
## 5           Deinococcus-Thermus    52.0     52

The total number of samples in the object is 360. Obviously, 52 is not 1% of 360, so my conclusion is that you are multiplying this by the sample variables, but then that does not seem right to me. 

For my dataset, I have results like this and would like to be sure about how your rule Deinococcus-Thermus;
                Phylum         1     2
1        Acidobacteria  1.000000     1
2       Actinobacteria 12.370242  7150
3        Bacteroidetes  5.860000  3223
4           Chlamydiae  2.222222    20
5          Chloroflexi  1.000000     3
6        Cyanobacteria  1.000000     3
7  Deinococcus-Thermus  1.000000     2

For Fusobacteria, it is clear to me that it appears in two samples. Would I be right to conclude that chloroflexi and cyanobacteria only appear once in 3 samples and should therefore be filtered out?

Thanks,

**Comment by joey711** [comment]
Can you show the code that is producing these outputs that you don't trust? 
Did you already solve your problem / answer your question?

I will close for now. Please feel free to clarify if still a problem...
