### ISSUE TITLE
estimate_richness suddenly stopped working

### ISSUE THREAD

**Issue by amusheg** [joey711/phyloseq#1009]
Hello,
I was just running a script I've run many times to re-generate figures and am getting an error I've never gotten before with estimate_richness:
```
Error in uniroot(d1fun, c(1, 50), extendInt = "upX", S = S, N = N, ...) : 
  did not succeed extending the interval endpoints for f(lower) * f(upper) <= 0
In addition: Warning message:
In value[[3L]](cond) :
  phyloseq::estimate_richness: Warning in fisher.alpha(). See `?fisher.fit` or ?`fisher.alpha`. Treat fisher results with caution
```
The dataset hasn't changed, as far as I know no package versions have changed, and actually a few lines above that I use estimate_richness successfully on a different phyloseq object. What might be going on?

Thank you!

**Comment by HeleenDeWeerd** [comment]
Hello,

I have the same issue, with larger sets I get the uniroot error. 
Have you found a solution?

Regards,
Heleen

**Comment by amusheg** [comment]
Hi - a workaround that worked for me was specifying the richness measures
that interested me, for example estimate_richness(obj,
measures="Observed"). Apparently, the error was being caused by the
calculation of one of the one of the richness estimators that I wasn't
actually using. I didn't investigate further than that.

**Comment by joey711** [comment]
Yes, the default behavior if no `measures` argument is provided is to calculate all supported measures. The recommendation to pick a specific measure that you want is a good solution.

**Comment by arachloroptera** [comment]
Having the same issue. Exact same Error and Warning message as above. Works for similar objects in the lines above and below but not for the one in between. Haven't changed the script, just re-ran the code after restarting R. All variables are defined
