### ISSUE TITLE
Facetted abundance barplots with phyloseq objects

### ISSUE THREAD

**Issue by alopgar** [joey711/phyloseq#1010]
Hello.
I am having some trouble finding a function for making bacterial abundance barplots averaged by treatment and facetted by time. I posted a question in Stackoverflow related with plot_composition function (https://stackoverflow.com/q/52605522/6858372) with no answer, but I would like to know if other barplot approaches are possible.

Thank you very much.

**Comment by joey711** [comment]
First, from experience, you probably don't want a bar plot for this. 

The easiest way to do this is probably to use the `psmelt` function (or alternatives people have been posting), and then use ggplot2 plotting commands on that. If you named your not-averaged bar plot `p`, then `p$data` would have a table similar to the one you want here. Then `dplyr` or `data.table` commands would help you compute the aggregating/summarizing values (e.g. mean) that you want.

Also, see this:
https://www.bioconductor.org/packages/devel/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-want-a-phyloseq-graphic-that-looks-like
