### ISSUE TITLE
Importing Data set 

### ISSUE THREAD

**Issue by reyt1** [joey711/phyloseq#1011]
Dear All, 

My name is Reynaldo Nunez, I am new into phyloseq and also into Qiime, I sent to sequencing my DNA to GENEWIZ, and I obtained from then, several files (GENEWIZ use QIIME 1.9.1), however I see 3 important file: 

- otu_table_mc2_w_tax.biom
- rep_set.fna 
- rep_set.tre

 I try to load this data into phyloseq, according to this script:
otu_table<-import_biom((BIOMfilename="otu_table_mc2_w_tax.biom", 
 treefilename="rep_set.tre")

and seen that I do not get any thing correct:
the result is Error in read_biom, both attempts to read input file: otu_table_mc2_w_tax.biom either as JSON (BIOM-v1) or HDF5 (BIOM-v2)
check file path, file name file itself

So I check file path and the file names. for me seen that I need to transfor the **.biom** in something else. 

Could you guys advice me, thanks in advance

I attach part of the otu_table_mc2_w_tax.biom as txt
[otu_table.txt](https://github.com/joey711/phyloseq/files/2464986/otu_table.txt)

**Comment by reyt1** [comment]
do you know how I could construct a tax_table in R from these file? 
thanks again

**Comment by joey711** [comment]
I suggest you get them to share the fastq.gz files, and run DADA2:

https://benjjneb.github.io/dada2/tutorial.html

Examples for taxonomy, tree, data import follow in there.
