### ISSUE TITLE
Tax glom error

### ISSUE THREAD

**Issue by NeetaParimi** [joey711/phyloseq#1012]
Hello, I am trying to run tax_glom and then phyloseq to metagenomeSeq. I have not has this issue in the earlier versions. Is there a way to fix this? This problem only comes up when I run tax_glom first. 
Thanks,

pa_genus1 <- tax_glom(rf,"Genus") and then 
mgs_obj_genus <- phyloseq_to_metagenomeSeq(pa_genus1 )
and I keep getting the following error:
> mgs_obj_genus <- phyloseq_to_metagenomeSeq(pa_genus1)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

**Comment by aphinneys** [comment]
Has this been resolved? When I run tax_glom and then try to plot_composition (in the Microbiome package); I get the same error mentioned above.

**Comment by joey711** [comment]
Check `taxa_names()` after your `tax_glom` call. Probably something strange there.
