### ISSUE TITLE
Stacked plot_bar generates spurious data lines

### ISSUE THREAD

**Issue by jdrum00** [joey711/phyloseq#1013]
Hi. I just noticed that, when I use plot_bar without internal lines*, I get a thin line of the top taxon's color on every column whether that taxon is in the data for that sample type or not. It makes it look like there is a small number of reads for that first taxon in all the plotted categories, even when the data says there isn't. It took me a long while to notice, because for all I knew, that taxon really did appear at low levels in every category.

The actual example from the tutorial doesn't exhibit the problem, but it's not using stacking. The code below demonstrates the problem with GlobalPatterns data.

`*` following https://joey711.github.io/phyloseq/plot_bar-examples.html, under "Add ggplot2 layer to remove the OTU separation lines"

```
library("phyloseq"); packageVersion("phyloseq")  # ‘1.24.2’
library("ggplot2"); packageVersion("ggplot2")    # ‘3.0.0’
library("dplyr")
data("GlobalPatterns")

testgp <- subset_taxa(GlobalPatterns, Phylum=="OP11")

# Demonstrate that there aren't any OP11-2 reads for Soil in this data subset
q <- plot_bar(testgp, x="SampleType", fill="Class")
select(filter(q$data, SampleType=="Soil"), Class, Abundance, SampleType)
# Demonstrate that there aren't any reads at all for Tongue in this data subset
select(filter(q$data, SampleType=="Tongue"), Class, Abundance, SampleType)

# Basic plot_bar with internal lines; works as expected
p <- plot_bar(testgp, x="SampleType", fill="Class")
p
# ggsave("basic-plot-bar.pdf", height=6, width=5)
```
[basic-plot-bar.pdf](https://github.com/joey711/phyloseq/files/2476027/basic-plot-bar.pdf)
```
# With line-removing technique from tutorial; introduces spurious lines
p <- plot_bar(testgp, x="SampleType", fill="Class")
p + geom_bar(aes(fill=Class, color=Class), stat="identity", position="stack")
# ggsave("problematic-plot-bar.pdf", height=6, width=5)
```
[problematic-plot-bar.pdf](https://github.com/joey711/phyloseq/files/2476028/problematic-plot-bar.pdf)
```
# Remove explicit "color" aesthetic, which sort of works but leaves ghost lines between blocks
p <- plot_bar(testgp, x="SampleType", fill="Class")
p$layers <- p$layers[-1]
p + geom_bar(aes(fill=Class), stat="identity", position="stack")
# ggsave("less-problematic-plot-bar.pdf", height=6, width=5)
```
[less-problematic-plot-bar.pdf](https://github.com/joey711/phyloseq/files/2476029/less-problematic-plot-bar.pdf)

**Comment by joey711** [comment]
Did you try saving as `png` instead? This might be a silly rendering issue, rather than a bug in phyloseq itself (so technically a bug in ggplot2 or dependency)...

I'll close for now, but can re-open if you think it is a bigger issue.
