### ISSUE TITLE
heads up: Bioc 3.8 package: if/while condition error

### ISSUE THREAD

**Issue by guidohooiveld** [joey711/phyloseq#1016]
Hi, in case this was missed:
Being a regular user of `phyloseq` I would like to point you to a heads up notification made at the Bioconductor dev mailing list, which apparently also applies to `phyloseq`:

_The packages below execute an if() or while() statement on a condition with length greater than 1. This is currently a warning in R but will soon become an **error**._

More info here ([link](https://stat.ethz.ch/pipermail/bioc-devel/2018-October/014186.html)):
https://stat.ethz.ch/pipermail/bioc-devel/2018-October/014186.html

Thanks,
Guido

**Comment by joey711** [comment]
Thanks!
I think I found where this happens (within `mt` and throwing an error in examples). It should be fixed, but I'm waiting for the clean build to show me for certain. will close for now.
