### ISSUE TITLE
Too much eukaryotic assignation?

### ISSUE THREAD

**Issue by AgustinPardo** [joey711/phyloseq#1022]
Hello. I used DADA2 to analyse several samples from different runs. The reads are 274 pb long and came from a region V1, V2, V3 480 pb long of ribosomal bacteria rna .

Then I continue working with phyloseq.

I create a phyloseq objetc "ps" and then I check this:

> table(tax_table(ps)[, "Kingdom"], exclude = NULL)

Archaea Bacteria Eukaryota NA
1    105407     67934      1356 

Then I checked for the reads that are lost by selection Bacteria:

> ps0 = subset_taxa(ps, Kingdom == "Bacteria")
> 
> All=sample_sums(ps)
> Bacteria=sample_sums(ps0)
> kingdome_filter_table=cbind(All , Bacteria)

 sample | All | Bacteria
-- | -- | --
P1A_Fall2015_R1 | 47081 | 22157
P1A_Fall2016_R1 | 63316 | 30135
P1A_Spring2016_R1 | 45016 | 21820
P1A_Spring2017_R1 | 68967 | 35560
P1A_Winter2017_R1 | 37060 | 19192
P1B_Fall2015_R1 | 42635 | 20099
P1B_Fall2016_R1 | 63432 | 31370
P1B_Spring2014_R1 | 50668 | 24594
P1B_Spring2016_R1 | 42072 | 20558
P1B_Spring2017_R1 | 67649 | 35876
P1B_Winter2017_R1 | 32438 | 16998
P1C_Fall2016_R1 | 40885 | 18531
P1C_Spring2017_R1 | 62984 | 33699
P1C_Winter2017_R1 | 34347 | 16847
P4A_Fall2015_R1 | 51572 | 22739
P4A_Fall2016_R1 | 37561 | 16970
P4A_Spring2016_R1 | 34791 | 18253
P4A_Spring2017_R1 | 47960 | 25277
P4A_Winter2017_R1 | 29901 | 16213
P4B_Fall2015_R1 | 41651 | 16935
P4B_Fall2016_R1 | 45112 | 22653
P4B_Spring2014_R1 | 24476 | 5328
P4B_Spring2016_R1 | 35469 | 17233
P4B_Spring2017_R1 | 64873 | 34245
P4B_Winter2017_R1 | 35930 | 17901
P4C_Spring2017_R1 | 69510 | 36694
P4C_Winter2017_R1 | 33065 | 16960
Ref2A_Spring2017_R1 | 70691 | 36575
Ref2B_Spring2017_R1 | 72328 | 37538
RefA_Fall2015_R1 | 48996 | 23895
RefA_Fall2016_R1 | 48553 | 24548
RefA_Spring2016_R1 | 27484 | 14161
RefA_Spring2017_R1 | 81565 | 42322
RefA_Winter2017_R1 | 15373 | 8296
RefB_Fall2015_R1 | 34849 | 19234
RefB_Fall2016_R1 | 52754 | 26367
RefB_Spring2014_R1 | 46709 | 22717
RefB_Spring2016_R1 | 45110 | 23711
RefB_Spring2017_R1 | 85247 | 43701
RefB_Winter2017_R1 | 9343 | 5420
RefC_Fall2016_R1 | 26478 | 14690
RefC_Winter2017_R1 | 14210 | 7703
SA_Fall2015_R1 | 63048 | 32590
SA_Fall2016_R1 | 57491 | 29661
SA_Spring2016_R1 | 33432 | 16942
SA_Spring2017_R1 | 65775 | 34879
SA_Winter2017_R1 | 32508 | 17366
SB_Fall2015_R1 | 61349 | 31710
SB_Fall2016_R1 | 55408 | 27695
SB_Spring2014_R1 | 31480 | 15938
SB_Spring2016_R1 | 36675 | 19902
SB_Spring2017_R1 | 79290 | 43942
SB_Winter2017_R1 | 17807 | 9588
SC_Fall2016_R1 | 24675 | 10869
SC_Winter2017_R1 | 28509 | 14976
SD_Spring2017_R1 | 70003 | 36603
Y1A_Fall2015_R1 | 46151 | 21962
Y1A_Fall2016_R1 | 52816 | 24748
Y1A_Spring2016_R1 | 45899 | 22812
Y1A_Spring2017_R1 | 74943 | 40393
Y1A_Winter2017_R1 | 31136 | 15460
Y1B_Fall2015_R1 | 55796 | 26671
Y1B_Fall2016_R1 | 48069 | 22540
Y1B_Spring2014_R1 | 57843 | 26949
Y1B_Spring2016_R1 | 46098 | 22862
Y1B_Spring2017_R1 | 76037 | 39312
Y1B_Winter2017_R1 | 29578 | 14637
Y1C_Fall2016_R1 | 31592 | 17517
Y1C_Spring2017_R1 | 44588 | 24011
Y1C_Winter2017_R1 | 30157 | 14556
Y4A_Fall2015_R1 | 47097 | 23122
Y4A_Fall2016_R1 | 51888 | 24457
Y4A_Spring2016_R1 | 33289 | 16047
Y4A_Spring2017_R1 | 60640 | 31272
Y4B_Fall2015_R1 | 49948 | 23893
Y4B_Fall2016_R1 | 48314 | 23922
Y4B_Spring2016_R1 | 41382 | 20884
Y4B_Spring2017_R1 | 45467 | 23274
Y4C_Spring2017_R1 | 85894 | 45301
Y4D_Winter2017_R1 | 27109 | 13014
Y4E_Winter2017_R1 | 33828 | 17285
Y4G_Winter2017_R1 | 31380 | 15509
Y6A_Fall2015_R1 | 33055 | 13122
Y6A_Fall2016_R1 | 49093 | 23550
Y6A_Spring2016_R1 | 39989 | 19986
Y6A_Spring2017_R1 | 69192 | 35664
Y6A_Winter2017_R1 | 28453 | 14841
Y6B_Fall2015_R1 | 33606 | 16698
Y6B_Fall2016_R1 | 51490 | 25946
Y6B_Spring2014_R1 | 47172 | 22053
Y6B_Spring2016_R1 | 50734 | 23665
Y6B_Spring2017_R1 | 83640 | 43288
Y6B_Winter2017_R1 | 32808 | 16426
Y6C_Fall2016_R1 | 26200 | 11799
Y6C_Spring2017_R1 | 72402 | 38328
Y6C_Winter2017_R1 | 32327 | 15850

I used Silva 132 in the dada2 taxonomic assignation (silva_nr_v132_train_set.fa.gz, silva_species_assignment_v132.fa.gz)
Is it common to have such a high proportion of eukaryotes?
What should I do to solve this issue?

**Comment by cjfields** [comment]
@AgustinPardo you should probably ask this on the dada2 github issues tracker: https://github.com/benjjneb/dada2/issues

**Comment by AgustinPardo** [comment]
I tried 
try assignTaxonomy(..., tryRC=TRUE), and addSpecies(..., tryRC=TRUE) and it was successful.
Before:
Archaea Bacteria Eukaryota NA
1 105407 67934 1356

After:
Archaea Bacteria Eukaryota NA
2 173842 744 110
