### ISSUE TITLE
Import_mothur with tree produced by tre.shared

### ISSUE THREAD

**Issue by andrebolerbarros** [joey711/phyloseq#1023]
I've been trying to find more effective ways to import my data from mothur. 

My first approach was to create two phyloseq files:
- one for phylogeny:
`phyl<-import_mothur(mothur_list_file = "total.final.pick.opti_mcc.list", 
                    mothur_tree_file = "total.final.pick.phylip.tre",
                    mothur_group_file = "total.final.pick.groups")`
- one for abundance:
`otu<-import_mothur(mothur_shared_file="total.final.pick.opti_mcc.shared",
                   mothur_constaxonomy_file = "total.final.pick.opti_mcc.0.03.cons.taxonomy")`

Now, I'm trying to use `import_mothur` with a .shared and .tre files, with the last one produced using `tree.shared` command in mothur (it's the file that is normally used for PCoA). 

However, when I try to do that, using the command:
`otu<-import_mothur(mothur_shared_file = "total.final.pick.opti_mcc.0.03.biom",
mothur_constaxonomy_file = "total.final.pick.opti_mcc.0.03.cons.taxonomy",
mothur_tree_file = "total.final.pick.phylip.tre")`

I get this error: `Error in read.table(text = x[grep(paste0("^", cutoff), x)], header = FALSE,  : 
  no lines available in input
In addition: Warning message:
In asMethod(object) : NAs introduced by coercion`

Has anyone got this error before?

**Comment by andrebolerbarros** [comment]
The files are here: https://drive.google.com/open?id=1TDx1YxRHN4rAGbrVOZBSRl_ilaBFR3gG

**Comment by joey711** [comment]
The `import_mothur()` function was written way before the `.biom` file format was defined or implemented in various workflows. Hence, `import_mothur` really only supports the old esoteric format(s) that `mothur` produced back in the day. `.biom` formats should be imported using `import_biom`.
