### ISSUE TITLE
One more question about phyloseq to deseq2

### ISSUE THREAD

**Issue by vhertzb** [joey711/phyloseq#1026]
What is the interpretation? That is, what is the reference level? How can we control that? If I am doing a two group comparison where the groups are A and B, which one is the referent?

**Comment by vhertzb** [comment]
For instance, in the Kostic example you give, does that meant that the bugs that have positive log2fold change are overexpressed in the treated group? I'm sorry to ask such a no-brainer question, but I really do need to have this spelled out.

**Comment by joey711** [comment]
Depends on how you provide it to the function. The deseq2 output object should show this for you (see their doc for definition), or you can figure it out by inspecting the abundances of one of the "hits". Whether a positive sign indicates A/B or B/A should be pretty obvious after just a few peeks at the data.

**Comment by vhertzb** [comment]
Thanks!
