### ISSUE TITLE
plot_richness

### ISSUE THREAD

**Issue by iratxezarra** [joey711/phyloseq#1028]
Hi 
Could anyone help me with an issue that raised when using plot_richness function?

The problem is that I am obtaining different results when plotting chao 1 and shannon estimates depending whether i upload a tree file ( together with the biom and metadata file) or not.  I find this weird cause as far as i understood those estimates are not phylogeny based, and thus, I do not understand how the output is different.

Thanks in advance for the help!

**Comment by joey711** [comment]
When you include other data components (tree, tax_table, etc.), the resulting phyloseq object keeps only the intersection of the taxa whose `taxa_names` match exactly. Most likely your issue derives from this, and you'll notice that the number of taxa is probably different between the two objects.
