### ISSUE TITLE
error with plot_ordination in v 1.26.0

### ISSUE THREAD

**Issue by nicholascdove** [joey711/phyloseq#1031]
I recently downloaded the newest version of phyloseq (1.26.0, Bioconductor 3.8), and I am now having difficulty with the plot_ordination() command. It returns the error message: "$ operator not defined for this S4 class".  When I reverted to 1.24.2 (Bioconductor 3.7), I was able to run the command.

**Comment by joey711** [comment]
I'm guessing this was a R/version changeover issue that fixed itself. If you still have the problem please post back here and I'll re-open.

**Comment by ChrisTrivedi** [comment]
Hi @joey711 , I just ran into this issue as well. I'm currently running phyloseq v1.26.1. Not quite sure how to troubleshoot this issue, but I think it might be a sample naming issue? I'm not sure. Any advice would be greatly appreciated. Thanks!

**Comment by nicholascdove** [comment]
For me, it was an issue with the function referencing the wrong package. Try phyloseq::plot_ordination()
