### ISSUE TITLE
Rarefaction curves and removing samples

### ISSUE THREAD

**Issue by Tre10** [joey711/phyloseq#1032]
Hi 

I am trying to get rarefaction curves for my data using the script by jakevc (https://github.com/mahendra-mariadassou/phyloseq-extended/blob/master/R/richness.R). However, after running the ggrare function I get the following error message: "Error in if (nrow(y) != 1) { : argument is of length zero". I think this might be because for one of my samples the TotalASVs count in the sdt file is only 1 (this sample is second last on the list, and the error message appears after rarefying the second last sample). 

I'm not a very experienced R user yet, so I was wondering what would be the best way to remove that one sample, or if there was something else I could do to solve this problem and get on with my analysis?

Any help would be greatly appreciated. : )

**Comment by joey711** [comment]
I think you need to ask the author of the rarefaction-plotting function you attempted to use here. It is not part of phyloseq.
