### ISSUE TITLE
question about UniFrac distance in ordinate()

### ISSUE THREAD

**Issue by hermetia** [joey711/phyloseq#1040]
Dear all,
I have a question about the arguments in the ordinate() function:

I want to perform a distance-based RDA based on weighted or unweighted UniFrac distances, of a phyloseq object (relative abundances, rooted tree) of 16S data from insect larvae and their feed substrate. At first, I thought I could use the ordinate() function by using the code (example):

> ordinate(physeq, method = "CAP", formula = ~ time * treatment + Condition(time), distance = "unifrac", weighted = TRUE)

However, there was no difference in output between weighted=T or weighted=F. Then I found out in Help that weighted=TRUE is an additional argument that "would be passed on to UniFrac if "unifrac" were chosen as the distance option and "MDS" as the ordination method option". Since I used method=CAP, I assume the formula ignored the distance and weighted arguments and returned the ordination using default distance="bray".

Is this indeed how it works, i.e. arguments weighted=T and distance=unifrac are only used if method=MDS, and are ignored if method=CAP (and "bray" is used instead)?

As an alternative I am using the code provided in the supplement to Shankar et al. 2017 (DOI:10.1038/s41598-017-06693-z). Using weighted or unweighted UniFrac distance matrices in the capscale() function then results in an ordination with much lower R-squared than in the CAP in the ordinate() code above, and also shows much lower % variance explained and only treatment or time effects non-significant, compared to quite a number of significant treatment and time effects in the CAP of ordinate() - though if this is unintendedly using bray-curtis instead of unifrac, then this may explain the difference.

Thanks in advance.

Stijn.

**Comment by joey711** [comment]
If you are unsure of the distance method used when you define it within `ordinate()`, you can also provide the distance directly, by using the `distance` function, then `ordinate`.

Please read the documentation for the `ordinate` function, as weighted here referes

```r
wfDist = distance(physeq, method = "wunifrac")
ordinate(physeq, method = "CAP", formula = ~ time * treatment + Condition(time), distance = wfDist)
```
