### ISSUE TITLE
Problems with merging phylogenetic tree and OTU table (phyloseq object)

### ISSUE THREAD

**Issue by ragnhv** [joey711/phyloseq#1044]
Hi

I am trying to merge a phylogenetic tree with my OTU table (phyloseq object) in order to generate Unifrac distances.  

My OTU table phyloseq object:

> phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3336 taxa and 197 samples ]
sample_data() Sample Data:       [ 197 samples by 3 sample variables ]
tax_table()   Taxonomy Table:    [ 3336 taxa by 6 taxonomic ranks ]

I made a maximum likelihood tree by using Mega7, and imported this into R. 
My tree:

> Phylogenetic tree with 22242 tips and 7413 internal nodes.
Tip labels:
	OTU_7099, 00000000, OTU_7338, 00000000, 00000000, OTU_6500, ...
Unrooted; includes branch lengths.

I then tried to merge it with the OTU table:

`library(ape)`
`tree <- read.tree(file="MLtree.nwk")`
`tree = phy_tree(tree)`
`plot(tree)`
`MLtree_phyl = merge_phyloseq(promikrobe_rare_phyl, tree)`

Then I get this error message:

> Error in `taxa_names<-`(`*tmp*`, value = gsub("\"", "", taxa_names(x),  : 
  taxa_names<-: You are attempting to assign duplicated taxa_names

What might be wrong here? Any help would be highly appreciated.

Best,
Ragnhild

**Comment by joey711** [comment]
almost always this happens when the tips of the tree (see `taxa_names(tree)`) don't match with `taxa_names` of your other objects... in this case it looks like your tree tips might have duplicated names. You'll have to inspect those two more closely to figure it out. Try `setdiff()`.
