### ISSUE TITLE
How to save the data contained in the plots

### ISSUE THREAD

**Issue by Marielis24** [joey711/phyloseq#1045]
Hello, 

I have done a lot of plots in Phyloseq, now my question is how can I save the data in those plots. For example, how can I save the data contained in this plot?

jpeg(filename="Phyloseq Plots/Richness_All.jpg", units="in", width = 10, height = 5, res=300, type="cairo")
plot_richness(physeq, measures=c("Shannon", "Simpson")) + labs(x = "Samples") + theme(axis.title.x = element_text(size=12, family="serif", hjust=0.5, face= "bold"),
                                                 axis.text.x  = element_text(size=5, family="serif", hjust=0.5),
                                                 axis.title.y = element_text(size=12, family="serif", face="bold"),
                                                 axis.text.y  = element_text(size=10, family="serif"),
                                                 legend.title = element_text(size=12, family="serif", face="bold", hjust=0.5),
                                                 legend.text = element_text(size=10, family="serif", hjust=0.5)) 
dev.off()

**Comment by benjjneb** [comment]
All phyloseq plot are `ggplot` objects. So, if you assign your plot to a variable (e.g. `p1 <0- plot_richness(...) + etc`, you can access the data underlying that plot by accessing the `data.frame` in the `ggplot` object: `p1$data`
