### ISSUE TITLE
Remove OTUs appearing less than 3 times across all samples

### ISSUE THREAD

**Issue by Hanhan0926** [joey711/phyloseq#1047]
Hi,
I'm new in phyloseq. Recently I tried to filter my OTU table by removing OTUs occurring less than 3 times across all (112 samples).
Is there any way to do this. 
# Remove taxa not seen more than 3 times in at least 20% of the samples. 
GP = filter_taxa(d, function(x) sum(x >= 3) > (0.2 *length(x)), TRUE)
The above code seems like only takes 20% in account. I would like to filter from all samples.
Many thanks~
han

**Comment by joey711** [comment]
Your question is not very clearly stated. There are multiple ways I can interpret what you are asking to achieve.

Please see this doc:

https://joey711.github.io/phyloseq/preprocess.html
