### ISSUE TITLE
subset_taxa based on list of genera

### ISSUE THREAD

**Issue by RachelIAdams** [joey711/phyloseq#1048]
Thanks for all your with on phyloseq. This is not an issue but a request for help. 

I have a list of ~25 genera, and I'd like to pull out a new phyloseq object of all the taxa (kept at the species level) that fall into those genera. I saw the post about how to do it with a few taxonomic names at a time (https://github.com/joey711/phyloseq/issues/414), but with so many genera, I'd like to pull out those taxa based on a separate vector. 

For a data set, let's say I want to pull out this list of genera from the Global Patterns dataset. 
gen_to_keep=c("Porphyromonas","Prauserella","Prevotella","Procabacter","Prochlorococcus","Prochlorothrix","Promicromonospora","Propionibacterium","Propionicimonas","Propionigenium","Prosthecobacter","Proteus","Pseudaminobacter","Pseudanabaena","Pseudidiomarina","Pseudoalteromonas","Pseudobutyrivibrio","Pseudochrobactrum","Pseudoclavibacter")

Any leads would be greatly appreciated. Thank you.

**Comment by RachelIAdams** [comment]
Never mind! It's this simple: 

gen_of_int = subset_taxa(GlobalPatterns, Genus %in% gen_to_keep)

**Comment by RPjose2020** [comment]
Hello, I am having same issue, but getting error with the code
gen_of_int = subset_taxa(GlobalPatterns, Genus %in% gen_to_keep) . Should the genes in the gen_to_keep be enclosed in double quotes? I have a list of genera which I am importing to R from an excel sheet. I am getting the below error whenever I try the subset_taxa command.
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent.
Can anyone please help?

Thanks
Rose

**Comment by Djeppschmidt** [comment]
@RPjose2020 When I've had this issue it was becaue there were no taxa that met that criteria in my sample. This could be spelling if there are prefixes like g__ on your genera; or it could be legit that none of your genera match.
