### ISSUE TITLE
taxa_sums by sample_data factor

### ISSUE THREAD

**Issue by RachelIAdams** [joey711/phyloseq#1049]
Thanks for all your work on phyloseq. 

I'm looking for a way to look at abundance of taxa by a factor in the sample data. In the Global Patterns dataset, it might be looking at taxa_sums by Sample Type.

Any clues would be greatly appreciated. Thanks.

**Comment by yiluheihei** [comment]
A workaround as following:

```
# sample data
phylo <- subset_taxa(GlobalPatterns, Phylum=="Chlamydiae")

# melt phyloseq data to data frame
mdf <- psmelt(phylo)

# compute taxa sum
sampletype_abund <- dplyr::group_by(mdf, OTU, SampleType) %>% 
  dplyr::summarise(abundance = sum(Abundance))

# spread 
spread(a, SampleType, abundance)
```

Hope it will be useful to you.

**Comment by RachelIAdams** [comment]
Thank you, that's helpful! 

For completeness, I'll mention that spread requires the tidyr package, and that the last command is
spread(sampletype_abund, SampleType, abundance)

**Comment by yiluheihei** [comment]
@RachelIAdams  
Sorry for the mistake
