### ISSUE TITLE
Can we cross-correlate OTU abundance and metabolome data by phyloseq?

### ISSUE THREAD

**Issue by microbod** [joey711/phyloseq#1054]
I dig but I could not find a tutorial which would be useful cross-correlate values from microbiome profiling and blood metabolites. I would like to draw a heat map correlating (Pearson/Spearman) OTU abundance in the sample with its metabolome data.
Appreciate any help. Thanks

**Comment by joey711** [comment]
We would typically describe this as a "two-table" approach, and there are lots of method choices available in R close at hand. One of our favorite packages for this is ade4. There is no for-purpose function in phyloseq that will do this for you. 

@spholmes  might have an example handy. Either way I will close this ticket for now.
