### ISSUE TITLE
Data import for Pyloseq

### ISSUE THREAD

**Issue by nasden** [joey711/phyloseq#1055]
Hi Joey,

the otu table in form of biom
the sequence is in form of tsv 
and the tree is in form of qza

How do I import these into R?

**Comment by joey711** [comment]
Please read this:
https://guangchuangyu.github.io/2016/07/how-to-bug-author/
I can respond to more properly formatted ticket.

Also, in principle your biom-format file should have all information you need. That is the point of that file format. If it is missing information, you may want to ask the QIIME developers why they are not including it.
