### ISSUE TITLE
conditional annotation for plot_ordination

### ISSUE THREAD

**Issue by yunsuhk** [joey711/phyloseq#1056]
Hello,

First of all, I appreciate this wonderful package.

I am trying to draw ordination plot with biplot or taxa option.

Default plot demonstrated all taxa (hundreds) points in phyloseq object.

Now I have a list of interesting taxa (about 10 taxa).

How can I put annotation only for interesting taxa with plotting all taxa ? (a.k.a conditional annotation for taxa inside default biplot or taxa plot)

I tried to use geom_text or geom_text_repel, but I couldn't figure our how to integrate that code into plot_ordination.

Thanks in advance.

**Comment by joey711** [comment]
Please see the corresponding section in [the phyloseq FAQ](https://www.bioconductor.org/packages/devel/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#modify-the-ggplot-object-yourself.)

Note for any new `geom_*` layer that you are adding, you can specify a subset of data. If your default plot was named `p`

Would have a form something like this:

```r
p + geom_text(data = p$data[{subset expression here}], mapping = aes(label = ...))
```
