### ISSUE TITLE
Merge Samples Issue

### ISSUE THREAD

**Issue by WhataShane** [joey711/phyloseq#1060]
I'm a high school student interning at a local lab. I wanted to reach out as I've been stumped by this question for a couple of weeks now. My apologies in advance if this is the wrong forum for this sort of question, especially if this question has been answered before. I've searched tirelessly, but haven't found a solution I was able to implement on my own. 

I've been trying to follow along with the tutorial on https://joey711.github.io/phyloseq/ for merging samples. Currently I'm generating graphs that look like [this](https://i.imgur.com/LHrYDF8.png), but I want to combine the "tamed" bar and "untamed" bar so that there are only two bars total. Can this be done by simply adding together OTU abundance data for each type of sample (ex. add all the OTU abundance data for the untamed1 column with the untamed2 column, and add all the OTU abundance data for the tamed1 column with the tamed2 column), before converting the data to relative abundance? If so, how would one do this?

Thank you so much in advance!

**Comment by joey711** [comment]
The function you are looking for is 
`merge_samples()`
Please see its documentation, and examples in various tutorials, vignettes.
