### ISSUE TITLE
plot_ordination R 3.5.1 v R 3.4.3

### ISSUE THREAD

**Issue by andrebolerbarros** [joey711/phyloseq#1062]
Hello everyone,

I'm running the same script on R 3.5.1 that I had run with a previous version of R (3.4.3) but, I'm getting different results. 

Is this expected? Were there any changes to the ordination and/or plot_ordination functions?

Thanks in advance!

**Comment by mikemc** [comment]
HI André, I suspect that to get an answer to this question you will need to give the phyloseq versions (and perhaps vegan versions) rather than the R version, and also the relevant phyloseq code or at least the type of ordination (dissimilarity metric and ordination method such as MDS)

**Comment by joey711** [comment]
@andrebolerbarros I will close for now, but we can re-open if you respond with more details to follow-up.
