### ISSUE TITLE
Merge samples from replicated treatments 

### ISSUE THREAD

**Issue by Erikaheadrick** [joey711/phyloseq#1066]
Hi! I have read so many of these forums trying to 1) decode the language and 2) apply the suggestions to my data set. I have a total of 200 samples. These samples are represented by over 6000 OTUs. I have figured out how to eliminate the samples I do not currently want to analyze, so this brings me down to 71 samples. I want to merge the samples given the same treatment.Here is some of what I've been looking at/using as a reference: https://rpubs.com/marschmi/133626
https://joey711.github.io/phyloseq/merge.html#merge_samples.

###  Time to (1) Sum between replicates and then (2) scale 
# Step 1.  Sum the reads 
Erika_sum_reps <- merge_samples(x = pruned_Erika, group = "Oil_Light", fun = "sum") # Sum between replicate samples
Erika_sum_reps <- prune_taxa(taxa_sums(Erika_sum_reps) > 0, Erika_sum_reps) # Remove any OTUs that are 0

Where I get lost is step 2, scale. 

All seems to work, until the end, when I try to make a new rel. abundance histogram.

I've attached a screen shot of the data processed as individual samples. I want to acheive this same thing, but combine the replicates indicated by the 1,2,3 at the end of the number sequence. 

Any and all help is appreciated and desperately needed. 

Best, 
-E

![screen shot 2018-10-18 at 5 33 36 pm](https://user-images.githubusercontent.com/47155988/51932409-c0fed880-23c4-11e9-9497-e4df08c249e3.png)

**Comment by Erikaheadrick** [comment]
I think I fixed this on my own, but still open to what others have to say! 

Best, 

-E

**Comment by fulbag** [comment]
@Erikaheadrick : could you please tell us how you did it? I have just started to use phyloseq and I guess I will have the same problem. Thanks!

**Comment by Erikaheadrick** [comment]
@fulbag : I'm not sure it is always necessary, in fact some sort of frown upon merging unless your replicates are pretty similar in the first place. I merged simply because The figure I showed above was far too much data to share in a talk in 10 minutes along with everything else I had to address in the talk. 

I first removed samples with low sequence yield from the analysis all together, I rarefied sequencing depth since the script i used was based upon the sum fxn, and then used the standard merge script which to my understanding is defaulted to merge by summing, rather than averaging taxonomic representatives from replicate samples. mergedErika = merge_samples(Data_file, "Factor_to_merge_by") from https://joey711.github.io/phyloseq/merge.html#merge_samples.


The final file looked like this...
![capture4894891](https://user-images.githubusercontent.com/47155988/52446487-cd391300-2af3-11e9-9441-9a6bf234a611.PNG)

**Comment by Erikaheadrick** [comment]
When I publish, I will most likely show all replicates separately, (not merged), unless a reader requires it.

**Comment by lingvv** [comment]
@Erikaheadrick

Hello!
Could you please share the details of how you resolved this issue? 
I've encountered the same problem and am currently searching for a solution. 
As I'm relatively new to phyloseq, your assistance would be highly valuable to me.

Thank you!
