### ISSUE TITLE
label NMDS by OTU rather than rank 

### ISSUE THREAD

**Issue by HSapers** [joey711/phyloseq#1067]
Hi, I'm really enjoying working with Phyloseq. I'm rather new to R and phyloseq so I apologize if this has been answered before, there was a similar thread ( #213) but I was having a bit of difficulty following and adapting. 

I've plotted an NMDS as follows
p1 = plot_ordination(data_ab, data_ab.ord, type="taxa", color="Genus", title="taxa", label = "RankX")
print(p1)

Rather than labeling by Rank in the tax_table, I would like to label by the OTU number (the equivalent of 'row name' in the tax_table?) 

Thank you
Haley

**Comment by mikemc** [comment]
Hi, it seems that the data frame created and used by `plot_ordination` (which you can access with p1$data) does not include a column with the OTU/taxa names, but only the tax_table columns. So as a cheat you can add an OTU column to the tax_table
```r
tax_table(data_ab) <- cbind(tax_table(data_ab), OTU = taxa_names(data_ab))
p1 <- plot_ordination(data_ab, data_ab.ord, type="taxa", color="Genus", title="taxa", label = "OTU")
p1
```

**Comment by HSapers** [comment]
Thank you @mikemc 
That worked perfectly!
