### ISSUE TITLE
Creating a new phylogenetic tree with phyloseq object

### ISSUE THREAD

**Issue by rlh13** [joey711/phyloseq#1072]
Hello,
I was wondering if there is a way to create a new phylogenetic tree using a phyloseq object as input? For DADA2, there is this article (https://f1000research.com/articles/5-1492/v1) describing how to create a tree from the data but I was wondering if there is anything that lets you construct a tree to add to the phyloseq object by just using the phyloseq object itself as input? The only posts I can find only talk about merging an already created tree with an existing phyloseq object.

Thank you!

**Comment by joey711** [comment]
Creating a phylogenetic tree for this purpose requires that you have a biological sequence (DNA, AA) for each "row" in your OTU table -- typically, the DNA sequence from each ASV inferred with DADA2. For older (no longer recommended) workflows that do OTU-clustering, you can use the representative sequence. The same tools used in the F1000 workflow paper to compute a phylogenetic tree can be used on these sequences. If the sequences are already in the phyloseq object, you can access them using the `refseq` accessor function:

```r
?refseq
```

**Comment by rlh13** [comment]
Hi joey711, thank you. I used the code in the F1000 paper, using the column names of the otu_table in the phyloseq object to assign seqs. (refseq only returned NULL since there is no tree and even after reading the R documentation I'm not sure how this is supposed to be used to get the sequences in the phyloseq object?). The issue I'm having is that when I try to use msa on the seqs object created with the column names of the phyloseq otu table, I don't get an error but the R session keeps aborting because it encounters a "fatal error".
