### ISSUE TITLE
differential data interpretation: what does each do mean?

### ISSUE THREAD

**Issue by saifsikdar** [joey711/phyloseq#1074]
Hi @joey711 ,

Can you please let me know what does it mean by 1 dot of a bacteria vs. 5 dot of a bacteria in log2FoldChange plot that you showed in your tutorial? In attached screenshot, you see there are 5 dots 
of Fusobacteria in left side column and 1 dot of Firmicutes in 2nd-right column.  Does it mean that 5 samples have that much of Fusobacteria while 1 sample have that much of Firmicutes?  

![capture](https://user-images.githubusercontent.com/34520963/52605085-908a5600-2e2a-11e9-9d79-a888d05b2890.JPG)

Thanks,

Saif

**Comment by mikemc** [comment]
Each row in the data frame, and thus each dot in the plot, corresponds to an OTU. There are apparently multiple OTUs per Genus, and thus multiple dots per Genus in the plot. Samples do not appear in any way, as DESeq is giving you an estimate of the average change between groups of samples defined by the contrast.
