### ISSUE TITLE
Reordering samples in plot_bar

### ISSUE THREAD

**Issue by owenNewcastle** [joey711/phyloseq#1075]
Hi 

I'm trying to create a bar plot in phyloseq for my dissertation. 

I used the command :
plot_bar(ps.top20, fill="Genus") + facet_grid(~Substrate, scales = "free", space = "free",  labeller = as_labeller(Substrate_names)) 

![image](https://user-images.githubusercontent.com/47703828/52906715-98426400-3249-11e9-855c-8d7dff6c967f.png)

I want to change the order individual samples within individual facets to make comparisons more useful. For me (I am planning to change the name of the samples later), this would be "MK4", "MK22", "MK5", "MK23", "MK6", "MK24" in the 'Coal' facet. 

I have read numerous other threads on issues related to this but they all seem to be related to heatmaps. 

Thanks 
Owen

**Comment by mikemc** [comment]
You need to turn the `Sample` variable in the underlying data frame being passed to `ggplot` into a factor, with the levels set to the order you want the samples to appear in. Try
```r
p <- plot_bar(ps.top20, fill="Genus") + facet_grid(~Substrate, scales = "free", space = "free", labeller = as_labeller(Substrate_names))
p$data$Sample <- factor(p$data$Sample, levels = desired_order)
print(p)
```
where `desired_order` is a list of all the sample names in the order you want them to appear. If you want to order the samples by some other variable in `p$data`, try googling the `forcats` package

**Comment by owenNewcastle** [comment]
> You need to turn the `Sample` variable in the underlying data frame being passed to `ggplot` into a factor, with the levels set to the order you want the samples to appear in. Try
> 
> ```r
> p <- plot_bar(ps.top20, fill="Genus") + facet_grid(~Substrate, scales = "free", space = "free", labeller = as_labeller(Substrate_names))
> p$data$Sample <- factor(p$data$Sample, levels = desired_order)
> print(p)
> ```
> 
> where `desired_order` is a list of all the sample names in the order you want them to appear. If you want to order the samples by some other variable in `p$data`, try googling the `forcats` package

Thanks for the quick reply Mike. 

I've done this but the outcome is the same:
desired_order <- list("MK4", "MK22", "MK5", "MK23", "MK6", "MK24", "MK1", "MK19", "MK2", "MK20", "MK3", "MK21", "MK7", "MK25", "MK8", "MK26", "MK9", "MK27",
                      "MK10", "MK28", "MK11", "MK29", "MK12", "MK30", "MK13", "MK31", "MK14", "MK32", "MK15", "MK33", "MK16", "MK34", "MK17", "MK35", "MK18", "MK36")

p <- plot_bar(ps.top20, fill="Genus") + facet_grid(~Substrate, scales = "free", space = "free", labeller = as_labeller(Substrate_names))

p$ps.top20$Sample <- factor(p$ps.top20$Sample, levels = desired_order)

print(p)

Thanks 
Owen

**Comment by mikemc** [comment]
Do you mean the following? (with "data" instead of "ps.top20")
```r
p$data$Sample <- factor(p$data$Sample, levels = desired_order)
```
