### ISSUE TITLE
abundance analysis

### ISSUE THREAD

**Issue by yogeshgupt** [joey711/phyloseq#1092]
I do have three tissue and three treatment conditions in physeq object. My aim is to only want to use the soil sample and want to see the treatment effect on microbial abundance.

How should I remove other tissue and only retain the soil sample in phyloseq object.

sample details:
> head(sample_data(physeq))
Sample Data:             [6 samples by 5 sample variables]:
                                        X.SampleID      Treatment       Tissue            Villages               Region
leaf-1.S68.L001         leaf-1.S68.L001           T1        Leaf                    Kholabari            Mymensingh
leaf-11.S29.L001       Soil-11.S29.L001         T1       Soil                      Gullapur              Rajshahi
leaf-13.S39.L001      leaf-13.S39.L001         T1       Leaf                        Gokul                Rajshahi
leaf-14.S49.L001      Soil-14.S49.L001         T2      Soil                           Jiol                 Rajshahi
leaf-16.S59.L001      leaf-16.S59.L001          T1      Leaf                      Talund               Rajshahi
leaf-17.S69.L001      soil-17.S69.L001           T3     Soil                       Chandia              Rajshahi

summary(sample_data(physeq)$Tissue)
Leaf Root Soil

And each tissue has given 3 treatment.

summary(sample_data(physeq)$Treatment)
T1 T2 T3 

Kind Regards

**Comment by mikemc** [comment]
Take a look at the `subset_samples` function
```r
library(phyloseq)
?subset_samples
```

**Comment by yogeshgupt** [comment]
Thanks a lot,
I use this code but it is showing error:

> physeq
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 67405 taxa and 162 samples ]
sample_data() Sample Data:       [ 162 samples by 5 sample variables ]
tax_table()   Taxonomy Table:    [ 67405 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 67405 tips and 67229 internal nodes ]

> physeq_soil <- subset_samples(physeq, SampleType=="Soil")
Error in eval(e, x, parent.frame()) : object 'SampleType' not found

**Comment by mikemc** [comment]
You need to replace `SampleType` with the name of the variable in your `sample_data(physeq)`---in this case, `Tissue`.

**Comment by yogeshgupt** [comment]
Thanks a lot.
