### ISSUE TITLE
Sorting stacked barplot based on abundance values

### ISSUE THREAD

**Issue by cdeanj** [joey711/phyloseq#1100]
Hey,

I am using phyloseq and ggplot2 to create a stacked barplot of relative abundances for each of my samples; however, I am having difficulties controlling the order of each block within each sample. I would like to have these blocks sorted by their abundances in descending or ascending order for easier viewing.

I am using the following code, which was borrowed from a Phyloseq tutorial:
```
base.genus <- merge.core.base.taxa %>% \n
  tax_glom(taxrank = "Genus", NArm=FALSE) %>%
  psmelt()
ggplot(base.genus, aes(x = X.SampleID, y = Abundance, fill = Genus)) +
  geom_bar(stat = "identity") +
  xlab("Sample ID")
```
Ideally, I would like to have each Genus ordered by their relative abundance, but the default ordering appears to be by alphabetic ordering of the Genus name. Is there a way to change this default behavior?

![plot_zoom_png](https://user-images.githubusercontent.com/17635887/54842171-38ebcf80-4c9f-11e9-8b15-4a1e28aabc02.png)

Best,
Chris

**Comment by mikemc** [comment]
You need to turn the variable you want to sort by into a factor whose levels are in the order you want. Since this is a ggplot2 question rather than a phyloseq question, you can learn more by googling how to order stuff in ggplot. Try the `fct_reorder` functions from the forcats package as exemplified here https://r4ds.had.co.nz/factors.html#modifying-factor-order for a possible quick way to do what you want.

**Comment by cdeanj** [comment]
Hey @mikemc, thanks for the quick and useful response. I was able to able to achieve what I wanted by using the `fct_reorder` function as you suggested.

```
ggplot(base.genus, aes(x = X.SampleID, y = Abundance, fill = fct_reorder(Genus, Abundance))) + 
  geom_bar(stat = "identity") +
  xlab("Sample ID")
```

Thanks!
Chris

**Comment by negin1986** [comment]
> Hey,
> 
> I am using phyloseq and ggplot2 to create a stacked barplot of relative abundances for each of my samples; however, I am having difficulties controlling the order of each block within each sample. I would like to have these blocks sorted by their abundances in descending or ascending order for easier viewing.
> 
> I am using the following code, which was borrowed from a Phyloseq tutorial:
> 
> ```
> base.genus <- merge.core.base.taxa %>% \n
>   tax_glom(taxrank = "Genus", NArm=FALSE) %>%
>   psmelt()
> ggplot(base.genus, aes(x = X.SampleID, y = Abundance, fill = Genus)) +
>   geom_bar(stat = "identity") +
>   xlab("Sample ID")
> ```
> 
> Ideally, I would like to have each Genus ordered by their relative abundance, but the default ordering appears to be by alphabetic ordering of the Genus name. Is there a way to change this default behavior?
> 
> ![plot_zoom_png](https://user-images.githubusercontent.com/17635887/54842171-38ebcf80-4c9f-11e9-8b15-4a1e28aabc02.png)
> 
> Best,
> Chris

Hi,
How did you make this plot based on relative abundance? I found the code physeq_relab=transform_sample_counts(physeq, function(otu) otu / sum(otu) ) but it seem to not be working correctly. I don;t want to subset specific taxa. I want to get the relative abundance of everything and then make spearate phylum, species, genus, etc. plots based on relative abundance. 

Thanks!
Negin

**Comment by LucieCartairade** [comment]
Hi Chris, 

Can you explain me how did you do to have grey bar for your NA Genus ? 

Thanks a lot 

Lucie

**Comment by david-barnett** [comment]
HI Lucie, 

You might find my R package microViz useful for easily making bar charts from phyloseq objects

e.g. from the tutorial page here https://david-barnett.github.io/microViz/articles/web-only/compositions.html 

```r
pseq %>%
  ps_filter(gender == "female") %>%
  comp_barplot(tax_level = "Genus") +
  coord_flip() # horizontal bars are often more readable
```

![https://david-barnett.github.io/microViz/articles/web-only/compositions.html#quick-example-barplot](https://david-barnett.github.io/microViz/articles/web-only/compositions_files/figure-html/simple-1.png)
