### ISSUE TITLE
Sorted plot_bars 

### ISSUE THREAD

**Issue by OnlyHigh** [joey711/phyloseq#1102]
Hi, 
I was wondering if there's a form to sort the bar plots of  ```plot_bars``` by their abundance, 

Thanks in advance, 
Luis Alfonso.

**Comment by mikemc** [comment]
You will need to be more specific. Do you want to sort samples by their total abundance, or the taxa by their mean abundance across samples? For the latter, see https://github.com/joey711/phyloseq/issues/1100

**Comment by OnlyHigh** [comment]
Excuse me for not being clear enough,
I want to sort samples by their total abundance, 

Thanks in advance, 
Luis Alfonso.

**Comment by OnlyHigh** [comment]
Excuse me for not being clear enough,
I want to sort samples by their total abundance, 

Thanks in advance, 
Luis Alfonso.

**Comment by mikemc** [comment]
Ok. For sorting samples in bar plots generally, please see #1075 . In your case, you want to make `Sample` a factor ordered by `sample_sums(ps)`, which you can do with
```r
desired_order <- names(sort(sample_sums(ps)))
```

**Comment by OnlyHigh** [comment]
Thanks Mike, 
It worked, 
Thank you, 
Luis Alfonso.
