### ISSUE TITLE
merge_phyloseq on four phyloseq objects with different OTU IDs?

### ISSUE THREAD

**Issue by wasimbt** [joey711/phyloseq#1107]
Hi ,

I have four phyloseq class object crated by using 4 different primer pairs (p1, p2, p3, p4) from same samples and against the same reference. I was able to successfully merged them,

M1234 <- merge_phyloseq(p1, p2, p3 , p4)

And the combined object has total of all taxa from each phyloseq object

ntaxa(p1)#5437
ntaxa(p2)#7002
ntaxa(p3)#6889
ntaxa(p4)#8448

ntaxa(M1234)#27816

Why the merged object is not having all the OTU ids from maximum OTU object? It looks like that OTU ids are different in each class object for the same taxa (mostly)?
Merging at OTU ID level is necessary to avoid problems in downstream analyses for example my merged object is now giving weird results for beta diversity analysis.
How can i give a common OTU id in each object so that in the end i can have a common merged OTU for a taxa in the merged object instead of 4 OTU ids for the same taxa.

Thanks alot!
Wasim

**Comment by morien** [comment]
You might consider using actual sequences for OTU IDs, and then merging the OTU tables using a command like rbind.fill(). Once you have a merged OTU table with a corresponding taxonomy table, you can load them as a new phyloseq object.

I did something similar to this recently and it worked quite well, and introduces NAs where there is missing data for an OTU for a particular sample, but combines OTUs that have exact sequence matches.

If this sounds like too much trouble, I'd suggest combining your data before processing (i.e. process the 4 datasets as a single dataset, and then separate them subsequently if you need to).

**Comment by wasimbt** [comment]
Hi, 

Thank you for your answer! 
I solved the problem (by somewhat similar approach to what you proposed), by first merging all the phyloseq objects and then collapsing them at species level by using tax_glom function. Now all the similar taxa with different OTU IDs are merged based on taxa identity and total sum of OTUs are not sum of all phyloseq object as i expected. 

Best regards, 
Wasim
