### ISSUE TITLE
Error in merge_taxa.indices.internal: invalid archetype provided.

### ISSUE THREAD

**Issue by morien** [joey711/phyloseq#1110]
Hello, I've got two phyloseq objects, and one of them is fine for a set of commands such as:
`test_plot <- all_combined %>%
  tax_glom(taxrank = "Rank5") %>%
  transform_sample_counts(function(x) {x/sum(x)} ) %>%
  psmelt() %>%
  arrange(Rank5)`
but the other returns the error:
`Error in merge_taxa.indices.internal(x, eqtaxa, archetype) : 
  invalid archetype provided.`

I've been able to figure out that the issue is with the taxonomy table, but haven't been able to figure out more than that. Here's how I created the object that has the issue:
`all_combined <- merge_phyloseq(otu_table(all_otus, taxa_are_rows=FALSE), sample_data(all_sample_data), tax_table(all_taxa))`
The object that works with the above command was created in essentially the same way, with matrices of data serving as the inputs for the merge_phyloseq() function.

The objects produce the same output from str() and class(), except that the data inside is different (i.e. different numbers of ASVs, different numbers and names of samples, different ASV counts per sample, etc.). I set the colnames of the taxonomy table manually, and the error remains. As far as I can tell, the class types of the taxa table are correct (i.e. the input taxa table for phyloseq creation is class "matrix", with class "character" for all columns).

I'm attaching an RDS with the offending object in it. Any help debugging this is appreciated.
[all_combined.phyloseq.RDS.zip](https://github.com/joey711/phyloseq/files/3056807/all_combined.phyloseq.RDS.zip)

**Comment by mikemc** [comment]
@morien I'm not sure exactly what is happening, but the problem has to do with your OTU table having NAs. I don't think phyloseq is designed to work with tables with NA entries. Try filtering the samples or taxa with NAs, or going back to when you created your table to see where the NAs are coming from, or replacing the NAs with zero. Then tax_glom should work.

**Comment by morien** [comment]
thanks! i feel a bit foolish, this fixed the issue. i was doing something hacky to combine datasets and it introduced NAs. i didn't even think about it at the time.
