### ISSUE TITLE
Sample name in OTU table has been changed automatically.

### ISSUE THREAD

**Issue by ysso1215** [joey711/phyloseq#1122]
Hello!
I have a problem to read my OTU table (.txt) converted from biom file in R.
After read in OTU table, a character 'X' is added in front of each sample name automatically.  
Although I removed the 'X' in file, the 'X' was automatically re-added after reading in R. 
Please see the below.

OTU table (otu_table.txt) Constructed from biom file
>OTUID	0_0_1	0_0_2	0_0_3	0_0_4	0_1_1	0_1_2	0_1_3	0_1_4	0_2_1	0_2_2	0_2_3	0_2_4	0_3_1	0_3_2

read in OTU table in R
>otu<-read.table(file="otu_table.txt", header=TRUE)
>head(otu)

>  OTUID X0_0_1 X0_0_2 X0_0_3 X0_0_4 X0_1_1 X0_1_2 X0_1_3 X0_1_4 X0_2_1
1 f55f526b5bfaa986c809b1f00201105c     49     26     38     34     84     25     10     54      7

For the phyloseq, I need to merge files into one phyloseq object, but it was failed because of the different sample names.

> physeq=phyloseq(OTU, TAX, META, phy_tree)

>Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component sample names do not match.
 Try sample_names()

Please help, I need your advice!

Best wishes
Soyoung Yeo

**Comment by mikemc** [comment]
Soyoung, you just need to make the sample names match before calling the `phyloseq()` function. How you do this is up to you, and there are many ways to go about it. If all you want to do is remove the first character (the "X") from the sample names in the OTU table, you can do
```r
otu<-read.table(file="otu_table.txt", header=TRUE)
OTU <- otu_table(otu, taxa_are_rows = TRUE)
sample_names(OTU) <- substring(sample_names(OTU), 2)
# Check the new sample names
head(sample_names(OTU))
```
and then proceed with creating the phyloseq object. But I recommend keeping the "X", or perhaps using an "S" for "sample", to avoid possible problems later with having the first character of your sample names being a number. In that case, you could do, after first doing the above,
```r
sample_names(OTU) <- paste0("S", sample_names(OTU))
sample_names(META) <- paste0("S", sample_names(META))
```

**Comment by ysso1215** [comment]
Michael, 
I added a "S" to each sample name in all data files, and the problem solved. 
I really appreciate your help.
