### ISSUE TITLE
Relative abundance_Out of 100%

### ISSUE THREAD

**Issue by EOMAK91** [joey711/phyloseq#1151]
Hi everyone,

So I'm new to the phyloseq package but trying to process my data. Unfortunately we have an uneven number of mice (12,12,11). When I plot the relative abundance, I get three bar stacked bar graphs with the Y-axis that says 12, 12, 11. I'd like it to be out of 100%. I've tried what others did (transform_sample_counts(ps0, function(x) 100 * x/sum(x))), but that didn't help all it did was multiply it by 100, so instead of 12, its 1200. Any help would be appreciated.

#load data
seqtab1 <-read.delim("seqtab1.txt")
taxtab1 <-read.delim("taxtab1.txt")
samdf1 <-read.delim("samdf1.txt")

set.seed(100)

#modify seqtab - sequence table
row.names(seqtab1) <- seqtab1$X
seqtab1$X <- NULL
seqtab1<-as.matrix(seqtab1)

#modify taxtab - taxonomy table
row.names(taxtab1) <- taxtab1$X
taxtab1$X <- NULL
taxtab1<-as.matrix(taxtab1)

#Transpose seqtab matrix
seqtab1 <- t(seqtab1)

#Confirm that SampleID equals seqtab rownames
all(rownames(seqtab1) %in% samdf1$SampleID) #TRUE

#Name samdf rows
rownames(samdf1) <- samdf1$SampleID
class(samdf1) #keep as data.frame

##treefile
treefile <- read.tree("99_otus.tree")

#Create object that combines all data
ps <- phyloseq(tax_table(taxtab1), sample_data(samdf1), otu_table(seqtab1, taxa_are_rows = FALSE), phy_tree(treefile))
ps

#find low prevalence phyla
ps0<-ps
prevdf = apply(X = otu_table(ps0),
               MARGIN = ifelse(taxa_are_rows(ps0), yes = 1, no = 2),
               FUN = function(x){sum(x > 0)})
# Add taxonomy and total read counts to this data.frame
prevdf = data.frame(Prevalence = prevdf,
                    TotalAbundance =taxa_sums(ps0),
                    tax_table(ps0))
plyr::ddply(prevdf, "Phylum", function(df1){cbind(mean(df1$Prevalence), sum(df1$Prevalence))})

# Define phyla to filter
filterPhyla = c("p__Fusobacteria", "p__Chloroflexi", "p__Euryarchaeota")
# Filter entries with unidentified Phylum.
ps0 = subset_taxa(ps0, !Phylum %in% filterPhyla)
ps0

# Define prevalence threshold as 5% of total samples
prevalenceThreshold = 0.05 * nsamples(ps0)
prevalenceThreshold
# [1] 1.75

# Execute prevalence filter, using `prune_taxa()` function
prevdf1 <- subset(prevdf, Phylum %in% get_taxa_unique(ps0, "Phylum"))
keepTaxa <- rownames(prevdf1)[(prevdf1$Prevalence >= prevalenceThreshold)]
ps0 <- prune_taxa(keepTaxa, ps0)
ps0

#normalize
ps0 = transform_sample_counts(ps0, function(x) x/sum(x))

#Phylum
plot_bar(ps0, x = "Group", fill = "Phylum")+
  geom_bar(aes(color=Phylum, fill=Phylum), 
           stat="identity", position="stack")+
  ylab("Relative Abundance")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

**Comment by mikemc** [comment]
I describe one way to deal with this problem [here](https://github.com/joey711/phyloseq/issues/1089#issuecomment-471334036).

Note, the `plot_bar()` function already adds a `geom_bar()` to the `ggplot` object, so you probably do not want to add another `geom_bar()` on top of it. If you want to build up the bar plot yourself (a good idea for your long-term understanding of R graphics) then you should start with the data frame and build up the ggplot object from scratch. You can do this by
```r
df <- psmelt(ps0)
ggplot(df, aes(Group, Abundance, fill = Phylum)) +
    geom_bar(stat="identity")+
    ylab("Relative Abundance")+
    theme_minimal()+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))   
```
This is essentially what the `plot_bar()` function internally.

**Comment by EOMAK91** [comment]
Thanks Mike. If I was interested in faceting by another variable how would one go about that?
I also noticed that the sample merge removed the original lettering on my samples, I compared it to the raw graphs to guide me recoding it.

df <- psmelt(ps0)
df$Group <- factor(df$Group, levels = c("1", "2", "3"), labels =c("HF0", "HF15", "LF")) 

You are right, there was no need to add the geom_bar to the ggplot object.

I had one more question regarding the faceting. The faceting according to phylum works out fine, but when I facet based on something like family, there are too many families and the graph becomes overcrowded. I was wondering if there was a way such that only the top 15 families would appear, thereby reducing the amount of space I would need to plot the faceted bar graphs.

**Comment by mikemc** [comment]
You seem to be using "faceting" to mean the fill color. Faceting is something else, see here: http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/

You can certainly make a barplot that only shows a subset of "top" families. As a starting point I'll take `ps0` that you've created above. Then we merge the samples with the same Group and normalize to proportions.
```r
ps1 <- merge_samples(ps0, "Group")
ps1 <- transform_sample_counts(ps1, function (x) x / sum(x))
```
Then aggregate OTUs to the family level.
```r
ps2 <- tax_glom(ps1, "Family")
```
There isn't one correct way to decide which families to include. For illustration, let's say you want to keep families that have a proportion > 0.05 in at least one "Group". Then you could do
```r
ps3 <- filter_taxa(ps2, function (x) max(x) > 0.05)
```
If instead you wanted the top 15 families as defined by the mean proportion of the family across Group's, you would first need to get a list of the families you want to keep and use `prune_taxa()`. You could do this by
```r
top_families <- names(sort(taxa_sums(ps2), decreasing = TRUE)[1:15])
ps3 <- prune_taxa(top_families, ps2)
```
Please check the documentation for all of these functions and check that this makes sense. Now you can make the plot:
```r
df <- psmelt(ps3)
ggplot(df, aes(Group, Abundance, fill = Family)) +
    geom_bar(stat="identity")+
    ylab("Relative Abundance")+
    theme_minimal()+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```

**Comment by EOMAK91** [comment]
Hi Mike,

Once again thank you so much, I actually ended up figuring this out. 
What I ended up doing was 

```
psF <- filter_taxa(ps2, function (x) max(x) > 0.05)
top20otusFam = names(sort(taxa_sums(psF), TRUE)[1:20])
psFam20 = prune_taxa(top20otusF, psF)
```

I decided to both plot the unfiltered taxa and the filtered taxa (above is the code that plots the filtered set). Using the code to filter kept my abundance above 95% and therefore I don't think I'll re-normalize.

Thank you once again!
