### ISSUE TITLE
Phyloseq subsetting at import step?

### ISSUE THREAD

**Issue by mstagliamonte** [joey711/phyloseq#1155]
Hi,

I have an OTU table with 2366 OTUs; when importing it with Phyloseq, I get a total of 2207. I was wondering how Phyloseq subsets the OTUs. I am probably missing something simple here.

Thank you for your kind attention,
Max

**Comment by mikemc** [comment]
When you call `phyloseq(...)` it subsets samples and taxa to the minimum set that is shared by all the objects in the (...). So if your tax table or phylogeny doesn't have all of the OTUs in the OTU table, some OTUs will be dropped.

**Comment by mstagliamonte** [comment]
Hi, @mikemc ,

Thank you for your insight. I have checked the tree file and only has 2,207 taxa. I need to review the pipeline calling OTUs to try and understand the reason.

OK, problem solved, at least concerning the Phyloseq part.

Best,
Max
