### ISSUE TITLE
Remove zeroes from a phyloseq object

### ISSUE THREAD

**Issue by ArneClaeys** [joey711/phyloseq#1164]
ps.filter.fam.rel  <- transform_sample_counts(ps.filter.fam, function(x) x / sum(x))

I get some relative abundances as follows: 0.00000000+0. Is there a way to remove them, I need the ps.filter.fam.rel in another line of code and get an error because of these 0 values.

**Comment by mikemc** [comment]
You can use the `transform_sample_counts()` function to transform the abundances however you like. It is up to you to decide which transformation is most appropriate for your goals. A common solution is to add a pseudocount to the read counts _before_ normalizing to proportions. So, if you are starting with read counts, you might do
```r
ps.filter.fam.rel <- transform_sample_counts(ps.filter.fam, function(x) {x <- x + 0.5; x / sum(x)})
```
However, whether such a pseudocount transformation is appropriate depends on your later analysis and goals. Try searching for "pseudocounts" and "transformations" and "normalizations" and "microbiome analysis"; there are many articles discussing this complex topic.
