### ISSUE TITLE
How to Set Plot_Richness Scale to a fixed value for Specific Plots

### ISSUE THREAD

**Issue by compbiolover** [joey711/phyloseq#1173]
Hi all,
I currently have 6 total richness plots generated using the plot_richness function. Unfortunately, the scale of one of the panels is different between my two variables of interest. I was hoping to find a way to manually set the scale of just those plots while leaving the others untouched. Thanks in advance!

**Comment by mikemc** [comment]
Look at the help for the `facet_wrap()` function from `ggplot2`, and in particular the `scales` option. Setting the relevant scales to "free" might fix the problem. I think you can override the faceting created by `plot_richness()`,
```r
p <- plot_richness(<ARGS>)
p +
  facet_wrap(<ARGS>)
```
but you might need to / be better off using `estimate_richess()` to get the data-frame and building up the plot your self.

**Comment by compbiolover** [comment]
@mikemc Awesome, will check out these suggestions. Thanks.
