### ISSUE TITLE
Subset by sample ID

### ISSUE THREAD

**Issue by FelixGiraud** [joey711/phyloseq#1185]
Hello, 

I'm trying to subset my otu_table by sample ID to plot properly some data. The thing is i can't figure out how to subset by sample ID. 

For example my sample names looks like this :

V1.T0.ZNT, V1.T1.ZNT , V2.T0.ZNT , V1.T1.ZNT , V3.T0.ZNT........... V20.T0.ZT7

And i would like to plot only sample at T0 for instance.

Any idea would be really appreciated. 
Thank you for your time.

Ps: Sorry if i missed one subject already talking about it, but i've been looking all day and i didn't find one :3

**Comment by mikemc** [comment]
To subset samples by name, use `prune_samples()`. If you want to subset by a variable in your `sample_data`, then you can use `subset_samples()`. E.g., if you have a sample variable called "Time" you would do `subset_samples(ps, Time == 0)`. An example of subsetting is given in the phyloseq basics vignette. See also the help for those two functions.

**Comment by FelixGiraud** [comment]
Thank you for your answer ! I can now close the subject.
