### ISSUE TITLE
error with mergeSequenceTables

### ISSUE THREAD

**Issue by lara-whoi** [joey711/phyloseq#1195]
Hello -
 I've created two sequencing tables, from two separate sequencing runs (one with Illumina and one with 454).  

I've processed both sets at SE reads.  

Both seqtab contain fragments of exactly 255 bp

 [(and primers are removed (using 27F and 519R)] 

However I think I need to reconfigure these two sequence tables.  When I try to merge the two tables, I receive this error:

Error in rval[rownames(tab), colnames(tab)] + tab : 
  non-conformable arrays

This was the command I used:

st.two <-mergeSequenceTables(seqtab1114,seqtab4901)

Also - I saved the seqtab .rds files as pdfs and attached them.

thanks so much!

**Here was some of the upstream script for
[seqtab1114 seqtab1114.csv.pdf](https://github.com/joey711/phyloseq/files/3422672/seqtab1114.seqtab1114.csv.pdf)
** 

derep_forward <- derepFastq(filtered_forward_reads, verbose=TRUE)
```

```{r}

dada_forward1114 <- dada(derep_forward, err=err_forward_reads, HOMOPOLYMER_GAP_PENALTY=-1, BAND_SIZE=32, multithread=TRUE)
```

```{r}
seqtab1114 <- makeSequenceTable(dada_forward1114)
```

```{r}
dim(seqtab1114)
```
[1]   2 858

```{r}
saveRDS(seqtab1114, file = 'seqtab1114New.rds')
```
```{r}
table(nchar(getSequences(seqtab1114)))
```
255 
858 

AND here for the illumina run

derep_forward <- derepFastq(filtered_forward_reads, verbose=TRUE)
```
Dereplicating sequence entries in Fastq file: 4901_R1_filtered.fq.gz
Encountered 21046 unique sequences from 34489 total sequences 

[seqtab4901 seqtab4901.csv.pdf](https://github.com/joey711/phyloseq/files/3422660/seqtab4901.seqtab4901.csv.pdf)
[seqtab4901 seqtab4901.csv.pdf](https://github.com/joey711/phyloseq/files/3422662/seqtab4901.seqtab4901.csv.pdf)


```
{r}
names(derep_forward) <- samples
```

```{r}
dada_forward <- dada(derep_forward, err=err_forward_reads, multithread = TRUE)
```
```{r}
seqtab4901 <- makeSequenceTable(dada_forward)
```
```{r}
dim(seqtab4901)
```
```{r}
table(nchar(getSequences(seqtab4901)))
```

255 
963

**Comment by mikemc** [comment]
This seems to be a question about DADA2, not phyloseq. You should move it over to https://github.com/benjjneb/dada2/issues

**Comment by lara-whoi** [comment]
Oops - thanks!
