### ISSUE TITLE
Corresponding samples and taxa

### ISSUE THREAD

**Issue by memoll** [joey711/phyloseq#1200]
Hi!

I was wondering if each time we prune_samples(), then we should correspond the taxa in the new object to the samples as well, and vice versa!

Example:
`ps2 = prune_samples(sample_data(ps)$sample_or_control == "control"), ps)`
 `ps2 = prune_taxa(taxa_sums(ps2) > 0, ps2)`

Best,
Mona

**Comment by roey-angel** [comment]
Naturally, when removing one or more samples you might end up with some taxa with 0 abundance in your tax_table.
This may or may not interfere with downstream analysis (depending on the method), but I regularly prune 0-abundance taxa every time I drop some samples, just in case.

**Comment by memoll** [comment]
Thanks @roey-angel ! This is also what I learned to do by experience. I just wanted to make sure it's the right way to do it :)
