### ISSUE TITLE
Merging specific sample combinations

### ISSUE THREAD

**Issue by grantbenjensen** [joey711/phyloseq#1201]
Hi, I am a relatively new phyloseq user and am attempting to merge specific sample combinations together to observe temporal trends in alpha diversity. 

In the example here I have a variety of samples taken at different points in time and want to view alpha diversity changes as a function of time (on the x-axis). Additional treatments/categories exist within each time point, one of which is whether fertilizer was added (Y/N). 

I visualized these variables together very simply with the plot_richness function:
`plot_richness(physeq, x="Time", color="Fertilizer", measures=c("Shannon"))`
![image](https://user-images.githubusercontent.com/23264809/62166294-66502600-b2ee-11e9-8090-5f99810c7fb0.png)

The only change I wish to make is to merge all fertilizer samples at a particular time point together so that there are only 2 points per time category (merged Y and merged N at each of D01, D08, etc).

From what I have seen in the examples in the tutorials merging samples is done across a variable to create a new category from the subset of options (e.g sample types organized into human or non-human origin). If I do something similar it will merge fertilizer of the same status across different time points together. I feel like there is a relatively simple way to do this that I just haven't seen yet. 

Either way any help is greatly appreciated!

**Comment by j0eschm0** [comment]
I am running into the same problem, did you figure it out?

**Comment by j0eschm0** [comment]
I didn't find the exact answer, but one option would be to  add  geom_boxplot() and then remove the individual dots to only show the box plots which is achieved by removing a layer, see link to Joey's code.

https://github.com/joey711/phyloseq/issues/836#issuecomment-342258516

If you do find answer to your question let me know!

**Comment by grantbenjensen** [comment]
I did end up using geom_boxplot() as you've said and removing the points all through ggplot so it was not really a phyloseq issue.
