### ISSUE TITLE
How to insert axis label in beta diversity

### ISSUE THREAD

**Issue by yogeshgupt** [joey711/phyloseq#1210]
Hi, 

could you please suggest me, how can insert axis label as PC1 and PC2 with percent of variance in the below code.

Now It is showing label as Axis1 (20%), Axis2(13%), I want PC1 and PC2 instead of axis.

phyloseq_prop = transform_sample_counts(ps5, function(x) 1E6 * x/sum(x))

phyloseq_prop_bray <- ordinate(phyloseq_prop, "PCoA", "bray")
p=plot_ordination(phyloseq_prop,phyloseq_prop_bray, color = "Treatment", shape="Villages")
p = p + geom_point(size = 4, alpha = 0.75)
p + ggtitle("PCoA 16S data, Bray distance")

Thanks

**Comment by evertonjlima** [comment]
You can make use of the [labs](https://ggplot2.tidyverse.org/reference/labs.html) function of ggplot2.

```
p + ggtitle("PCoA 16S data, Bray distance") + labs(x='PC1 [%?]', y='PC2 [%?]')
```

**Comment by yogeshgupt** [comment]
> You can make use of the [labs](https://ggplot2.tidyverse.org/reference/labs.html) function of ggplot2.
> 
> ```
> p + ggtitle("PCoA 16S data, Bray distance") + labs(x='PC1 [%?]', y='PC2 [%?]')
> ```
