### ISSUE TITLE
Unable to reorder names in Phyloseq

### ISSUE THREAD

**Issue by shashibisht9** [joey711/phyloseq#1254]
I am unable to reorder names in my alpha diversity plot. I want to arrange the treatment in order Control 1, Control 2, WT, S839I, S839I (No Antibiotic), S839I (Antibiotic Treated). Enclosed the script and alpha diversity plot.
[script_diversity_plot.docx](https://github.com/joey711/phyloseq/files/3772236/script_diversity_plot.docx)

[Treatment_AlphaDiv.pdf](https://github.com/joey711/phyloseq/files/3772231/Treatment_AlphaDiv.pdf)

**Comment by mikemc** [comment]
You need to make the treatment a "factor" in R. You can do this either in the `sample_data(ps)` object, or in the data frame that makes the plot. For more help, try searching in the open and closed issues, or google how to create factors or convert data frame variables to factors, as well as how to order character values / categorical values in ggplot2

**Comment by shashibisht9** [comment]
Thank you for solving my issue.
