### ISSUE TITLE
How can I get distance between sample using phyloseq?

### ISSUE THREAD

**Issue by shashankx** [joey711/phyloseq#1274]
I have a phyloseq object, where I have 100 samples, out of which 50 samples from the left hand (skin samples) and other 50 samples from the right hand (skin samples). I would like to calculate the distance between these two samples that individual microbiome are closer to each other than other individual skin microbiomes. 
Are there any functions or scripts that could help me with this?
Best, Shanky

**Comment by fconstancias** [comment]
Hi Shanky.
Please have a look here : https://github.com/joey711/phyloseq/issues/714
