### ISSUE TITLE
Pairwise comparison after adonis test

### ISSUE THREAD

**Issue by MaristelaMorais** [joey711/phyloseq#1292]
Hello!
I have a phyloseq object of the following dimension. Containing 182 samples and 4 field treatments.
phyloseq-class experiment-level object:
otu_table() OTU Table: [ 5666 taxa and 182 samples ]
sample_data() Sample Data: [ 182 samples by 52 sample variables ]
tax_table() Taxonomy Table: [ 5666 taxa by 8 taxonomic ranks ]
refseq() DNAStringSet: [ 5666 reference sequences ]

I'm using adonis test on RStudio to determine significant treatment affects.
To do that I used the command:
all_OTUs = names(sort(taxa_sums(F1_phyloseq), TRUE))
GPex = prune_taxa(all_OTUs, F1_phyloseq)
GPdist = phyloseq::distance(GPex, "bray")
GPNMDS = ordinate(GPex, "NMDS", GPdist)
adonis(GPdist ~ Treatment, as(sample_data(GPex), "data.frame"))

And I obtained a result like this:
Permutation: free
Number of permutations: 999
Terms added sequentially (first to last)

           Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
Treatment   4     9.074 2.26844   6.599 0.12978  0.001 ***
Residuals 177    60.845 0.34375         0.87022           
Total     181    69.918                 1.00000           
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

There is a significant difference between the treatments, but I would like to ask if it is possible to use adonis function to determine the treatments significantly different and differences between each treatment, like on a pairwise comparison.

Can someone help me with that issue?
Thanks!

**Comment by SteffenSchwaiger** [comment]
Maybe this library can help you: [Pairwise Adonis](https://github.com/pmartinezarbizu/pairwiseAdonis)

**Comment by MaristelaMorais** [comment]
Hi Steffen!
Thanks for the help!
