### ISSUE TITLE
Barplot of Relative Abundance Does Not Stack to 100% 

### ISSUE THREAD

**Issue by REngstrand** [joey711/phyloseq#1293]
Hi

I am trying to make a barplot of relative abundance of phyla in my ITS dataset. 

I type the following code to get relative abundance of phyla in my data:

ps_phylum <- mines %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  filter(Abundance > 0.02) %>%                         # Filter out low abundance taxa
  arrange(Phylum)                                      # Sort data frame alphabetically by phylum

I have double checked that this creates an abundance looking at: ps_phylum$Abundance, and that there are no unknowns visually inspecting output of this command: unique(ps_phylum$Phylum)

When I make a plot, using code:
ggplot(ps_phylum, aes(x = Age, y = Abundance, fill = Phylum)) + 
  facet_grid(Disturbance~Cover) +
  geom_bar(stat = "identity") +
  scale_x_discrete(labels=c("0-4", "5-10", "11-14","15+","Unmined"))+
  guides(fill = guide_legend(reverse = TRUE, keywidth = 1, keyheight = 1)) +
  ylab("Relative Abundance (Phyla > 2%) \n") +
  ggtitle("Phylum Composition of Soil Fungi \n Fungal Communities by Sampling Site and Depth") 

I get a stacked barplot. The scale goes from 0-8 when I expect it to go from 0-1. Likewise, the barplots do not all sum to 1, or even to the same value on the mysterious 0-8 scale. Do you know what is the cause of this? I have been messing with this for ages. The same thing happens when I try Family, Order, Genus, etc.

![image](https://user-images.githubusercontent.com/21990888/73600799-6b469a00-450a-11ea-9ba1-9db0ba4e7d8d.png)

**Comment by Misemi9** [comment]
Is there a solution to this issue? I have the same problem and I don't find a solution anywhere.
