### ISSUE TITLE
Change facet labels for plot_richness

### ISSUE THREAD

**Issue by bethang7607** [joey711/phyloseq#1302]
This feels like a very obvious stupid question.. but how can the facet labels for plot_richness be changed?

I made a boxplot of richness (Observed) and Shannon-Wiener diversity (Shannon) by Site:
p <- plot_richness(T0_rarefied, x = "Site", measures = c("Observed", "Shannon")) + 
  geom_boxplot(lwd=1.2, alpha=0.7, aes(fill=Site))

Then made a new labelling vector for variable:
p.facet.labels <- c(Observed = "OTU Richness", Shannon = "Shannon-Wiener Diversity")

Then tried to facet by variable with the new labels. The facet labels changed, but now both facets are on the same scale and scales="free_y" doesn't let each facet have its own scale.
p + 
  facet_grid(~variable,  labeller=labeller(variable = p.facet.labels), scales="free_y")

Is there a blindingly obvious solution?

**Comment by cresil** [comment]
Use facet_wrap rather than facet_grid

**Comment by bethang7607** [comment]
Heh. Definitely thought I'd already tried this. I knew it was an obvious fix! Thanks!
