### ISSUE TITLE
facet_grid in plot_richness 

### ISSUE THREAD

**Issue by henganl2** [joey711/phyloseq#1327]
Hello, 

I am trying to use plot_richness with facet_grid, but it doesn't work as I thought. 

Here is my code: 

`p <- plot_richness(mergephyseq_mergeOTU, x ="Stage", color="Seed", measures=c("Observed", "Shannon", "Simpson") )+ geom_boxplot()
`

![Rplot](https://user-images.githubusercontent.com/33666783/81371006-47bc5e00-90bc-11ea-9f25-fe97bf079942.png)

I want to further separate the plot by "Seed".  The plot I want should look like

![Picture2](https://user-images.githubusercontent.com/33666783/81372977-4a6d8200-90c1-11ea-9190-92cac9ac1ac6.png)

I tried to use facet_grid as follow

`p <- plot_richness(mergephyseq_mergeOTU,  x ="Stage", color="Seed" , measures=c("Observed", "Shannon", "Simpson") )+ geom_boxplot()+facet_grid(~Seed)
`
But the figures turns out like this

![Rplot01](https://user-images.githubusercontent.com/33666783/81371187-c9ac8700-90bc-11ea-85f2-11557c7481ef.png)

I think my problem might be similar to [#363](https://github.com/joey711/phyloseq/issues/363), but I just can't figure it out. 

Can anyone give me some advice to solve this problem? 

Thank you in advance!

**Comment by fconstancias** [comment]
The following should work:
`p <- plot_richness(mergephyseq_mergeOTU, x ="Stage", color="Seed" , measures=c("Observed", "Shannon", "Simpson") )+ geom_boxplot()+facet_grid(variable~Seed) `

If you check how data are organized after using plot_richness():
`p <- plot_richness(mergephyseq_mergeOTU, x ="Stage", color="Seed" , measures=c("Observed", "Shannon", "Simpson"))`

`p$data`

You will see that it is in long format and the **variable** column differentiate between metrics.

**Comment by henganl2** [comment]
Hi @fconstancias , 

Thanks for your response! 
I try the code you suggest as follow

`p <- plot_richness(mergephyseq_mergeOTU, x ="Stage", color="Seed" , measures=c("Observed", "Shannon", "Simpson") )+ geom_boxplot()+facet_grid(Seed~variable)`

![Rplot](https://user-images.githubusercontent.com/33666783/81441299-264c8800-9137-11ea-9faa-e2282df173cc.png)

But the Y-axis for Shannon and Simpson disappear
I try to add `facet_grid(Seed~variable, scales = "free_y")`
It returns the same result. 

How do I fix this?

**Comment by fconstancias** [comment]
my bad, `facet_grid(variable ~ Seed, scales = "free_y")` should do the job.

**Comment by henganl2** [comment]
When I tried `facet_grid(variable ~ Seed, scales = "free_y")`, only the Y-axis on the first grid change

![Rplot01](https://user-images.githubusercontent.com/33666783/81444202-65310c80-913c-11ea-9177-e1ba3ca66304.png)

then I add 

`facet_grid(Seed ~ variable)+facet_wrap(Seed~variable, scale="free_y")`

It kind of works, but I wonder how to move the "Seed" information to the right side of the figure...

![Rplot02](https://user-images.githubusercontent.com/33666783/81444217-68c49380-913c-11ea-8ad6-5e54c0ed27c9.png)

**Comment by henganl2** [comment]
Thanks for your reply!! I figure it out.

**Comment by als3376** [comment]
I have the same problem. I done up to 

facet_grid(Seed ~ variable)+facet_wrap(Seed~variable, scale="free_y")
It kind of works, but I wonder how to move the "Seed" information to the right side of the figure...

Can you tell me what you did after that?
