### ISSUE TITLE
Rename data functions for consistency, and "taxa" instead of "species"

### ISSUE THREAD

**Issue by joey711** [joey711/phyloseq#136]
Old name      New Name

(Accessors)
getSpecies  get_taxa
getSamples  get_samples
getTaxa     get_taxa_unique
getVariable get_variable
nsamples    nsamples
nspecies    ntaxa
rank.names  rank_names
sample.names    sample_names
species.names   taxa_names
sampleSums  sample_sums
speciesSums taxa_sums
sample.variables    sample_variables
speciesAreRows  taxa_are_rows
otuTable    otuTable
taxTab      taxTable
tre     tree
samData     samData

(Processors)
merge_phyloseq  merge_phyloseq
merge_samples   merge_samples
merge_species   merge_taxa
tipglom     tip_glom
taxglom     tax_glom
transformSampleCounts   transform_sample_counts
filterfunSample     filterfun_sample
genefilterSample    genefilter_sample  
prune_species   prune_taxa
subset_species  subset_taxa 
subset_samples  subset_samples

**Comment by marsfro** [comment]
Hello! Couldn't you help me! I can't to add sample data to my phyloseq object from biom-kraken file:
> sample_names(com2@sam_data)
NULL

> com2
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1111 taxa and 3 samples ]
tax_table()   Taxonomy Table:    [ 1111 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 1111 tips and 1110 internal nodes ]
