### ISSUE TITLE
How to import metaphlan merged_abundance file into phyloseq

### ISSUE THREAD

**Issue by DEEPCHANDA7** [joey711/phyloseq#1365]
Hi... I have analysed shotgun metagenomic data with metaphlan 3.0. Now, I want to do statistical analysis with the output data. All the abundance profile files from 60 samples have been merged into a single abundance file. Rows are taxa and columns are samples.  But I am wondering as there's no phyloseq importer function available for metaphlan. 
Can anyone please help me ?

**Comment by sarahisherb** [comment]
Hi! Did you ever figure this out?
