### ISSUE TITLE
How to investigate plot results from differential abundance test?

### ISSUE THREAD

**Issue by MaristelaMorais** [joey711/phyloseq#1379]
Dear all,

I'm working on differential abundance with my 16S amplicon sequencing data and to do that I followed the example documentation on this topic ([http://bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-mixture-models.html](http://bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-mixture-models.html)).

As the suggested example, I used a covariate to compare the microbiomes of pairs of pasture and sugarcane soils. 
Some OTUs (ASVs) were among the significantly deferentially abundant between the soil samples. 
When I plot the log2-fold-change result showing the Phylum and ASVs differences, I would like to know if it's possible to infer or conclude based on the log axis which side (0 to -6 or 0 to 6) is attributed to the type of soil use (in my case, pasture or sugarcane). 

![example](https://user-images.githubusercontent.com/54032420/89420065-95bb1f00-d708-11ea-90f7-e208545e1886.jpeg)

Is it possible to have this kind of information based on the test result table and plot?

Thank you very much for attention. 

Kind regards,
Maristela

**Comment by rogarcia1992** [comment]
Hi Maristela, 

I have the same question. Where you able to find a solution? I would like to include in the plot the environmental gradientes from which I sampled as shape or different facets.

**Comment by MaristelaMorais** [comment]
Hello, Garcia.

I haven't find any solution yet.
However I found a paper that used shapes for samples conditions and indicated which size of the differential abundance plot belongs to their experimental conditions. So, I do suppose it's possible. I tried to get in touch with the authors to know how they did it but got no answer.
You can find the paper here: [https://doi.org/10.3389/fmicb.2019.02371](url)

If I figure out something, I'll post here.

Thank you!

**Comment by MaristelaMorais** [comment]
Hi, Garcia.

I got the answer from the authors. And I hope that helps you as well.

To include the metadata variables to the plot, one option is to merge your metadata file (data frame format) to the differential abundance table results but those files must have the same sampleIDs. 
You can follow merge commands here for R:  https://www.statmethods.net/management/merging.html

Then, you just have to use ggplot2 commands like that:
ggplot(da_type, aes(y=interaction(OTU, Phylum), x=log2FoldChange, color= Brand, shape = Condition)) + geom_vline(xintercept = 0.0, color = "gray", size = 0.5) + geom_point(size=2) + theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust=0.5))

Use color and shape for your environmental data.

Some documents that might help to understand better about DeSeq2:
https://doi.org/10.1186/s13059-014-0550-8

http://bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-mixture-models.html

**Comment by rogarcia1992** [comment]
Hi Maristela,

Thank you for your help! I will try to make this work. Hope it works for
you as well.

Best regards,
Ray.
