### ISSUE TITLE
Filtering taxa based on relative abundance

### ISSUE THREAD

**Issue by srisvs33** [joey711/phyloseq#1385]
Hello community

I am relatively new to R.
I want to filter the taxa (relative abundance) from a phyloseq object (physeq) and create a new phyloseq object (physeq1) for those taxa which falls between >1% and <0.1% of the of the total percentage of reads. How do i set up my filter_taxa functions. 

Many thanks in advance

Regards
Venkat

**Comment by rogarcia1992** [comment]
Hi,

See command line below, hopefully this helps.

SAM_OTUTAX_Phylum <- SAM_OTUTAX %>%
  tax_glom(taxrank = "Phylum") %>%
  transform_sample_counts(function (x) {x/sum(x)}) %>% 
  psmelt() %>%
  filter(Abundance > 0.02) %>%
  arrange(Phylum)

**Comment by srisvs33** [comment]
Many thanks @rogarcia1992 

It worked very well. 

regards
Venkat
