### ISSUE TITLE
Bubble plot of relative abundance from phyloseq object

### ISSUE THREAD

**Issue by mguid73** [joey711/phyloseq#1396]
Hi! I've tried several different scripts to make a bubble plot for relative abundance data, and I've had no luck. 
Does anyone know of a way to make a plot like the one attached from a phyloseq data frame? Other suggestions welcomed!
<img width="802" alt="Screen Shot 2020-09-28 at 3 02 41 PM" src="https://user-images.githubusercontent.com/42591287/94474441-aa151880-019b-11eb-92ce-a650f762f898.png">

**Comment by sklasek** [comment]
Hi Megan,
Maybe you could do something like this:

`f.ra <- transform_sample_counts(ps.frdp, function(OTU) OTU/sum(OTU)) # creates relative abundance phyloseq object
f.ra.top.c <- subset_taxa(f.ra, Class=="JS1" | Class=="Deltaproteobacteria" | Class=="Methanomicrobia" | Class=="Dehalococcoidia" | Class=="Anaerolineae" | Class=="Campylobacteria" | Class=="Aminicenantia" | Class=="Bacteroidia" | Class=="Phycisphaerae" | Class=="Lokiarchaeia" | Class=="Woesearchaeia" | Class=="Gammaproteobacteria" | Class=="Thermoplasmata" | Class=="Alphaproteobacteria" | Class=="Nitrososphaeria") # top 15 classes

# use a nested for-loop to pull relative abundance data out of phyloseq objects (by taxonomic division):
graphclass <- unique(tax_table(f.ra.top.c)[,3])
graphclass <- as.vector(graphclass)
class.sums.m <- matrix(nrow=76, ncol=15) # define matrix dimensions like this
rownames(class.sums.m) <- sample_names(f.ra.top.c) # specify row names
colnames(class.sums.m) <- graphclass # specify column names

for (i in sample_names(f.ra.top.c)) { 
  for (j in graphclass) {
        class.sums.m[[i,j]] <- sum(otu_table(f.ra.top.c)[sample_names(f.ra.top.c)==i,which(tax_table(f.ra.top.c)[,3]==j)]) # this is calculating the average percent abundance of each class
    }
}
# make data frames (in long format) from the matrix of abundances to use with ggplot
flux.class.wide <- t(class.sums.m)
taxonrep <- rep(rownames(flux.class.wide), each=76)
tax <- as.character(taxonrep)
grouprep <- colnames(flux.class.wide)
groups <- rep(grouprep,times=15)
abund <- as.numeric(t(flux.class.wide))
longdf <- cbind.data.frame(tax,abund,groups)
`
Noting here that I'm selecting fifteen microbial classes and have 76 samples. 
Happy to share more code or explain anything that isn't clear...
-Scott

**Comment by mguid73** [comment]
Thanks so much for the input, Scott! I've got a nice script up and running now. Take care!

**Comment by Dasia-w** [comment]
Hi Megan, do you mind sharing your scripts? I'm a newbie and this seems the only source I found discussing bubble plot with phyloseq object. Thank you__Dasia

**Comment by mguid73** [comment]
Hi Dasia, I've pasted below the code I was able to use most successful. I didn't end up using the phyloseq data frame, but this script used the same input files. I would be happy to answer any questions!

`## BUBBLE PLOT OF RELATIVE ABUNDANCES ACROSS SAMPLE GROUPS
# Modified script from:
# https://github.com/alex-bagnoud/OTU-table-to-bubble-plot
# author:alexandre.bagnoud@gmail.com
# version: 06.07.2018

# set working directory
getwd()
setwd("/Users/meganguidry/Desktop/KellyLab/BubblePlot_Sept")

# Before starting script, we have to create an ASV table with relative abundances instead of raw read counts
OTU = read.table("ASVtable.txt", header=TRUE, sep="\t", row.names = 1)
RAtab <- sweep(OTU,1,rowSums(OTU),"/")
#write.csv(RAtab, "ASVtablePercent.csv") #uncomment this to write out your new ASV table
#row sums before
rowSums(OTU)
#check row sums after-- should be 1 for all samples
rowSums(RAtab)

# Starting with the bubble plot, now that the ASV table is in the correct format (with proportions instead of counts)

# This R script computes a bubble plots from an OTU/ASV table and from a corresponding annotation file.
# Both input files should be tab-separated and contain as first column the OTU identifiers.
# Of course those should be the same between the two files.
# Their first line should either contain the sample names (for the OTU table), or the taxonomic level of annotations.

#### 1. Import variables

# Here are the main variables to set up to use this script.

# Load the environment
library("reshape2")
library("stringr")
library("ggplot2")

# set working directory
getwd()
setwd("/Users/meganguidry/Desktop/KellyLab/BubblePlot_Sept")

# Path to input files -- the files you would input into phyloseq
otu_tab_file <- "YourOTUTable.csv"
tax_file <- "YourTaxonomyTable.csv"

# Defining sample names and groups
# List of the corresponding replicates groups to which the individual replicates belong to.
# The order should match the one of 'replicates_list'.
# If some samples were not replicated, simply re-copy here the 'replicates_list' just above.
# The order of this list determines the sample order in the bubble plot.

replicates_list <- c() #I filled in my sample names here
replicates_groups <- c() #I filled in metadata here corresponding to the sample names (in the same order as the sample names)
#example below (where samples 1-3 are water samples, samples 4-6 are soil samples, and samples 7-9 are coral samples.)
# replicates_list <- c("Sample1", "Sample2", "Sample3", "Sample4", "Sample5", "Sample6", "Sample7", "Sample8", "Sample9")
# replicates_group <- c("water", "water", "water", "soil", "soil", "soil", "coral", "coral", "coral")


# Taxonomic level that will be aggregated and displaeyed in the bubble plot.
# It should match a taxonomic level from the taxonomic annotation file.
# If you want to display OTUs/ASVs, simply write 'OTU'.
tax_aggr <- "Class"

# Number of taxonomic bins to be displayed in the bubble plot.
tax_number <- 30 #threshold for how many taxa get displayed; others will be pooled into "other"

# Taxonomic level that will be used for colouring bubbles (i.e. categorical variable)
# It should match a taxonomic level from the taxonomic annotation file
# (and it should be a higher taxonomic level that the one from 'tax_aggr').
tax_col <- "Phylum"

#### 2. Import files

otu_tab <- read.table(otu_tab_file, header = TRUE, comment.char = "", sep = ",")
names(otu_tab)[1] <- "OTU"
otu_tab[1:5,1:5]

tax_tab <- read.table(tax_file, header = TRUE, comment.char = "", sep = ",", fill = TRUE)
names(tax_tab)[1] <- "OTU"
tax_tab[1:5,1:5]


#### 5. Merge the OTU and taxonomic tables together

m <- merge(otu_tab, tax_tab)   

# Has the merged table the expected dimension?
dim(m)

#### 6. Aggregate the table to taxonomic level defined in the variable 'tax_aggr'

# First, we should save in a column the taxonomic information needed for computing the bubble plot

taxonomy <- c()
for (row in 1:nrow(m)) {
  taxonomy <- c(taxonomy, paste0(m[row,names(m)==tax_col], ";", m[row,names(m)==tax_aggr]))
}

# Subset from the merged table the selected samples only
m2 <- m[,names(m) %in% replicates_list]

# Aggregate 'm2' based on the selected taxonomic level
m3 <- aggregate(m2, by=list(taxonomy), FUN=sum)

dim(m3)
m3[1:5,1:5] #this will be in alphabetical order by taxon

#### 7. Sort the table by decreasing size of taxonomic groups

# Here we only keep the 'x' top taxonomic groups, as defined in the ```tax_number``` variable.
# All the others taxonomic groups will be pooled together in a new bin labelled 'Other'.

# Sort the taxonomic table

if (tax_number > nrow(m3)) {
  tax_number <- nrow(m3)
}

m3$average <- rowMeans(m3[,-1])
m3.sorted <- m3[order(-m3$average),]

# Aggregate the smaller taxonomic bins together
m3.sorted$selection <- rep("discarded", nrow(m3.sorted))
m3.sorted$selection[1:tax_number] <- "retained"
m3.sorted$Group.1[m3.sorted$selection == "discarded"] <- "Other;Other"
m3.sorted$average <- NULL
m3.sorted$selection <- NULL
m4 <- aggregate(m3.sorted[,-1], by=list(taxonomy=m3.sorted$Group.1), FUN=sum)

# What is the relative abundances of the taxonomic bins that were pooled together in the 'Other' bin?
m4[m4$taxonomy == "Other;Other", -1]
mean(as.numeric(m4[m4$taxonomy == "Other;Other", -1]))  

# If you find this mean number is too big, you can simply increase the value of the 'tax_number' variable,
# Or alternatively choose a higher taxonomic level to display

#### 8. Transpose 'm4'

n <- m4$taxonomy
m4.t <- as.data.frame(t(m4[,-1]))
colnames(m4.t) <- n
m4.t$sample <- rownames(m4.t)
rownames(m4.t) <- NULL

m4.t[1:5,1:5]

#### 9. Calculate the mean and the standard deviation for each sample

m4.t$replicate <- rep(NA, nrow(m4.t))
for (line in 1:(nrow(m4.t))){
  m4.t$replicate[line] <- replicates_groups[m4.t$sample[line] == replicates_list]
}

# Compute the mean
m4.t.mean <- aggregate(m4.t[,1:(ncol(m4.t)-2)],
                       by = list(m4.t$replicate),
                       FUN = "mean")
names(m4.t.mean)[1] <- "sample"

dim(m4.t.mean)                              
m4.t.mean[1:5,1:5]

# Compute the standard deviation                             
m4.t.sd <- aggregate(m4.t[,1:(ncol(m4.t)-2)],
                     by = list(m4.t$replicate),
                     FUN = "sd")
names(m4.t.sd)[1] <- "sample"

dim(m4.t.sd)                              
m4.t.sd[1:5,1:5]

#### 10. Melt and merge the two dataframes

# Melt the dataframes
molten.mean <- melt(m4.t.mean, id.vars = "sample")
molten.mean$id <- paste0(molten.mean$sample, "-", molten.mean$variable)

molten.sd <- melt(m4.t.sd, id.vars = "sample")
molten.sd$id <- paste0(molten.sd$sample, "-", molten.sd$variable)

# Merge the dataframes
molten <- merge(molten.mean, molten.sd, by.x = "id", by.y = "id")

#### 11. Final rearragement of the dataframe
# Few last things before we can plot the data!

molten$id <- NULL
molten$sample.y <- NULL
molten$variable.y <- NULL
names(molten) <- c("sample", "taxonomy", "mean", "sd")

molten$tax_col <- str_split_fixed(molten$taxonomy, ";", 2)[,1]
molten$tax_bin <- str_split_fixed(molten$taxonomy, ";", 2)[,2]

# Reorder the taxonomic annotation for the plot
molten <- molten[order(molten$tax_col),]
tax_levels <- as.character(molten$tax_bin[!duplicated(molten$tax_bin)])
tax_levels <- tax_levels[tax_levels != "Other"]
tax_levels <- c(tax_levels, "Other")
# Lines below allow you to chose how you order the taxa on your plot. You can go with the default by abundance or set the order yourself by filling in your own taxa
#molten$tax_bin <- factor(molten$tax_bin, levels = rev(tax_levels)) 
molten$tax_bin <- factor(molten$tax_bin, levels = c("Alphaproteobacteria", "Deltaproteobacteria", "Gammaproteobacteria"))
# Remove null values
molten2 <- molten[molten$mean > 0,]

#### 12. Compute the bubble plot (finally!)

"""
* You can choose between different palettes from 'ColorBrewer3', as shown here: https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf
* It could be that ther are not enough colours in this different sets to cover all the categories to display. In this case, some of them will appear transparent in the plot. To fix this, you can alternatively:
    * select a higher taxonomic level to display with the ```tax_col``` variable, or
    * use ```scale_fill_discrete()``` instead of ```scale_fill_brewer()```,
    * create your own color palette using ```scale_fill_manual()```. See https://www.nceas.ucsb.edu/~frazier/RSpatialGuides/colorPaletteCheatsheet.pdf for more information about colours in R.
"""

bubble_plot <- ggplot(molten2,aes(sample,tax_bin)) +
  #geom_point(aes(size=mean+sd), shape=16, color = "red") +                      #line plots the stdev in a red circle if desired
  geom_point(aes(size=mean, fill=sample),shape=21,color="black") +
  theme(panel.grid.major=element_line(linetype=1,color="grey"),
        axis.text.x=element_text(angle=90,hjust=1,vjust=0),
        panel.background = element_blank()) +
  ylab("Class") +
  xlab("Samples") +
  scale_fill_manual(values= c("#98DF8A","#98DF8A", "#2CA02C", "#2CA02C","light grey", "light grey", "dark grey", "dark grey"), name= "Sample Group") +
  #scale_fill_brewer(palette="Paired", name="Taxonomic\nclade") +
  #scale_fill_discrete(name="Taxonomic\nclade") +
  scale_size(name = "Relative\nabundance")
bubble_plot

#### 13. Exporting the plot
pdf(file_name, width = plot_dim[1], height = plot_dim[2])
bubble_plot
dev.off()`
