### ISSUE TITLE
Error with UniFrac in distance function

### ISSUE THREAD

**Issue by jananiharan** [joey711/phyloseq#1416]
I've been using the distance function to calculate unweighted UniFrac distances for a while now, but I suddenly got this new error today, both on my own data and on the test dataset.

```
data(esophagus)

distance(esophagus, "uunifrac")

Error in as.vector(data) : 
  no method for coercing this S4 class to a vector
```

Any idea why this is happening and how to fix this issue?

**Comment by fconstancias** [comment]
Could you try using phyloseq::distance(esophagus, "uunifrac")?

**Comment by jananiharan** [comment]
Works, thank you!
