### ISSUE TITLE
changing an integer to a factor 

### ISSUE THREAD

**Issue by jbell364** [joey711/phyloseq#1419]
Hello, 

I have data that has repeated, weekly sampling. Currently week is coded at an integer in my sample data, but I would like to change it to a factor so I have have discrete weekly intervals when plotting and don't end up with continuous scales.

Thank you

**Comment by fconstancias** [comment]
You could add another variable to your metadata `week_factor` based on your existing `week_integer` metadata. Something like this should work:

`sample_data(phyloseq_obj)$week_factor <- as.factor(sample_data(phyloseq_obj)$week_integer)`

**Comment by jbell364** [comment]
It worked, thanks!
