### ISSUE TITLE
Is it possible to add a repeat rarefy plugin to phyloseq?

### ISSUE THREAD

**Issue by yxia0125** [joey711/phyloseq#1428]
Hi, I just wonder if phyloseq supports users to add a customized plugin? 

I just added the repeat rarefy plugin to QIIME2 (https://github.com/yxia0125/q2-repeat-rarefy), but some of my colleagues can only use phyloseq. So I need to add this function into phyloseq so that they can use it. Thank you very much for your time.

**Comment by spholmes** [comment]
We don't have plugins, most people just write their simple scripts as
functions they diffuse or a little add on package.

**Comment by yxia0125** [comment]
It's a pity. Thanks.
