### ISSUE TITLE
Abundance Filtering using relative abundance and absolute value

### ISSUE THREAD

**Issue by tcrispino13** [joey711/phyloseq#1453]
HI everyone, Ive been trying to filter my phyloseq object for downstream analysis using the following codes:
##Abundance Filtering using relative abundance
filt.phy = transform_sample_counts(physeq, function(x) x / sum(x) )
filt.phy= filter_taxa(filt.phy, function(x) mean(x) > 1e-5, TRUE)
##Abundnace Filtering using absolute abundance
Only retain taxa in absolute abundance table with abundance > .1%
filt.phy = filter_taxa(physeq, function(x) mean(x) < .1,TRUE)

I was wondering if I am doing and executing the correct codes for these purposes and also I would like to ask what is the basis of the filtering threshold used in filtering (>1e-5 & <.1). I just used these because these are the common values when I am searching the net. 

I appreciate your help on this matter, My degree depends on this TT

**Comment by ycl6** [comment]
Hi @tcrispino13 

You can check if you are getting the correct number of taxa in the filtered objects. 
Using the `GlobalPatterns` example:

```R
data(GlobalPatterns)

GP = GlobalPatterns
GP.prop = transform_sample_counts(GP, function(x) x / sum(x) )

filt1 = filter_taxa(GP.prop, function(x) mean(x) > 1e-5, TRUE)
filt2 = filter_taxa(GP, function(x) mean(x) < 0.1, TRUE)

> ntaxa(GP)
[1] 19216
> ntaxa(filt1)
[1] 4624
> ntaxa(filt2)
[1] 3555
```

If we use `rowMeans` to calculated the row-wise mean of the OTU Table and check the number of rows that have mean values satisfing the given conditions:

```R
> table(rowMeans(otu_table(GP.prop)) > 1e-5)

FALSE  TRUE 
14592  4624 

> table(rowMeans(otu_table(GP)) < 0.1)

FALSE  TRUE 
15661  3555 
```

Therefore the codes you have is *correct*. However I can't comment on your choice of the cutoffs though.
It seems odd that you are using an average abundance of `< 0.1` to get taxa that are deemed to have low abundance. Also your code does not give you `0.1%` (or `0.001`) but a cutoff at average abundance of `0.1`.

Even though this is oldish paper, you can check out the section on [Filtering](https://f1000research.com/articles/5-1492#d17888e2178).

**Comment by tcrispino13** [comment]
Thanks for this clarifications!
