### ISSUE TITLE
Adding sample data to phyloseq object

### ISSUE THREAD

**Issue by mr2raccoon** [joey711/phyloseq#1455]
Hey I am trying to add my sample data to my phloseq object but it won't show.
At first I realized sample names had a slight difference betweent OTU-table and sample data. I fixed this but it still won't work.

Any suggestions?

My OTU-table
![image](https://user-images.githubusercontent.com/81871773/113842732-40ea0f80-9793-11eb-9bc3-f3074538abb9.png)

my sample data 
![image](https://user-images.githubusercontent.com/81871773/113842658-2c0d7c00-9793-11eb-9680-770c42290e52.png)

I converted the sample data correctly from csv to matrix before trying to read it into phyloseq

**Comment by sghignone** [comment]
It is not clear to me if you already have your phyloseq object, or you're trying to build it with OTU and SAMPLE tables only. In the latter case, it won't work because you also need the TAX table to use the builder function
physeq<-phyloseq(otu_table, tax_table, sample_data)

**Comment by mr2raccoon** [comment]
I solved the problem thank you!
