### ISSUE TITLE
Error in function (classes, fdef, mtable)

### ISSUE THREAD

**Issue by tboonf** [joey711/phyloseq#147]
Hi,
I received the following error message as I was trying to plot a tree:

> plot_tree(test)
> Error in function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function "otu_table", for signature "phylo"

Does anyone have any idea what might have gone wrong? Please let me know.

Thanks
:)

**Comment by gayensubrata** [comment]
Hi
I am having the following errors ... Does anyone have any idea what might have gone wrong? Please let me know.

run = 10
> for(i in 1:run){
+   ind = sample(1:nrow(predictors_values_america_selected), size = 	floor(0.7*nrow(predictors_values_america_selected)), replace = FALSE)
+   train_data = predictors_values_america_selected[ind, ]
+   test_data = predictors_values_america_selected[-ind, ]
+     
+   background = randomPoints( predictors_america, 10000)
+   pseudo_absence_values = extract(predictors_america, background)
+     
+   train_y = c(rep(1,length(ind)), rep(0,nrow(pseudo_absence_values))) 
+   train_sdm_data_america = cbind(train_y, rbind(train_data, 	pseudo_absence_values))
+     
+   Model = maxent(train_sdm_data_america[,-1], p = train_y)
+   show(Model)
+     
+   r = predict(Model, test_data, progress='text', args = c("outputformat=raw"))
+   }
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘maxent’ for signature ‘"matrix", "numeric"’
In addition: Warning message:
In couldBeLonLat(mask) : CRS is NA. Assuming it is longitude/latitude
