### ISSUE TITLE
subset_taxa based on partial string match

### ISSUE THREAD

**Issue by Boon-Keat** [joey711/phyloseq#1477]
Subsetting string with a hyphen, e.g. 
```
p__Deinococcus-Thermus = subset_taxa(phyloseq_TnN_step0, Phylum == "p__Deinococcus-Thermus")
```
returns an error 
```
Error in p__Deinococcus - Thermus = subset_taxa(phyloseq_TnN_step0, Phylum ==  : 
  object 'p__Deinococcus' not found
```
understandably as hyphen has been treated as a minus sign. Is there a way to still subset the following taxa based on partial string match? 

Many thanks.

**Comment by ycl6** [comment]
Hi @Boon-Keat 

The error you have experienced is due to the fact that you are using an invalid variable name for the output, i.e. hyphen is generally not allowed in variable name in programming languages. In your case, you can change it to:

```R
p__DeinococcusThermus = subset_taxa(phyloseq_TnN_step0, Phylum == "p__Deinococcus-Thermus")

p__Deinococcus_Thermus = subset_taxa(phyloseq_TnN_step0, Phylum == "p__Deinococcus-Thermus")
```

**Comment by Boon-Keat** [comment]
Ah how silly I am! I have overlooked my very own mistake at the variable. Many thanks again for the fix.
