### ISSUE TITLE
Same issue as Normalize barplots by number of samples #702

### ISSUE THREAD

**Issue by TJrogers86** [joey711/phyloseq#1486]
I have the same problem as Normalize barplots by number of samples #702. However, the solution to the problem was never given. It ends with user sfeds saying:

"Hi Jeff,
I understand. In my case I don't even think I need variables "F" or "X_F". I would like to plot samples merged by variable "X", intro its 3 levels == "abs" or "<med" or ">med".
When I transform_sample_counts it all goes well, checked colSums, all fine. But the merging does something funky with my sample_data I think.
Maybe I don't get the concept of the function correctly, but if there is a way to plot samples grouped by a specific variable (in my case "X"), in order to be able to compare between "groups" (in my case the 3 levels of variable "X") there should be a way to normalize these groups by the n per level. Otherwise you can't really compare between the groups you're plotting, as this is then very much dependent of the number of samples per group (unless you have perfect grouping for all your variables you want to plot and your "n" per group is always the same). So even when transforming into, e.g. %, the plotting is "cumulative", adding all the values in each group, which renders a graph that, for comparison purposes, would not be useful."
 
I have the exact same problem:
![image](https://user-images.githubusercontent.com/48442658/126186411-f8f670a4-6a97-4528-abc1-2d88c0b96ab4.png)

I need to normalized based on sample number within each catagory (arc, forearc, and outer_forearc). Is there a solution?

**Comment by ycl6** [comment]
Hi @TJrogers86 the `plot_bar` function doesn't handle/normalise the abundance, so you will need to calculate it and create the bar plot without using `plot_bar`.

Below is an example:

```R
library(phyloseq)
library(dplyr)
library(ggplot2)

data(GlobalPatterns)

# Limit to Bacteria
gp <- subset_taxa(GlobalPatterns,Kingdom == "Bacteria")

# Create a extra factor 'Type' to include in plot
sample_data(gp)$Type <- "Environmental"
sample_data(gp)[sample_data(gp)$SampleType %in% c("Feces","Skin","Tongue"),]$Type <- "Human"

# Limit to top 100 ASVs
top100 <- names(sort(taxa_sums(gp), decreasing=TRUE))[1:100]
gp.top100 <- prune_taxa(top100, gp)

# Prepare data.frame
df <- psmelt(gp.top100)

# Calculate the following in each phylum in each SampleType and keep 'Type' in the resulting table
# - Total abundance (Sum)
# - Number of samples (N)
# - Abundance per sample (normAbundance)
df <- df %>% group_by(Phylum, SampleType, Type) %>%
        summarise(Sum = sum(Abundance), N = length(Sample), normAbundance = Sum/N)
```

```
> head(df, 10)
# A tibble: 10 x 6
# Groups:   Phylum, SampleType [10]
   Phylum         SampleType         Type              Sum     N normAbundance
   <chr>          <fct>              <chr>           <dbl> <int>         <dbl>
 1 Actinobacteria Feces              Human          154293    36        4286. 
 2 Actinobacteria Freshwater         Environmental  780176    18       43343. 
 3 Actinobacteria Freshwater (creek) Environmental   14083    27         522. 
 4 Actinobacteria Mock               Environmental  241762    27        8954. 
 5 Actinobacteria Ocean              Environmental  193736    27        7175. 
 6 Actinobacteria Sediment (estuary) Environmental    1831    27          67.8
 7 Actinobacteria Skin               Human           10602    27         393. 
 8 Actinobacteria Soil               Environmental     630    27          23.3
 9 Actinobacteria Tongue             Human           99591    18        5533. 
10 Bacteroidetes  Feces              Human         2257087   112       20153. 
```

Compare the plots

```R
p1 <- plot_bar(gp.top100, x = "SampleType", fill = "Phylum") + 
        facet_grid(. ~ Type, scales = "free_x", space = "free_x")

p2 <- ggplot(df, aes(SampleType, normAbundance, fill = Phylum)) + 
        geom_bar(stat = "identity", position = "stack", color = "black") +
        facet_grid(. ~ Type, scales = "free_x", space = "free_x") +
        theme(axis.text.x = element_text(angle = -90, hjust = 0)) +
        ylab("Abundance per sample")

gridExtra::grid.arrange(p1, p2)
```

![plot_bar_per-sample_abumdance](https://user-images.githubusercontent.com/9032946/126473109-8132ac83-916a-4a65-941a-d7d7f2e26cea.png)

**Comment by TJrogers86** [comment]
Thank you so much! And sorry for the late reply
