### ISSUE TITLE
Phyla graph for each time point

### ISSUE THREAD

**Issue by MonicaSteffi** [joey711/phyloseq#1488]
Dear All,

I have a timeseries dataset where, each patient has four visit like follows:

Patient     Time
E1              V1
E1             V2
E1             V3
E1             V4
E2             V1
E2             V2
E2             V3
E2             V4

I am trying plot abundance of each Phyla in the various time points.  the x axis would be Time points (V1,V2,V3 and V4), y axis would be relative abundance. 

`ps_phylum <- phyloseq::tax_glom( physeq_fil_relative , "Phylum")
 phyloseq::taxa_names(ps_phylum) <- phyloseq::tax_table(ps_phylum)[, "Phylum"]
  phyloseq::psmelt(ps_phylum) %>%
   ggplot(data = ., aes(x = Visit, y = Abundance)) +
   geom_line(aes(color=Phylum)) +
   geom_point(aes(color=Phylum))+
   labs(x = "Visit", y = "RelativeAbundance\n") +
   facet_wrap(~OTU, scales = "free")`

I got the following image. the points are vertical. 
![image](https://user-images.githubusercontent.com/12621929/126911906-2c04b44d-40b4-4df3-9eba-5ecb0d62c881.png)

But I need something like this:

![image](https://user-images.githubusercontent.com/12621929/126911988-a78986fc-0d0f-45cb-bff9-1483335fc2bd.png)

Main aim is to show abundance of each phyla across 4 different time points for each patients. How do I proceed?

**Comment by ycl6** [comment]
Hi @MonicaSteffi, I think what you need is to use the `group` aesthetic 

https://stackoverflow.com/questions/45465804/combining-geom-point-and-geom-line-when-using-facet-grid-and-multiple-data-point
https://stackoverflow.com/questions/8592585/combine-points-with-lines-with-ggplot2

**Comment by omrctnr** [comment]
Hello, 

If you managed to create it, could you please share with me?
