### ISSUE TITLE
Rarefaction error: sample.size less than or equal to zero. Need positive sample size to work.

### ISSUE THREAD

**Issue by marwa38** [joey711/phyloseq#1506]
Hello 

How to deal with error when I am having the minimum (of sample_sums of the phyloseq object) equals to zero 

`summary(sample_sums(ps.prev))
`
> Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
> 0.0   268.5   789.0  2210.3  1799.8 50924.0 

while rarefying I found that error message pop up. 

> sample.size less than or equal to zero. , 
>          Need positive sample size to work.

here is the code I used 
```
set.seed(9242) 
ps.rare <- rarefy_even_depth(ps.prev, sample.size = min(sample_sums(ps.prev)))
```

**Comment by ycl6** [comment]
Hi @marwa38 

You can try removing the samples that have 0 taxa from your phyloseq object before applying `rarefy_even_depth`

```R
# Keep samples with non-zero total taxa
pruned <- prune_samples(sample_sums(ps.prev) > 0, ps.prev)

# Check total taxa in each sample again
sample_sums(pruned)
```
