### ISSUE TITLE
Random assigning of the root?

### ISSUE THREAD

**Issue by marwa38** [joey711/phyloseq#1510]
Hello 
Could you please guide me regarding the phylogenetic tree?

I was wondering why I get this warning message that the tree root is randomly assigned?
![image](https://user-images.githubusercontent.com/68851733/138343736-f23aac8e-9126-4a27-8716-e6d0bfa79f69.png)

although I ran rooting of the tree beforehand as follow:
```
ps.tree <- ps
phy.tree(ps.tree) <- root(phy_tree(ps.tree), sample(taxa_names(ps.tree), 1), resolve.root = TRUE)
is.rooted(phy_tree(ps.tree))

```

Many thanks

**Comment by marwa38** [comment]
Thanks very much, This is was so helpful I-Hsuan @ycl6 
It worked fine doing outgroup but based on [this ](https://groups.google.com/g/qiime-forum/c/rGXLnfnHbFA)I need to prune that outgroup from the tree in Dendroscope.
Your comments/advice on how to do so would be very much appreciated.

**Comment by ycl6** [comment]
Hi @marwa38 You probably don't have to do additional pruning of the outgroup/root. In the example mentioned in the qiime forum, the person deliberately chosen a taxon from Archaea as the outgroup (and rightly so if majority of the taxa are Bacteria). He chooses to remove the outgroup to avoid long branch to Archaea.
