### ISSUE TITLE
Relative abundance too low for top 10 longitudinal samples plot 

### ISSUE THREAD

**Issue by pdhrati02** [joey711/phyloseq#1515]
Hi,
I have a longitudinal dataset with 5 time points and 3 different groups. I certainly made top 10 plots for each group at each time point and merged them together (for example group 1 -t1, group 1- t2, t3, t4, and t5 and placed them in a single panel). 
But I am trying to make a plot by subsetting my phyloseq object for one group and then merging samples based on time point (so that I get one plot with 5 time points at once). 
The code I am using for it is as follows: 

ps.infant_csnoab <- subset_samples(pps,Group%in%c("CS_noab"))
ps.infant_csnoab

PHY_csnoab_genus <- tax_glom(ps.infant_csnoab, taxrank = "Genus")
PHY_csnoab_genus_abun <- prune_taxa(names(sort(taxa_sums(PHY_csnoab_genus), TRUE)[1:10]), 
                                    PHY_csnoab_genus)
PHY_csnoab_genus_abun
mrg_csnoab <- merge_samples(PHY_csnoab_genus_abun, "Timepoint")

# Normalize by number of samples in each sample type
otu_table(mrg_csnoab) <- otu_table(mrg_csnoab)[, ]/as.matrix(table(sample_data(ps.infant_csnoab)$Group))[, 
                                                                                                         1]
p_csnoab <- plot_bar(mrg_csnoab)
c_csnoab <- p_csnoab + geom_bar(aes(fill = Genus), stat = "identity", position = "stack") + 
  scale_fill_brewer(palette = "Set3", "Genus") + ylab("Relative abundance (%)") + 
  xlab("")

c_csnoab

![image](https://user-images.githubusercontent.com/54065254/142607488-7f1d9534-5c78-4d4f-8bc9-575b9ed12e7d.png)

But this ends up giving me a plot in which the relative abundance on Y axis goes up to only 20%. Which can't be true as in individual plots my top 10 relative abundance at each time point is about 70%. 

Can someone help me with what I am doing wrong here? Any insights would be great help.

Thank you
Best
DP

**Comment by ycl6** [comment]
Hi @pdhrati02 This should achieve what you wanted. 
Using demo dataset `GlobalPatterns`.

```R
library(phyloseq)
library(ggplot2)
data(GlobalPatterns)

GP <- GlobalPatterns
```

```
> GP
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 19216 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 19216 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 19216 tips and 19215 internal nodes ]
```

```R
# Merge sample by SampleType
mergedGP <- merge_samples(GP, "SampleType")
mergedGP
```

```
> mergedGP
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 19216 taxa and 9 samples ]
sample_data() Sample Data:       [ 9 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 19216 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 19216 tips and 19215 internal nodes ]
```

```R
# Merge taxa with same Genus
mergedGP.genus <- tax_glom(mergedGP, taxrank = "Genus")
mergedGP.genus
```

```
> mergedGP.genus
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 996 taxa and 9 samples ]
sample_data() Sample Data:       [ 9 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 996 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 996 tips and 995 internal nodes ]
```

```R
# Calculate relative abundance
mergedGP.genus.prop <- transform_sample_counts(mergedGP.genus, function(x) x / sum(x) )

# Save top 5 taxa from each SampleType
top <- list()
for(i in 1:nsamples(mergedGP.genus.prop)) {
        t <- head(sort(t(otu_table(mergedGP.genus.prop)[i,]), decreasing = TRUE), 5)
        top[[colnames(t)]] <- rownames(t)
}

# Prune to keep taxa in list
mergedGP.genus.prop.top <- prune_taxa(unlist(top), mergedGP.genus.prop)
mergedGP.genus.prop.top
```

```
> mergedGP.genus.prop.top
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 39 taxa and 9 samples ]
sample_data() Sample Data:       [ 9 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 39 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 39 tips and 38 internal nodes ]
```

```R
plot_bar(mergedGP.genus.prop.top) + geom_col(aes(fill = Genus), color = "black") +
        guides(fill = guide_legend(title = "Genus"))
```

![top10](https://user-images.githubusercontent.com/9032946/142701002-6197d919-df79-4768-9761-81066a1f12be.png)

**Comment by pdhrati02** [comment]
hello @ycl6 
Thank you very much for your help, I just have one question. Should one try to get overall top 10 or top 10 at each time point as you have described above? 
Is there any right or wrong with that?

Thank you for your help once again.
Best
DP

**Comment by ycl6** [comment]
Hi @pdhrati02 It depends what you want to present to your readers. The two results are obviously different, the first option shows the top N abundant taxa in your overall collection, irregardless of group/time/condition, the latter option allows you to show top N taxa on individual group/time/condition.

**Comment by pdhrati02** [comment]
Hi @ycl6 
Thank you very much, however in the code you gave above you select for top 5 from each sample but in the plot end up getting 7/8/9. Why is that so? 
If we select say top 5 we should get top 5 for each site/condition/timepoint right?
How to correct that?

Best
DP

**Comment by ycl6** [comment]
Hi @pdhrati02 Do you mean if we choose top 5 from each group, why the plot shows more than 5 genera in a given group?

In the step where I prune `mergedGP.genus.prop` to keep taxa in the list, I am keeping top 5 taxa identified in all the groups. Therefore when we plot the abundance of the resulting object, each group will show not only its own top 5 taxa, but also taxa identified in other groups. If you want to show just the 5 (or 10) taxa in each group, you'll have to plot each group separately, i.e. you only have 1 bar in a plot. and join the plots together afterwards.

**Comment by pdhrati02** [comment]
Hi @ycl6 Yes that is what I meant, your explanation made it clear for me. Thank you very much for your explanation and all the help. Much appreciated. 

Best
DP
