### ISSUE TITLE
visualising relative abundance of top 20 genus?

### ISSUE THREAD

**Issue by marwa38** [joey711/phyloseq#1516]
Hello 

I am trying to choose the top 20 Genus in a phyloseq object then visualise the relative abundance as following:

`ps.prev.genus <- aggregate_taxa(ps.prev, level = "Genus")`
`ps.prev.genus.top20 <- top_taxa(ps.prev.genus, n = 20)`

# Transform to relative abundance 
`ps.prev.genus.top20 <- transform_sample_counts(ps.prev.genus.top20, function(ASV) ASV/sum(ASV))`

# Melting for visualising
`ps.prev.genus_top20_melt <- ps.prev.genus.top20 %>% psmelt()`

Could you have please advice on the last two steps (transform and melt). Or do you advise any other way to choose the top taxa from a certain taxa_rank?

Many thanks 
Marwa

**Comment by ycl6** [comment]
Hi @marwa38 You can do this without using functions from the `microbiome` package.

```R
library(phyloseq)
library(ggplot2)
data(GlobalPatterns)

GP <- GlobalPatterns

# Agglomerate taxa at genus level
GP.genus <- tax_glom(GP, taxrank = "Genus")

# Top N taxa
N <- 20
top <- names(sort(taxa_sums(GP.genus), decreasing = TRUE))[1:N]

# Calculate relative abundance
GP.genus.prop <- transform_sample_counts(GP.genus, function(x) x / sum(x) )

# Subset object to top N taxa
GP.genus.prop.top <- prune_taxa(top, GP.genus.prop)
```

```
> top
 [1] "331820" "279599" "171551" "360229" "94166"  "98605"  "326977" "550960"
 [9] "470973" "471122" "256977" "298875" "323845" "557211" "259569" "536311"
[17] "291090" "357795" "228764" "299892"

> GP.genus.prop.top
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 20 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 20 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 20 tips and 19 internal nodes ]
```

**Comment by marwa38** [comment]
Thanks very much for that. 
Before you shared with me 
I tried the following but the difference between tax_glom and aggregate_taxa is that the former retains the tree which is helpful later on in visualising the tree

Here are my codes:
```
ps.prev2.genus <- aggregate_taxa(ps.prev2, level = "Genus")
# select top 20 genus 
ps.prev2.genus.top20 <- top_taxa(ps.prev2.genus, n = 20)
# [1] "Pseudomonas"          "Aeromonas"            "Lactobacillus"        "Staphylococcus"      
# [5] "Streptococcus"        "Escherichia-Shigella" "Porphyromonas"        "Acinetobacter"       
# [9] "Arcicella"            "Pseudorhodobacter"    "Enterococcus"         "Luteolibacter"       
# [13] "Chryseobacterium"     "Polaromonas"          "Sphaerotilus"         "Rhodobacter"         
# [17] "Pedobacter"           "Arsenicibacter"       "Leuconostoc"          "Rhodoferax" 

# prune to have only which is genus top20 as phyloseq object 
ps.prev2.top20genus <- prune_taxa(ps.prev2.genus.top20, ps.prev2.genus)

# two steps for visualising purposes 
# transfrom 
ps.prev2.top20genus.transformed <- transform_sample_counts(ps.prev2.top20genus, function(ASV) ASV/sum(ASV))
# melt the phyloseq object 
ps.prev2.top20genus.transformed_melt <- ps.prev2.top20genus.transformed %>%
  psmelt()
```
  

```
 Showing the difference between both tax_glom and aggregate_taxa
 GP.genus <- tax_glom(GP, taxrank = "Genus")
GP.genus.aggregate <- aggregate_taxa(GP, level = "Genus")
identical(GP.genus, GP.genus.aggregate)
# > GP.genus
# phyloseq-class experiment-level object
# otu_table()   OTU Table:         [ 996 taxa and 26 samples ]
# sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
# tax_table()   Taxonomy Table:    [ 996 taxa by 7 taxonomic ranks ]
# phy_tree()    Phylogenetic Tree: [ 996 tips and 995 internal nodes ]
# > GP.genus.aggregate
# phyloseq-class experiment-level object
# otu_table()   OTU Table:         [ 997 taxa and 26 samples ]
# sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
# tax_table()   Taxonomy Table:    [ 997 taxa by 7 taxonomic ranks ]
```

**Comment by ycl6** [comment]
@marwa38 Thanks for showing the difference. I've not used `microbiome` before, good to know `phyloseq`'s `tax_glom` function retains the tree data.

**Comment by marwa38** [comment]
You are very welcome. @ycl6 
My apologies I just need to reopen for this relevant query if you don't mind. 
Do you think there is a reason why I get some samples plain without any top taxa (Species in that case)? and if there is any advice that I can rerun my previous codes in a way that those don't appear like that (hollow areas) in the below-attached fig, as I don't think they will be acceptable in publishing. 
![image](https://user-images.githubusercontent.com/68851733/143088473-4c95fff7-5198-47e8-81dd-a2c084437ec1.png)

**Comment by ycl6** [comment]
Hi @marwa38 This is more of a question on how to best use `ggplot2`.
It will be better that you create the bar plot using `ggplot` (after `psmelt`) which gives you more control of the plot aesthetics than using `phyloseq`'s `plot_bar` function which is a wrapper of `ggplot`'s `geom_bar`.

The below discussion with demo using `facet_wrap` or `facet_grid` should help.
https://stackoverflow.com/questions/11301738/ggplot2-drop-unused-factors-in-a-faceted-bar-plot-but-not-have-differing-bar-wi

**Comment by Srvcl** [comment]
Thanks a lot! 
Another way for yours options:

```{r, fig.width=18, fig.height=9}
TOPS = names(sort(taxa_sums(physeq1), TRUE)[1:20])
TOPS
TOPS1 = prune_taxa(TOPS, physeq1)
TOPS1
plot_bar(TOPS1, fill = "Family", x = "Specie", facet_grid=~Alimentacion)
plot_tree(TOPS1)
```

**Comment by ElizabethOLeary** [comment]
Hi @ycl6,

Thank you for the above code for plotting relative abundance data. I do have a question for you, if you do not mind. I realize that this may be a ggplot2 issue, but so far my search to remedy my issue haven't been solved by any updates to my code for the graph.

The issue I am having, is that I would like the Abundance on the y axis to appear as a value out of 100, rather than 1.00, 0.75. 0.5, etc. as is shown in the attached graph. 

Do you by chance know how to fix this?

Thanks in advance for any insight. 
![000021](https://github.com/joey711/phyloseq/assets/115184532/1c2fb22f-eca2-425d-b6f4-1c6fe6a75bbd)

**Comment by ycl6** [comment]
Hi @ElizabethOLeary Not sure if you have found a solution to your question. 
If you have not, you can use the `label_percent` function from `scales` package to change the y-axis in the ggplot object.
https://scales.r-lib.org/reference/label_percent.html
