### ISSUE TITLE
Using Phyloseq with dataframes.

### ISSUE THREAD

**Issue by abalter** [joey711/phyloseq#1525]
I work with dataframes without rownames in keeping with the "tidy" ethos. My ASV and taxa tables have a column for "ASV" and my sample metadata has a column called "SampleID" or "SampleName." I'm having trouble building a phyloseq object from these tables.

When I try to use dataframes, I get a warning that taxa and OTU names do not match. I'm guessing this has to do with a `taxa_are_rows` issue---maybe phyloseq wants my ASVs as the columns if I use a datframe? I also get a warning suggesting not to use dataframes at all.

So, I tried  converting my dataframes to matrix objects. I still get this nagging "sam_data slot is empty" error.

I've created a reprex with simple fabricated data showing these problems.

``` r
library(tidyverse)
library(phyloseq)

asv_table = tibble(
  ASV = c("aaa", "bbb", "ccc"),
  S1 = round(runif(3)*10),
  S2 = round(runif(3)*15)
)

taxa_table = tibble(
  ASV = c("aaa", "bbb", "ccc"),
  Kingdom = replicate(3, sample(letters, 3) %>% paste0(collapse="")),
  Phylum = replicate(3, sample(letters, 3) %>% paste0(collapse="")),
  Class = replicate(3, sample(letters, 3) %>% paste0(collapse="")),
  Order = replicate(3, sample(letters, 3) %>% paste0(collapse="")),
  Family = replicate(3, sample(letters, 3) %>% paste0(collapse="")),
  Genus = replicate(3, sample(letters, 3) %>% paste0(collapse="")),
  Species = replicate(3, sample(letters, 3) %>% paste0(collapse="")),
)

sample_data = tibble(
  SampleID = c("S1", "S2"),
  FavoriteColor = c("Azure", "Magenta"),
  FavoriteFlavor = c("Butter Pecan", "Pistachio")
)

ps = phyloseq(
  otu_table(
    asv_table %>% column_to_rownames("ASV"),
    taxa_are_rows = T
  ),
  tax_table(taxa_table %>% column_to_rownames("ASV")),
  sample_data(sample_data %>% column_to_rownames("SampleID"))
)
#> Warning in .local(object): Coercing from data.frame class to character matrix 
#> prior to building taxonomyTable. 
#> This could introduce artifacts. 
#> Check your taxonomyTable, or coerce to matrix manually.
#> Error in validObject(.Object): invalid class "phyloseq" object: 
#>  Component taxa/OTU names do not match.
#>  Taxa indices are critical to analysis.
#>  Try taxa_names()

ps = phyloseq(
  otu_table(
    asv_table %>% 
      column_to_rownames("ASV") %>% 
      as.matrix(),
    taxa_are_rows = T
  ),
  tax_table(
    taxa_table %>% 
      column_to_rownames("ASV") %>% 
      as.matrix()
  ),
  sample_data(
    sample_data %>% 
      column_to_rownames("SampleID") %>% 
      as.matrix()
  )
)
#> Error in access(object, "sam_data", errorIfNULL): sam_data slot is empty.
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by joey711** [comment]
Your ASV table must also have sample IDs (in this case column indices) that match the rownames in your sample_data. `phyloseq()` is taking the intersection of these different tables based on the corresponding index. ASV/OTU table has both sample and taxa indices. Hope that helps!

**Comment by abalter** [comment]
@joey711 Thanks for the quick response!

I'm not quite getting it. Once transformed to a matrix, my ASV table has a column for the abundance in each sample: S1 and S2.

```
> asv_table %>% 
+   column_to_rownames("ASV") %>% 
+   as.matrix() %>% 
+   colnames()
[1] "S1" "S2"
> asv_table %>% 
+   column_to_rownames("ASV") %>% 
+   as.matrix() %>% 
+   rownames()
[1] "aaa" "bbb" "ccc"
```

These end up as the rownames for the sample matrix. 

```
> sample_data %>% 
+   column_to_rownames("SampleID") %>% 
+   as.matrix() %>% 
+   colnames()
[1] "FavoriteColor"  "FavoriteFlavor"
> sample_data %>% 
+   column_to_rownames("SampleID") %>% 
+   as.matrix() %>% 
+   rownames()
[1] "S1" "S2"
```

Incidentally, I also tried taking the transpose of the asv matrix and switching to `taxa_are_rows = F` and this did not help.

**Comment by joey711** [comment]
Check the output of the `sample_data()` method directly. I believe it needs an object inheriting from `data.frame` as input, not matrix. This makes sense when you think about what it is storing (heterogenous mixture of data types summarizing experimental covariates and metadata).

**Comment by abalter** [comment]
Ok, got it. When the sample_data goes in as a dataframe, and the others as matrices, I don't get an error. 

If I could find the time to add some code to handle different input data with a little more flexibility, and maybe some improved error messages, would that be a welcome addition?

**Comment by joey711** [comment]
Always welcome. For instance, `sample_data()` should complain with an error when a matrix is provided. This might have cleared things up for you right away. More informative error messages regarding the indices that `phyloseq()` "sees" when it is doing its comparison would also probably clear up a lot of user-confusion.
