### ISSUE TITLE
Phylo seq error

### ISSUE THREAD

**Issue by karims-1** [joey711/phyloseq#1526]
Hi, 

I am a newbie to R and microbiome analysis- Trying to debug a code and finding this error. I will highly appreciate your feedback. Thank you in advance 

My code 
#estimating alpha diversity using many measures
alpha_div = estimate_richness(physeq.OR.2019.16S)

#making "sample" a column of data in the alpha diversity dataframe
alpha_div$Sample = sample_names(physeq.OR.2019.16S)
#extracting the sample data from the phyloseq object as a dataframe
meta_alpha = data.frame(sample_data(physeq.OR.2019.16S))
#making "sample" a column
meta_alpha$Sample = sample_names(physeq.OR.2019.16S)
#merging the shannon  dataframe with the sample data
alpha_div_metadata = merge(alpha_div,meta_alpha,by="Sample") 

#plot by many different alpha diversity measurements by treatment and month
plot_richness(alpha_div_metadata, x = "Treatment", color = "Treatment") + geom_boxplot()+facet_wrap(~Month)

**The error message is "Error in .local(object, taxa_are_rows) : 
  argument "taxa_are_rows" is missing, with no default'.** 

#plot specific alpha diversity metrics by by month and color by treatment using "measures=c("")"
plot_richness(alpha_div_metadata, x="Month", color = "Treatment", measures=c("Observed", "Shannon")) + geom_boxplot()

**The error message is "Error in .local(object, taxa_are_rows) : 
  argument "taxa_are_rows" is missing, with no default'.**

**Comment by ycl6** [comment]
Hi @karims-1

The `plot_richness` takes a `phyloseq-class` or `otu_table-class` object. It looks like your `alpha_div_metadata` is a `data.frame`? If you already have all the values required stored in a `data.frame`, why not generate the plot using `ggplot2` directly.

**Comment by karims-1** [comment]
Thank you @ycl6 . It is a data frame and I got it by using ggplot2 directly. Thank you once again.

**Comment by ycl6** [comment]
Hi @karims-1 Sounds good! You can close this issue if you think this is now resolved.
