### ISSUE TITLE
subset_taxa does not work as intended 

### ISSUE THREAD

**Issue by akckwok** [joey711/phyloseq#1536]
Hi, 

I was doing what I thought was simple but when I subset taxa for Cyanobacteria or Mito, using the ! (not) the operation seems to filter the object improperly.

This was classified using SILVA138 off the Silva repo. 
I expected 93 to be deducted from 3944, but instead, 353 OTUs were trimmed.
I opened up the original ASV.txt file to analyze the taxonomic ranks.

**93** is the number of **mitochondrial** OTUs.
**3944** is the **total** number of OTUs.
I am unsure how the Family !="Mitochondria" **removed** **353** OTUs.

I was hoping someone could give a look-see into the subset_taxa function. 

Below is the console, 
--- 
> qiimex
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3944 taxa and 34 samples ]
sample_data() Sample Data:       [ 34 samples by 11 sample variables ]
tax_table()   Taxonomy Table:    [ 3944 taxa by 8 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 3944 tips and 3923 internal nodes ]

> subset_taxa(qiimex, Family=="Mitochondria")
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 93 taxa and 34 samples ]
sample_data() Sample Data:       [ 34 samples by 11 sample variables ]
tax_table()   Taxonomy Table:    [ 93 taxa by 8 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 93 tips and 92 internal nodes ]

> subset_taxa(qiimex, Family!="Mitochondria")
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3591 taxa and 34 samples ]
sample_data() Sample Data:       [ 34 samples by 11 sample variables ]
tax_table()   Taxonomy Table:    [ 3591 taxa by 8 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 3591 tips and 3570 internal nodes ]

**Comment by ycl6** [comment]
Hi @akckwok 

Using `!=` operator in `subset_taxa` is not returning ***all*** the remaining taxa because it does not include those that have `NA` in the `Family` rank.

For example:

```R
library(phyloseq)
data(GlobalPatterns)

GP <- GlobalPatterns

sub1 <- subset_taxa(GP, Family == "Cyanobacteriaceae")
sub2 <- subset_taxa(GP, Family != "Cyanobacteriaceae")
```

```
> GP
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 19216 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 19216 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 19216 tips and 19215 internal nodes ]

> sub1
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 7 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 7 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 7 tips and 6 internal nodes ]

> sub2
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 13606 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 13606 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 13606 tips and 13605 internal nodes ]

> table(is.na(as.data.frame(tax_table(GP))$Family))

FALSE  TRUE 
13613  5603 

> 7+13606+5603
[1] 19216
```

In order to keep those with `NA`, you can manually extract the taxa ID (the row names of the `tax_table`) that match the conditions `Family != "Cyanobacteriaceae" | is.na(Family)`, and then use `prune_taxa` to subset the object.

```R
taxa <- rownames(subset(as.data.frame(tax_table(GP)), Family != "Cyanobacteriaceae" | is.na(Family)))
sub3 <- prune_taxa(taxa, GP)
```

```
> sub3
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 19209 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 19209 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 19209 tips and 19208 internal nodes ]
```

**Comment by ycl6** [comment]
@akckwok 

Actually, using the same logical expression `Family != "Cyanobacteriaceae" | is.na(Family)` works with `subset_taxa` :wink: 

```
> subset_taxa(GP, Family != "Cyanobacteriaceae" | is.na(Family))
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 19209 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 19209 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 19209 tips and 19208 internal nodes ]
```

**Comment by akckwok** [comment]
> @akckwok
> 
> Actually, using the same logical expression `Family != "Cyanobacteriaceae" | is.na(Family)` works with `subset_taxa` 😉
> 
> ```
> > subset_taxa(GP, Family != "Cyanobacteriaceae" | is.na(Family))
> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 19209 taxa and 26 samples ]
> sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
> tax_table()   Taxonomy Table:    [ 19209 taxa by 7 taxonomic ranks ]
> phy_tree()    Phylogenetic Tree: [ 19209 tips and 19208 internal nodes ]
> ```

Thanks so much, really appreciate it.
