### ISSUE TITLE
Transforming relative abundance into counts for richness estimations. 

### ISSUE THREAD

**Issue by Or-Sharon** [joey711/phyloseq#1537]
Hello, 

In my analysis I'm filtering low abundance taxa by transforming the counts to relative abundance and then doing the filtering in two different steps: 

psra <- transform_sample_counts(ps, function(x){x / sum(x)}) # ra transforms, but just for filtering, not for subsequent analysis
ps5 <- filter_taxa(psra, function(x) sum(x) > .005, TRUE) # filtering

Now when I'm trying to clculate the diversity of the samples with:

estimate_richness( ps5, measures = "Observed")

I get the error: 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': function accepts only integers (counts). 

Is there a way to transform back the data to counts? Or to filter the taxa without transforming the counts first? 

Thank you!

**Comment by ycl6** [comment]
Hi @Or-Sharon 

Given the `ps5` contains the filtered taxa, you can use `taxa_names` to retreive the taxa ID from `ps5`, and then use `prune_taxa` on the original `ps` object to subset the object with the taxa you want to keep.

**Comment by Or-Sharon** [comment]
Hi @ycl6 

Thank you for your help, it worked!
