### ISSUE TITLE
taxa_glom not aggregating reads

### ISSUE THREAD

**Issue by maxmiao** [joey711/phyloseq#1551]
Hello, 

I am trying to aggregate reads using the taxa_glom function in phyloseq (version 1.38). Somehow, I am able to execute the command but the output does not aggregate reads based on phyla or any other taxa. This is what I wrote: 

> rank_names(physeq_trimmed)
 [1] "otu_id"      "taxonomy"    "Kingdom"     "Phylum"      "Class"      
 [6] "Order"       "Family"      "Genus"       "Species"     "last_taxon" 
[11] "final_names" "otu" 

> physeq_phyla = tax_glom(physeq_trimmed,taxrank=rank_names(physeq_trimmed)[4])
> physeq_phyla
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 8852 taxa and 284 samples ]
sample_data() Sample Data:       [ 284 samples by 28 sample variables ]
tax_table()   Taxonomy Table:    [ 8852 taxa by 12 taxonomic ranks ]

I've also tried doing:

> physeq_phyla = tax_glom(physeq_trimmed,taxrank="Phylum")

and got a similar result....

The tax table shows phylums names but there's no merging of reads based on those names and was hoping that using this function it would merge all the reads for w/e phyla into one row. Instead, what I see is that phylum taxa is maintained but still no merging and in fact there are multiple taxa that are redundant and not being merged in my phyloseq object. Is there a way to better diagnose the issue or method to better tackle what I am trying to do? Or am I misinterpreting what tax_glom is suppose to do?

Thanks, 
Max

**Comment by ycl6** [comment]
Hi @maxmiao 

Can you try the function on the demo dataset so that we can be sure the package it working fine on your environment?

```R
library(phyloseq)
data(GlobalPatterns)

GP <- GlobalPatterns
Phylum1 <- tax_glom(GP, taxrank = "Phylum")
Phylum2 <- tax_glom(GP, taxrank = rank_names(GP)[2]) # Same as Phylum1
```

```
> GP
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 19216 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 19216 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 19216 tips and 19215 internal nodes ]

> rank_names(GP)
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"

> Phylum1
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 66 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 66 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 66 tips and 65 internal nodes ]

> Phylum2
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 66 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 66 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 66 tips and 65 internal nodes ]
```

**Comment by maxmiao** [comment]
Hello, 

So I just ran the command you just provided. It looks like tax_glom function is working I am getting the same outputs as what you wrote above. I guess there must be something weird about how I formatted my data for phyloseq that is causing the issue.

**Comment by ycl6** [comment]
@maxmiao I can take a look into this if you don't mind sharing your phyloseq object (or a subset of the data).

**Comment by maxmiao** [comment]
Sounds good! 

I've just attached two different subsets of my data: 

[ps.A.zip](https://github.com/joey711/phyloseq/files/7982572/ps.A.zip)
[ps.merged.zip](https://github.com/joey711/phyloseq/files/7982575/ps.merged.zip)

Also, if you could tell me what I maybe doing that is causing this would be great too so that I may avoid it in the future. 

Thanks in advance, 
Max

**Comment by ycl6** [comment]
Hi @maxmiao 

I have a look at your `tax_table` structure and the `tax_glom` function. In the line I quote below, the function selects the matrix with `1:CN`, where `CN` is the rank that was chosen to agglomerate. For a typical `phyloseq` object that starts with `Kingdom` in its Taxonomy Table, this would have work alright, but because your sturcture contain additional columns before `Kingdom`, the merging process does not work properly. By moving the first 2 column to the back, the function will work as intended. 

https://github.com/joey711/phyloseq/blob/dc35470498c79284231d41d1add1a74940f51fb7/R/transform_filter-methods.R#L406-L407

```R
library(phyloseq)
ps.A = readRDS("ps.A")
```

```
# "otu_id" and "taxonomy" before "Kingdom"
> rank_names(ps.A)
 [1] "otu_id"      "taxonomy"    "Kingdom"     "Phylum"      "Class"       "Order"      
 [7] "Family"      "Genus"       "Species"     "last_taxon"  "final_names" "otu"        
```

```R
# Re-order the columns
tax_table(ps.A) <- tax_table(ps.A)[,c(3:12,1,2)]
```

```
# Starts with "Kingdom"
> rank_names(ps.A)
 [1] "Kingdom"     "Phylum"      "Class"       "Order"       "Family"      "Genus"      
 [7] "Species"     "last_taxon"  "final_names" "otu"         "otu_id"      "taxonomy"   
```

```R
Phylum <- tax_glom(ps.A, taxrank = "Phylum")
Phylum
```

```
> ps.A
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 10615 taxa and 414 samples ]
sample_data() Sample Data:       [ 414 samples by 28 sample variables ]
tax_table()   Taxonomy Table:    [ 10615 taxa by 12 taxonomic ranks ]

> Phylum
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 36 taxa and 414 samples ]
sample_data() Sample Data:       [ 414 samples by 28 sample variables ]
tax_table()   Taxonomy Table:    [ 36 taxa by 12 taxonomic ranks ]
```

**Comment by maxmiao** [comment]
Thank you!!!

**Comment by Palliko** [comment]
Hi There,

I am having a problem when converting my phyloseq object at the genus level and it shows the following error

Problematic Genus values detected in tax_table:
 Ruminococcus  Clostridium
-
taxa_name / Kingdom / Phylum / Class / Order / Family / Genus / Species / ASV / ASV_tax
ASV.00099 /  Bacteria /  Firmicutes /  Clostridia /  Clostridiales /  Ruminococcaceae /  Ruminococcus
ASV.00363 /  Bacteria /  Firmicutes /  Clostridia /  Clostridiales /  Clostridiaceae /  Clostridium
ASV.01006 /  Bacteria /  Firmicutes /  Clostridia /  Clostridiales /  Lachnospiraceae /  Clostridium
ASV.04743 /  Bacteria /  Firmicutes /  Clostridia /  Clostridiales /  Ruminococcaceae /  Clostridium
ASV.11033 /  Bacteria /  Firmicutes /  Clostridia /  Clostridiales /  Lachnospiraceae /  Ruminococcus
-
Error in tax_agg(., rank = "Genus") : Taxa not unique at rank: Genus
See last messages for convergent taxa rows.

To fix the problem, try:
  `yourData %>% tax_fix(unknowns = c(" Ruminococcus", " Clostridium"))`

Try tax_fix_interactive() to find and fix further problems

I have to fix this issues can anyone help with this 
Thanks

**Comment by david-barnett** [comment]
Hi @Palliko,

This is a [microViz](https://david-barnett.github.io/microViz/index.html) question as tax_agg is a microViz function.

The instructions here can help you further https://david-barnett.github.io/microViz/articles/web-only/tax-fixing.html

Your problem is slightly surprising to me though, as you have, for example, ASVs classified as "Clostridium" at the Genus level within both the families Clostridiaceae and Ruminococcaceae  ... 

I am curious, what tool/pipeline/reference database did you use for the taxonomic classification?

**Comment by Palliko** [comment]
Hi@david-barnett,

thanks, I was used Qiime2 dada2 pipeline. Do you have any comments on this why "Clostridium" is under both families?
 Is these tool/pipeline issues?  or anything else

thanks

**Comment by david-barnett** [comment]
not sure, what classifier and what reference database? 

For your use case you'll need to decide what to do with these taxa, and manually correct their taxa table entries, e.g. delete the genus classification for the mismatching rows and let tax_fix copy across the family name to fill those gaps. But my guess would be that they are rare ASVs, possibly some odd sequencing errors that confused the classifier

**Comment by Palliko** [comment]
Hi david
Thanks for your suggestions, I will correct it manually then.

One thing I need to clarify with you 

I am having a problem with the R script for my analysis using ancom.
My study approach is 2 x 2 factorial design i.e 2 genetic lines and 2 efficiencies ( for example, E line high and low, Z line high and low efficiency). I want to see the interaction of 2 genetic lines with the month as a random effect

It shows an error while using the below script

Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘NSBS’ for signature ‘"formula"

out = ancom(data = NULL, assay_name = NULL,

        tax_level = "Genus", phyloseq = Digestibilitya,
        p_adj_method = "holm", prv_cut = 0.10, lib_cut = 20000,
        main_var = "Genotype + Efficiency + Genotype:Efficiency", adj_formula = NULL,
        rand_formula = "MONTH", lme_control = NULL,
        struc_zero = TRUE, neg_lb = TRUE, alpha = 0.05, n_cl = 1)

Can anyone give me a suggestion on my approach? Can we able to do the interaction approach using ancom?
It would be highly appreciated if you provide me with the right direction for my approach.

thanks
