### ISSUE TITLE
plot_richness() Chao1 graph?

### ISSUE THREAD

**Issue by marwa38** [joey711/phyloseq#1553]
Hello
Could you please let me know why I am getting the Choa1 graph with (dashes) - over the points rather than only points ( .) as the other graphs?
this is the code I used
```
plot_richness(ps.prev.f, x = "phase", measures = c("Observed", "Shannon", "Chao1")) +
  geom_boxplot() +
  theme_classic() +
  theme(strip.background = element_blank(), axis.text.x.bottom = element_text(angle = -90))  +
  stat_compare_means(method = "kruskal.test") 
```
your comment or advice would be helpful  
![image](https://user-images.githubusercontent.com/68851733/154484767-0bedbb62-36a1-4910-9fe8-01ef76f6f222.png)

**Comment by ycl6** [comment]
Hi @marwa38 

If you just use `plot_richness`, you'll notice Chao1 estimates are presented with errorbar. 
So you might want to use `estimate_richness` to calculate the alpha diversity estimates, then create your own plot with `ggplot2`.

```R
library(phyloseq)
data(GlobalPatterns)

plot_richness(GlobalPatterns, x = "SampleType", measures = c("Observed", "Shannon", "Chao1"))
```

![plot_richness](https://user-images.githubusercontent.com/9032946/154679480-80053101-0cf3-4413-9b12-9a7e032cc1ea.png)

https://github.com/joey711/phyloseq/blob/dc35470498c79284231d41d1add1a74940f51fb7/R/plot-methods.R#L760-L764
