### ISSUE TITLE
When removing samples from phyloseq object, their corresponding taxa are not removed in parallel

### ISSUE THREAD

**Issue by emankhalaf** [joey711/phyloseq#1572]
Hi,

I need to remove a specific variable from the metadata, so I removed samples representing this variable from the phyloseq object as follows:
#remove wild genotype
```{r}
to_remove <- c("sample1", "sample2")

ps <- prune_samples(!(sample_names(ps0) %in% to_remove), ps0)
ps
```
However, when extracting sequences from the phyloseq object, I still see taxa that exclusively exist in removed samples. 
Any recommendation about how to remove samples along with their taxa from the phyloseq object?

Thanks!

**Comment by benjjneb** [comment]
Follow up with pruning taxa with zero abundance.

```
ps <- prune_taxa(taxa_sums(ps)>0, ps)
```

**Comment by emankhalaf** [comment]
@benjjneb 
Much thanks!
