### ISSUE TITLE
plot_ordination() visualisation query?

### ISSUE THREAD

**Issue by marwa38** [joey711/phyloseq#1618]
Hi Guys
Do you know why the dots are in between and not on each boxplot?
![image](https://user-images.githubusercontent.com/68851733/187221432-65e5f062-24e6-42b2-8612-cfcf0b45f847.png)
Thanks 
M

**Comment by ycl6** [comment]
Hi @marwa38 It's a ggplot2 thing, [check this post](https://stackoverflow.com/questions/50650423/r-ggplot-how-to-align-points-with-dodged-bars)

**Comment by marwa38** [comment]
Hi @ycl6 

Thanks for your reply. Will ask my query there then. This is helpful. 
Regarding plot_ordination() I tried many changes to the code to delete the title/subtitle/caption (I don't how to define it) of the previous word "Shannon" in my attached figure in the post, do you know what I can do to get rid of it?

**Comment by marwa38** [comment]
Hi @ycl6
Here are the codes if you would to have a quick look;
```
plot_richness(ps.prev.intesParts.f, x = "part", measures = "Shannon", 
              color = "Samples") +
  geom_boxplot() +
  theme_classic() +
  theme(text = element_text(size = 20)) +
  theme(strip.background = element_blank(), axis.text.x.bottom = element_text(angle = 90)) +
  labs(x = "Intestinal Parts", y = "Shannon Index") +
  theme(legend.title = element_blank())

```

I think that the figure issue is not the same as the one in stackflow you kindly shared, and might be originating from the original `plot_richness() ` code outputs, what do you think? in addition, I haven't seen this issue before using ggplot.
