### ISSUE TITLE
rm.na.phyloseq in plot_ordination

### ISSUE THREAD

**Issue by fanhuan** [joey711/phyloseq#1650]
Hi,

I was trying to make some aesthetics adjustments to `plot_ordination`, but in this github repo I could not find a function called `rm.na.phyloseq` which was used in `plot_ordination`. Any idea where I could find it? 

Best,
Huan

**Comment by ycl6** [comment]
Hi @fanhuan 

You can use the search box (top left) to search `rm.na.phyloseq` in this repo. This is where the function resides:

https://github.com/joey711/phyloseq/blob/dc35470498c79284231d41d1add1a74940f51fb7/R/plot-methods.R#L1161-L1175
