### ISSUE TITLE
importing files from qiime

### ISSUE THREAD

**Issue by CarlyMuletzWolz** [joey711/phyloseq#167]
Hello,

I am trying to bring in otu_table.biom, mapping file = SMP_Run1_Map.txt, and a tree rep_set.tre

``` S
otufile = "otu_table.biom"
mapfile = "SMP_run1_Map.txt"
treefile = "rep_set.tre"

run1 <- import_qiime (otufile, mapfile, treefile)
```

but when I run the the import_qiime command this is what I get

```
Processing map file...
Processing otu/tax file...

Reading and parsing file in chunks ... Could take some time. Please be patient...

Building OTU Table in chunks. Each chunk is one dot.
.
Error in `colnames<-`(`*tmp*`, value = character(0)) : 
  attempt to set colnames on object with less than two dimensions
```

what am I doing wrong?

I can import the biom file with 

``` S
import_biom(otufile)
```

and get this:

```
phyloseq-class experiment-level object
OTU Table:          [2592 species and 28 samples]
                     species are rows
Taxonomy Table:     [2592 species by 6 taxonomic ranks]:
```

I can import the mapping file 

``` S
import_qiime_sampleData(mapfile)
```

and see all of my mapping data

How do I import my tre file? I tried this with no success

``` S
import_qiime(otufilename=F, mapfilename=F, treefile)
```

In my 454 run I had one control that came back with no sequences and I don't know if that is causing an issue (zeros in the biom file??) in the import_qiime function?

I had to manually add a blank line in the biom file so that it didn't have an 'incomplete' line or R would not import it

But by bringing in these files separately I realize that I am missing commands that are built into the function 

``` S
import_qiime 
```

I can do the import_qiime function with the sample obesity data set so I assume there is something wrong with my files that I am too much of a rookie to figure out. After a day of searching and trying to troubleshoot on my own I now pass my issue on to an expert! 

Thanks - Carly

**Comment by Paula0666** [comment]
Hey, I'm importing the mapping file just fine, and the tree as well. But I'm having problems with the biom file. I added the metadata using biom --add metadata, but when I imported it into R, I got the following:
import_biom(otufile)
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 27566 taxa and 24 samples ]
sample_data() Sample Data:       [ 24 samples by 4 sample variables ]
tax_table()   Taxonomy Table:    [ 27566 taxa by 7 taxonomic ranks ]
Warning message:
In strsplit(msg, "\n") : input string 1 is invalid in this locale

I tried several times, and I have no idea how to solve this. Any thoughts? Thanks
