### ISSUE TITLE
Error "taxa_names<-: You are attempting to assign duplicated taxa_names" when substituting OTUs to Genus

### ISSUE THREAD

**Issue by francescaangiol** [joey711/phyloseq#1671]
Hello!!

I am trying to clean my taxonomic table and I am encountering an error that I cannot seem to get passed by. I have already aggregated to genus level the OTUs successfully and all I need is just to substitute the names of such OTUs to the genus. When I run the command this message pops:
Error in `taxa_names<-`(`*tmp*`, value = new("taxonomyTable", .Data = c("MarineGroupII",  : 
  taxa_names<-: You are attempting to assign duplicated taxa_names

I have already checked with _duplicated()_ but seems like I don't have any duplicates. 

I have searched in many forum questions but nothing is really helpful. I also tried checking on my table if there are issues with the higher ranks but I have almost 7000 OUTs and doing it one by one is too long.

I'd really appreciate any suggestions or help

**Comment by gmteunisse** [comment]
There probably are genera in your `tax_table` that have identical names, despite having a different upstream taxonomy. I would suggest to simply leave the agglomerated ASV names as the `taxa_names` - I don't think there are many analyses for which the `taxa_names` matter. However, if you do have an application that requires is, you will need to somehow label duplicated genera to make them unique. I have implemented such a function in the [`fantaxtic` package](https://github.com/gmteunisse/Fantaxtic): `label_duplicate_taxa` will identify any duplicated annotations at a specified taxonomic rank (e.g. Genus), and add a tag to ensure unique annotations.

**Comment by francescaangiol** [comment]
Thank you, in deed I left the names as they were and it was okay.
