### ISSUE TITLE
Sudden Error with the distance() function

### ISSUE THREAD

**Issue by Aliceall** [joey711/phyloseq#1688]
Hi!
I have started having this sudden error with the distance() function in phyloseq. I did not have this error few weeks ago.
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'distance' for signature '"phyloseq", "missing"'
Script is: jacc_distance = distance(data, method = 'jaccard')
Other functions work well.
I have R4.1.2 phyloseq 1.44
Please let me know if you have any clue!
Thank you very much

**Comment by ycl6** [comment]
Hi @Aliceall 

You've probably loaded a R package that has a function also named `distance` that has taken precedence. 
You can use `phyloseq::distance()` to explicitly use the `distance` function from `phyloseq`.

**Comment by Aliceall** [comment]
Thank you @ycl6! Such an easy fix...I hadn't really thought of it.
