### ISSUE TITLE
Error in eval(call("force", as.symbol(paste0("..", x))))

### ISSUE THREAD

**Issue by fconstancias** [joey711/phyloseq#1736]
Hello there,

I have been working with phyloseq for a while now. I have recently installed phyloseq on a new Mac M2 and I am now facing the issues described with the example below:

```
BiocManager::install("phyloseq", force = TRUE)
require(phyloseq)
data(GlobalPatterns)
GlobalPatterns
phyloseq-class experiment-level object
Error in eval(call("force", as.symbol(paste0("..", x)))) : 
  argument "..2" is missing, with no default
```

ANy idea what is going on here?

Thanks

**Comment by ycl6** [comment]
Hi @fconstancias 

The error message seems to be originated from the `glue_data` function from the `glue` package. 

https://github.com/tidyverse/glue/blob/9f88e2179fc7aa6ff11214271fd61bba169f925c/R/glue.R#L116-L127

I don't see `glue` as one of `phyloseq`'s dependencies. So I am wondering if it is another package required by `phyloseq` but wasn't installed properly.

**Comment by fconstancias** [comment]
Thanks for your help. It seems restarting R after the installation solved the issue...
