### ISSUE TITLE
Help with permanova test via vegan::adonis

### ISSUE THREAD

**Issue by maxru** [joey711/phyloseq#184]
Hi Joey,

I was wondering if it would be possible to add the option to do a permanova on your NMDS distance data e.g., similar to the adonis function from vegan?

cheers and thanks for your work!
max

**Comment by mechagear** [comment]
@maxru 
I'm sorry for the off-topic comment, but I couldn't find any other way to get in touch with you. 

In case you don't already need your username, I'd like to use it for my repositories (I've been using the same username since the early 2000s). 
Please contact me by email from my profile.
