### ISSUE TITLE
Genus labels incorrection with plot_heatmap (ggplot2 bug)

### ISSUE THREAD

**Issue by dragonflywingz** [joey711/phyloseq#192]
Hello,
I noticed when I add genus labels to my heat map they are labelled incorrectly. I do have some OTUs where the genus is "NA". When I label the heat map with Orders it is fine. I am guessing because and all of my OTUs are assigned at the order level.

It would be best if the unknown Genus names could be labelled "NA"

Here is my code:

``` S
test <- plot_heatmap (denoised_fil, sample.label = "Sample", species.label="Genus")
test + theme(axis.text.x = element_text(size=11, angle=90, hjust=1), axis.text.y=element_text(size=11))
```

I would like to be able to control the order of the samples and taxa if possible. Do you know of a way to do this?

Thanks,
Amber

**Comment by montoyah** [comment]
Hi Joey,

I've a similar problem but with bar_plot. The unresolved genera are reported as NA, and they're not showing up in the legend but the colored graphs are in the plot. The solution for the heatmap issue here was also implemented for bar_plots. If it was, how can I use it to convert the NAs into text so I can replace them with scale_fill_manual(), for example?

Thanks in advance.

**Comment by negin1986** [comment]
Hi all,

I made a heatmap based on phylum on the Y axis and species on the X axis. However, my taxa labels are so long (for some reason) that the labels are not visi
<img width="567" alt="Screen Shot 2019-03-21 at 11 12 48 AM" src="https://user-images.githubusercontent.com/12476457/54766978-471bec00-4bca-11e9-86ff-cbf2f8a96817.png">
ble at all.
