### ISSUE TITLE
Some related questions about OTU names and refseqs

### ISSUE THREAD

**Issue by joey711** [joey711/phyloseq#208]
I was recently emailed a string of good and related questions about using phyloseq. Here are the questions and my answers. There was no bug fix or documentation task, so I am posting my answers here along with the questions in case they are useful.
### OTU names for refseq

The ID in the tree is obviously the OTU ID (rather than this full name), so this initial number should be all that's required to connect the OTU abundance per sample with its phylogeny in the tree and the sequence in the refseq file.  Does that sound correct to you?  If so, I can just strip out everything from the space and all is well.  The reason I'm slightly concerned is that in [your HMP example on github](http://joey711.github.io/phyloseq-demo/HMP_import_example.html) the sequences are called 
`OTU_97.1`, `OTU_97.2`, etc., 
implying that there a multiple sequences for an OTU called 97...
- **Answer**: No, this statement is `FALSE`. the OTU names do have that format with "OTU_97" prepended in the front. The reason appears to be to emphasize that it was a 97% similarity cutoff. The actual identifying information appears to be everything after the `.`, so the code that I provided above should be all you need. You can important the sequences first with `Biostrings::readDNAStringSet()`, rename them, and then use `merge_phyloseq` to properly combine all the data.
- Parsing the names of representative OTU sequences to use as refseqs -
  Yes, you will have to make sure the name of each sequence is just the OTU name. There was code for doing this in the HMP example:

``` S
names(refseqs) <- gsub("(^[[:print:]]{7,13})([[:space:]]{1,})([[:print:]]{0,}$)", "\\1", names(refseqs))
head(names(refseqs))
```
### Non-matching sequences.
- I've noticed in the past that occasionally there will be small numbers of OTUs in the OTU table that don't have a matching tip in the rep_set tree produced by QIIME via FastTree (I still haven't got to the bottom of why this is).  Is this going to be problematic for phyloseq objects?  
- **Answer**: No.
- I think I read in the documentation that these are discarded from phyloseq objects,
- **Answer**: That's correct. Only OTUs present in every component are kept in the merged phlyoseq data object.
- but is it possible to see which OTUs and rep_seqs they are?  
- **Answer**: Yes. You can import the components separately (these must be from different files, by definition), and then compare their OTU names. Something like:

``` S
setdiff(union(taxa_names(myOTUtab), taxa_names(tree)), intersect(taxa_names(myOTUtab), taxa_names(tree)))
```

will tell you right away which OTUs are found only in a subset.
- If it's an abundant OTU then I might be discarding information that I should be keeping and will have to come up with another solution. Right?
- **Answer**: It would be absolutely bizarre if an important, abundant OTU was not represented in one of your output files from QIIME. That would be a bug that you should report to the qiime developers. More likely, there are OTUs included in the tree that were not (ever) in your original data. I'm not sure why QIIME includes these. Meanwhile, I'm not sure what you would want to do with extra OTUs that are in your tree but you cannot explain and for which you don't have abundance information.
### Stacked bar charts

Finally, I have an aversion to stacked bar charts nearly as great as an aversion to pies (possibly completed unjustified), but have been attempting to make them a little better. Again in case it's useful for phyloseq, here's a change I've made to attempt to improve http://palecomic.tumblr.com/post/48523558818/a-slightly-better-stacked-bar
It works best for dominated samples, such as those we see in clinical infection.  

**Answer**:
It's unclear to me why you would be "against" stacked bar charts, particularly the highly flexible way that I've layered it on top of ggplot2 in phyloseq. Bar charts as a general category convey quantitative information in a way that is cognitively easy to understand. The internal rectangles in the stack are admittedly difficult for humans to compare (still probably better than pie slices), but my intention in creating the `plot_bar` function was for comparing the height of each stack -- however you decide to organize it -- while being honest about the relative contributions of the OTUs that make up the total, since these can change dramatically. Sometimes this is sufficient, sometimes it takes multiple plots and organizations to fully display it all. Note that this is categorically different than the clear argument leveraged by statisticians against pie charts, which is that humans are demonstrably bad at quantitatively interpreting area slices -- especially circular ones, but even rectangular areas suffer these challenges. Conversely, humans are very good at comparing the heights of things and identifying linear trends. Hence the preference for bar charts. 

Combined with the rest of the facilities in ggplot2, the`plot_bar` function is pretty powerful. For instance, it is already capable of creating the faceted bar chart you showed at your link. Try the following example code:

``` S
data("GlobalPatterns")
gp.ch = subset_taxa(GlobalPatterns, Phylum == "Chlamydiae")
plot_bar(gp.ch, fill="as.character(OTU)") + facet_wrap(~OTU, nrow=ntaxa(gp.ch))
plot_bar(gp.ch, fill="Genus") + facet_wrap(~OTU, nrow=ntaxa(gp.ch))
```

Hope that helps, and thank you very much for the feedback!

**Comment by Gian77** [comment]
Hello Joey,
I have renamed my OTUs using the taxa_names() easily, but off course the OTU representative sequences haven't been renamed. Is there a way to do that so they match they new OTU names?
Thanks in advance,
Gian
