### ISSUE TITLE
`read_tree` broken w/ latest GreenGenes

### ISSUE THREAD

**Issue by audy** [joey711/phyloseq#224]
The phylogenetic trees included latest GreenGenes database ([13.5](http://greengenes.secondgenome.com/downloads/database/13_5)) break the `read_tree` function in PhyloSeq. These trees are in annotated Newick format and contain the taxonomic description for each node. If the quoted text is removed, `read_tree` fine.

I see two possible fixes for this:

1.) Ignore the quoted text in the Newick parser.
2.) Use the quoted text to return a taxonomy table object and a phylogenetic tree in one go.
### Code to reproduce the error:

``` S
library(phyloseq)

read_tree('97_otus.tree')
```

Produces the error:

```
NULL
Warning messages:
1: In go.down() : NAs introduced by coercion
Calls: read_tree ... doTryCatch -> read.tree -> lapply -> FUN -> go.down
2: In go.down() : NAs introduced by coercion
Calls: read_tree ... doTryCatch -> read.tree -> lapply -> FUN -> go.down
```

Or, if you use the full tree:

``` S
read_tree('gg_13_5_otus_99_annotated.tree')
# quietly returns NULL
```

The 99 annotated tree seems to contain un-quoted labels of the most-specific taxonomic description for each node.

**Comment by hochoy** [comment]
Hi, I noticed that this problem has returned with the newer greengenes  v13_8. This affects both the annotated and unannotated trees. I got my tree files from this link: ftp://greengenes.microbio.me/greengenes_release/gg_13_8_otus/trees/ 

```r
library("phyloseq")
# v13_8
gg_13_8_99 <- read_tree_greengenes("99_otus.tree")
```
the `read_tree_greengenes()` function works. However, it produces the following warnings:
```r
Warning messages:
1: In go.down() : NAs introduced by coercion
2: In go.down() : NAs introduced by coercion
3: In go.down() : NAs introduced by coercion
4: In go.down() : NAs introduced by coercion
5: In go.down() : NAs introduced by coercion
6: In go.down() : NAs introduced by coercion
7: In go.down() : NAs introduced by coercion
8: In go.down() : NAs introduced by coercion
9: In go.down() : NAs introduced by coercion
10: In go.down() : NAs introduced by coercion
11: In go.down() : NAs introduced by coercion
12: In go.down() : NAs introduced by coercion
13: In go.down() : NAs introduced by coercion
14: In go.down() : NAs introduced by coercion
15: In go.down() : NAs introduced by coercion
16: In go.down() : NAs introduced by coercion
17: In go.down() : NAs introduced by coercion
```
and plotting doesn't work
```r
plot_tree(gg_13_8_99)
# output
Error in ape_node_depth_edge_length(Ntip, Nnode, z$edge, Nedge, z$edge.length) : 
  NA/NaN/Inf in foreign function call (arg 6)
```
I looked into the tree object itself and found that the NA's are found in the `edge.length` property.
```r
head(gg13_8_99$edge.length)
#output
[1] 0.30560 0.01212 0.01587      NA      NA 0.02539
head(gg13_8_99$node.label)
[1] ""             ""             "'k__Archaea'" ""             "'0.961"       "'0.972" 
```
I tried to run `read_tree_greengenes()` with the unannotated version of the tree but plotting produced the same error
```r
gg_13_8_99_unannotated <- read_tree_greengenes("99_otus_unannotated.tree")
plot_tree(gg_13_8_99_unannotated)

# output
Error in ape_node_depth_edge_length(Ntip, Nnode, z$edge, Nedge, z$edge.length) : 
  NA/NaN/Inf in foreign function call (arg 6)

gg13_8_99_unannotated$edge.length %>% is.na() %>% which()
#output
[1] 9884

gg13_8_99_unannotated$edge.length[9880:9890]
#output
 [1] 0.05304 0.03791 0.53452 0.17677      NA 0.11173 0.05307 0.00922 0.01669 0.04260 0.06976

```
