### ISSUE TITLE
Understanding filterfun_sample

### ISSUE THREAD

**Issue by diana-t** [joey711/phyloseq#226]
Hi Joey and Phyloseq users,

I am trying to filter my samples ( top 10 OTUs from each sample) using the filterfun_sample function, and just be trying on the example code this is what I've done:

``` S
mydata3
```

```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3542 taxa and 32 samples ]
sample_data() Sample Data:       [ 32 samples by 8 sample variables ]
tax_table()   Taxonomy Table:    [ 3542 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 3542 tips and 3540 internal nodes ]
```

``` S
f1=filterfun_sample(topp(0.1))
wh1=genefilter_sample(mydata3,f1,A=2)
top10=prune_taxa(wh1,mydata3)
top10
```

```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3542 taxa and 32 samples ]
sample_data() Sample Data:       [ 32 samples by 8 sample variables ]
tax_table()   Taxonomy Table:    [ 3542 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 3542 tips and 3540 internal nodes ]
```

I'm wondering why this is not working. I also tried the `A=0.5` of `nsamples` as in the demo, but that doesnt work as well. I guess I'm not really sure what the `A` value should be and if it is necessary. What I would like in the end is to show what are the top OTUs for each sample.

Thanks very much!!

Dian

**Comment by DeniRibicic** [comment]
Hi All,

I see this is a older post, but I'm having problem understanding how filterfun_sample works. Let's say I define the function 
`f1=filterfun_sample(topp(0.005))`
Does this mean that I return abundances greater than 5%. If not how would you achieve that?
Any help appreciated,
Deni
