### ISSUE TITLE
Alternative order of samples/taxa

### ISSUE THREAD

**Issue by ConnieHa** [joey711/phyloseq#230]
Hi Joey,

This is my first time using R so I have lots of questions on how to generate heatmaps. After following your extensive tutorial I managed to plot a heatmap using my own data (see attached), great colours but I need help to make it better. 

![hfdgenuslog10](https://f.cloud.github.com/assets/5134744/891540/5e2244c6-fa5e-11e2-9159-ed26e476d0b5.png)

1) My aim was to show the effect of diet on microbiota at the genus level. Is there a way to group all the samples by diet? For instance, all control samples on the left and all HFD on the right? 

2) I also want to group genera by their phylogenetic relationship but at this stage they seem to be all over the place. For this heatmap I used otu table from qiime, a tree file of all the otus and a mapping file as the input. Do I need additional info to group the taxa phylogenetically or just additional commands on top of the ones you showed in the demo?

3) Can you provide more information on how the program compute abundance from the otu table? The number of reads varies between samples (range from 2000-10000) so I was wondering does the plot_heatmap command normalise the data before generating a heatmap or do I have to do that manually (like provide a provide of relative abundance rather than absolute counts)?

It would be great if you can give me a few pointers!

Cheers,
Connie

**Comment by rachaelantwis** [comment]
Hi @ConnieHa ,

I was wondering if you would be willing to share your code you used to produce this figure agglomerated to genus level? I have been sing the following and all the genus-level names are displaying as NA:

```{r}
roots.ra = tax_glom(roots, taxrank="Genus")
roots.heatmap = transform_sample_counts(roots.ra, function(x){x / sum(x)})
fig <- plot_heatmap(roots.heatmap, "Genus", taxa.label = "Genus")
```

Any help would be much appreciated!
Many thanks in advance

**Comment by rahel31** [comment]
Hi @joey711 

In this thread in 2013 you mentioned What I should probably do is include a user-definable option for the "start" sample and/or OTU, in case this helps better center the key clusters in the heatmap.

My heatmaps are not very well centered - similar clusters on the edges. Hoped I can just lift them in the Illustrator on the right side, but that doesn't appear to be too simple either. 
Have you managed to look into it ? Is there any way to define a start sample and OTU? 

Thank you in advance!
