### ISSUE TITLE
merge_samples hiccup

### ISSUE THREAD

**Issue by dmap02** [joey711/phyloseq#243]
I've been trying to merge replicate samples using the merge_samples function in phyloseq. I'm starting with a phyloseq object called "filtered".

If I run this:

> map <- sample_data(filtered)
> dereplicate <- map$DeReplicate
> derep = merge_samples(filtered, dereplicate, fun=sum)

Two things happen that perhaps shouldn't.
1. The sample names change. The original object was "filtered" and the output object was "derep". The change in sample names is shown below. I think it's renaming the samples by the dereplicate variable.

``` S
sample_names(filtered)
```

```
   [1] "Run1.P1.1.03B.D2.R0"   "Run1.P1.1.14B.D8.R0"   "Run1.P1.1.30L.D4.R0"   "Run1.P1.1.25B.D5.R0"  
   [5] "Run1.P1.1.30B.D2.R0"   "Run1.P1.1.19L.D6.R0"   "Run1.P1.1.30B.D3.R0"   
```

``` S
head(sample_names(derep))
```

```
[1] "P1-1.03B.D1" "P1-1.03B.D2" "P1-1.03B.D3" "P1-1.03B.D4" "P1-1.03B.D5" "P1-1.03B.D6"
```
1. The mapping file changes. Categorical variables get converted to continuous variables, and then summed as well.

``` S
head(sample_data(filtered))
```

```
Sample Data:        [6 samples by 19 sample variables]:
                             X.SampleID BarcodeSequence  LinkerPrimerSequence Plate  Run       Name Habitat Well
Run1.P1.1.03B.D2.R0 Run1.P1.1.03B.D2.R0    AACTCGTCGATG GCACTCCTACGGGAGGCAGCA     1 Run1 338F_BC002     03B   A2
Run1.P1.1.14B.D8.R0 Run1.P1.1.14B.D8.R0    ACTATTGTCACG GCACTCCTACGGGAGGCAGCA     1 Run1 338F_BC048     14B  D12
```

``` S
head(sample_data(derep))
```

```
Sample Data:        [6 samples by 19 sample variables]:
            X.SampleID BarcodeSequence LinkerPrimerSequence Plate Run Name Habitat Well PrimerAKey Tooth Jaw
P1-1.03B.D1          1               1                    1     1   1    1       2    1          1    19   2
P1-1.03B.D2          2               2                    1     1   1    2       2    5          1    19   2
```

I tried to run the `merge_samples` on the OTU table independently of the mapping file and tre in order to circumvent the summing of the mapping file, but since the `sample_names` change I can't merge it with the tree...

Any suggestions?

**Comment by orenkolodny** [comment]
Perhaps worth writing something about this issue in the command documentation. It took me half an hour of trying to work this out until I found this thread... Thanks!

**Comment by joey711** [comment]
That's a fair request. I won't re-open this issue, but I will note the doc update as a requirement for closing #608

**Comment by orenkolodny** [comment]
Thanks!



On Wed, Mar 15, 2017 at 10:44 AM, Paul J. McMurdie <notifications@github.com

**Comment by rachaelantwis** [comment]
Hi, further to my request on another thread today, I think this thread is more similar to my problem. I have just realised that I am having the same problem with factors becoming continuous variables for multiple variables. Is there a way to return these to their original names without renaming all labels? Many thanks

**Comment by rachaelantwis** [comment]
This is the code I have used:
df <- as.data.frame(lapply(sample_data(final.data.reduced.0),function (y) if(class(y)!="factor" ) as.factor(y) else y),stringsAsFactors=T) #change any non-factors to factors
row.names(df) <- sample_names(final.data.reduced.0) 
sample_data(final.data.reduced.0) <- sample_data(df)
merged.raw = merge_samples(final.data.reduced.0, "Tree_leaflet_groups")
SD = merge_samples(sample_data(final.data.reduced.0), "Tree_leaflet_groups")
print(SD)
print(merged.raw)
sample_names(merged.raw)
identical(SD, sample_data(merged.raw))

I am then using:
sample_data(merged.raw)$Tree_leaflet_groups <- factor(sample_names(merged.raw))
to return Tree_leaflet_groups to original labels, but if I use, e.g. 

sample_data(merged.raw)$Tree_status <- factor(sample_names(merged.raw)),
this just relabels Tree_status with the Tree_leaflet_groups labels

Thank you
