### ISSUE TITLE
Plotting environmental vectors in CCA

### ISSUE THREAD

**Issue by kfontanez** [joey711/phyloseq#274]
Joey-

I've been using CCA to plot functional pathways. I'd like to plot the environmental vectors in a similar way that vegan does. Is there a way to do this in phyloseq?

I can make a pretty plot in phyloseq, which has everything I want, but it lacks the biplot arrows:

> c=plot_ordination(TOP5,cca.deptreat,shape="TREATMENT",label="Definition",type="biplot",color="DEPTH",title="CCA of Top5 KEGG orthologs constrained by treatment*depth")
> c+scale_color_gradient(limits=c(150,500),low="red",high="blue",expression(Depth[meters]))

![screen shot 2013-12-04 at 11 30 08 am](https://f.cloud.github.com/assets/5814641/1674959/62306862-5d01-11e3-8a6c-6837e7d2d0a4.png)

In vegan I use the output of your ordinate function to make a plot with the arrows included: 

> cca.deptreat

Call: cca(formula = OTU ~ DEPTH \* TREATMENT, data = data)

Inertia Proportion Rank
Total          0.4983     1.0000
Constrained    0.3211     0.6443    3
Unconstrained  0.1773     0.3557    3
Inertia is mean squared contingency coefficient

Eigenvalues for constrained axes:
   CCA1    CCA2    CCA3
0.14973 0.11848 0.05285

Eigenvalues for unconstrained axes:
    CA1     CA2     CA3
0.08029 0.05853 0.03846

> plot(cca.deptreat,choices=c(1,2),display=c("wa","bp"),type="points",xlim=c(-4,1.5),scaling=2)
> points(cca.deptreat,disp="sites",pch=21,col="red",bg="red",cex=1.3)
> text(cca.deptreat,"sites",pos=3,axis.bp=TRUE) 
> ![screen shot 2013-12-04 at 11 28 44 am](https://f.cloud.github.com/assets/5814641/1674940/29dd6f78-5d01-11e3-8af5-0a4e9dd04ea8.png)

I'd like to got those biplot arrows onto the phyloseq plot. Can this be done?

Thanks,
Kristina

**Comment by montoyah** [comment]
Hi all,

I'm trying to reproduce this example to add arrows to my CAP plot, following [this tutorial](http://deneflab.github.io/MicrobeMiseq/demos/mothur_2_phyloseq.html#data_import) but have no idea where the arguments for "display" like "sites" or "species" in "vegan::scores()" function come from. Must they be variable names in the ps object? I even replaced one of my sam_data columns to "sites" but throws an error: 

`Error` in scores.default(ordcapPlot, display = "sites") : Can't find scores` 

In my case, I have taxa down to genus, no species. The Vegan help pages I found didn't clarify my doubts. 

`abundancesTop20NoNA <- abundancesTop20 %>%
  subset_samples(
    !is.na(phosphate..mM..alkaline) & 
      !is.na(phosphate..mM..acidic) &
      !is.na(Acetate..mM.) & 
      !is.na(sulfate..mM.)
  )`


`bray_no_na <- phyloseq::distance(physeq = abundancesTop20NoNA, method = "bray")`

`ordcap = ordinate(abundancesTop20NoNA, #abundances, 
                  method =  "CAP", 
                  distance = bray_no_na,
                  formula = ~  sites * phosphate..mM..alkaline)`

Create plot:

`ordcapPlot <- plot_ordination(abundancesTop20NoNA,  
                ordination = ordcap,
                #type = "biplot",
                color="sites",
                axes = c(1, 2)) +
  aes(shape = sampleReceived) +
  geom_point(aes(color = type),alpha = 0.4, size = 4) + 
    geom_point(colour = "grey90", size = 1.5) + 
    scale_color_manual(values = c("#a65628", "red"))      #, "#ffae19", "#4daf4a",  "#1919ff", "darkorchid3", "magenta")`
  
Here'e were the error appears:
`arrowmat <- scores(ordcapPlot, display = "sites")`

Thanks in advance for any help,

Oscar.

[psObject.zip](https://github.com/joey711/phyloseq/files/849236/psObject.zip)

**Comment by CarlyRae** [comment]
Yes, it would be great to have an updated example for this! I am running into errors. 

Mine start at:

> arrow_map = aes(xend = CCA1, yend = CCA2, x = 0, y = 0, shape = NULL, color = NULL, 
+     label = labels)
Error in aes(xend = CCA1, yend = CCA2, x = 0, y = 0, shape = NULL, color = NULL,  : 
  could not find function "aes"

**Comment by jflater** [comment]
Try 

`arrowmat <- vegan::scores(ordcapPlot, display = "sites")` or try changing display to bp `display = "bp"`

**Comment by gretchend** [comment]
Hi there--

Has anyone tried to add environmental vectors while plotting the 2nd and 3rd axes of their ordination? I can't seem to figure out how to get the arrow coordinates for any axes besides 1 and 2.

Thanks in advance!
Gretchen
