### ISSUE TITLE
Problem importing biom file using import_qiime()

### ISSUE THREAD

**Issue by anmwinter** [joey711/phyloseq#302]
Hi Joey,

  A friend pointed me towards phyloseq as a tool I should be using for our upcoming papers. I had a few questions about the import_qiime function.

I am on an OS X 10.7.5 running R 3.x and RStudio. I installed the newest version of phyloseq from the github repo. I am using QIIME 1.8

Here is how I brought my qiime files in. 

``` S
biom_file = "otu_table.biom"    
map_file = "VLmapping.csv"      
tree_file = "rep_set_tree.tre"
villaluz <- import_qiime(biom_file, map_file, tree_file)
```

```
Processing map file...
Processing otu/tax file...

Reading and parsing file in chunks ... Could take some time. Please be patient...

Building OTU Table in chunks. Each chunk is one dot.
.
Error in `colnames<-`(`*tmp*`, value = character(0)) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

I saw this error from a year ago here on the forums but didn't find an answer to that. 

I can still proceed downstream:

``` S
villaluz
```

```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 4977 taxa and 7 samples ]
sample_data() Sample Data:       [ 7 samples by 10 sample variables ]
tax_table()   Taxonomy Table:    [ 4977 taxa by 8 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 4977 tips and 4975 internal nodes ]
```

``` S
rank_names(villaluz)
```

```
[1] "Rank1"   "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"
```

``` S
get_taxa_unique(villaluz, "Phylum")
```

```
 [1] NA                 "WPS-2"            "ZB3"              "AC1"             
 [5] "Gemmatimonadetes" "GN04"             "GOUTA4"           "FCPU426"         
 [9] "Actinobacteria"   "Firmicutes"       "NKB19"            "Proteobacteria"  
[13] "BHI80-139"        "Nitrospirae"      "Lentisphaerae"    "OP3"             
[17] "Verrucomicrobia"  "Planctomycetes"   "LD1"              "BRC1"            
[21] "WS3"              "OP8"              "PAUC34f"          "GAL15"           
[25] "GN02"             "Chloroflexi"      "OD1"              "Elusimicrobia"   
[29] "[Thermi]"         "WS2"              "TM7"              "Armatimonadetes" 
[33] "OP11"             "TM6"              "Acidobacteria"    "SR1"             
[37] "Spirochaetes"     "WS1"              "FBP"              "Cyanobacteria"   
[41] "Bacteroidetes"    "TPD-58"           "[Caldithrix]"     "Fibrobacteres"   
[45] "Chlorobi"  
```

The main problem I am running into is when I do anything with the tree all I get for node id's are the denovo numbers and not actual OTUs that were assigned in QIIME.

I will keep my questions to a minimum so I don't clutter up the thread to much.

1) Why I am getting this error using import_qiime
Error in `colnames<-`(`*tmp*`, value = character(0)) : 
  attempt to set 'colnames' on an object with less than two dimensions

but I can see the phyla and running all the box plots of alpha diversity and make bar plots

2) Why can't I get my tree nodes to assign their taxonomy correctly?

Thanks for the help and suggestions!
ara

**Comment by jsilve24** [comment]
I am getting the same error when the following code is run:  (Note I was just following your tutorial found [here](http://joey711.github.io/phyloseq-demo/HMP_import_example.html))
```
library(phyloseq)

otutax = '/Users/Justin/Research/data/_data_derived/HMP16s/otu_table_psn_v35.txt.gz'
map = '/Users/Justin/Research/data/_data_derived/HMP16s/v35_map_uniquebyPSN.txt.bz2'

tree = read_tree_greengenes('/Users/Justin/Research/data/_data_derived/HMP16s/rep_set_v13.tre.gz')
tree$tip.label <- gsub("'", "", tree$tip.label, fixed = TRUE)

HMPv35 <- import_qiime(otutax,map,tree)
```
I get the following error after the call to import_qiime
```
Processing map file...
Processing otu/tax file...
Reading file into memory prior to parsing...
Detecting first header line...
Header is on line 2  
Converting input file to a table...
Read 45383 rows and 4790 (of 4790) columns from 0.409 GB file in 00:00:07
Defining OTU table... 
Parsing taxonomy table...
Processing phylogenetic tree...
 
Error in cat(list(...), file, sep, fill, labels, append) : 
  argument 2 (type 'list') cannot be handled by 'cat'
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by spholmes** [comment]
Justin,
What people usually do is biom convert their old qiime files to the newer
biom format and then
import.
https://github.com/joey711/phyloseq/issues/480
If you can't get a more recent format.

I would separate the steps into 3 separate imports to pinpoint the error.
Some of our tutorials are written in earlier versions of both qiime and
phyloseq so some things have changed.

It might be worth trying a small test example and providing us with a
minimum working example
so we can try to see where it is going wrong,

Best
Susan

On Mon, Feb 29, 2016 at 12:32 PM, Justin Silverman <notifications@github.com
> wrote:

> I am getting the same error when the following code is run: (Note I was
> just following your tutorial found here
> <http://joey711.github.io/phyloseq-demo/HMP_import_example.html>)
>
> library(phyloseq)
>
> otutax = '/Users/Justin/Research/data/_data_derived/HMP16s/otu_table_psn_v35.txt.gz'
> map = '/Users/Justin/Research/data/_data_derived/HMP16s/v35_map_uniquebyPSN.txt.bz2'
>
> tree = read_tree_greengenes('/Users/Justin/Research/data/_data_derived/HMP16s/rep_set_v13.tre.gz')
> tree$tip.label <- gsub("'", "", tree$tip.label, fixed = TRUE)
>
> HMPv35 <- import_qiime(otutax,map,tree)
>
> I get the following error after the call to import_qiime
>
> Processing map file...
> Processing otu/tax file...
> Reading file into memory prior to parsing...
> Detecting first header line...
> Header is on line 2
> Converting input file to a table...
> Read 45383 rows and 4790 (of 4790) columns from 0.409 GB file in 00:00:07
> Defining OTU table...
> Parsing taxonomy table...
> Processing phylogenetic tree...
>
> Error in cat(list(...), file, sep, fill, labels, append) :
>   argument 2 (type 'list') cannot be handled by 'cat'
> In addition: There were 50 or more warnings (use warnings() to see the first 50)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/302#issuecomment-190373360>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by apoosakkannu** [comment]
Hi, I created biom file using qiime and imported in phyloseq using following command

OTU_TAXA<-import_biom("D:/Czech/Triatomine2019/microbiome_data_20182019/data/otutable97_taxa_20182019.biom")


The import was successful but i found that there were 20 taxonomy ranks instead of 7 taxonomy ranks in my phyloseq object. Some of my OTUs are having blank taxonomy, could that be a problem. If so please let me know, how to overcome this problem. 

Thanking you and looking forward to hear from you.
