### ISSUE TITLE
data transformation in ordinate

### ISSUE THREAD

**Issue by laurenms** [joey711/phyloseq#315]
Hi Joey, 
I would like to use the ordinate function but I'm trying to figure out if I need to square root transform the data before using the function or if the data is transformed within ordinate. Since the ordinate function wraps metaMDS does that mean that argument autotransform=TRUE? If so, then it seems like the data is transformed within ordinate?

In the metaMDS documentation it says autotransform can be set to false so that the data transformation can be controlled by the user before using metaMDS. Is there a way to do this with the ordinate function in phyloseq? If not, that would be helpful.
Thanks!
lauren

**Comment by yzhong005** [comment]
ORD3<-ordinate(phy,"NMDS","jaccard",trymax=1000,autotransform =FALSE)
I tried to change autotransform to FALSE, didn't work, it provide the same result with autotransform =TRUE
