### ISSUE TITLE
Reading in data and merging

### ISSUE THREAD

**Issue by annidjurhuus** [joey711/phyloseq#316]
When using the import_biom and sample_data functions is it possible to merge these to with the merge_phyloseq function? 

I have some problems getting my metadata and phylogenetic data into the same dataframe, which means it is not possible for me to add labels to the figures appropriately (e.g. by month/year/geographical location). When I read in the sample data and the biom file and merge them with the merge_phyloseq all the columns of the metadata are not correctly read in and I don't get all the data necessary for analysis. 

Am I supposed to join them before reading them into R or is there an essential function I have missed? 

My code is:

biom <-import_biom("biom_file", sam_data)

sampledata <- sample_data(data.frame(Location = sample("metadata", size = nsamples(biom), replace = TRUE), size = nsamples(biom), replace = TRUE,row.names = sample_names(biom), stringsAsFactors = FALSE))

df <- merge_phyloseq(sampledata,biom)

This is my output from the dataframe:
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 43143 taxa and 181 samples ]
sample_data() Sample Data:       [ 181 samples by 3 sample variables ]
tax_table()   Taxonomy Table:    [ 43143 taxa by 7 taxonomic ranks ]

The problem happens when I read in the sample data, not with the merging, however, I am not entirely sure what I am doing wrong. 

Thank you very much for your help!

Best wishes,
Anni

**Comment by Aanuoluwaduro** [comment]
> "When using R to read in CSV files it doesn't work to merge the biom and mapping file because the mapping file is not a phyloseq object, I presume"
> 
> You presume incorrectly. Any data object in R can be coerced into a format for phyloseq. In this case, use the `sample_data` function on the `"data.frame"`-class object that you create when you read the csv file using `read.csv`. Also note that you already did this without knowing it in your code above (in the `sample_data(data.frame( ... ))` call).
> 
> ```m68k
> physeq = import_biom("biom_file")
> # Define a data frame from your csv table
> sampleDF = read.csv("path/sampleDataFile.csv", row.names=1)
> # Check that the rownames match the sample names
> all(rownames(sampleDF) %in% sample_names(physeq))
> # Convert to "sample_data" class
> sampledata = sample_data(sampleDF)
> # Now merge.
> physeq2 = merge_phyloseq(sampledata, physeq)
> ```
> 
> Hope that helps! Obviously you will need to modify the file path/name for your data, and you may have to tweak the arguments to `read.csv` or use `read.table`, depending on your file.
> 
> p.s. You should review the documentation for the `sample` function. It is not something you want to be using when you are assigning ID values to a table...

This just helped me! Thanks!
