### ISSUE TITLE
ordiellipse for ordinations

### ISSUE THREAD

**Issue by davidelliott** [joey711/phyloseq#323]
Hi Joey

Thanks for phyloseq, I find it very useful and recently published a paper which relied on it a lot. 

I wanted to do CCA with environmental variables and ellipses to graphically highlight some groupings. To achieve this I used phyloseq to do the ordination then used the generated data to plot with base graphics and allow use of the envfit() and ordiellipse() functions in vegan. I noticed you recently demonstrated plotting environmental vectors within the ggplot framework ([issue 274](https://github.com/joey711/phyloseq/issues/274)) and wondered if something similar might be possible for the ellipses. 

Here is an example demonstrating how I did it:

```R
library(phyloseq)
library(vegan)

data(enterotype)
# simplify the data
enterotype = subset_samples(enterotype, !is.na(Enterotype))
enterotype = subset_samples(enterotype, SeqTech!="Sanger")
expt = prune_taxa(names(sort(taxa_sums(enterotype), TRUE)[1:50]), enterotype)

ord = ordinate(expt~Enterotype, "CCA", "bray")
(ordplot <- plot_ordination(expt, ord, "samples", color="Enterotype",shape="SeqTech"))

# get data from the plotted ordination. Not strictly necessary but can be useful
orddata <- ordplot$data

# add a fake variable to the experiment
sample_data(expt)$fake <- 1:nsamples(expt)

# get map out of phyloseq object 
map.df <- data.frame(sample_data(expt))

# use the envfit function of vegan
(ord.ef <- envfit(ord~fake,permu=1000,data = map.df))

# make a blank plot
plot(x=orddata$CCA1, y=orddata$CCA2,type="n") 

# plot the points for each type
points(ord, disp="si", cex = 0.5, col=map.df$Enterotype,pch=19)

# draw ellipses
ordiellipse(ord, map.df$SeqTech,label=TRUE,cex=0.7,conf=0.99,col="brown") 

# show the fitted fake variable
plot(ord.ef) 

# add a legend
legend("bottomleft", inset=c(-0.0,0), legend=levels(map.df$Enterotype), bty = "n", col = levels(map.df$Enterotype), pch = 19, title="Enterotype")

# The end result of this example is a plot showing points coloured
# by entrotype, and ellipses indicating the sequencing technology
```

Can something like this be done in ggplot or directly with phyloseq? 

Dave

**Comment by joey711** [comment]
I've been hoping to solve this one for apparently more than 2 years now! My how time flies...

# Ellipses feature now supported directly by ggplot2

## This part is same as your code...

```R
library(phyloseq)
```

```R
data(enterotype)
# simplify the data
enterotype = subset_samples(enterotype, !is.na(Enterotype))
enterotype = subset_samples(enterotype, SeqTech!="Sanger")
expt = prune_taxa(names(sort(taxa_sums(enterotype), TRUE)[1:50]), enterotype)

ord = ordinate(expt, formula = ~Enterotype, "CCA", "bray")
(ordplot <- plot_ordination(expt, ord, "samples", color="Enterotype",shape="SeqTech"))
```


![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/841437/15061539/7b94666c-12eb-11e6-985d-1108cb16780b.png)


## Now add the ordination ellipses

The following includes two different types of ellipse layers, added to the same plot.
As a phyloseq/ggplot2/R user, you can decide which to use, if any,
and also what distribution you'd like them to use as basis for the ellipse.
In this case, a t-distribution and normal distribution (dashed) are demonstrated. 

```R
library("ggplot2")
ordplot + 
  stat_ellipse(type = "norm", linetype = 2) +
  stat_ellipse(type = "t") +
  theme_bw()
```


![unnamed-chunk-2-1](https://cloud.githubusercontent.com/assets/841437/15061544/83d0f502-12eb-11e6-9fd9-85c0fadec5f4.png)

**Comment by joey711** [comment]
Forgot to link, [ellipses with ggplot2, stat_ellipse](http://docs.ggplot2.org/current/stat_ellipse.html)

**Comment by davidelliott** [comment]
Thank you

Time flies indeed. It is great to be able to do this all within phyloseq/ggplot now. 

Best wishes

**Comment by mpricketts** [comment]
Hey,
Related to this, i am having trouble with an ordination where somehow the order of the variable I am mapping to both the color of points (in plot_ordination: color=) and to the fill of the ellipses (stat_ellipse: aes(fill=).  See below:
  
    ordination <- ordinate(pseq_filt20_prop,"PCoA", "unifrac")
    p1 = plot_ordination(pseq_filt20_prop, ordination, type="sample", color="Site", shape="Layer", title="PCoA - Unifrac") + theme_bw()
    p1 + stat_ellipse(geom = "polygon", type="norm", alpha=0.4, aes(fill=Site))

This results in 
![rplot](https://user-images.githubusercontent.com/5720683/39586573-fbf28fe6-4ebc-11e8-8318-2a24ec6bff4a.jpeg)

Notice that while the points, and even the ellipses themselves, have the correct color, the colors of the fill for HC and HV have flip-flopped, and its been driving me bonkers!
Any help is appreciated.

**Comment by mpricketts** [comment]
Thanks!!

**Comment by maherrl** [comment]
Hi, 
I am trying to use the stat_ellipse() function to draw ellipses around the variable I specified with shape = rather than color =.

`a <- plot_ordination(ps, nmds_bc, color = "geno", shape = "bleach") + 
  geom_point(size = 2) + 
  theme_classic() +
  theme(legend.position = "left") +
  labs(color = "Genotype") +
  scale_colour_manual(values = myCol)
a + stat_ellipse(geom = "polygon", type = "norm", aes(fill=bleach))
`
I get the following warning:
Too few points to calculate an ellipse
Too few points to calculate an ellipse
Too few points to calculate an ellipse
Too few points to calculate an ellipse
Too few points to calculate an ellipse

![image](https://user-images.githubusercontent.com/29050285/70748226-72a5b000-1cde-11ea-8465-9d29bb4b4c94.png)

Can I add ellipses to the "bleach" variable even though I colored points with "geno"?

**Comment by silvtal** [comment]
Hi,

The "+ stat_ellipse() works great with just one ordination plot, thank you! However, when I try to add ellipses to multiple ordinations that have been plotted together (which also works fine by using "+ geom_point()", I get the following warning message and the ellipses get ignored.

```
        ordplot <- plot_ordination(
          justDF = TRUE,
          physeq = abun_ps, 
          ordination = ord, 
          type  = "taxa",
          shape = "id.type",
          color = "n",
          title = X)
        all_plots <- all_plots + # all_plots has been initialized with another ordplot before, but with "justDF=FALSE"
          geom_point(data = ordplot) +
          stat_ellipse(type = "norm", linetype = 2)      
```

```
Warning messages:
1: Removed 1098 rows containing non-finite values
(stat_ellipse).
```
Any ideas on how I can make this work?

**Comment by fullertonhe** [comment]
This thread suggests that stat_ellipse is misleading. How best could I use ordiellipse with a phyloseq object?
https://stackoverflow.com/questions/72206348/adding-a-95-confidence-interval-to-nmds-plot
