### ISSUE TITLE
phyloseq_to_deseq2 not found?

### ISSUE THREAD

**Issue by slindgreen** [joey711/phyloseq#325]
Hi

I have just installed phyloseq (version 1.6.1 according to R) after reading your recent paper in PLoS Comp Bio. I want to use the DESeq2 approach instead of rarefying our data. However, I cannot use the function "phyloseq_to_deseq2" mentioned in the manual. I get the error:
Error: could not find function "phyloseq_to_deseq2"

Everything else I have tried works fine (reading BIOM files, plotting etc.)

What am I doing wrong?

Thanks,
Stinus

**Comment by Zuby88** [comment]
I have the same error "phyloseq_to deseq2 not found". 

Please , how do you install the latest version of phyloseq or the phyloseq version 1.7.12 so that the function phyloseq_to deseq2  could work. A download link fo phyloseq version 1.7 will be very helpful. 

Thank you
