### ISSUE TITLE
subset_taxa by OTU id

### ISSUE THREAD

**Issue by audy** [joey711/phyloseq#332]
Is it possible to use subset_taxa using the taxonomy ID in the tax_table?

Based on what I see here in the code for [`subset_taxa`](https://github.com/joey711/phyloseq/blob/master/R/taxonomyTable-class.R#L109-L125) I don't think it is but I remember seeing a warning about using `OTU` as a column header in the taxonomy table being a no-no.

So I was thinking this might be planned for the future.

It could be made possible by adding `rownames(tax_table(phy))` as a column in the taxonomy table but I don't know if that might break `tax_glom` and friends.

Anyway, It would be useful :smile:

**Comment by glickmac** [comment]
b1 = tax_glom(ps, taxrank = "Genus")
Genus10 = names(sort(taxa_sums(b1), TRUE)[1:10])
x1 = prune_taxa(Genus10, b1)
tax = as.data.frame(x1@tax_table)
top_ten = as.character(tax$Genus)
