### ISSUE TITLE
Counting unique OTUs per sample at different taxonomic levels

### ISSUE THREAD

**Issue by spencerJD** [joey711/phyloseq#337]
Hello,

I am a new user to phyloseq and have a quick question with regards to data display. I know that there is the function sample_sums(x) which returns the number of sequences per sample, but I am wondering if there is a way to do a count of the number of OTUs at different taxonomic levels. For instance, if I wanted to know the number of Orders or Genera present for each sample. Is there a way to do this using phyloseq?

Thank you for your response!

All the best,
Spencer

**Comment by coyk** [comment]
Hi,
 I interpreted spencer JD's question differently and it's the same question I have.  Here's an example of what I'm looking for.

I have a total of 1000 reads and 10 OTUs.  OTU 01 has 900 reads.  OTU 02 has 50 reads.  OTU 3 has 43 reads.  OTUs 4-10 each have a single read.  OTU 01, 4,7,9 all belong to Family A.  OTU 02, 5, 10 belong to Family B.  OTU 03 and 06 belong to Family C.  OTU 08 belongs to Family D.  What I am trying to achieve is a table of the unique families with just the number of OTUs in each one.  Not the number of reads.  In this case:
Family A	4
Family B	3
Family C	2	
Family D	1

Here is what I don’t want, but it’s what I get:
Otu01 903
Otu02 52
Otu03 44
Otu08 1

Everything I’ve come across gives a table with OTU vs read count.  I saw the issue number that says “mt function now adds taxonomy if present, as of v1.5.4.” and I monkeyed around with mt but I couldn’t get this simple output.  Tax_glom reports results as reads as opposed to taxonomic classifications as well.  Is there a simple way to do this that I am overlooking?

**Comment by jeffkimbrel** [comment]
Try this, changing `phyloObject` to the name of your phyloseq object, and "Family" to whatever your taxonomy you want the counts for.

```
table(tax_table(phyloObject)[,"Family"])
```

**Comment by coyk** [comment]
Bless you.  The output is a bit clunky but I'll take it!

**Comment by jeffkimbrel** [comment]
No problem. You can do all of the usual things with it, such as make it a data frame by putting the command inside `as.data.frame()`.

**Comment by aamurilloc** [comment]
Hello guys, 
Nice post! I'm trying to get something slightly different, but related. I need to extract the unique OTUs per sample, whit his taxonomy associated. Any idea? 
I tried with:
> observationThreshold = 1 
> apply(gentab > observationThreshold, 2, sort) 
But what I got was a table full of 'FALSE' outputs 

Thanks in advance

**Comment by brunob7** [comment]
Hi all,
This post has been tremendously helpful, but I am running into a little problem.
It works well when I do the analysis at the Genus level, but at the Species level most of my OTUs are NA. I really need to be able to differentiate between species, or at least have multiple repeats on the Genus level, to account for this differences. Any ideas?

Thanks!

**Comment by raw937** [comment]
How do you find the number of OTUs per sample?

**Comment by leonardonormando** [comment]
@raw937 
I'm new to phyloseq, but I think something like this would work:
```
sample01 <- subset_samples(PHY, SampleID == "sample01")
sample02 <- subset_samples(PHY, SampleID == "sample02")

sample01 <- filter_taxa(sample01, function(x) sum(x) > 0, TRUE)
sample02 <- filter_taxa(sample02, function(x) sum(x) > 0, TRUE)

ntaxa(sample01)
ntaxa(sample02)
```
The `SampleID` field was added to the metadata table before the creation of the phyloseq object (using `merge_phyloseq(otus+tree, metadata)`)

**Comment by anniewest** [comment]
For those of you looking for the number of OTUs/ASVs per sample, I used this code:

asv_df <- t(otu_table(phyloseq_object))
colSums(asv_df != 0)

Make sure that your samples are columns, not rows (ASV/OTU in rows).

**Comment by kenreally** [comment]
Not sure when it was implemented, but this is built into phyloseq now:

plot_richness(phyloseq_object, x = "SampleID", measures = "Observed" )
