### ISSUE TITLE
dist objects in ordinate()

### ISSUE THREAD

**Issue by michberr** [joey711/phyloseq#344]
Hi Joey,

I'm getting very different results when I calculate a distance metric in-line of the ordinate function versus passing in a dist object

For example:
# Bray curtis distance

bdist = distance(fruit.scale,"bray")
# Ordinate and plot NMDS

bray.nmds = ordinate(fruit.scale, method="NMDS", distance = bdist)
plot_ordination(fruit.scale,bray.nmds,color = "Tribe") 

versus:
# Ordinate and plot NMDS

bray.nmds = ordinate(fruit.scale, method="NMDS", distance="bray")
plot_ordination(fruit.scale, bray.nmds, color="Tribe")

I tried with a few different distance metrics, and had similarly mismatched results. Not sure why this is happening because  metaMDS should take either a dist object or a community matrix + a distance.

**Comment by michberr** [comment]
Two years later, I'm glad i now know how to effectively use markdown. Here's an MRE

```
data("GlobalPatterns")
gp <- GlobalPatterns

# Distance matrix calculated from call to distance
bray_dist <- phyloseq::distance(gp, "bray")
nmds_bray <- ordinate(gp, method = "NMDS", distance = bray_dist)
plot_ordination(gp, nmds_bray, color = "SampleType")
```
![dist](https://cloud.githubusercontent.com/assets/6405404/14325621/25037752-fbf8-11e5-9028-5237ef5f26ce.jpeg)


```
# Distance calculated inline
nmds_bray_inline <- ordinate(gp, method = "NMDS", distance = "bray")
plot_ordination(gp, nmds_bray_inline, color = "SampleType")
```

![dist_inline](https://cloud.githubusercontent.com/assets/6405404/14325625/28c0d79a-fbf8-11e5-8b66-b3129be2dd06.jpeg)

Now that i look at the output more closely, it seems that when you call `distance = "bray"` inline (which is a call to `vegan::metaMDS`) it automatically applies a square root transformation and a Wisconsin double standardization.  These transformations are not applied when you call `phyloseq::distance` and subsequently pass the output dist object to `ordinate`.

Case closed :)

**Comment by joey711** [comment]
Nice! Good sleuthing. Do you have any suggestion for how to improve the phyloseq doc to make this more transparent to the user?

**Comment by michberr** [comment]
I can add something to the `ordinate` documentation and submit a PR

**Comment by yogeshgupt** [comment]
I am not able to understand this discussion:

what is  the difference between Distance matrix calculated from call to distance and Distance calculated inline?

which one is correct?

after DESeq2 vst normalisation should I use these two codes for beta diversity?

# Distance calculated inline
nmds_bray_inline <- ordinate(gp, method = "NMDS", distance = "bray")
plot_ordination(gp, nmds_bray_inline, color = "SampleType")

**Comment by yyachung** [comment]
It's been a few years and I just discovered the same issue as well when contrasting my output using ordinate( , distance="bray") inline vs. directly using metaMDS() on the otu_table from the phyloseq object. Why are there default transformations applied in the first case as OP mentioned? If I wanted them to happen, I would prefer the opportunity to directly specify that. None of the documentation that I could find mentioned this potential discrepancy. More transparency please!
