### ISSUE TITLE
Canonical Correspondence including environmental variables

### ISSUE THREAD

**Issue by kmikkels** [joey711/phyloseq#350]
Hey - 
I have been going through the ordination methods (in the phyloseq tutorials) and have been able to create some great plots using plot_ordination (CCA and PCoA) but I cannot figure out how to create a canonical correspondence plot that includes the environmental variables as separate axes (bi or triplot). Is there a tutorial or example script that goes over this?

Thanks!
~Kristin

**Comment by bedemickan** [comment]
Hey Kristin, how did you go including env variables into your ordination plots? Im at the same stage now, did you get it sorted?

Cheers,

Bede

**Comment by kmikkels** [comment]
Hi Bede -

I ended up first graphing the CCA in phyloseq and then using the CCA scores from vegan to add arrows. Definitely not an efficient way to go about doing this, but the example at the bottom of issue #274 was a great tutorial and easy to follow.

Good luck!
~Kristin

**Comment by bedemickan** [comment]
Cheers kmikkels, I forgot to reply - you earn 1 virtual beer:)
