### ISSUE TITLE
Question regarding DESeq2 model

### ISSUE THREAD

**Issue by spencerJD** [joey711/phyloseq#351]
Hello,

I am following the example you have presented here (http://joey711.github.io/phyloseq-extensions/DESeq2.html) with my own data, and I have a question regarding the DIAGNOSIS variable and how DESeq2 uses it. 

When you convert your phyloseq object to a deseq object, and then run the deseq() function, I am unsure which variable it makes the 'control' variable, and which the 'test'. For instance, I would assume that in the example you give, the 'Healthy' samples are the control, and that the log2FoldChange which is given is of OTUs in the 'Tumor' samples which differ from the 'Healthy' (so the sign of the log2FoldChange is of the OTU abundance in the 'Tumor' sample as compared to the 'Healthy' sample). Is this assumption correct?

If that is the case, in my data set, I want to see which OTUs are significantly enriched in one sample type over another, let's say in treatment 'A' over treatment 'B'. How do I make sure that the sign of the differential abundance is reflecting this test instead of the opposite (ie. which OTUs are significantly more abundant in treatment 'B' over treatment 'A'.) 

I hope that is clear, and if it is not, please let me know so i can clarify further. 

Thank you for your help!

Spencer

**Comment by rahulnccs** [comment]
I have similar question.
We have analyzed differential OTU abundance between disease (CeD) and control (DC) groups. To visualize the differential OTUs we used ggplot2 package. But we are unable to know, in which category a certain OUTs are abundant. For e.g. in image ( https://ibb.co/cOe7fF) OUT belonging to Balutia is enriching in one of the group how to know whether it is enriching in disease(CeD) group or control (DC) group?

Thanks in advance
