### ISSUE TITLE
request to expand plot_tree function

### ISSUE THREAD

**Issue by StefPN** [joey711/phyloseq#355]
Hi,

In large projects, plotting the abundance of each species at the tips of the tree may not be very easy to visualise. I wonder how I could plot the median of all samples in one group (I have 700 samples in a total of 5 groups) instead of the abundance of each sample at the tips? Instead of having sizes of symbols representing the abundance, maybe the option to plot bars of the respective length (median) could be very informative? In this particular project, I have some metadata info I would also like to filter accordingly. E.g. one tree with only the female samples from the phyloseq object and compare to a "male only" tree.  Finally, I would like to label the tips not by a taxa level such as "Genus" or "Species" but rather the original otu number, as in several cases, I have the same taxa name (i.e. same species) but different otu numbers (clustered att 99%) and I need to distinguish between them.

Thanks a lot for your help!
Cheers,
Stef

**Comment by neavemj** [comment]
Hi Joey, just wondering if this feature has now been implemented into phyloseq? 

Thanks!

Matt.

**Comment by joey711** [comment]
Nope, not implemented directly in phyloseq.
The recommended way to do this is to aggregate among samples "manually" to define a new/temporary/aggregated phyloseq object, and then pass this along to `plot_tree` for plotting.

I also recommend checking out [ggtree](https://www.bioconductor.org/packages/release/bioc/html/ggtree.html)
