### ISSUE TITLE
phyloseq_to_deseq2() adds 1 to the counts

### ISSUE THREAD

**Issue by JCSzamosi** [joey711/phyloseq#387]
It looks like the function phyloseq_to_deseq2() adds 1 to the counts as part of an attempt to make sure the data are integers. I believe this is artificially driving down the dispersion estimates of low-abundance OTUs by converting all the 0s to 1s, which could lead to spurious significant p-values of low-abundance OTUs.

I have implemented a new version of phyloseq_to_deseq2() with that line commented out and I haven't yet encountered any errors.

**Comment by amckinlay** [comment]
@joey711 Should maybe the tutorials be updated, too? http://joey711.github.io/phyloseq-extensions/extensions-index.html

**Comment by amckinlay** [comment]
Actually, it looks like the "DESeq2" tutorial was similar to the mixture model vignette at some point, and has diverged in other ways, too. Should the tutorial just be scrapped for the vignette?

**Comment by JacobRPrice** [comment]
@amckinlay I was running into the same problems as @JCSzamosi when following the [tutorial](http://joey711.github.io/phyloseq-extensions/DESeq2.html). The procedure in the [vignette](https://www.bioconductor.org/packages/devel/bioc/vignettes/phyloseq/inst/doc/phyloseq-mixture-models.html) works just fine.

**Comment by rlh13** [comment]
I am attempting to run this alternate code on my phyloseq object but I am still encountering the following error after estimateSizeFactors:
Error in .local(object, ..., value) : all(!is.na(value)) is not TRUE
Any idea why this might be happening?
