### ISSUE TITLE
renamed sample Ids after import_qiime_sample_data

### ISSUE THREAD

**Issue by muol** [joey711/phyloseq#395]
Hi,
I'm using phyloseq 1.8.2 and R 3.1.1 in ubuntu 12.04 x64. I tried to import a tab delimited sample mapping file, which was validated and worked in qiime 1.8. Sample Ids are labeled with plane numbers, like 1,2,3..., but after import_qiime_sample_data they are all renamed and prefixed  with "sa", i.e. sa1, sa2, sa3...

This of course throws an error message when I try to merge the map with my otu biom file.

Details:

bash:
>head -5 my_map.tsv | cut -f1
#SampleID
1
2
3
4

R:
>map_file = "my_map.tsv"
>map <- import_qiime_sample_data(map_file)
>sample_names(map)
 [1] "sa1"  "sa2"  "sa3"  "sa4"  "sa5"  "sa6"  "sa7"  "sa8"  "sa9"  "sa10"
[11] "sa11" "sa12" "sa13" "sa14" "sa15" "sa16" "sa17" "sa18" "sa19" "sa20"
[21] "sa21" "sa22" "sa23" "sa24" "sa25" "sa26" "sa27" "sa28" "sa29" "sa30"
[31] "sa31" "sa32" "sa33" "sa34" "sa35" "sa36" "sa37" "sa38" "sa39" "sa40"
[41] "sa41" "sa42" "sa43" "sa44" "sa45" "sa46" "sa47" "sa48" "sa49" "sa50"
[51] "sa51" "sa52" "sa53" "sa54" "sa55" "sa56" "sa57" "sa58" "sa59" "sa60"
[61] "sa61" "sa62" "sa63"

Any idea what might be causing this?
Thanks

**Comment by OlliLaroche** [comment]
Hi muol, I'm experiencing a similar problem. I'm importing cvs files but the name of my samples are changed in my OTU_table, a X is added to the name (i.e: 1ab_site becomes X1ab_site). Did you find out what is causing this?

**Comment by michberr** [comment]
Hi, this post should answer that question for you https://github.com/joey711/phyloseq/issues/488. 

Long story short, there are many R packages that dislike strings that start with numbers, so you will need to rename your samples.

**Comment by OlliLaroche** [comment]
Thanks Michelle, it makes sense now. I'll keep that in mind next time I label.

**Comment by Ambassadormathismathews** [comment]
> Hi, I'm using phyloseq 1.8.2 and R 3.1.1 in ubuntu 12.04 x64. I tried to import a tab delimited sample mapping file, which was validated and worked in qiime 1.8. Sample Ids are labeled with plane numbers, like 1,2,3..., but after import_qiime_sample_data they are all renamed and prefixed with "sa", i.e. sa1, sa2, sa3...
> 
> This of course throws an error message when I try to merge the map with my otu biom file.
> 
> Details:
> 
> bash:
> 
> > head -5 my_map.tsv | cut -f1
> > # SampleID
> > 1
> > 2
> > 3
> > 4
> 
> R:
> 
> > map_file = "my_map.tsv"
> > map <- import_qiime_sample_data(map_file)
> > sample_names(map)
> > [1] "sa1"  "sa2"  "sa3"  "sa4"  "sa5"  "sa6"  "sa7"  "sa8"  "sa9"  "sa10"
> > [11] "sa11" "sa12" "sa13" "sa14" "sa15" "sa16" "sa17" "sa18" "sa19" "sa20"
> > [21] "sa21" "sa22" "sa23" "sa24" "sa25" "sa26" "sa27" "sa28" "sa29" "sa30"
> > [31] "sa31" "sa32" "sa33" "sa34" "sa35" "sa36" "sa37" "sa38" "sa39" "sa40"
> > [41] "sa41" "sa42" "sa43" "sa44" "sa45" "sa46" "sa47" "sa48" "sa49" "sa50"
> > [51] "sa51" "sa52" "sa53" "sa54" "sa55" "sa56" "sa57" "sa58" "sa59" "sa60"
> > [61] "sa61" "sa62" "sa63"
> 
> Any idea what might be causing this? Thanks

jerradalenmathews@yahoo.com

**Comment by Ambassadormathismathews** [comment]
Wtf
