### ISSUE TITLE
.jplace compatibility

### ISSUE THREAD

**Issue by wbrazelton** [joey711/phyloseq#396]
Are there any plans to allow importing of a .jplace file into phyloseq? Reference:
http://www.plosone.org/article/info%3Adoi%2F10.1371%2Fjournal.pone.0031009

I ask because I would like to be able to use plot_tree to illustrate the number of query sequences placed onto a reference tree, i.e. output from RAxML-EPA or pplacer. In practice, I think the only difference would be allowing for the possibility to plot the sample abundance associated with each node of the tree instead of the sample abundance at each tip. Perhaps this is already possible without a formal input function for .jplace files, but I couldn't find a way. 

Another way of phrasing this question is that I am looking for an alternative to the "fat tree" style of visualization of pplacer or EPA results in archaeopteryx (e.g. Figs 1-2 in http://arxiv.org/abs/1005.1699). I would rather plot the abundance data as a colorized plot next to the tree, as implemented in phyloseq, but with each plot associated with an internal node rather than a branch tip. What do you think?

Bill Brazelton

**Comment by joey711** [comment]
I think [ggtree](http://www.bioconductor.org/packages/release/bioc/html/ggtree.html) is what you're looking for. Seems like a next-step in ggplot2-based tree visualization. I'm hoping to connect to it more in phyloseq, but in the mean time, you probably want to check it out...
