### ISSUE TITLE
DESeq2 creates error with distance function

### ISSUE THREAD

**Issue by cw808** [joey711/phyloseq#399]
Hi,

I was trying to look at the list of distance methods and received the following error:

> unlist(distance("list"))
> Error in unlist(distance("list")) : 
>   error in evaluating the argument 'x' in selecting a method for function 'unlist': Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘distance’ for signature ‘"character", "missing"’

In trying to track down this error discovered I only receive it when I have loaded DESeq2 using.  I not only received the error just trying to look at the list but also trying to run the distance function on a phyloseq object.  If I begin without loading DESeq2 then I do not get the error and the function seems to work fine.  The following shows the sequence of before and after loading DESeq2.

> library("phyloseq")
> unlist(distance("list"))
>      UniFrac        DPCoA          JSD     vegdist1     vegdist2     vegdist3     vegdist4     vegdist5     vegdist6     vegdist7     vegdist8     vegdist9    vegdist10    vegdist11 
>    "unifrac"      "dpcoa"        "jsd"  "manhattan"  "euclidean"   "canberra"       "bray" "kulczynski"    "jaccard"      "gower"   "altGower"   "morisita"       "horn"  "mountford" 
>    vegdist12    vegdist13    vegdist14    vegdist15   betadiver1   betadiver2   betadiver3   betadiver4   betadiver5   betadiver6   betadiver7   betadiver8   betadiver9  betadiver10 
>       "raup"   "binomial"       "chao"        "cao"          "w"         "-1"          "c"         "wb"          "r"          "I"          "e"          "t"         "me"          "j" 
>  betadiver11  betadiver12  betadiver13  betadiver14  betadiver15  betadiver16  betadiver17  betadiver18  betadiver19  betadiver20  betadiver21  betadiver22  betadiver23  betadiver24 
>        "sor"          "m"         "-2"         "co"         "cc"          "g"         "-3"          "l"         "19"         "hk"        "rlb"        "sim"         "gl"          "z" 
>        dist1        dist2        dist3   designdist 
>    "maximum"     "binary"  "minkowski"        "ANY" 
> library("DESeq2")
> unlist(distance("list"))
> Error in unlist(distance("list")) : 
>   error in evaluating the argument 'x' in selecting a method for function 'unlist': Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘distance’ for signature ‘"character", "missing"’

I am running the following versions:

> packageVersion("phyloseq")
> [1] ‘1.8.2’
> packageVersion("DESeq2")
> [1] ‘1.4.5’

Based on this I can perform the DESeq2 steps I would like to and then continue the distance analysis in a new session without DESeq2 loaded.  Is this a problem with my versions?

Thanks,
Chuck

**Comment by PrashINRA** [comment]
Hello Joey,

While using distance on Phyloseq object I am also facing an error:
 Error in (function (classes, fdef, mtable)  : 
 unable to find an inherited method for function ‘distance’ for signature ‘"phyloseq", "missing"’.
It worked before and gave a disance object with many empty rows  and later I could not plot the ordination as well.

**Comment by vries189** [comment]
Dear Joey,

I am also getting the exact same error as PrashINRA. Additionally, when I use your suggestion of Nov 30, 2014, I get the following:
> phyloseq::distance("list")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘distance’ for signature ‘"character", "missing"’

Kind regards,
Hugo

**Comment by jenlang** [comment]
Hi there, 
Same problem. I tried loading the phyloseq library last but that didn't work. Defining the package did. Below is what worked!

`unw_pcoa_dm <- phyloseq::distance(pso, "uunifrac")`

**Comment by PrashINRA** [comment]
1. Try to detach the the DESeq2 using this code: detach("package:DESeq2", unload=TRUE) or restart the R-session without attaching DeSEq2
2. object 'pso' not found- for this use the correct phyloseq data object.

**Comment by jeffreyblanchard** [comment]
Thanks for the quick comment. 
1.  I don't have the library DESeq2 loaded.  I restarted R and got
> detach("package:DESeq2", unload=TRUE)
Error in detach("package:DESeq2", unload = TRUE) : 
  invalid 'name' argument
2. Oh yeah. I would still like to have it work without this step.

**Comment by jeffreyblanchard** [comment]
PS. Thanks for making these great tutorials available!
