### ISSUE TITLE
Merge low abundance OTUs in a "Others" category

### ISSUE THREAD

**Issue by ericjcgalvez** [joey711/phyloseq#402]
Hello,
First thanks for this nice tool,
I wonder if there is a way to group all the low abundance OTUs in a "Others" category from a phyloseq object. I would like to make a bar_plot where I could have all the low abundance OTUs (less than 1% ) in a category call "Others" something like was shown in issue #291.

thanks,

**Comment by joey711** [comment]
I don't want to support this directly, as it is not a recommended way of transforming or storing data. However, the example you reference and others like, and the lower level tools like `merge_taxa`, make it straightforward to accomplish. 

I will close for now.
