### ISSUE TITLE
normalizing OTU table in phyloseq

### ISSUE THREAD

**Issue by camel315** [joey711/phyloseq#403]
Dear Paul,

In you latest release of package 'phyloseq', you proposed a new idea for subsampling which seems to be built in phyloseq_to_deseq2 according to your new alogrithem. It's very interesting. This idea was also proposed in your paper "Waste not, want not: why rarefying microbiome data is inadmissible" in PLoS Comput Biol.

However, I could not find the solution to get the normalized OTU table. Could you please give a example flow for getting subsampled OTU data?

By the way, what do you think the major disadvantages of subsampling and naive proportion, compared to your new method? Is the naive proportion is a bit better than subsampling? And why do you remove singletons in the function remove_singletons_empties at the link of http://joey711.github.io/waste-not-supplemental/simulation-cluster-accuracy/simulation-cluster-accuracy-server.html

Thank you in advance,

Sizhong

**Comment by CarlyRae** [comment]
Look at the package metagenomeseq to do the normalization. I would share my code with you on how to do this, but they have updated the package and my code no longer works with the newest package. Here is a post on github about it (https://github.com/nosson/metagenomeSeq/issues/16). 

You can load .biom files from QIIME, if that is what you were using to do initial data processing, with mybiom = load_biom("my_file.biom").

You basically load your biom file, calculate a normalization factor (it finds a 'core community' in your samples), applies the normalization factor to your dataset (each sample has it's own normalization number based on how much of the 'core' it shares with the overall average) and then you can write a file with the new normalized numbers. Or at least that is my take on it. Keep an eye on the post to see what the Metagenomeseq developer thinks about my conclusion.

If Phyloseq now has this ability it would be great to know how to do this in that package as well.

Cheers,

Carly

**Comment by joey711** [comment]
There are already two separate methods available for obtaining variance stabilized (what you are probably meaning by "normalized") values from a DESeq2 data object created from the `phyloseq_to_deseq2` function. Essentially these are accessor functions to "pull out" the matrix of transformed values from the original dataset, which in both phyloseq and DESeq2 contains much more information. 

The two methods are regularized-log and variance-stabilization. The short names in the package contain `vst` and `rlog`, but you will need to search for some already-documented examples, in the DESeq2 package or in my provided examples. 

I have an example in the Waste Not documentation for using Joseph's metagenomeSeq, as we compared its performance in the paper. I didn't know he changed the API as Carly has suggested, but I have pinged him here to see if he'd like to respond :-)

@nosson , what say you? 

@camel315 , I will close this issue for now as I think Carly and I have addressed your OP. Save for one point about "getting subsampled OTU data", which I don't recommend that you do. Ever.

Cheers and best,

joey

**Comment by nosson** [comment]
Thanks @joey711!

As Joey mentioned, most stats researchers in the field currently recommend a number of alternatives to subsampling and proportions in terms of clustering and testing. Joey provides convenient methods for regularized and variance stabilizing normalization methods and within metagenomeSeq I endorse a scaling factor methodology based on a dataset's sample count distribution.

Joey discusses the issues of subsampling in the plos comp bio paper and I discuss scaling factor methods in my nmeth paper along with a commentary discussion in response [http://www.nature.com/nmeth/journal/v10/n12/full/nmeth.2658.html], [http://www.nature.com/nmeth/journal/v11/n4/full/nmeth.2898.html].

Thanks a ton @CarlyRae for point out metagenomeSeq's normalization methodology to @camel315 and sample code! I tried to provide a solution for you in the issue [https://github.com/nosson/metagenomeSeq/issues/16], let me know if you have anymore questions.
