### ISSUE TITLE
Trouble Using Colors in Ordination Plot

### ISSUE THREAD

**Issue by ckcollings** [joey711/phyloseq#416]
I do not know how to get colors in my ordination plots.  I'm
not sure what is wrong.

*** Here is my distance matrix

unweighted_UniFrac_distance_matrix
ABiochar1 AControl2 ABiochar3 ABiochar2 AControl1
AControl2 0.6027745

ABiochar3 0.6078315 0.6177005

ABiochar2 0.6003199 0.5476134 0.6193400

AControl1 0.5856539 0.5679646 0.5851082 0.5661961

AControl3 0.6070889 0.5432251 0.6268210 0.5595632 0.5699145

*** Here is my attempt to plot

iMDS <- ordinate(data2, "MDS", distance = unweighted_UniFrac_distance_matrix)
plot_ordination(data2, iMDS, type = "samples", color = "Treatment")

*** Error
No available covariate data to map on the points for this plot type
Warning message:
In plot_ordination(data2, iMDS, type = "samples", color = "Treatment") :
Color variable was not found in the available data you provided.No color mapped.

*** Phyloseq Object
data2
phyloseq-class experiment-level object
otu_table() OTU Table: [ 57783 taxa and 6 samples ]
sample_data() Sample Data: [ 6 samples by 1 sample variables ]
tax_table() Taxonomy Table: [ 57783 taxa by 7 taxonomic ranks ]
phy_tree() Phylogenetic Tree: [ 57783 tips and 57781 internal nodes ]

*** "Treatment" is a group.
sample_data(data2)
Sample Data: [6 samples by 1 sample variables]:
                 Treatment
ABiochar1 Biochar
AControl2 Control
ABiochar3 Biochar
ABiochar2 Biochar
AControl1 Control
AControl3 Control

*** This is my OTU table.
head(otu_table(data2))
OTU Table: [6 taxa and 6 samples]
taxa are rows
ABiochar1 AControl2 ABiochar3 ABiochar2 AControl1 AControl3
New.ReferenceOTU99252 0 0 1 0 0 1
New.ReferenceOTU30910 1 0 5 0 4 0
New.ReferenceOTU55833 0 0 10 0 2 0
New.ReferenceOTU242194 0 0 2 0 1 0
New.ReferenceOTU384960 0 0 1 0 1 0
New.ReferenceOTU497495 0 0 1 0 0 1

**Comment by zalexa** [comment]
Hello,

I have the same problem. 
mydata:
> mydata
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 119 taxa and 127 samples ]
sample_data() Sample Data:       [ 127 samples by 1 sample variables ]
tax_table()   Taxonomy Table:    [ 119 taxa by 13 taxonomic ranks ]

> class(sample_data(mydata)$Treatment)
[1] "character"
> head(sample_data(mydata)$Treatment)
[1] "Con" "Con" "Con" "Con" "Con" "Con"

> p1 = plot_ordination(mydata, GP.ord, type = "samples", color = "Treatment", title = "samples")
No available covariate data to map on the points for this plot `type`
Warning message:
In plot_ordination(mydata, GP.ord, type = "samples", color = "Treatment",  :
  Color variable was not found in the available data you provided.No color mapped.

Is character the wrong class? I also tried factor but it didn't work either. Any suggestions what's wrong with my phyloseq object?

**Comment by joey711** [comment]
What version of phyloseq are you using? How did you come by this ordination object `GP.ord`? Can you include that code as well? In principle it could be one line preceding the `plot_ordination` call.

**Comment by zalexa** [comment]
I'm using version 1.10.0. The ordination call was:
>Gp.ord<-ordinate(mydata, "NMDS", "bray")
Anyway, I've solved the problem by adding the mapping file separately to the phyloseq object, instead of including the metadata information in the biom file. Nevertheless, it would be interesting, why it didn't work before.

**Comment by LaserKate** [comment]
Hi Joey,
I am also having the same problem with mapping colors or labels with ordination plots in Phyloseq. However, I have confirmed that the relevant data is available. Please see my example below:

    a<-otu_table(sedblastplus, taxa_are_rows=TRUE)
> a
OTU Table:          [128 taxa and 10 samples]
                     taxa are rows
                                                                                         sample1 sample2
OTU_1                                                                               0            0
OTU_2                                                                                0            0

    sedvar2<-sample_data(sedvar)

Sample Data:        [10 samples by 1 sample variables]:
                                  SampleType

    sed=merge_phyloseq(a, sedvar2)
class(sed)
[1] "phyloseq"
attr(,"package")
[1] "phyloseq"

    sample_data(sed)$SampleType
#correct output

    plot_ordination(sed, ordinate(sed, "MDS", "bray"), color=("SampleType")) + geom_point(size=5)
No available covariate data to map on the points for this plot `type`
Warning message:
In plot_ordination(sed, ordinate(sed, "MDS", "bray"), color = ("SampleType")) :
  Color variable was not found in the available data you provided.No color mapped.

Any hints on what might be going wrong? Any tips would be appreciated. It seems that SampleType can be found in the phyloseq object "sed."
Thanks!

**Comment by LaserKate** [comment]
edit: I have phyloseq package version 1.10.0

**Comment by aditisg** [comment]
Did anybody figure a way around this? I am getting similar warning message. I have the necessary variable in my sample_data table.

**Comment by aditisg** [comment]
Just an update: I had to restructure my sample_data table. The example files associated with the plot_ordination analyses will give an idea about structuring the data table. Pretty straightforward it is.

**Comment by Knarpie** [comment]
Same issue here. I changed the type variable and then it worked though

**Comment by sentausa** [comment]
I'm having the same issue here. Could aditisg and Knarpie please explain how exactly they restructure the sample_data table or change the type variable? I'd really appreciate that.

**Comment by joey711** [comment]
I will close for now. This is redundant with
https://github.com/joey711/phyloseq/issues/541
which does a better job describing the issue.

**Comment by abalter** [comment]
I'm having the same issue, but getting a slightly different error.

I know this isn't an MRE, but this is what I'm getting:

**CODE:**
```
temp_ps = f_and_b_ps
temp_metadata = temp_ps@sam_data
temp_metadata = temp_metadata[,c(
  'SampleID', 
  'SampleName', 
  'Age', 
  'Age_Group', 
  'CaseString'
  )]
temp_ps@sam_data = sample_data(temp_metadata)
temp_ps
ps_ord = ordinate(temp_ps, "PCoA", "bray")
plot_ordination(
  temp_ps, 
  ps_ord, 
  type="samples", 
  color="CaseString", 
  title="taxa"
  )
```

**OUTPUT**
```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 4074 taxa and 134 samples ]
sample_data() Sample Data:       [ 134 samples by 5 sample variables ]
tax_table()   Taxonomy Table:    [ 4074 taxa by 6 taxonomic ranks ]

Error: Must request at least one colour from a hue palette.
```

As with the OP, the following makes a lovely plot:

```
plot_ordination(
  temp_ps, 
  ps_ord, 
  type="taxa", 
  color="Phylum", 
  title="taxa"
  )
```

**Comment by markklick206** [comment]
Please see the edited code below. The main issue was with the ```sample_data table``` not actually having the ```sample_names``` as rows. See my fixes below indicated by #### MARKKLICK206 ####
```library(phyloseq)
library(ggplot2)
library(reshape2)
library(plyr)
library(dplyr)
library(stats)
library(tidyr)
library(tibble)
library(vegan)

N_ASVs = 12
N_samples = 7
N_variables = 2

sample_names = paste0("Sample", 1:N_samples)
sample_names

asv_table = matrix(sample(1:100, N_ASVs*N_samples, replace = TRUE), nrow = N_ASVs, ncol = N_samples)
rownames(asv_table) <- paste0("ASV", 1:nrow(asv_table))
colnames(asv_table) <- sample_names

taxonomy_table = matrix(sample(letters, N_ASVs*7, replace = TRUE), nrow = N_ASVs, ncol = 7)
rownames(taxonomy_table) <- rownames(asv_table)
colnames(taxonomy_table) <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")

study_metadata = data.frame(
  var1=sample(c('Y','N'), N_samples, replace = TRUE),
  var2=sample(1:100, N_samples, replace = TRUE)
  )
#### MARKKLICK #### -- this was the crucial error in constructing the sample_data table, i.e., the names of the rows need to equal the sample_names
rownames(study_metadata) <- sample_names

ps = phyloseq(
  otu_table(asv_table,taxa_are_rows=TRUE), #### MARKKLICK206 #### need taxa_are_rows=TRUE here to properly construct the phyloseq object
  sample_data(study_metadata),
  tax_table(taxonomy_table)
  )

ps_ord = ordinate(ps, method='MDS', distance='bray')
plot_ordination(ps, ps_ord, color='var1')```

![example](https://user-images.githubusercontent.com/10012736/48865635-05e30f00-ed85-11e8-8889-e86a5e8516dc.png)

**Comment by SungUk** [comment]
I might find the exact cause of the error.
I used only one sample data.
1 dimension.
Although I used coordinated data form taxa data to draw plots, the function may check the dimension of sample data for coloring.
I added a trash column to my sample data, and it worked.
