### ISSUE TITLE
export data used to plot graphs

### ISSUE THREAD

**Issue by spamjit** [joey711/phyloseq#423]
Hi,

Is there a way to export data into text file in csv or excel format ? I generated a bar chart with abundance in y axis and genus in x axis, now i want to export the data to excel file, but cant find a way to do it. 

thanks.

**Comment by joey711** [comment]
Try

```
write.table(as(otu_table(physeq1), "matrix"), ...)
```

Fill in your preferred parameters for `write.table` to replace `...` and note that `physeq1` is your phyloseq data object.

If you want to export other components you can replace `otu_table` with other accessors.

Will close for now. Thanks for using phyloseq!

joey
