### ISSUE TITLE
Arranging rows/columns in plot_heatmap

### ISSUE THREAD

**Issue by jport1** [joey711/phyloseq#425]
Hi Joey,

I have a question on the plot_heatmap function. I'd like to plot my otu_table in the exact orientation that the rows and columns appear in my table (i.e. without any ordination). When I plot without specifying any method or distance options the rows and columns are still re-arranged according to some orientation, and if I specify method=NULL the rows are ordered alphabetically and columns still arranged according to some metric.

Is there a way to plot the otu_table without any rearrangement?

Thanks much,
Jesse

**Comment by joey711** [comment]
Yep, this feature is already supported. Please see the `plot_heatmap` function documentation, either by `?plot_heatmap` after you've loaded phyloseq, or for instance, the [official phyloseq package manual](http://www.bioconductor.org/packages/release/bioc/manuals/phyloseq/man/phyloseq.pdf)

The relevant arguments to `plot_heatmap` are `sample.order` and `taxa.order`. The following is an untested draft of what you're asking.

```S
sampleOrder = unique(sample_names(physeq1))
taxaOrder = unique(taxa_names(physeq1))
plot_heatmap(physeq1, sample.order = sampleOrder, taxa.order = taxaOrder)
```

where `physeq1` is your phyloseq data object.

I will close for now, but feel free to comment back on the success or failure of this solution, and what worked for you.

Cheers

joey

**Comment by ometzit** [comment]
Sorry to open the thread again, but which object type is sample.order?
Is it a simple list separated by spaces, tabs or commas?
When I use these as a result of sampleName <-"My list" I get an error
Error in `[.data.frame`(as(sample_data(physeq), "data.frame"), , varName) : 
  undefined columns selected

And by using sample_names function I obtain a different order than the one I had on my mapping file. I know that this has to be with the ordering aspects of taxa and samples that makes a heatmap usable but for my purpose it would be handy to keep my samples in the same order as in the mapping file. Is this possible?

**Comment by joey711** [comment]
Hi @ometzit ,

Please RTFM. Typing `?plot_heatmap` in an R session with phyloseq package loaded, or even clicking the link to the official phyloseq PDF manual and searching for `plot_heatmap` give a detailed description of what `sample.order` can be. And I quote:

"`sample.order` (Optional). Default NULL. Either a single character string matching one of the
`sample_variables` in your data, or a character vector of `sample_names` in the
precise order that you want them displayed in the heatmap. This overrides any
ordination ordering that might be done with the method/distance arguments.
"

So it is not only possible, but explicitly supported that you can specify any permutation of the sample labels that you prefer.

Hope that helps

joey
