### ISSUE TITLE
Converting phyloseq data to text file

### ISSUE THREAD

**Issue by sjjose2** [joey711/phyloseq#426]
I do have a question on phyloseq. Is it possible to convert a phyloseq .Rdata for example HMPv35.Rdata into a text format file? I am basically trying to parse out identified bacterial at the genus level for each of the samples in the HMP project. Is it possible to do that? I tried merging the sample data with the OTU data but I am getting another phyloSeq object.

**Comment by audy** [comment]
It is not possible to convert the Rdata file into a text file but it is possible to export the OTU table to a text (csv) file:

(using GlobalPatterns data as an example)

```S
data(GlobalPatterns)
glom <- tax_glom(GlobalPatterns, taxrank='Genus')

otus <- otu_table(glom)

write.csv(otus, file='otus-genus.csv')
```
You can also export the genus-level data alongside the sample data using the `psmelt` function:

```S
dat <- psmelt(glom)
write.csv(dat, file='otus-genus-with-sample-data.csv')
```

I don't have the HMPv35 data handy but the process should be similar.

**Comment by joey711** [comment]
Seems like [biomformat](http://bioconductor.org/packages/release/bioc/html/biomformat.html) would be the way to go here...
