### ISSUE TITLE
information about importing data from QIIME

### ISSUE THREAD

**Issue by shashankx** [joey711/phyloseq#428]
Hi,
I am new to R and phyloseq packages. Till now i have used QIIME for metagenome analysis and statistical analysis.

I have installed R (x64) (new version) and installed packages using:

source("http://bioconductor.org/biocLite.R")
biocLite("phyloseq")

Now i have OTU.biom, otu_biom.txt, rep_set.tre, map.txt files from QIIME.

first question is how can i import these files in R ?
Second is how can i do alpha diversity and other analysis (which can be done) using R ?

If possible please tell me step by step for doing these analysis.

Best !
Shashank

**Comment by joey711** [comment]
This is heavily documented
