### ISSUE TITLE
rank_names; output is not Kingdom,phylum...

### ISSUE THREAD

**Issue by nidhi13** [joey711/phyloseq#436]
biomdata=import_biom(treefilename="C:\\Users\\Owner\\Desktop\\biostat\\qiime thesis\\fasttree_uclust.tre","C:\\Users\\Owner\\Desktop\\biostat\\qiime thesis\\trial_otu_table.biom",parseFunction=parse_taxonomy_default,parallel=FALSE)
> print(biomdata)
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 105 taxa and 21 samples ]
tax_table()   Taxonomy Table:    [ 105 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 105 tips and 103 internal nodes ]
> rank_names(biomdata)
[1] "Rank1" "Rank2" "Rank3" "Rank4" "Rank5" "Rank6" "Rank7"

How do I get Kingdom, Phylum, class, order, genus, species? could something be wrong with my qiime files?

**Comment by audy** [comment]
This probably has something to do with your input data but I have no way to tell.

You can manually re-assign rank names.

For example,

```S
data(GlobalPatterns)
rank_names(GlobalPatterns)
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"
t <- data.frame(tax_table(GlobalPatterns))
colnames(t) <- c('A', 'B', 'C', 'D', 'E', 'F', 'G')
tax_table(GlobalPatterns) <- tax_table(as.matrix(t))
rank_names(GlobalPatterns)
[1] "A" "B" "C" "D" "E" "F" "G"
```

**Comment by nidhi13** [comment]
got it! thanks!
