### ISSUE TITLE
plot_bar() - consistent ordered bars between samples

### ISSUE THREAD

**Issue by pljames** [joey711/phyloseq#442]
I have been asked on a few occasions if there was an easy way to order the stacked
bars in plot bars(physeq, ...) so that they are in the same order across bars for
comparisons. Often this is not the correct thing to do, however in some cases
e.g. comparing the same sample on multiple runs or examining "stability" in
patients it may be of use.... or it might not. Here is an example of how to implement this with a
slight modication of plot bar provided as part of the Phyloseq package. 

First here is some example data taken from [here](http://joey711.github.io/phyloseq/import-data)
```
#Set seed
set.seed(22886)
# load phyloseq module
library(phyloseq)
# load ggplot2
library(ggplot2)
# Make some data
otumat = matrix(sample(1:100, 100, replace = TRUE)
, nrow = 10, ncol = 10)
rownames(otumat) <- paste0("OTU", 1:nrow(otumat))
colnames(otumat) <- paste0("Sample", 1:ncol(otumat))
taxmat = matrix(sample(letters, 70, replace = TRUE),
nrow = nrow(otumat),
ncol = 7)
rownames(taxmat) <- rownames(otumat)
colnames(taxmat) <- c("Domain",
"Phylum",
"Class",
"Order",
"Family",
"Genus",
"Species")
OTU = otu_table(otumat, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)
physeq = phyloseq(OTU, TAX)
```

Now we can use the default plot_bar() to see what it produces

```
p0 <- plot_bar(physeq, fill = "Family")
p0 + ggtitle("plot_bar() Example")
```

![image](https://cloud.githubusercontent.com/assets/11415582/6587509/f380bf10-c77c-11e4-901a-fd52eba747f5.png)

I have modified the plot_bar function a bit (and hopefully not incorrectly) to produce an ordered plot. Here is the function i have rather un originally called plot_ordered_bar(). 

```
plot_ordered_bar<-function (physeq, x = "Sample", 
                            y = "Abundance", 
                            fill = NULL, 
                            leg_size = 0.5,
                            title = NULL, facet_grid = NULL) 
{
  require(ggplot2)
  require(phyloseq)
  require(plyr)
  require(grid)
  bb <- psmelt(physeq)
  .e <- environment()
  p = ggplot(bb, aes_string(x = x, y = y, 
                            fill = fill), environment = .e)
 
  
  p = p + geom_bar(aes(order=desc(bb[,fill])),
                  stat = "identity", 
                  position = "stack", 
                  color = "black") 
  
  p = p + theme(axis.text.x = element_text(angle = -90, hjust = 0))
  
  p = p + guides(fill = guide_legend(override.aes = list(colour = NULL))) 
  p = p + theme(legend.key = element_rect(colour = "black")) 
  
  p = p + theme(legend.key.size = unit(leg_size, "cm"))
  
  if (!is.null(facet_grid)) {
    
    p <- p + facet_grid(facet_grid)
  }
  
  if (!is.null(title)) {
    p <- p + ggtitle(title)
  }
  return(p)
}
```
This should be back compatible with plot_bar() but I have added a "leg_size" switch to alter the legend size easily (if you have loads of taxa names). It keeps the order of the bars in the plot consistent between samples and also in the same order as the legend (alphabetical top-bottom) which should make working out which bar relates to which taxa easy. Also it removes the slashes on the legend but maintains the outer box and separators. Sorry if this is an issue, but I needed it for my own code.

Here is the same plot but using the above function

```
p1 <- plot_ordered_bar(physeq, fill="Family", leg_size = 0.6) 
p1 + ggtitle("plot_ordered_bar() Example")
``` 
![image](https://cloud.githubusercontent.com/assets/11415582/6587598/37033a50-c77e-11e4-870f-a903798e5f8f.png)

I'm quite new to using ggplot2 so if i have made a mistake in implementing this please feel free to chip in!

All the best,

Phill

p.s. the quality and size difference between the two plots just comes from my inexperience with git hub, they were screen shots pasted in here. There should be no difference in quality if run in r directly.

**Comment by joey711** [comment]
@pljames Thanks for the post. This is a very nice example using `psmelt` to mod a version of one of the phyloseq figures for your custom specs. I like it. 

I would not want to make a separate `plot_` function in phyloseq for it, but rather add a `constantOrder` argument that is `FALSE` by default, and can be set to `TRUE` to achieve your version.

Zooming out, I think faceting is a much, much better way to do this graphic. Some of the patterns for the internal bar sections are completely lost because their origin is moving around. Dodging is one solution that is better when there are only a 4 or fewer components (rough rule of thumb), but faceting is the cleanest and surest way.

My two cents. Since `plot_bar` is already in there, I'd entertain a pull request with this as a new option in `plot_bar` with a new parameter included. I'll try to merge it into the next release of phyloseq. I'll close this issue for now, but reference it if you send the pull request.

Cheers and thanks again

joey

**Comment by dylandahan** [comment]
Hi Joey,
Did you have a chance to add the constantOrder argument? I was using this plot_ordered_bar function for some time but it seems to have stopped working with my version (v1.14.0)

Cheers
Dylan

**Comment by pjames1** [comment]
Hello Dylan,

Got a notification through so thought I'd try to help. 

Yes one of the changes in  the updated ggplot removes the "...aes(order=..." from geom_bar and unfortunatly it broke my function. I've modified it for you a bit so hopefully it should work as before but I haven't really tested it all that much. I would point out again Joeys advice on data presentation through faceting etc (see his post above) but as I started this thread I feel somewhat responsible for it and don't want to take up others time fixing my random dodgie bits of code! :)  Anyway, using the example above: 

```{r, warning=FALSE, message=FALSE}
# Make some example data
#Set seed
set.seed(22886)
# load phyloseq module
library(phyloseq)
# load ggplot2
library(ggplot2)
# Make some data
otumat = matrix(sample(1:100, 100, replace = TRUE)
, nrow = 10, ncol = 10)
rownames(otumat) <- paste0("OTU", 1:nrow(otumat))
colnames(otumat) <- paste0("Sample", 1:ncol(otumat))
taxmat = matrix(sample(letters, 70, replace = TRUE),
nrow = nrow(otumat),
ncol = 7)
rownames(taxmat) <- rownames(otumat)
colnames(taxmat) <- c("Domain",
"Phylum",
"Class",
"Order",
"Family",
"Genus",
"Species")
OTU = otu_table(otumat, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)
physeq = phyloseq(OTU, TAX)

########
# Plot_ordered_bar function 
# (name kept the same for back compatibility
# may want to change to avoid confusion!)
#Note: There may be some hangovers 
# from another script I was writing 
# that I pillaged for this one

###### Start of Function Here ######

plot_ordered_bar<-function (physeq, x = "Sample", 
                                    y = "Abundance", 
                                    fill = NULL, 
                                    leg_size = 0.5,
                                    title = NULL) {
  require(ggplot2)
  require(phyloseq)
  require(plyr)
  require(grid)
  bb <- psmelt(physeq)
  
  samp_names <- aggregate(bb$Abundance, by=list(bb$Sample), FUN=sum)[,1]
  .e <- environment()
  bb[,fill]<- factor(bb[,fill], rev(sort(unique(bb[,fill])))) #fill to genus
  
  
  bb<- bb[order(bb[,fill]),] # genus to fill
  p = ggplot(bb, aes_string(x = x, y = y, 
                            fill = fill), 
             environment = .e, ordered = FALSE)
  
  
  p = p +geom_bar(stat = "identity", 
                  position = "stack", 
                  color = "black") 
  
  p = p + theme(axis.text.x = element_text(angle = -90, hjust = 0))
  
  p = p + guides(fill = guide_legend(override.aes = list(colour = NULL), reverse=TRUE)) + 
    theme(legend.key = element_rect(colour = "black")) 
  
  p = p + theme(legend.key.size = unit(leg_size, "cm"))
  
  
  if (!is.null(title)) {
    p <- p + ggtitle(title)
  }
  return(p)
}

# END #
```

Test

```{r}
plot_ordered_bar(physeq, fill = "Genus", title = "New Plot Ordered Bar Example For Dylan")
```
![image](https://cloud.githubusercontent.com/assets/8667864/14535916/ffc46f2a-0267-11e6-9abf-84fbf4033452.png)

Hope this helps a bit, sorry if there are bugs in it and that it's not very neat.

All the best,

Phill

**Comment by pjames1** [comment]
Ohl, thats annoying, its cut the title off the graph.... Weird, didn't do that in the pdf markdown thingy I tested it in.... oh well, you get the idea anyway.

**Comment by joey711** [comment]
## Faceting beats stacking pretty much all the time

Here's an illustrative example of my point about faceting versus stacking...

```S
# Test
theme_set(theme_bw())
p = plot_ordered_bar(physeq, fill = "Genus", title = "New Plot Ordered Bar Example For Dylan")
```

### Function output (without faceting)

```S
p
```

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/841437/14536633/4c39bd3c-0228-11e6-8584-764b4cf48f05.png)


### Same plot, with faceting

```S
p + facet_wrap(~Genus) + ggtitle("Faceting is better than stacking...")
```

![unnamed-chunk-1-2](https://cloud.githubusercontent.com/assets/841437/14536681/73b464e8-0228-11e6-8ff2-44ce43bf40b8.png)


The plot clearly communicates that faceting is better than stacking ;-)

**Comment by dylandahan** [comment]
Phill, thanks for the update! "...aes(order=... " was giving me some trouble right after the release and I should've realized this was the source of error.  

Joey, in this example the faceting looks great. And, I agree that when looking at a handful of genera it makes more sense than stacking. However, what do you think about faceting when you are just visualizing few phyla? It seems like a bit of overkill to me. 

Anyway, I've attached some of my data at the Phylum and Family levels and would interested to know what you think. The fact that I'm plotting relative abundance might be a whole different problem..

Cheers,
D

### Plot ordered bar with Phylum, only retaining seqs > 0.01%
```{r}
```{r Plot phylum}
psFRphy = filter_taxa(psFR, function(x) mean(x) > 0.001, TRUE)

phyplot = plot_ordered_bar(psFRphy, fill = "Phylum") +
  scale_x_discrete(limits=increaseAs)  + geom_bar(aes(order = desc(bb[,fill])), stat = "identity", position = "stack") +
    scale_fill_manual(values=cbPalette) 

phyplot
```
![image](https://cloud.githubusercontent.com/assets/13370432/14543654/2569e23a-028d-11e6-90ed-afc3a6b2ab91.png)

### Phylum facet
```{r}
phyplot + facet_wrap(~Phylum) + ggtitle("Faceting is better than stacking...")
```
![image](https://cloud.githubusercontent.com/assets/13370432/14543677/3ed61b12-028d-11e6-9a76-c2bd534ddd3d.png)

### Plot ordered bar with Family, only retaining sequences  > 0.3%
```{r}
psFRFam = filter_taxa(psFR, function(x) mean(x) > 0.003, TRUE)

famplot <- plot_ordered_bar(psFRFam, fill = "Family") +
  scale_x_discrete(limits=increaseAs) 

famplot
```
![image](https://cloud.githubusercontent.com/assets/13370432/14544083/411ccde2-028f-11e6-9a82-1f22bd777ba1.png)

### Family facet
I think faceting makes good sense here..
```{r}
famplot + facet_wrap(~Family) + ggtitle("Faceting is better than stacking...")
```
![image](https://cloud.githubusercontent.com/assets/13370432/14544125/7c92511c-028f-11e6-9a8b-1c2f9e3e3c42.png)

**Comment by kelvinfrog** [comment]
A simple question. What code do you add at the end to eliminate the stack line in the bar graph?

**Comment by gabuali** [comment]
Just got an email on this and wanted to see what all the activity is about.  
@joey711 - Definitely agree that 'faceting is better than stacking...' and allows more detailed exploration and communication of data.  I also think that stacking has a purpose when trying to explore overall trends in abundance variation.  And this is one common way of summarizing such variation and the literature is chock-full of such examples.  I'm attaching one of my own to show what I mean.  Here I facet samples (from same individuals were applicable) by collection timepoint and want to eyeball if there are apparent differences in phylum fluctuation over timepoints.
[phyla.pdf](https://github.com/joey711/phyloseq/files/263773/phyla.pdf)

**Comment by joey711** [comment]
@gabuali  - thanks and glad you agree. My point is that because we have modern graphics systems like ggplot2, there's no need to make the stacked bar plot as a "quick look" option -- it is just as fast and easy to make the faceted version where you can actually visualize the data in a quantitative way.

The fact that microbiome literature is chock full of stacked bars is not a justification for using them. It speaks more to what popular pipelines provide than what is actually good data-viz practice.

**Comment by slvrshot** [comment]
How would you add a black line around the actual bars so there is a bit more contrast @joey711?

Like what would the code look like in your faceting example?

**Comment by Gian77** [comment]
Hello Everybody,
sorry for pushing on this, but it is very difficult to produce "good looking" bar plots. I was wondering, is there a way to make the genera plotted in a certain custom order (e.g. similar guild) instead of alphabetical?
Thank you,
G.
