### ISSUE TITLE
prune_taxa with log2 normalized values

### ISSUE THREAD

**Issue by davidmartinad200** [joey711/phyloseq#446]
Hi,
I´m trying to prune_taxa to different rank_names. From the documentation it seems that for each rank (e.g Genus) phyloseq does sum counts for each same Genus Otu. 

In my case , and please correct me if i´m wrong I have first normalized my data using Deseq2 
normdata <- counts(cds, normalized=T)
Then importing back the normdata into a otu_table and bulding a phyloseq object.

Can prune_taxa deal with normalized data. Deseq2 will return log2 normalized reads ???  How can i handle this situation , specially if i want to compare rank_names ?? The prune_taxa will do the sum of logs which should not be appropriate if you have normalized data.

thanks for your help,
david

**Comment by spholmes** [comment]
Hi there David
Really you need an inverse transform back to simili counts and then do the
pruning,
it would be worth comparing what this does versus pruning first, then
normalizing.
I can't remember what I did for the inverse of the rlog, let me revisit...
Thanks for the question, making us think through every different step order
in the workflow
Susan

On Tue, Mar 17, 2015 at 7:26 AM, davidmartinad200 <notifications@github.com>
wrote:

> Hi,
> I´m trying to prune_taxa to different rank_names. From the documentation
> it seems that for each rank (e.g Genus) phyloseq does sum counts for each
> same Genus Otu.
>
> In my case , and please correct me if i´m wrong I have first normalized my
> data using Deseq2
> normdata <- counts(cds, normalized=T)
> Then importing back the normdata into a otu_table and bulding a phyloseq
> object.
>
> Can prune_taxa deal with normalized data. Deseq2 will return log2
> normalized reads ??? How can i handle this situation , specially if i want
> to compare rank_names ?? The prune_taxa will do the sum of logs which
> should not be appropriate if you have normalized data.
>
> thanks for your help,
> david
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/446>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by davidmartinad200** [comment]
Thanks Susan,
Would that be statistically relevant to prune samples before normalizing the data if you directly work with raw counts ? Specially if you want to compare samples at the rank level. My thoughts are that you need to normalize the data prior to any differential expression analysis and suming raw counts does sound very good ?? Maybe i´m wrong since i´m not statistician myself.
Reversing back data from Deseq would be a mess. 
thanks

**Comment by davidmartinad200** [comment]
I have checked in the pyloseq code. I think the prune_taxa uses the taxa_sums function in the otuTable-class.R
One suggestion to handle this could be to create a new taxa_sums_normalized function

#Log2 normalized table as input otu
taxa_sums_normalized <- function(x){
	x <- otu_table(x)
	if( taxa_are_rows(x) ){
		#rowSums(x)
                log2(apply(x, 1, prod)) # If i´m not wrong , log2(a)+log2(b) = log2(a*b)
	} else {
              #colSums(x)
		log2(apply(x, 2, prod)) # 
	}
I guess that should do the trick ?

**Comment by joey711** [comment]
Nope, `prune_taxa` is a low-level filtering wrapper only. You provide it with either (1) a logical vector of the same length as the number of taxa in your object, or (2) a character vector of the `taxa_names` that you want to keep. As far as this function is concerned, the rest is up to you. You have to decide how this vector is defined and then provide it to the function. `taxa_sums` is not called and is not needed by `prune_taxa`.

That said, this means that `prune_taxa` does not care if your data is normalized, raw, binary, the beginning or end of a workflow, it will all work fine... procedurally. The larger question of *how* to do the filtering and for what purpose is up to you.

David, I'm going to close this issue for now. Please read the documentation more carefully and also have a look at the `filter_taxa` function, as well as the `tax_glom` function. There are hints in your post that one of these two functions, especially `tax_glom`, might already do what you are trying to do, or at least be an important step in the workflow that you want.
