### ISSUE TITLE
How is the library size information incorporated into the estimate_richness function?

### ISSUE THREAD

**Issue by sfujio** [joey711/phyloseq#447]
Hi Joey,
I have a follow up question from the closed Issue#287 How does estimate_richness deal with uneven sequencing depth? 

I have used plot_richness and estimate_richness with boxplot function to generate plots, and they have very large variance. I have seen that in many tutorials and in the #287 Issue, it is said not to trim or standardize the library size but also have come across with papers such as DOI: 10.1111/j.1462-2920.2011.02550.x and DOI: 10.1002/ece3.508 were it´s discussed that different library size would affect to the estimation of richness and diversity and that the sample´s library size should be standardize. Could you specify how is the library size information incorporated into the estimation? so I can justify why I used the raw data when I present my results.

Thank you

PS: I have seen the word normalize used, after using the DESeq transformation of the data, but strictly speaking it should be standardize, because normalizing is transforming the data so it has a normal distribution, which I would think is not what happens when that command is used.. or is that what happens?

**Comment by joey711** [comment]
As a reviewer once asked me to emphasize in [our recent article in PLoS Comp Biol](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531)
a library-size dependence in richness estimates is a symptom of
a failure to adequately de-noise and model species distribution,
it is **not** evidence of a true dependency of richness.
How could it be? The true richness of a microbial community does not care how many times you sampled from it and change its true value accordingly. 
The larger we make our libraries, the more accurate our estimates should be,
but only if we're adequately de-noising sequencing errors and 
adequately modeling (or non-parametrically estimating) richness.
An important fact there is that larger sequencing libraries also have numerically larger populations of sequences with errors in them, and therefor a badly denoised collection of libraries
is expected to have its richness estimates exhibit a strong dependence on library size.
This would be the case even if your libraries were derived from a single species!
Most off-the-shelf denoising methods (like defaults in QIIME) 
fail to remove this dependency,
resulting in a lot of subsequent misinterpretation of alpha-diversity
and its wrongly-perceived "dependence" on library size.

The methods supported in phyloseq's `estimate_richness` and `plot_richness`
do not necessarily account for your particular species distribution,
but each method's original author has described
what kind of assumptions and expectations they have for data in their richness estimation.
I recommend evaluating those assumptions, choosing accordingly,
and bearing those in mind in your subsequent interpretation.
More importantly, these methods definitely do not perform any sequence denoising for you.
The expectation in these methods is that you have "real" observations of OTUs/species/genotypes
as input, not noise. 
Garbage in, garbage out. 

You are right that "normalize" would not be the appropriate precise term here.

Just to re-link to the tutorials for other users seeing this page...

http://joey711.github.io/phyloseq/plot_richness-examples.html

Again, in summary, you do not want to transform or filter your data before estimating richness,
other than necessary sequence denoising.
**[Rarefying is not a appropriate for this purpose. Nor ever.](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531).**

I will close for now. Thanks for the clarification, and your interest in phyloseq!

joey
