### ISSUE TITLE
Difference in PCoA plots

### ISSUE THREAD

**Issue by anusurendra** [joey711/phyloseq#448]
Hi,
I have posted this question on the Qiime google groups (https://groups.google.com/forum/#!topic/qiime-forum/e_YjXihLSxI) but felt it might be more relevant here. I have used Qiime 16s pipeline to generate an OTU-table and the beta diversity distance matrix. I am using the phyloseq and APE packages in R to generate the pcoa values and plot. I am also doing the same with Qiime principal_coordinates.py and make_2d_plots.py. However, I am finding that there are orientation differences between the two plots. The plot generated by R have the signs flipped but with the same value for the value. I am using the same distance matrix as the input in both cases. The 2 plots are attached.

Here are the commands I used:
my.ord <- ordinate(my.physeq,method="PCoA", distance=as.dist(beta.m.distance))
p1 <- plot_ordination(my.physeq, my.ord, "samples", axes=c(1,3),color=sample_variables(map)[[4]])

Thanks in advance for your help

![pc1vspc2plot_qiime](https://cloud.githubusercontent.com/assets/5685804/6716186/ff9a83a0-cd79-11e4-83f5-d01f1e0ea3ca.png)

![pc1vspc2plot_r](https://cloud.githubusercontent.com/assets/5685804/6716193/05a8844a-cd7a-11e4-9822-14dd52965e03.png)

**Comment by joey711** [comment]
In a PCoA/MDS, you are allowed to invert the sign of an axis when comparing two different but comparable results... which is to say that the two plots being mirror images of each other doesn't matter whatsoever, and indeed your biological interpretation of those two plots would be exactly the same.

Thanks for including the code that produced your plot. Unfortunately I only see the QIIME result.

I will close for now, but please feel free to post back here if there is an additional related problem (or just to upload the phyloseq plot that you are comparing).

Thanks for your feedback and interest in phyloseq!

joey

**Comment by anusurendra** [comment]
Thanks for your quick reply. I am attaching the 2 plots here.


Anu

On Wed, Mar 18, 2015 at 3:26 PM, Paul J. McMurdie <notifications@github.com>
wrote:

> In a PCoA/MDS, you are allowed to invert the sign of an axis when
> comparing two different but comparable results... which is to say that the
> two plots being mirror images of each other doesn't matter whatsoever, and
> indeed your biological interpretation of those two plots would be exactly
> the same.
>
> Thanks for including the code that produced your plot. Unfortunately I
> only see the QIIME result.
>
> I will close for now, but please feel free to post back here if there is
> an additional related problem (or just to upload the phyloseq plot that you
> are comparing).
>
> Thanks for your feedback and interest in phyloseq!
>
> joey
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/448#issuecomment-83129719>.
>



-- 
Anu Surendra
Bioinformatician
Guttman Laboratory
Department of Cell & Systems Biology
University of Toronto
labs.csb.utoronto.ca/guttman

416-946-7121

Centre for the Analysis of Genome Evolution & Function
University of Toronto
www.cagef.utoronto.ca

416-946-0043

25 Willcocks St.
Toronto, ON  M5S 3B2
Canada

**Comment by anusurendra** [comment]
Thanks for your quick reply. I am attaching the 2 plots here. 

Qiime:
![pc1_vs_pc2_plot_qiime](https://cloud.githubusercontent.com/assets/5685804/6717957/7aae20c2-cd86-11e4-956c-961620bce40a.png)

Phyloseq:
![pc1vspc2plot_r](https://cloud.githubusercontent.com/assets/5685804/6717963/8c7595c4-cd86-11e4-8395-f5f4231668a5.png)

**Comment by joey711** [comment]
Again, it doesn't matter, by definition. Your colors and shapes are different, but these two plots look like each mirror images on each axis with exactly the same scale and fraction of variance. You can reverse the sign for each axis and they would be identical within some negligible numerical error.

**Comment by anusurendra** [comment]
Thanks again. I have one quick question:
In the pcoa class, is the Relative_eig, found in the values slot, the variation explained?
