### ISSUE TITLE
Problem in importing mothur list file

### ISSUE THREAD

**Issue by microbiologist** [joey711/phyloseq#451]
Can anyone help me fix the problem in my mothur list file so I can import it to phyloseq?

> library("phyloseq")
> mothlist = system.file("extdata", "SCA.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.an.unique_list.list", package = "phyloseq")
> mothgroup = system.file("extdata", "SCA.contigs.good.groups", package = "phyloseq")
> mothtree = system.file("extdata", "SCA.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.phylip.tre", package = "phyloseq")
> show_mothur_cutoffs(mothlist)
[1] "label"  "unique" "0.01"   "0.02"   "0.03"   "0.04"   "0.05"   "0.06"  
> cutoff = "0.03"
> x = import_mothur(mothlist, mothgroup, mothtree, cutoff)
Error in 3:as.integer(rawlines[2]) : NA/NaN argument
In addition: Warning message:
In import_mothur_otulist(mothur_list_file, cutoff) :
  NAs introduced by coercion

**Comment by joey711** [comment]
It might be a faster solution to your problem to have mothur output into an exchange format, like csv or BIOM, and import it that way.

I will close for now. 

Note that you are more likely to receive help/solutions when posting a minimal reproducible example. This one is hard to diagnose without having the code + data to reproduce it.
