### ISSUE TITLE
problem in richness boxplot by phyloseq

### ISSUE THREAD

**Issue by Githubjglee** [joey711/phyloseq#452]
Hi, I am doing richness boxplot by phyloseq using the following commands:
library(phyloseq)
library(ggplot2)
library(plyr)
library(scales)
library(reshape)
library(RColorBrewer)
setwd("~/Documents/phyloseq/Data")
biomfile = "otu_table_wTax_filt_bfly.biom"
trefile = "rep_set_phylo.tre"
mapfile = "fruit_mapping.txt"
biomot = import_biom(biomfile, parseFunction = parse_taxonomy_greengenes) bmsd = import_qiime_sample_data(mapfile) 
class(bmsd)
dim(bmsd)
biomot
Bushman = merge_phyloseq(biomot, bmsd)
Bushman
plot_richness(Bushman, x = "SEX", color = "SOLUBLE_DIETARY_FIBER_G_AVE") + geom_boxplot()

After the last command line (plot_richness(Bushman, x = "SEX", color = "SOLUBLE_DIETARY_FIBER_G_AVE") + geom_boxplot() ) , I got the following error: Error in `[<-.data.frame`(`*tmp*`, i, "se", value = NULL) :   replacement has length zero. 
The version of my phyloseq is 2.1.3, so it should not due to the older version. Could you please let me know the reason for the error and how to fix it? Thanks a lot

**Comment by joey711** [comment]
That's not a real phyloseq version. We haven't gotten up to that value yet.

What version of R, Bioconductor, and phyloseq are you using?

Try 

```S
sessionInfo()
```

It's not clear to me what the error is. I will close this for now. Please feel free to post back some more details, including a reproducible example of the problem and your session info.
