### ISSUE TITLE
Comparing abundance between groups at different taxonomical level

### ISSUE THREAD

**Issue by sfujio** [joey711/phyloseq#453]
Hi all,
I have a statistical question regarding the test I can do to see differences between treatment groups considering the nature of the sequencing data.Sorry for my ignorance, I don´t have much statistical/mathematical knowledge. 

I understand since this are count data, for searching for differential abundance the most correct way to go with the available methods is using the GLM fitting to a negative binomial distribution, as done with DESeq2. In this way I get a set of parameters for each OTU per variable considered  in the design formula that I can compare and retrieve OTUs that are differentially abundant doing the contrast. 

 I have seen in papers such as David 2014 doi:10.1038/ismej.2013.155 (fig1), or Evans 2014 doi:10.1371/journal.pone.0092193 (fig 4) they have  graphs were they compare the relative abundance for a given taxonomical level and they do statistical test, such as Mann Withney, nos paired t-test or 2 way anova, and see there is a significant difference between groups of interest. 
I wish to do a similar comparison for different taxonomic level, but considering that the information used still comes from count data I get the feeling that is not a proper way to compare. I am right? would it be an ok comparison if I transforme the data with rlog?

What I though I could do is to use the  Phyloseq comand tax_glom with different taxonomical level and then do the analysis with that object with DESeq2. Is this correct?

Also if I were to plot as the papers I mentioned, for example, a bar plot to visualize the abundance of a certain taxonomical level from my different groups, what data should I use?  I rather not use proportion considering how highly abundant OTUs can distort the ratio of the remaining OTUs sequences regarding the total. 
I tried to used the data normalized by DESesq2 but many values are negative and the plot turns out to be upside down...

I am ok with that analysis of DESeq2 done with all the data at OTU level,  but I also want to do more traditional comparison such as the ones done from qPCR data for example. Since I am not strong in statistics,  I don´t to know if it´s possible or correct to compare the count data in that way.

Thank you very much,

Cheers.

**Comment by spholmes** [comment]
Hi

If you want to test at several taxonomic levels
(using the transformed data of course), you might look
into account the multiple testing but using the phylogeny as done in
Sankaran and Holmes, 2014:
http://www.jstatsoft.org/v59/i13/paper.

The simplest possible method is just to test using a hypergeometric as
suggested
here:
http://psb.stanford.edu/psb-online/proceedings/psb11/holmes.pdf
similar to what people do using the Gene Ontology.

Hope this helps
Susan

On Sat, Mar 21, 2015 at 2:39 PM, sfujio <notifications@github.com> wrote:

> Hi all,
> I have a statistical question regarding the test I can do to see
> differences between treatment groups considering the nature of the
> sequencing data.Sorry for my ignorance, I don´t have much
> statistical/mathematical knowledge.
>
> I understand since this are count data, for searching for differential
> abundance the most correct way to go with the available methods is using
> the GLM fitting to a negative binomial distribution, as done with DESeq2.
> In this way I get a set of parameters for each OTU per variable considered
> in the design formula that I can compare and retrieve OTUs that are
> differentially abundant doing the contrast.
>
> I have seen in papers such as David 2014 doi:10.1038/ismej.2013.155
> (fig1), or Evans 2014 doi:10.1371/journal.pone.0092193 (fig 4) they have
> graphs were they compare the relative abundance for a given taxonomical
> level and they do statistical test, such as Mann Withney, nos paired t-test
> or 2 way anova, and see there is a significant difference between groups of
> interest.
> I wish to do a similar comparison for different taxonomic level, but
> considering that the information used still comes from count data I get the
> feeling that is not a proper way to compare. I am right? would it be an ok
> comparison if I transforme the data with rlog?
>
> What I though I could do is to use the Phyloseq comand tax_glom with
> different taxonomical level and then do the analysis with that object with
> DESeq2. Is this correct?
>
> Also if I were to plot as the papers I mentioned, for example, a bar plot
> to visualize the abundance of a certain taxonomical level from my different
> groups, what data should I use? I rather not use proportion considering how
> highly abundant OTUs can distort the ratio of the remaining OTUs sequences
> regarding the total.
> I tried to used the data normalized by DESesq2 but many values are
> negative and the plot turns out to be upside down...
>
> I am ok with that analysis of DESeq2 done with all the data at OTU level,
> but my tutors want to see more traditional comparison such as the ones done
> from qPCR data for example. Since I am not strong in statistics, I don´t
> know if it´s possible or correct to compare the count data in that way (
> and need know so I can convince them! to do the most correct analysis
> possible).
>
> Thank you very much,
>
> Cheers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/453>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by sfujio** [comment]
Thank you Susan I will look into it. 
If I may ask, if one uses non parametric statistic no assumption regarding the distribution of the data is being made, so If I use it to compare proportion data such as the relative abundance of OTUs it would be statistically correct. However is advice not to do so because when I transform the count data to proportion and then test for significance, I am not taking into account the effect of the different library size per sample that gives a different uncertainty to the abundance estimate, which could turn into a increase in type 1 error.
Is this correct?

Thank you again,

Cheers

**Comment by spholmes** [comment]
@sfujio:

Comparing any measurements is always done better when we know the
variability,
so using relative abundances losing that is always inferior to a method
that uses that
information.

Noparametric methods are safer and more robust because they don't make
distributional assumptions,
hope that helps,
Susan

On Sat, Mar 21, 2015 at 8:53 PM, sfujio <notifications@github.com> wrote:

> Thank you Susan I will look into it.
> If I may ask, if one uses non parametric statistic no assumption regarding
> the distribution of the data is being made, so If I use it to compare
> proportion data such as the relative abundance of OTUs it would be
> statistically correct. However is advice not to do so because when I
> transform the count data to proportion and then test for significance, I am
> not taking into account the effect of the different library size per sample
> that gives a different uncertainty to the abundance estimate, which could
> turn into a increase in type 1 error.
> Is this correct?
>
> Thank you again,
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/453#issuecomment-84513067>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
@sfujio In most cases you are probably going to increase Type-II error (loss of power) when using a non-parametric test **relative to a suitable parametric test**. If your experiment/data is not modeled appropriately by the available parametric tests, then this point is moot, and even a weak/modest test is better than an inappropriate/invalid test.

By definition, proportions do take into account library size, and a non-parametric test on proportions is valid, just not necessarily the most sensitive, data-efficient test at your disposal.
