### ISSUE TITLE
adding error bars to abundance plots

### ISSUE THREAD

**Issue by ClaireA** [joey711/phyloseq#454]
Hello,

I am hoping I can get a bit of help with my abundance plots. Here is the list of commands I currently use to get transformed abundance bars:

claire.table = import_qiime(otufilename = "fileclaire.txt", mapfilename = "mapclaire.txt", parseFunction = parse_taxonomy_simple)
clairenosingle = prune_taxa(taxa_sums(claire.table) > 1, claire.table)
clairef <- filter_taxa(clairenosingle, function(x) sum(x > 3) > (0.2 * length(x)), TRUE)
claireft <- transform_sample_counts(clairef, function(OTU) OTU/sum(OTU))
claireftt <- transform_sample_counts(claireft, function(x) 500 * x/sum(x))
TopNOTUs <- names(sort(taxa_sums(claireftt), TRUE)[1:100])
clairetop100ftt <- prune_taxa(TopNOTUs, claireftt)
clairef0 = subset_samples(clairetop100ftt, Generation %in% c("F0"))
clairef0m = merge_samples(clairef0, "Treatment")
sample_data(clairef0m)$Treatment <- levels(sample_data(clairef0)$Treatment)
clairef0m = transform_sample_counts(clairef0m, function(x) 100 * x/sum(x))
p = plot_bar(clairef0m, "Treatment", fill="Family", facet_grid= ~Domain)
p + geom_bar(aes(color=Family, fill=Family), stat="identity", position="stack") 

How can I modify this to include error bars (SEM or SD) in these bar graphs?

Thanks in advance,

Claire

**Comment by audy** [comment]
I would calculate them myself. This example uses the `dplyr` function from the `ddply` package.

```S
# convert your processed phyloseq object into a dataframe
df <- psmelt(claref0m)

# group by Treatment and Family, calculate mean abundance and standard deviation
avgs <- dplyr(df, ~ Treatment + Family, function(x) {
  mean <- mean(x$Abundance)
  sd <- sd(x$Abundance)
})

# plot bar graph with standard deviation as error bars
ggplot(avgs, aes(fill=treatment, x=Family, y=mean)) + 
    geom_bar(position='dodge') +
    geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd))
```

**Comment by joey711** [comment]
`geom_errorbar` is the way to go, IMO. See the code of `plot_richness` for an in-phyloseq example.

Thanks @audy for the answer.

joey
