### ISSUE TITLE
error in making heatmap by phyloseq

### ISSUE THREAD

**Issue by Githubjglee** [joey711/phyloseq#455]
when I made heatmap by phyloseq (plot_heatmap(gpt, sample.label="ClincalStatus")), I got the following error: could anyone interpret the error information and let me know how to fix? Thanks a lot.

Error in if (any(dist < -sqrt(.Machine$double.eps))) warning("some dissimilarities are negative -- is this intentional?") :
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In distfun(comm, method = distance, ...) :
  you have empty rows: their dissimilarities may be meaningless in method “bray”
2: In distfun(comm, method = distance, ...) : missing values in results

**Comment by joey711** [comment]
Can you provide a minimal reproducible example, for instance using the `GlobalPatterns` dataset?

It sounds like you have negative values somewhere in your abundance matrix.

Thanks

**Comment by joey711** [comment]
Closed for now. No response in greater than 30 days, not reproducible issue. Can re-open if more details are posted.

**Comment by mariabernard** [comment]
Dear Paul,

this is a very old post, but I have the same issue.
In fact it happends when a sample has all abundance equal to 0 for the OTU selected.

the error is returned by `metaMDS(veganifyOTU(physeq), distance)` called in `ordinate()` function called in `plot_heat_map` to order sample and taxa.

To solve it, I just remove the sample with sample_sums(physeq) >0, but it's a shame they don't appear in the final heatmap.

Would it be possible in plot_heatmap to remove these "empty" samples before calling `ordinate` and add them at the end ordered sample vector to generate the plot ? Or deal with this in an other way you prefer ...

Regards

Maria

**Comment by gcuster1991** [comment]
Hi @joey711, 

I'm having a similar issue when trying to make a heatmap using Z-score transformed data. Any suggestions? 


```
data(GlobalPatterns)
GP_Z<-microbiome::transform(GlobalPatterns, transform = "Z", target = "OTU")
phyloseq::plot_heatmap(GP_Z)
```

I get the following error: 

'comm' has negative data: 'autotransform', 'noshare' and 'wascores' set to FALSE
Warning: results may be meaningless because data have negative entries
                 in method “bray”Warning: some dissimilarities exceed expected maximum 1Warning: argument is not numeric or logical: returning NAError in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'mean': subscript out of bounds
