### ISSUE TITLE
network file editable in gephi, cytosape

### ISSUE THREAD

**Issue by deoonda1** [joey711/phyloseq#456]
hi Joey;

I started using the network function of the package. However, I am just wondering if there are possibilities of exporting the data on network in network editing platforms like gephi and cytoscape?

Thanks a lot.

deo

**Comment by joey711** [comment]
Yes, I think there are already functions in the igraph package for converting to other network formats. Furthermore, other graph packages besides igraph often also provide their own conversion/coercion functions. For instance, see `rgexf`.

For your questions, `make_network` would return an igraph object that you could then transfer/convert to other tools. I'm thinking of releasing an example that would use the Sigma javascript library to represent networks in a more fun, interactive way. 

Let me know if you think that would be useful. Hope that helps (will close for now)
