### ISSUE TITLE
network analysis

### ISSUE THREAD

**Issue by Biyorun** [joey711/phyloseq#457]
Dear Dr. McMurdie,

I'm using phyloseq 1.10.0 for network analysis.
I have following problems you might know an answer to:

when I use "plot_network(ig,physeq = physeq)" and try to colorize the OTU vertices by e.g. phylum, I get an error (Error in TAX$Phylum : $ operator is invalid for atomic vectors), while this does not occur when using "plot_net(physeq, type = "taxa", distance = "bray", maxdist=0.1, color="Phylum")".
How can I avoid this?

When I try to set shape by using presence/absence (1/0) or effectively assigning a string to it (e.g. 1= water, 0=soil), I get "Error: A continuous variable can not be mapped to shape". I don't see how this could be a continuous variable?

I was also wondering if it would be possible to correlate environmental variables to the clusters of OTUs I observe using the "sample_table"? Or does this have to be done via a detour?

Thanks in advance.

Sincerely,
Bjorn

**Comment by joey711** [comment]
Can you provide a minimal reproducible example, for instance using the `GlobalPatterns` dataset?

Also your last question is separate issue / feature question. Please post as a separate issue. I suspect other users will jump in with their preferred methods there. Yes, it is possible.

Thanks
