### ISSUE TITLE
Aggregate a phyloseq object

### ISSUE THREAD

**Issue by locon833** [joey711/phyloseq#458]
Hi all,
I'm trying to separate out the Month factor of my dataset so that I can plot a dendrogram to do beta diversity stats on my data to see which months were statistically significant. When I try to use the aggregate function in R I'm getting the following error:

> aggdata <- aggregate.data.frame(Lauren.scale, by=list(MonthSampleTaken), mean)
Error in as.data.frame.default(x) : 
  cannot coerce class "structure("phyloseq", package = "phyloseq")" to a data.frame

My data was converted from a .biom file into a phyloseq object so I believe it's still in matrix format. If anyone knows how I can go about separating out my month factor from a phyloseq object I would greatly appreciate any advice!

**Comment by spholmes** [comment]
Hello,
I believe you need to take just the sample data information
through the command
samp=sample_data(LaurenScale)
then use samp$MonthSampleTaken
as your merging variable.

You will then make a new phyloseq object with the new merged months.
I cannot help you more as you have not really provided us with the exact
phyloseq object or the names of your variables, but this is my guess.

Susan

On Wed, Apr 8, 2015 at 7:06 AM, locon833 <notifications@github.com> wrote:

> Hi all,
> I'm trying to separate out the Month factor of my dataset so that I can
> plot a dendrogram to do beta diversity stats on my data to see which months
> were statistically significant. When I try to use the aggregate function in
> R I'm getting the following error:
>
> aggdata <- aggregate.data.frame(Lauren.scale, by=list(MonthSampleTaken),
> mean)
> Error in as.data.frame.default(x) :
> cannot coerce class "structure("phyloseq", package = "phyloseq")" to a
> data.frame
>
> My data was converted from a .biom file into a phyloseq object so I
> believe it's still in matrix format. If anyone knows how I can go about
> separating out my month factor from a phyloseq object I would greatly
> appreciate any advice!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/458>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by michberr** [comment]
Hi,

you can't transform a phyloseq object into a data frame, but you can transform its individual parts ie
data.frame(sample_data(physeq))

You can also join your otu table, taxonomy table, and sample data together into one dataframe using the awesome psmelt() function. You could then call any dataframe-based functions on that. 

I'm a little confused about what you're trying to do. Are you trying to use the aggregate function to pool all of your samples by month (average samples within a month)? In this case, you should use the merge_samples() function. 

If you just want to isolate the month column from your phyloseq object, data.frame(sample_data(physeq))$Month should do it.

**Comment by locon833** [comment]
Thank you for the responses. I'm sorry for being a bit vague.

My purpose for wanting to isolate the month factor from my dataset is because I want to do statistical tests (Adonis, etc.) on my samples using the month sample taken variable to see which months varied significantly from each other in terms of diversity. I have merged my mapping file, tree file, and .biom file in phyloseq and called it Lauren_data_merged:

> Lauren_data_merged
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 40687 taxa and 82 samples ]
sample_data() Sample Data:       [ 82 samples by 11 sample variables ]
tax_table()   Taxonomy Table:    [ 40687 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 40687 tips and 40685 internal nodes ]

> head(Thesis_mapping)
Sample Data:        [6 samples by 11 sample variables]:
     X.SampleID BarcodeSequence LinkerPrimerSequence InputFileName MonthSampleTaken Location Salinity WaterTemperature Season
PE12       PE12              NA                   NA    PE12.fasta             July       M9     26.0               30    Wet
PE15       PE15              NA                   NA    PE15.fasta             July       M9     14.5               30    Wet
PE17       PE17              NA                   NA    PE17.fasta             July       BB     17.0               30    Wet
PE18       PE18              NA                   NA    PE18.fasta             July       M9     17.0               30    Wet
PE20       PE20              NA                   NA    PE20.fasta           August       BB     22.5               30    Wet
PE21       PE21              NA                   NA    PE21.fasta           August       M9     22.5               30    Wet
     Weather    Date
PE12    Rain 7/10/13
PE15    Rain 7/19/13
PE17    Rain 7/23/13
PE18    Rain 7/23/13
PE20    Rain  8/3/13
PE21    Rain  8/3/13 

Therefore, I'm trying to figure out a way to isolate the MonthSampleTaken variable along with the taxonomy data,OTU counts, etc associated with the samples so that I can do the statistics based on the month variable.

**Comment by michberr** [comment]
Thanks for the clarification. I would use:

bdist = phyloseq::distance(lauren_data_merged,"bray")
adonis.test=adonis(bdist~MonthSampleTaken, as(sample_data(lauren_data_merged),"data.frame"))

Obviously you can change the distance matrix if you want to use a different measure of community dissimilarity than bray-curtis

**Comment by locon833** [comment]
Hi Michelle,

I have actually already done the adonis test that way. My results came back significant so the reason that I originally wanted to separate my month data from the dataset was because I want to determine which months were statistically significant from each other. I'm not sure if you have any ideas on how to test that, but that's where I'm stuck at the moment.

**Comment by michberr** [comment]
Hi Lauren,

I don't know of a posthoc test for adonis. Jari Oksanen (the author of vegan) hasn't developed one yet either: http://r-sig-ecology.471788.n2.nabble.com/post-hoc-test-for-adonis-PERMANOVA-td7577679.html.

However, if you want to ask which taxa taxa are differentially abundant between months I would follow the phyloseq tutorial on using DESeq2. 

If you want to ask how something like alpha diversity is different between your months you could run a kruskal wallis test followed by something like the kruskalmc command in pgirmess package. This is also a good read: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0009788

**Comment by locon833** [comment]
Thank you for the comments. I tried using DeSeq2 with my data, but because I don't have replicates on individual samples, rather just 4 samples/month, I was running into issues. I may need to look into DeSeq a little more.

I've done the kruskal wallis on my alpha diversity, thank you for the article. I appreciate all your help!

**Comment by michberr** [comment]
Hi Lauren,

You should be able to run DeSeq2 without replicate samples. In fact, i think it is inadvisable to run it with replicates because those samples are not independent. If you are getting an error while running DeSeq2, you  probably are starting with too sparse of a matrix. All this means is that you need to eliminate rare OTUs from your OTU table - for instance OTUs that are below 1% or .1% by relative abundance. 

If you are having a different issue with Deseq2, please post again with more details,

Best,
Michelle

**Comment by locon833** [comment]
I followed the DESeq2 tutorial on phyloseq to determine my significantly different OTUs and plotted them the same way as seen in the tutorial. As I'm fairly new to the bioinformatics world, I'm not sure how to work with the data DESeq generates in order to find my differentially abundant taxa by month. This is an example of my data:

> head(sigtab)
      baseMean log2FoldChange     lfcSE       stat       pvalue         padj  Kingdom        Phylum                 Class
2398 254.38309       5.263683 0.3683447  14.290100 2.522464e-46 5.133215e-43 Bacteria Cyanobacteria Synechococcophycideae
2865 158.89254       5.025619 0.4165693  12.064304 1.630357e-33 1.658888e-30 Bacteria Cyanobacteria Synechococcophycideae
3253  73.80649      -5.219725 0.4746818 -10.996261 3.983083e-28 2.701858e-25 Bacteria Cyanobacteria           Chloroplast
2732  99.52343       5.274010 0.5285491   9.978279 1.897298e-23 9.652505e-21 Bacteria Cyanobacteria Synechococcophycideae
4939  76.75427       4.770687 0.4948392   9.640883 5.372382e-22 2.186559e-19 Bacteria Cyanobacteria Synechococcophycideae
1389 257.05131      -1.877288 0.2183460  -8.597767 8.128241e-18 2.756828e-15 Bacteria Bacteroidetes        Flavobacteriia
                Order           Family         Genus Species
2398  Synechococcales Synechococcaceae          <NA>    <NA>
2865  Synechococcales Synechococcaceae          <NA>    <NA>
3253    Stramenopiles             <NA>          <NA>    <NA>
2732  Synechococcales Synechococcaceae Synechococcus    <NA>
4939  Synechococcales Synechococcaceae          <NA>    <NA>
1389 Flavobacteriales   Cryomorphaceae          <NA>    <NA>

I've read the DESeq2 vignette, but due to my inexperience with coding and bioinformatics I'm not sure that I'm understanding how to manipulate the data in order to make it meaningful.

**Comment by spholmes** [comment]
You probably want to check with a statistician, this is not a
Bioinformatics problem
but a statistical interpretation issue the padjusted are the adjusted
p-values, small values like
these mean that those OTUs are significantly changed.

Susan

On Tue, Apr 14, 2015 at 8:45 AM, locon833 <notifications@github.com> wrote:

> I followed the DESeq2 tutorial on phyloseq to determine my significantly
> different OTUs and plotted them the same way as seen in the tutorial. As
> I'm fairly new to the bioinformatics world, I'm not sure how to work with
> the data DESeq generates in order to find my differentially abundant taxa
> by month. This is an example of my data:
>
> head(sigtab)
> baseMean log2FoldChange lfcSE stat pvalue padj Kingdom Phylum Class
> 2398 254.38309 5.263683 0.3683447 14.290100 2.522464e-46 5.133215e-43
> Bacteria Cyanobacteria Synechococcophycideae
> 2865 158.89254 5.025619 0.4165693 12.064304 1.630357e-33 1.658888e-30
> Bacteria Cyanobacteria Synechococcophycideae
> 3253 73.80649 -5.219725 0.4746818 -10.996261 3.983083e-28 2.701858e-25
> Bacteria Cyanobacteria Chloroplast
> 2732 99.52343 5.274010 0.5285491 9.978279 1.897298e-23 9.652505e-21
> Bacteria Cyanobacteria Synechococcophycideae
> 4939 76.75427 4.770687 0.4948392 9.640883 5.372382e-22 2.186559e-19
> Bacteria Cyanobacteria Synechococcophycideae
> 1389 257.05131 -1.877288 0.2183460 -8.597767 8.128241e-18 2.756828e-15
> Bacteria Bacteroidetes Flavobacteriia
> Order Family Genus Species
> 2398 Synechococcales Synechococcaceae
> 2865 Synechococcales Synechococcaceae
> 3253 Stramenopiles
> 2732 Synechococcales Synechococcaceae Synechococcus
> 4939 Synechococcales Synechococcaceae
> 1389 Flavobacteriales Cryomorphaceae
>
> I've read the DESeq2 vignette, but due to my inexperience with coding and
> bioinformatics I'm not sure that I'm understanding how to manipulate the
> data in order to make it meaningful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/458#issuecomment-92919390>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
I don't think this is an issue with phyloseq. I will close for now. If you can identify a bug or a missing feature that seems worth adding, please post back and I can re-open.

Cheers
