### ISSUE TITLE
Comparing abundance for two different groups at each taxonomic rank

### ISSUE THREAD

**Issue by saidheeraj1** [joey711/phyloseq#459]
Hi All,

I am new to Phyloseq and just getting started. As of now I am able to import biom file data and make a phyloseq object (using otu_table, tax_table, sample_data and tree). 
 I have 4 phyloseq objects for 4 different groups. I need to compare OTU abundance at each taxonomic rank in between groups 1 &2, groups 3&4. So I need to combine the abundance value for all the samples in a group, where abundance percentage is represented for each sample, then make an error plot to know the difference between groups(say 1 & 2).  
For example, there are 6 samples in group 1, 7 samples in group 2. I need to compare at phylum level, the abundance values for each OTU. Suppose "Firmicutes" has its abundance percentage as follows in group 1 : 5%, 2.4%, 3.2%, 1.6%, 6.7%, 4.8%. These percentages represent its abundance level when compared to other OTU in its sample. Similarly repeating for group 2 and then compare this OTU "Fermicutes"  for both groups and observe the error plot.

I hope that my description is understood. I am not sure which functions will help me to first combine the abundance values at each taxonomic rank for all the samples , represent then in percentages, draw the error plot. Repeating the same for other group and then compare both the groups.

Group 1:
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1541 taxa and 6 samples ]
sample_data() Sample Data:       [ 6 samples by 2 sample variables ]
tax_table()   Taxonomy Table:    [ 1541 taxa by 9 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 1541 tips and 1540 internal nodes ]

Group2:
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1484 taxa and 7 samples ]
sample_data() Sample Data:       [ 7 samples by 2 sample variables ]
tax_table()   Taxonomy Table:    [ 1484 taxa by 9 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 1484 tips and 1483 internal nodes ]

Maybe these things are addressed before but I am failed to understand. I am sorry if I am just repeating the same question.  
Also let me know on the resources(for biom files particularly) where I can find more examples in using phyloseq for different analysis, so that i get better hands-on using phyloseq

Any help on this is highly appreciated. Thanks in advance.

**Comment by michberr** [comment]
Hi,

First, I recommend you merge all of your data into 1 phyloseq object. You can differentiate your groups by having a column in your sample data called "Group". This way you will not have to repeat functions on all 4 objects. It will be easy to compare your groups at the end just by using that column in your sample data. If you have a biom file with all of your samples you can simply reload this data into phyloseq. If not, you can use:
merged_groups<- merge_phyloseq(Group1,Group2,Group3,Group4)

To compare taxa at different phylogenetic levels, you can use the tax_glom() function. For example:
phylum_glom<-tax_glom(merged_groups, taxrank="Phylum")
Make sure whatever taxrank you select matches the column header in your tax_table

To transform your counts to percentages you can use the transform_sample_counts() function. For example: 
phylum_relative <- transform_sample_counts(phylum_glom, function(x) {(x/sum(x))})

Im not sure i understand what kind of plot you want to make. If you are looking to see which taxa are differentially abundant between two groups, I recommend you use first read http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531 and then use the phyloseq_to_deseq2() function. 

Best,
Michelle

**Comment by saidheeraj1** [comment]
Thanks Michelle.

I have data in different files for each group. However i created four phyloseq objects for each group.
new1, new2, new3, new4.
After this, i created a subset which contains OTU for Domain only "Bacteria". Named them as bacteria1, bacteria2, bacteria3, bacteria4.
here is the code for group1:
>new1 = phyloseq(OTU,TAX,tree)
 // Created otu_table, tax_table, phy_tree before
>new1 = merge_phyloseq(new1, SD) 
//after creating sample_data, merged it with phyloseq object. Final phyloseq object is new1.
>bacteria1<-subset_taxa(new1, taxonomy2=="Bacteria")
// created a subset which contains only bacterias, taxonomy2 is "Domain"
Similarly did the same for group2 and created new2, bacteria2.
Now I am merging the samples using code below
>mergeGrp2<- merge_samples(bacteria2, "Grp")
//Grp is variable name which has value '2' for all samples
>merge2_relative = transform_sample_counts(mergeGrp2, function(OTU) 100*OTU/sum(OTU))
>plot_bar(merge2_relative, fill="taxonomy3")
// When i run the above code for bar plot, i will get the abundance in % for each phylum.
 I am able to do this only for group2. When I am doing the same for group 1, I am getting the error

> mergeGrp1<- merge_samples(bacteria1, "Grp")
Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component sample names do not match.
 Try sample_names()
 I am unable to figure out the reason for this, as I am doing the same steps for each group. Successfully done for other groups but not for group1.
If I am able to do this, then I want to compare the two bars in one plot so that i can easily understand the abundance % of a particular phylum and know which group has more abundance %.

Hope I clearly explained.
Let me know in how to correct to avoid the error.

Thanks
