### ISSUE TITLE
Mothur tree file

### ISSUE THREAD

**Issue by tidusff10** [joey711/phyloseq#460]
Hi.
First, congratulation for your package.
iI'm wondering if s it possible to to make a tree file with mothur which is compatible with phyloseq object ?

Thanks

**Comment by joey711** [comment]
Yes. See the `read_tree` function documented in phyloseq, which also refers to useful functions for reading phylogenetic tree files elsewhere.

There are lots of ways to get tree information into R, and then into phyloseq. The precise way to do it will depend on your file format, but there is not theoretical limitation. Eventually the tree needs be represented in R as a `"phylo"` class object (originally defined by the ape package), in which the leaves/tips of the tree match the OTU IDs (`taxa_names`) in your phyloseq object. `merge_phyloseq` or `phyloseq` will help you then bind this data together as one coherent phyloseq object.

Cheers
