### ISSUE TITLE
Getting Top N (10 or 15) abundant OTU for each taxa rank

### ISSUE THREAD

**Issue by saidheeraj1** [joey711/phyloseq#462]
Hello everyone,

I am trying to get the top10 abundant OTU for taxa rank Genus. However I am unable to do that. Here is my code,

> b1 = prune_taxa(taxa_sums(bacteria1) > 0, bacteria1)
// bacteria is phyloseq object that contains otu_table, tax_table, tree and sample data)
>mergedb1=merge_samples(b1, "Mouse.Type")
// Mouse.Type is the variable which identifies the mouse
>SD = merge_samples(sample_data(b1), "Mouse.Type")
>identical(SD, sample_data(mergedb1))
[1] TRUE
>OTU10 = names(sort(taxa_sums(b1), TRUE)[1:10])
>b10=prune_taxa(OTU10, b1)
>mb10 = prune_taxa(OTU10, mergedb1)
>rowSums(otu_table(b10))
// I get the below result, but unable to understand it. I know that first row is abundance values, but what does the values in second row indicate?

66734 101877 320116 360657 105514 360611 110629 105458 360612 360613 
   639    639    561   1176    531   1176    953    531   1176   1176 

plot_bar(b10, "Mouse.Type", fill = "Mouse.Type", facet_grid=~taxonomy7)
//taxonomy7 is the genus

![image]  (https://cloud.githubusercontent.com/assets/11686303/7205115/888d044c-e4ec-11e4-96cb-a0fefd961c3e.png)

In the above image I only see 6 genus instead of 10? 
What does the separating lines indicate in the bar? For example genus "Streptococcus", all bars contain lines.

Please help me out with this, let me know if there is any mistake in my code and any other better approach to do this.

Thanks in advance

**Comment by michberr** [comment]
Hi,
An easy way to check how many taxa are stored in a phyloseq object is just to type the name of the object into the console as a command. For example, type b10 and press enter and it should tell you if there are 10 taxa stored in it or not. 

I'm guessing that you do have 10 OTUs stored in that object, but they only span 6 genera. If you want your top 10 genera, you need to first use the tax_glom() function to agglomerate OTUs at a given taxonomic level and then select the 10 most abundant taxa. For example:

b1_genus<-tax_glom(b1, taxrank="Genus")
Genus10 = names(sort(taxa_sums(b1_genus), TRUE)[1:10])

**Comment by saidheeraj1** [comment]
Thanks for the reply.
I just figured it out the reason that it is showing only 6 (infact it is showing 10).
 I have total 9 taxonomy ranks.
taxonomy1 - Doamin, 2 - Kingdom, 3 - phylum.....8 - Species, 9 - id. When i say to get top 10 abundant taxa, it is taking with respective to taxonomy9 which is "id" as it is unique.  So when we ask to plot bar for taxonomy7 (genus), 4 of the unique id's are corresponding to the same genus, so in bar plot we can see those 4 separated with line (In Genus - Streptococcus). Similarly for genus "Enterococcus" we see 2 id's mapped.  When we add now for all we get 10 (Clostridium1, Egerthella 1, Enterococcus 2, Ethanoligineus 1, Porphyromonas 1, Streptococuus 4).

I think the better way is to use tax_glom and then sort the abundant Otu.
I will try using that.
Thanks for helping me out.

**Comment by saidheeraj1** [comment]
Michelle,

Any idea on how to merge two phyloseq objects. I am using "merge_phyloseq" function but unable to do.
With reference to the above code, bacteria1 is my phyloseq object which has 5 samples.
I have an other phyloseq object bacteria2, which has 6 samples. Now i am trying to merge both objects using the code below:
> merge12 <- merge_phyloseq(bacteria1, bacteria2)
Error in FUN(X[[2L]], ...) : one tree has a different number of tips
I am getting the above error and unable to merge.
My idea is to compare the abundant OTU at each level for both the groups (bacteria1, bacteria2).
Once if I merge two phyloseq objects, i can bar plot using variable "Grp" which has values "1 & 2" and then compare the abundant OTU at each level for both groups.
Let me know if you have any idea in doing this.

**Comment by saidheeraj1** [comment]
Hi Michelle,
 I am able to get the bar plots for two groups. I filtered data for top 30 abundant taxa. There are six phylums for it. I was able to merge two groups which were in different files by using merge_phyloseq_pair first (for merging Otu_table, taxa_table, Sample data of two groups), then created a phyloseq object using merged Otu_table, taxa_table, Sample data. Then created a subset for domain which contains only bacteria (named it as bacteria12), then used below code:
> b12 = prune_taxa(taxa_sums(bacteria12) > 0, bacteria12)
> b12OTU10 = names(sort(taxa_sums(b12), TRUE)[1:30])
> any(taxa_sums(b12OTU10)== 0)
> b10_12=prune_taxa(b12OTU10, b12)
> b10new = prune_taxa(taxa_sums(b10_12)>0, b10_12)
> p12<-plot_bar(b10new, "taxonomy3", fill = "taxonomy3", facet_grid=~Grp)
> p12 + geom_bar(aes(color=taxonomy3, fill= taxonomy3), stat="identity", position="stack")
Plot looks like this
![image](https://cloud.githubusercontent.com/assets/11686303/7254925/8d050ed0-e80b-11e4-8b6c-8b044422c659.png)

Now i am stuck at two things:
1. How to convert abundance into percentages?
While using transform_sample_counts function I am able to only convert within the sample abundance values, so in a group all the samples are being added and percentage is displayed (which will obviously be more than 100%). Through transform_sample_counts function there is no sample to sample interaction possible. Is there any other function through which i can enable sample to sample interaction and represent abundance values in percentages.

2. How to get a boxplot using the above barplot?
Let me know on the required packages, and process to get a box plot.

Any help on the above is highly appreciated.

Thanks,
Sai Dheeraj

**Comment by michberr** [comment]
Hi Sai,

1) I would use merge_samples() to merge all of your samples in the same group and then apply transform_sample_counts()

2) Making different kinds of plots with ggplot is pretty simple. Instead of geom_bar() use geom_boxplot()
http://docs.ggplot2.org/0.9.3.1/geom_boxplot.html

**Comment by saidheeraj1** [comment]
I tried using merge_samples, but i got the below error
> m1<-merge_samples(b10new, "Grp")
Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component sample names do not match.
 Try sample_names()

So i didn't merge samples, instead used variable "Grp" in facet_grid while plotting bar.
Same error is also reported in issue #459

**Comment by joey711** [comment]
Can you provide a minimal reproducible example, for instance using the `GlobalPatterns` dataset?

Thanks

**Comment by ClaireA** [comment]
Hi there,

I was reading this thread and I think the code below will allow you to transform everything to percentage and have 100 as your maximum value:

clairef0m = merge_samples(clairef0, "Treatment")
sample_data(clairef0m)$Treatment <- levels(sample_data(clairef0)$Treatment)
clairef0m = transform_sample_counts(clairef0m, function(x) 100 * x/sum(x))

Then plot the merged object. This is my preferred graph:

p = plot_bar(clairef0m, "Treatment", fill="Family", facet_grid= ~Domain)
p + geom_bar(aes(color=Family, fill=Family), stat="identity", position="stack")

Hope it helps,

Claire

**Comment by joey711** [comment]
This looks solved. Let me know if not and I'll re-open.
