### ISSUE TITLE
no 

### ISSUE THREAD

**Issue by elinekl** [joey711/phyloseq#467]
I loaded a .biom file that I created in qiime by summarizing Taxa in OTU Table. Previously I used the original otu.biom talbe from qiime and that works fine. Only this one has 17000 otu's, and the size of this table interferes with phyloseq. THerefor I wan tto use the summarized table with 200 otu's. But when I load this table and look for the taxonomy it says: 
Error in access(object, "tax_table", errorIfNULL) : 
  tax_table slot is empty.

The text file of this summarized table looks fine. What can I do. I was thinking of loading the text file instead of the .biom file but I don't know which command to use for phyloseq in R. What do you recommend. Then I want to merge this file with the sample data file. And generate some figures with phyloseq.

**Comment by joey711** [comment]
Can you update your title?

Also, you haven't provided much information for anyone to go on. What version of QIIME? What version of BIOM (yes, there are two very different versions of the file format now)? 

The theoretical computational limit on the number of OTUs you could include is much, much greater than 17,000. Unless you're trying to do this on an old computer, the number of OTUs is probably not the problem.

**Comment by joey711** [comment]
I will close for now unless/until you provide more details that verify what the problem. There are already previously closed issues related to the biom file format. I suggest reviewing those, and posting back what you find out.

Cheers
