### ISSUE TITLE
Plotting distance between treatment groups

### ISSUE THREAD

**Issue by ClaireA** [joey711/phyloseq#469]
Hi,

I am trying to figure out a way to plot distance values (Bray) between treatment groups so that I can calculate if they are statistically different or not (see example of what I'd like to do in image below). So far I have only been able to get the distance values using the distance () function but it can only provide values based on taxa or samples. Do you know of a different function I can use to do this?

Thanks,

C
![screen shot 2015-04-30 at 11 23 17 pm](https://cloud.githubusercontent.com/assets/2497244/7427437/f4065004-ef8f-11e4-9bd5-cd1788b6c952.png)

**Comment by spholmes** [comment]
Claire
There is something you have not provided in your question:
although you are interested in the Bray distance there are many ways of
computing the distance between groups:
The maximum distance between points from different groups.
The average distance between points from different groups.
The minimum distances between points from different groups....
weighted distances etc....

Once you have decided, it is just one or two lines of R code
to do the computation.

Hope this helps,
Susan

On Thu, Apr 30, 2015 at 11:24 PM, ClaireA <notifications@github.com> wrote:

> Hi,
>
> I am trying to figure out a way to plot distance values (Bray) between
> treatment groups so that I can calculate if they are statistically
> different or not (see example of what I'd like to do in image below). So
> far I have only been able to get the distance values using the distance ()
> function but it can only provide values based on taxa or samples. Do you
> know of a different function I can use to do this?
>
> Thanks,
>
> C
> [image: screen shot 2015-04-30 at 11 23 17 pm]
> <https://cloud.githubusercontent.com/assets/2497244/7427437/f4065004-ef8f-11e4-9bd5-cd1788b6c952.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/469>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by ClaireA** [comment]
That makes sense. Would you be able to provide the code to compare it to the median of the treatment group?

Many thanks,

Claire


________________________________________

**Comment by ClaireA** [comment]
Hello Susan,
I was hoping to obtain the code to calculate the distance between groups. I have a presentation next Tuesday and would like to include this analysis. I'd really appreciate your help. Thanks!

Claire

**Comment by negin1986** [comment]
Have you found a solution to this?
