### ISSUE TITLE
Using Bray-Curtis with variance stabilizing transformation of count data - Waste Not Want Not

### ISSUE THREAD

**Issue by barbara1** [joey711/phyloseq#470]
Hi Joey, 

In your "Waste not, want not" paper you construct a Bray-Curtis distance matrix from the variance stabilizing transformation of count data - which ends up having negative values. I looked through the supplemental information but did not notice any altering or scaling to obtain the Bray-Curtis distance matrix. Just wondering if you could explain how it was done. My quick solution was to add a "scalar" to the VSD values (the minimum value +1) to remove negatives, but am not sure that is an acceptable approach to the problem and would greatly welcome your comments on the proper way to successfully use the VSD data in Bray-Curtis distance matrices.

Thanks in advance.

Barbara

**Comment by joey711** [comment]
This is discussed in the [phyloseq FAQ](http://bioconductor.org/packages/devel/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html).

By the way, for many datasets, simple proportions work fine for the purpose of calculating Bray-Curtis. If you do need/want to use the vst values for BC, you would still need to take care that the sample sums are similar, as BC is sensitive to differences in totals. It is also sensitive to negative values, as you point out, but you can address this with a pseudocount (e.g. adding some minimum value before vst), or simply setting a floor on small values such that the smallest value is slightly positive.
