### ISSUE TITLE
Deseq2 parameters

### ISSUE THREAD

**Issue by ademenez** [joey711/phyloseq#471]
Hi,

I have used Deseq2 to test for differential abundance in my dataset. I followed this analysis example 
http://joey711.github.io/phyloseq-extensions/DESeq2.html

I understand that I do not have to perform filtering of rare sequences as DESeq2 does that by default, is that correct?
Also, what assumptions are made about the data in order to use the Wald test? And how would you analyse the data to determine what test is appropriate? 

Many thanks,

Alexandre

**Comment by ademenez** [comment]
One more issue I forgot to ask before: since the analysis example above provides adjusted p-values, I don't have to perform another round of correction or adjustment of p-values?

Thanks,

Alex

**Comment by joey711** [comment]
`DESeq2::DESeq` does do independent filtering by default. You should make certain that the relevant parameter has that turned on, and also that you understand what kind of filtering that is, and if it's sufficient and appropriate for you experiment. It is probably a good idea to use it, in most cases.

Assumptions... You'll need to read up about this elsewhere. A comprehensive list here would not be appropriate. Some oft-missed assumptions for multiple univariate testing include "approximate independence" of features (e.g. OTUs), which in this context is also related to an assumption that most features are not differentially abundant. You should be worried if more than 20% of your features are being detected as differentially abundant, in which case you might want to consider treating the data with multivariate methods and finding a useful summary that way.

The Wald test is very general, and not specific to this problem. I think you are asking about a diagnostic test for the negative binomial. There are many available in DESeq2, edgeR, and probably others. Although there are some built-in protections against outliers in DESeq2, it is still going to be sensitive to data that deviates substantially from the negative binomial. However, most HT-seq data is usefully approximated by the negative binomial, and so this would be an unusual case. 

Hope that helps.

Joey

**Comment by joey711** [comment]
Adjusted P-values:
That is a loaded question as-asked. I don't know what else you're doing with these results, so it could be more complicated. 

The default results from `DESeq2::DESeq` do include the B-H corrected p-values (aka FDR, aka q-value) as an additional column that you should use instead of p-values if you are considering type-1 error.
