### ISSUE TITLE
Potential DPCoA Error

### ISSUE THREAD

**Issue by wkingc** [joey711/phyloseq#472]
Dear Dr. McMurdie,

I wanted to report a potential bug I found in the Phyloseq function ‘DPCoA’.  I never ran into this issue before so I suspect it comes from an update to ade4.

The function ‘dpcoa’ in ade4 expects a data frame with taxa on the columns and samples on the rows (was it previously taxa on the rows?) but in the ‘DPCoA’ function you have the following statement:

    if (!taxa_are_rows(OTU)) {
        OTU <- t(OTU)
    }

In this case, if taxa_are_rows(OTU) evaluates as TRUE, the symbol “!” changes it to FALSE and so the matrix is not transposed, causing ‘dpcoa’ to return an error (it can tell something is wrong because the number of taxa on the tree will not match the number of taxa it expects from the abundance table).  To fix this error I think you need to remove the “!” so that the matrix is transposed when the taxa are on the rows.

Sincerely,

Wade Copeland

Wade K. Copeland
Fred Hutchinson Cancer Research Center, 
PHS Shared Resources Biostatistician
1100 Fairview Ave North, M2-A113
Seattle, WA 98109
wcopelan at fredhutch dot org

**Comment by joey711** [comment]
Hi Wade!

You are correct. There was a change to ade4, and it did involve the orientation of the matrix as one of the changes. There was a recent fix pushed to both release and devel versions of phyloseq on this issue.

What versions of phyloseq and ade4 are you using?

**Comment by joey711** [comment]
I'll close for now. I can re-open if you can clarify this bug exists even in the updated version of phyloseq (e.g. `1.12.2+`)

**Comment by wkingc** [comment]
Ops, sorry Joey!  I completely missed that you replied.  I am actually using R on a sever maintained by the organization I work at and they haven't updated to R 3.2 yet, so I cannot download the updated version of bioconductor yet.  I can verify that If the version of DPCoA that is published at https://github.com/joey711/phyloseq/blob/master/R/ordination-methods.R is currently being used, then it will probably works just fine :).

**Comment by joey711** [comment]
Great! Thanks for the update. Glad the issue is resolved!

joey
