### ISSUE TITLE
plot_bar crashes with example data

### ISSUE THREAD

**Issue by antagomir** [joey711/phyloseq#478]
data(enterotype)
plot_bar(enterotype)

Error in .Method(..., na.last = na.last, decreasing = decreasing) : 
  argument 1 is not a vector

data(GlobalPatterns)
plot_bar(GlobalPatterns, fill = "Phylum")
Error in .Method(..., na.last = na.last, decreasing = decreasing) : 
  argument 1 is not a vector

**Comment by spholmes** [comment]
Leo
I just executed these commands and only got a warning,
what package Version do you have?
> require(phyloseq)
> data(enterotype)
> plot_bar(enterotype)
Warning message:
position_stack requires constant width: output may be incorrect
> data(GlobalPatterns)
> plot_bar(GlobalPatterns)
> packageVersion("phyloseq")
[1] ‘1.10.0’

Susan

On Sat, May 16, 2015 at 2:15 PM, Leo Lahti <notifications@github.com> wrote:

> data(enterotype)
> plot_bar(enterotype)
>
> Error in .Method(..., na.last = na.last, decreasing = decreasing) :
> argument 1 is not a vector
>
> data(GlobalPatterns)
> plot_bar(GlobalPatterns, fill = "Phylum")
> Error in .Method(..., na.last = na.last, decreasing = decreasing) :
> argument 1 is not a vector
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/478>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by antagomir** [comment]
I now notice that restarting R and running these commands I cannot reproduce the bug. It might be due to some package conflict but could not find out yet. I will report this again with sessionInfo() if I can reproduce it.

My phyloseq version is 1.12.2
