### ISSUE TITLE
plot_tree flexibility (psmelt?) / ggplot2 summary plots for DESeq2

### ISSUE THREAD

**Issue by ckcollings** [joey711/phyloseq#479]
Hi Joey,

*** Trees:

Is there a way to list more than a single taxa level in labels.tips?
It would be nice to label the tips with both phylum and genus information for example
or even the entire classification.

Also, how can one gain more control color and shape assignment using psmelt?
I don't think there are good examples available for easily learning how to use psmelt.

*** ggplot2 summary plots for DESeq2 output

Do you know a way in which one could rearrange the order of the taxa on x axis  (and also control their presence) ?

If you plot phylum versus genus, it would be nice to order the genuses so that the
same phylum colors would be grouped together (except for the unclassified ones)

Thanks for your time.
-Clayton

**Comment by joey711** [comment]
@ckcollings there are lots of examples on [the phyloseq tutorials](http://joey711.github.io/phyloseq/tutorials-index) pages and in the vignettes.

What you are currently asking for on the tree is not directly supported, but you can agglomerate your phyloseq object at your desired taxonomic rank using `tax_glom`, and then redo the `plot_tree`.

I do have some efforts in the work for more interesting tree-inspired graphics, but they are not yet available.

I will close for now. Can re-open if a more specific bug or issue comes up.

Thanks for your feedback and interest in phyloseq!

joey
