### ISSUE TITLE
Error in prune_samples

### ISSUE THREAD

**Issue by locon833** [joey711/phyloseq#482]
I am trying to keep the sponge samples in my data and remove others with there following script, could you please tell me why and how to overcome this error.

```S
spongeidx = as.vector(sample_data(merge)$Sample=="Sponge")
spongeid = prune_samples(spongeidx,merge)
```

```
Error in prune_samples(spongeidx, merge) : 
  logical argument to samples is wrong length. Should equal nsamples(x)
```

**Comment by benjjneb** [comment]
Have you checked whether spongidx is length 0? That may happen if "Sample" is not a valid column in sample_data(merge).

Otherwise that code looks like it should work.

**Comment by nidhi13** [comment]
Yes it did work on a different computer :|
Thanks

**Comment by joey711** [comment]
@locon833 
Looks like you solved this issue. Thanks @benjjneb for the comment. I agree that the code looks like it should work. 

Here is an equivalent approach:

```S
data("GlobalPatterns")
spongeidx = as.character(get_variable(GlobalPatterns, "SampleType")) == "Ocean"
prune_samples(spongeidx, GlobalPatterns)
```

Or, if you prefer elegant one-liners that incur some namespace peril

```S
data("GlobalPatterns")
subset_samples(GlobalPatterns, SampleType == "Ocean")
```

I will close for now
