### ISSUE TITLE
subset_samples appears to misbehave if included in functions

### ISSUE THREAD

**Issue by macrobiotus** [joey711/phyloseq#483]
Hi Paul,

Two examples briefly: 
````ps_ob.lt <- subset_samples(ps_ob, sample_data(ps_ob)[,which(colnames(sample_data(ps_ob)) == "Location")] == "Lake_Terrasovoje")````

````ps_ob.lt <- subset_samples(ps_ob, sample_data(ps_ob)$Location == "Lake_Terrasovoje")````

Works both fine outside functions, but does not do the right thing when inside a function.

Perhaps this is because my $Location column in sample(data) are factors, but I will have to invesihate this further. Its giving quite some grief, but perhaps it will all be good soon.

Sorry for being brief.

Cheers,
Paul

**Comment by macrobiotus** [comment]
Factors were not  the issue.. I'll code around that for now

**Comment by macrobiotus** [comment]
Seems a merged ps.object is not the issue either. 99% sure something weird happens inside function there.

**Comment by macrobiotus** [comment]
Hi Paul,

I am still not entirely sure if it is my data or the subsetting function "subset_samples", but writing out the initial function value to the global environment seems to help. I have a similar thing when I use the ``` stats::step()``` function in combination with ```vegan::cca()``` so either my data is somewhat screwed, or this issue seems to happen frequently. Anyways. Looks like I found a way around it. Finding this can be quite hard, and I did this by erasing all variables from the Global environment immediately after I did not need them anymore.

Example function, now working:
```
# BUGGED?: function: prepare plots - filter empty phylotypes / samples, normalise sample counts
PlotMergedSamples <- function(ps_ob) {
    
# Initialize function - REQIRES GARBAGE COLLECTION!
assign("ps_ob", ps_ob, envir=globalenv())
message(paste("Check Garbage Collection after this step. Object ps_ob is being written to global Environment"))
  
  
# subset by location
 ps_ob.lt <- subset_samples(ps_ob, sample_data(ps_ob)[,which(colnames(sample_data(ps_ob)) == "Location")] == "Lake_Terrasovoje")
ps_ob.me <- subset_samples(ps_ob, sample_data(ps_ob)[,which(colnames(sample_data(ps_ob)) == "Location")] == "Mawson_Escarpment")
ps_ob.mm <- subset_samples(ps_ob, sample_data(ps_ob)[,which(colnames(sample_data(ps_ob)) == "Location")] == "Mount_Menzies")
  	
# remove empty samples and rows
ps_ob.lt <- RmZeroCounts(ps_ob.lt)
ps_ob.me <- RmZeroCounts(ps_ob.me)
ps_ob.mm <- RmZeroCounts(ps_ob.mm)
	
# normalize sample counts
ps_ob.lt <- transform_sample_counts(ps_ob.lt, function(OTU) OTU/sum(OTU))
ps_ob.me <- transform_sample_counts(ps_ob.me, function(OTU) OTU/sum(OTU))
ps_ob.mm <- transform_sample_counts(ps_ob.mm, function(OTU) OTU/sum(OTU))
      
 # create plots
p1 <- plot_bar(ps_ob.mm , fill="Class", facet_grid="Phylum~Location") + theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))
p2 <- plot_bar(ps_ob.me , fill="Class", facet_grid="Phylum~Location") + theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))
p3 <- plot_bar(ps_ob.lt , fill="Class", facet_grid="Phylum~Location") + theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 6))
    
# combine plots
grid.arrange(p1, p2, p3, nrow = 2)
  
# garbage cleaning
rm(ps_ob, ps_ob.lt, ps_ob.me, ps_ob.mm, p1, p2, p3 )
rm(ps_ob, envir=globalenv())

}
```
Kind regards,

Paul

**Comment by macrobiotus** [comment]
Hi Paul,

check this out as well - ```subset_taxa()``` does look in the Global Environment almost certainly, when called from within functions:

```
# CAUTION: Subset object to different phyla, clean each table, return list 
IsolateTaxa <- function(ps, level = c("Superphylum", "Phylum", "Class", "Order", "Family", "Genus", "Species")){

  # Initialize function - REQIRES GARBAGE COLLECTION!
  message(paste("Check Garbage Collection after this step. Multiple objects / variables are being written to global Environment"))
  assign("ps_ob", ps, envir=globalenv())
    
  # tax table index number corresponding to specified string
  level.index <- which(colnames(tax_table(ps_ob)) == level)
    
  # vector with unique taxa at specifed level
  unq.taxa.lev <- c(unique(tax_table(ps_ob)[,which(colnames(tax_table(ps_ob)) == level)]))
    
  # initialize list (length + 1) to carry through one not - subsetted object
  ps.list <- vector("list", length(unq.taxa.lev) + 1)
        
  # name list components with "All taxa" + taxa names in taxa vector
  names(ps.list) <- c(unq.taxa.lev, "All_Taxa" )
  
  # store complete object at list position 1
  ps.list[[length(unq.taxa.lev) + 1]] <- RmZeroCounts(ps_ob)
  
  #stuff to do the number of times that unq.taxa.lev is long
  for(i in 1:length(unq.taxa.lev)){
     # print the taxon string that is needed for pruning OTU table
    message(paste("Subsetting to",level, unq.taxa.lev[i]))
   
    # working around subset_taxa() 1/2
    assign("level.index", level.index, envir=globalenv())
    assign("unq.taxa.lev", unq.taxa.lev[i], envir=globalenv())
    
    # subset the OTU table of the input phyloseq object and store in list after the first item
    ps.list[[i]] <- RmZeroCounts(subset_taxa(ps_ob, tax_table(ps_ob)[,level.index] == unq.taxa.lev))
    
    # working around subset_taxa() 2/2
    rm("level.index", envir=globalenv())
    rm("unq.taxa.lev", envir=globalenv())
    
    }
  
  # Finishing up
  results <- ps.list
  
  # Garbage collection after testing
  rm(level, level.index, unq.taxa.lev, ps.list, i)
  rm(ps_ob, envir=globalenv())
  
  return(results)
  
}

# Apply function
PhySeqList <-  IsolateTaxa(ps.merged, "Phylum") 

# check results
lapply(PhySeqList, FUN=tax_table)
lapply(PhySeqList, FUN=ntaxa)
lapply(PhySeqList, FUN=otu_table)
lapply(PhySeqList, FUN=sample_data)

```

Kind regards,

Paul

**Comment by macrobiotus** [comment]
On top of this the Environment handling appears to be different in Rstudio and RGui. I don't know what going on anymore. Giving up. I use the work around now anyways, perhaps my code above is helpful. Thanks.

**Comment by joey711** [comment]
@macrobiotus 

Sorry for the late reply. In general `subset_*` and `subset` family functions in R are dangerous for including within functions. I've actually been recommended by R Core to use more explicit (but less elegant) `"["` methods for developing extraction methods in packages because of this issue.

You are correct it is a namespace issue, and it does have to do with the timing of evaluation of the expression argument passed to `subset` by `subset_samples`. The recommended approach to building functions or extensions to phyloseq that include an extraction step would be `prune_samples` or `prune_taxa`. These typically require an extra line of code, but don't suffer from namespace ambiguity.

Hope that helps. Sorry for the confusion. `base::subset` and `phyloseq::subset_samples` are intended to be top-level user interactive functions, rather than lower-level functions for building on. There might be a nice fix using an explicit `env` pass, but I haven't had the time to track it down, and I'm discouraged to try given the recommendation regarding `subset` from R Core. Let me know if there is a more precise feature request that could be adopted in phyloseq.

Thanks for your feedback, the code example, and your interest in phyloseq!

joey

**Comment by macrobiotus** [comment]
Hi Paul,

I can see your point, but at the same time I am also a little bit disappointed in the solution you offer. Anyways, the package is very useful and I would not want to complain. I would like to suggest though that the limitations of the subset_phyloseq functions are more highlighted in the documentation, because it was really difficult to find out  that the function seemingly does not comply with the R conventions and could in fact introduce serious errors in analyses if used improperly (and without knowing). Or you could perhaps (I don't how how) allow its use only in the global environment then.

Kind regards,

Paul
