### ISSUE TITLE
Plotting Barchart Error

### ISSUE THREAD

**Issue by locon833** [joey711/phyloseq#490]
I am trying to make bar charts of my data for specific orders. I have used this command previously and it worked, generating the plots that I wanted. I am trying to recreate these same plots but am now getting an error message. 

Here are the commands:
>Lauren.Vibrio<- subset_taxa(Lauren_data_merged, Order=="Vibrionales")
> plot_bar(Lauren.Vibrio)
Error in order(mdf$Abundance, decreasing = TRUE) : 
  argument 1 is not a vector

Any help would be appreciated

**Comment by michberr** [comment]
Hi Lauren,

I actually just submitted a Pull Request to fix this issue. https://github.com/joey711/phyloseq/pull/489

You likely have the package reshape loaded instead of reshape2. Simply unload the package and try again. 

detach(package:reshape)

**Comment by joey711** [comment]
This issue should now be fixed in vers `1.13.3+`. Thanks @michberr for the diagnosis, PR, and workaround for users that don't want to install the devel version. It's a shame any packages still depend on the original (slow) reshape package. 

Will close for now.
