### ISSUE TITLE
Creating category for less abundant taxa for use with plot_bar

### ISSUE THREAD

**Issue by Nick243** [joey711/phyloseq#494]
Hello,

I am new to the use of phyloseq and was wondering how I might go about adding a "new taxa" group to represent "less abundant taxa" when using the plot_bar function. For example, I would like to generate a plot showing the relative abundance for the top 20 genera across levels of a sample variable, but to have the plot contain an additional genus-level classification representing the aggregation of all less abundant genera (all those not in the top 20).  I have been able to work through some examples to get to here:

x1 <-tax_glom(x, "Genus" ))                                                    #glom to genus-level
(x2 = merge_samples(x1, "Partition"))                                     #merge samples by sample variable 
TopNOTUs <- names(sort(taxa_sums(x2), TRUE)[1:20])        #generate list of top 20 OTUs
x3 = transform_sample_counts(x2, function(x) x/sum(x))        #generate rel abundance by group
x4 <- prune_taxa(TopNOTUs, x3)                                            #prune less abundant taxa
plot_bar(x4, fill="Genus")                                                          #plot bar chart

However, I would like to modify this to add an additional single category representing all the other less abundant genera so that the relative abundances for each level of the variable Partition sum to 1 (100%). I looked through the forum and tutorials (as I am sure I am missing something quite simple here), but was unable to resolve the issue (apologies if this has already been addressed and thanks in advance for pointing me to the answer).

It would also be nice to be able to use the plot_bar function without pruning the taxa, but to restrict the legend to just showing the top 20 or so genera; however, I was unable to figure out as well.

Thanks in advance for any thoughts or direction.

**Comment by audy** [comment]
I recently had to do this. As far as I know, there isn't a native Phyloseq way of doing this. My approach was to "melt" the Phyloseq object into a `data.frame` and rename all of the taxa below 1% as "remainder."

Here is an example using the GlobalPatterns dataset. I had to use the `plyr` package to calculate the median relative abundance of each Phylum in the dataset.

```S
library(ggplot2)
library(plyr)
library(phyloseq)

data(GlobalPatterns)

# get abundance in %
phy <- transform_sample_counts(GlobalPatterns, function(x) x/sum(x))

# agglomerate taxxa
glom <- tax_glom(phy, taxrank = 'Phylum')

# create dataframe from phyloseq object
dat <- psmelt(glom)

# convert Phylum to a character vector from a factor because R
dat$Phylum <- as.character(dat$Phylum)

# group dataframe by Phylum, calculate median rel. abundance
medians <- ddply(dat, ~Phylum, function(x) c(median=median(x$Abundance)))

# find Phyla whose rel. abund. is less than 1%
remainder <- medians[medians$median <= 0.01,]$Phylum

# change their name to "Remainder"
dat[dat$Phylum %in% remainder,]$Phylum <- 'Remainder'

# boxplot
ggplot(dat,
       aes(x=Phylum,
           y=Abundance)) + geom_boxplot() + coord_flip()
```

@joey711 maybe it would be useful to add this feature via making it possible to agglomerate taxa using a function in `tax_glom`. Forgive my ignorance if this is already possible :wink:.

**Comment by Nick243** [comment]
Audy,

Thanks for the quick and very helpful reply!  I was able to use what you sent to generate the stacked bar graph by sample group using the following code:

# agglomerate taxa
y1 <- tax_glom(y, taxrank = 'Genus')              

# merge samples on sample variable of interest
(y2 = merge_samples(y1, "Partition"))

#get abundance in %
y3 <- transform_sample_counts(y2, function(x) x/sum(x))

# create dataframe from phyloseq object and convert to character
y4 <- psmelt(y3)
y4$Genus <- as.character(y4$Genus)

#rename genera with < 1% abundance (to have represented as single group in plot) 
y4$Genus[y4$Abundance < 0.01] <- "Genera < 1% abund."

#set color palette to accommodate the number of genera 
colourCount = length(unique(y4$Genus))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

#plot   
p <- ggplot(data=y4, aes(x=Sample, y=Abundance, fill=Genus))  
p +  geom_bar(aes(), stat="identity", position="stack") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position="bottom") + guides(fill=guide_legend(nrow=5))


This gave me what I was looking for. Agreed that the box plot may often be a better choice.

**Comment by joey711** [comment]
The original example to address this oft-asked feature request is shown in the [Restroom Biogeography Tutorial](http://joey711.github.io/phyloseq-demo/Restroom-Biogeography). Unfortunately the old QIIME server is down for ever, so the tutorial data download needs to be updated to include the Qiita REST-API, whenever that becomes available.

I like @audy 's example, but I've been falling in love with data.table recently. Here is a mod of that for data.table.

```S
library(ggplot2)
library(phyloseq)
library(data.table)
data(GlobalPatterns)
# Remove OTUs not 3 greater than 3
keepTaxa = apply(X = as(otu_table(GlobalPatterns), "matrix") > 3L,
                 MARGIN = 1, FUN = sum) >= 3L
phy = prune_taxa(keepTaxa, GlobalPatterns)
# get abundance in %
phy <- transform_sample_counts(phy, function(x) x/sum(x))
# agglomerate taxa
glom <- tax_glom(phy, taxrank = 'Phylum')
# create dataframe from phyloseq object
dat <- data.table(psmelt(glom))
# convert Phylum to a character vector from a factor because R
dat$Phylum <- as.character(dat$Phylum)
# group dataframe by Phylum, calculate median rel. abundance
dat[, median := median(Abundance, na.rm = TRUE), 
    by = "Phylum"]
# Change name to remainder of Phylum less than 1%
dat[(median <= 0.01), Phylum := "Remainder"]
# boxplot
ggplot(dat[Abundance > 0],
       aes(x=Phylum,
           y=Abundance)) + 
  geom_boxplot() + 
  coord_flip() +
  scale_y_log10()
```

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/841437/8343367/54873924-1a89-11e5-86b9-dcdc1cf67c95.png)

This issue seems solved. I will close for now.

@audy your `tax_glom` mod sounds like a feature request suitable for another issue. If I understand correctly, you're asking to expose the agglomeration to a user-defined function, probably with the (current) `sum` as default. Am I close?

**Comment by joey711** [comment]
https://github.com/joey711/phyloseq/issues/442

**Comment by yogeshgupt** [comment]
> I recently had to do this. As far as I know, there isn't a native Phyloseq way of doing this. My approach was to "melt" the Phyloseq object into a `data.frame` and rename all of the taxa below 1% as "remainder."
> 
> Here is an example using the GlobalPatterns dataset. I had to use the `plyr` package to calculate the median relative abundance of each Phylum in the dataset.
> 
> ```m68k
> library(ggplot2)
> library(plyr)
> library(phyloseq)
> 
> data(GlobalPatterns)
> 
> # get abundance in %
> phy <- transform_sample_counts(GlobalPatterns, function(x) x/sum(x))
> 
> # agglomerate taxa
> glom <- tax_glom(phy, taxrank = 'Phylum')
> 
> # create dataframe from phyloseq object
> dat <- psmelt(glom)
> 
> # convert Phylum to a character vector from a factor because R
> dat$Phylum <- as.character(dat$Phylum)
> 
> # group dataframe by Phylum, calculate median rel. abundance
> medians <- ddply(dat, ~Phylum, function(x) c(median=median(x$Abundance)))
> 
> # find Phyla whose rel. abund. is less than 1%
> remainder <- medians[medians$median <= 0.01,]$Phylum
> 
> # change their name to "Remainder"
> dat[dat$Phylum %in% remainder,]$Phylum <- 'Remainder'
> 
> # boxplot
> ggplot(dat,
>        aes(x=Phylum,
>            y=Abundance)) + geom_boxplot() + coord_flip()
> ```
> 
> @joey711 maybe it would be useful to add this feature via making it possible to agglomerate taxa using a function in `tax_glom`. Forgive my ignorance if this is already possible .
> 
> edit: @Nick243 I just noticed you wanted a bar-graph instead of a boxplot but boxplots might be better for you as they convey the distribution of abundance. Let me know if you still want a bar graph and I can adapt my example.

Could you please advise how we can also write the dat  object relative abundance with phyla level taxonomy?
Many thanks
