### ISSUE TITLE
levels not found in sample_data (but they are...?)

### ISSUE THREAD

**Issue by bedemickan** [joey711/phyloseq#498]
OK, so I imported BIOM (with metadata included) from mother. 

I have 6 samples by 3 sample variables.

>	head(sample_data(e3fungiR))						
Sample	Data:	[6	samples	by	3	sample	variables]:
	water	substrate	mass				
11H10RE.Ie3F	ww	hyphae	10				
11R0.5RE.Ie3F	ww	root	0.5				
11S0.5RE.Ie3F	ww	soil	0.5				
16H100GP.Ie3F	ww	hyphae	100				
16H10GP.Ie3F	ws	hyphae	10				
16R0.5GP.Ie3F	ws	root	0.5				

but when I want to find levels none of my variables work, crap :(

> levels(sample_data(e3fungi)$water)
NULL

ANy idea how I can get my levels back???

Cheers,

Bede

Any help would be greatly appreciated - it should be an easy on hey?

**Comment by zachcp** [comment]
Could be (1) you need to convert to data frame or (2) it could be loss of factor (factor->string).

```
#if (1) try:
df  <- as.data.frame(sample_data(e3fungi))
levels(df$water)

#if (2) try:
levels(as.factor(sample_data(e3fungi)$water))

```

**Comment by bedemickan** [comment]
Thanks mate I appreciate this - you gain a beer credit🍻
