### ISSUE TITLE
error from import_biom

### ISSUE THREAD

**Issue by jiarong** [joey711/phyloseq#499]
I have a biom file from make.biom following suggesions in https://github.com/joey711/phyloseq/issues/245, and there is an error when I do import_biom.
Error in otu_table(as(biom_data(x), "matrix"), taxa_are_rows = TRUE) : 
  error in evaluating the argument 'object' in selecting a method for function 'otu_table': Error in .fixupDimnames(value) : could not find function "lengths"

I've got around this problem by using mothur_shared_file and mothur_constaxonomy_file.

**Comment by joey711** [comment]
This should be resolved by the switch to *biomformat* in the next package update. 

Will close for now.

In the future, please post a reproducible example, sharing the data if necessary. Otherwise it is very difficult to diagnose if/where there is a problem.
