### ISSUE TITLE
import_biom error 

### ISSUE THREAD

**Issue by DeniRibicic** [joey711/phyloseq#500]
I have a problem when importing a biom file. I'm always getting the same error message when running this command (no matter what reference database I use in Qiime ): 

import_biom(biomfile, treefile, parseFunction = parse_taxonomy_default())

Error: 

Error in gsub("^[[:space:]]{1,}", "", char.vec) : 
  argument "char.vec" is missing, with no default

Anyone knows what this means?

Thanks,
Deni

**Comment by joey711** [comment]
Hard to diagnose without a file. 
- Can you provide a (preferably small) file that gives that error?
- Did you try importing with out providing the other file?
- What version of the biom-format is this file?

**Comment by DeniRibicic** [comment]
Hi again, 

I'm actually new to R, the file is big and I don't know how to make it smaller :/. However, when I import just biom file it works!. The biom file was created with Qiime 1.8.0.
Anyways, I managed to import all the necessary data with import_qiime command.

Deni

**Comment by joey711** [comment]
Great!
