### ISSUE TITLE
Error with biom file import

### ISSUE THREAD

**Issue by kbrann** [joey711/phyloseq#503]
Hello, I am using phyloseq version 1.12.2
I am just trying to import a biom file created by QIIME. Have imported other biom files with no error.

Error in otu_table(as(biom_data(x), "matrix"), taxa_are_rows = TRUE) : 
  error in evaluating the argument 'object' in selecting a method for function 'otu_table': Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

Thanks!

**Comment by kbrann** [comment]
I see that maybe it is a QIIME issue from problem #443 even though it is not the same error. I will try the suggestions listed in that forum to see if any of them work.

**Comment by joey711** [comment]
Try the beta version of the "biomformat" package that @nosson and I have posted.

Otherwise, I'm not sure how to diagnose this issue without further information or a reproducible example...
