### ISSUE TITLE
plot_tree distance method

### ISSUE THREAD

**Issue by ceya** [joey711/phyloseq#505]
Hi,
I've a beginner question on plot_tree. When making trees with ggplot there are options of different distance methods. Is there a similar argument for that in plot_tree? Or how do I select different distance methods for trees?

Thanks!

**Comment by joey711** [comment]
### "When making trees with ggplot there are options of different distance methods."

I'm not aware of a tree-drawing function in ggplot2. To what function(s) are you referring?

### "Is there a similar argument for that in plot_tree?"

No. `plot_tree` is showing an already-calculated tree that you have stored inside a "phyloseq" object with the rest of your microbiome data. Its job is to render the tree and some aspect(s) of that data that you select.

### "Or how do I select different distance methods for trees?"

Unless you are referring to UniFrac, w-UniFrac, or DPCoA distances, this is not done with phyloseq. Tree calculations must be done elsewhere. Too many avenues to be worth listing here. phyloseq can import Newick or Nexus format via `read_tree`. 

If you meant a "tree-based microbiome distance", then you probably meant *weighted UniFrac*. See phyloseq's `distance` function. There are lots of documentation pages available for this function and what you might do with the results.

Cheers
