### ISSUE TITLE
Help with changing an integer to factor

### ISSUE THREAD

**Issue by moyegunle** [joey711/phyloseq#506]
I definitely think my issue is minor but since Ive spent a whole week on this - I have to ask for help or at least point my to another published issue I can reference.
Basically, I want to change an integer variable called group (with values 0,1,2) to a factor with 3 levels within a phyloseq item ( i have not melted it into a data frame yet).

>levels(A$group) <- c("low", "medium", "high")
Error in `*tmp*`$group : $ operator not defined for this S4 class

OR when I try

> studygroup <- getVariable(A, "group") %in% c(0, 1, 2), c("low", "medium", "high")
Error: unexpected ',' in "studygroup <- getVariable(A, "group") %in% c(0, 1, 2),"

I might have gotten the syntax all wrong.........
This step is important to me because I would like to create richness plots that will not have 0,1,2  values but low, medium and high 
 
p <- plot_richness(A,  "group","sampletype")
(p <- p + geom_boxplot(data = p$data, aes(x = group, y = value, color = NULL), 
                       alpha = 0.1))

Sorry if too basic.
I am guessing it is because I have not melted the phyloseq object into a dataframe.
If I do melt it, can I change in back to a phyloseq object?

Thanks!

**Comment by benjjneb** [comment]
Try: levels(sample_data(A)$group) <- c("low", "medium", "high")

**Comment by moyegunle** [comment]
Thanks a lot!!!

Now how do I  view these labels/levels on the plot such that i dont see 0, 1  or 2 but rather low medium high.
