### ISSUE TITLE
drop specific variables from faceted plot_richness plots

### ISSUE THREAD

**Issue by shandley** [joey711/phyloseq#507]
Hello phyloseq community,

I was wondering if there was a way to eliminate unused factors for specific facets of a facet_grid. Specifically from plot_richness. I believe in base ggplot of these types of graphs you just use drop=TRUE, but I am having trouble getting that to work with my data. 

The code I am using is

```plot_richness(closed, "Condition", measures="Shannon") + facet_grid(~Month, scale="fixed", drop=TRUE)```

phyloseq version 1.10.0

And I am trying to remove the empty "Controller", "Protected" and "Unchallenged" from the ARD facet.

![image](https://cloud.githubusercontent.com/assets/660111/8916347/752211a8-3470-11e5-9934-8524ea2ff82e.png)

Any suggestions you might have would be great! Getting this to work with facet_grid instead of plotting each one separately would save a lot of time in my workflow.

Thanks!

**Comment by joey711** [comment]
Hi @shandley 

I think you just need to set the horizontal scale to "free".

```S
plot_richness(closed, "Condition", measures="Shannon") + 
    facet_grid(~Month, scale="free_x", drop=TRUE)
```

In ggplot2 having a fixed facet scale requires that the scales are the same in every panel. Alternatively you can let panels collapse to the in-panel data with `"free"` (both axes), `"free_x"`, or `"free_y"`.

Hope that helps!

I'll close for now, but please confirm that it works (and I'll re-open if not).

joey

**Comment by shandley** [comment]
Brilliant! Works just as you say.

Thanks Joey!
