### ISSUE TITLE
microbio_me_qiime()

### ISSUE THREAD

**Issue by mendessoares** [joey711/phyloseq#509]
Hi. I have tried repeatedly to download files from the qitta using the above command and was never able to establish a connection with the server. I was wondering if I am the problem ( I may be missing something) or the server is the problem? 
Here's the info:

> GlobalPatterns = microbio_me_qiime(721) #or 722
trying URL 'ftp://thebeast.colorado.edu/pub/QIIME_DB_Public_Studies/study_721_split_library_seqs_and_mapping.zip'
downloaded 0 bytes

Error in download.file(zipftp, zipfile, ...) : 
    Couldn't connect to server

And here is the system information:
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          2.1                         
year           2015                        
month          06                          
day            18                          
svn rev        68531                       
language       R                           
version.string R version 3.2.1 (2015-06-18)
nickname       World-Famous Astronaut      

Thanks.

**Comment by joey711** [comment]
FYI, this is basically a duplicate issue to a previous question regarding the "Restroom Biogeography" tutorial

https://github.com/joey711/phyloseq/issues/491

Short answer: There is no Qiita API yet, at least not that I'm aware of. The QIIME-DB server based at University of Colorado Boulder is permanently down. In this sense, the `microbio_me_qiime` function should be considered deprecated. 

However, a user can manually download files from Qiita in biom format, and then import them into phyloseq.

Please post further comments on the earlier issue.

Thanks!

**Comment by mendessoares** [comment]
Awesome! Thanks!
