### ISSUE TITLE
Phyloseq 1.12.1 - Component sample names do not match.

### ISSUE THREAD

**Issue by bioinfonm** [joey711/phyloseq#513]
I am using phyloseq 1.12.1 under R 3.2.2 with biom files generated from QIIME 1.9.0. I was running phyloseq 1.10 with the same mapping and biom file but after the upgrade when every I did this:

Command line
**biom convert -i denovo_sumaclust.biom -o fixed_bat_bacteria.biom --table-type="OTU table" --to-json**

In Phyloseq
**phylo <- merge_phyloseq(phylo,map)**

I get: 
**Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component sample names do not match.
 Try sample_names()**

I ran sample_names and I am currently comparing the names in the biom file to the names in the mapping file but haven't found any differences yet. 

Was this a change from 1.10 to 1.12.1 that phyloseq doesn't except mismatches between the mapping and the biom file. I noticed this on another biom file I tried on Sunday. 

Thanks!
ara

**Comment by bioinfonm** [comment]
I just ran a diff command on the sample names from the biom file and the sample names from the mapping file and there were no differences.

**Comment by bioinfonm** [comment]
Solve it! I had opened the mapping file into LibreOffice and saved it. LibreOffice defaults to a sep = ','.

Note to self don't use LibreOffice to work with the mapping file or do so carefully. 

Sorry.

**Comment by mr2raccoon** [comment]
Hey, could you in more detail describe how you solved it?

I am having a similar issue now. I edited my sampledata in "Libreofficecalc" saved it to ".csv-file". Then I imported it into R and am trying to built a "physeq-object" but it does not work.
