### ISSUE TITLE
reorder samples in sample_data() 

### ISSUE THREAD

**Issue by colinbrislawn** [joey711/phyloseq#518]
Hello Joey,

I'm looking for a way to sort or reorder the samples I have in a phyloseq object. For example:
``` R
> sample_data(filtered)[1:5,c(4,7,8)]
Sample Data:        [5 samples by 3 sample variables]:
              PATIENT_NUMBER N_TIMEPOINTS TIMEPOINT_NUMBER
1115600180.L4            206            8                7
1015600162.L2            908            6                4
1015600260.L2            206            8                3
1015600195.L2            471            7                5
1115600036.L2            206            8                5
```

I would like to sort / reorder these samples by TIMEPOINT_NUMBER. I understand that order does not usually matter, but I just discovered that `geom_path` connects points based on the order of samples in your data table. To connect my timepoints in order, my samples must be in order.

Thanks Joey! Any advice would be appreciated!

**Comment by joey711** [comment]
I have a better solution.

If you have a ggplot object created from a misordered table, the best thing to do would simply be to **reorder the table in the ggplot object**.

```S
pTime = ggplot(...) + ...
print(pTime)
# Oh no, the table wasn't ordered
library("data.table")
newtab = data.table(pTime$data)
setorder(newtab, TIMEPOINT_NUMBER)
pTime$data <- newtab
print(pTime)
# Yay it worked!
```

**Comment by colinbrislawn** [comment]
Excellent alternative!

**Comment by Maya0801** [comment]
Hi, 
I am also looking  for a way to sort or reorder the samples. 
I tried what you suggested above, but it didn't work, I didn't get any errors, however the bar chart didn't change at all. 

here are the commands I ran for the plot, and reordering:

# Plot 
>bar_plot = ggplot(TS3_phylum, aes(x = Description, y = Abundance, fill = Phylum)) + 
    geom_bar(stat = "identity") +
    # Remove x axis title
    theme(axis.title.x = element_blank(),
          axis.text.x = element_text(angle=45,hjust = 1, vjust=1)) + 
    #
    guides(fill = guide_legend(reverse = TRUE, keywidth = 1, keyheight = 1)) +
    ylab("Relative Abundance (Phyla > 2%) \n") +
    ggtitle("Phylum Composition of Theonella swinhoei \n Bacterial Communities by collection time") 

print(bar_plot)

# Reorder 
>library("data.table")
>newtab = data.table(bar_plot$data)
>setorder(newtab, order)
>bar_plot$data <- newtab
>print(bar_plot)

Thanks,

Maya

**Comment by bashma** [comment]
I have a similar problem. In order to perform a paired t-test in multtest I need the samples to be in a certain order (by subjectID). 
```
pairttest <- mt(ps, "TimePoint", test="paart")
```
I get the following error:
```
Some errors in specifying classlabel for the paired t test for the block 1 located at ( 1 2 )
 your classlabel= 1 
```

 I tried:
```
sample_data(ps) <- sample_data(ps)[order(sample_data(ps)$subjectID), ]
``` 
which does not reorder the sample data although 
```
sample_data(ps)[order(sample_data(ps)$subjectID), ]
``` 
gives me the right order.

I also tried to order the sample data file before creating the phyloseq object, but samples are still disordered in the resulting ps-object. I'm assuming the order is based on the OTU/RSV-table.

any suggestions? Thank you

**Comment by bashma** [comment]
I have found a work around. Instead of reordering the sample_data() you just need to reorder the otu_table()
```
map <- read.delim("mapping file.txt", stringsAsFactors = FALSE) 

all(rownames(seqtab.nochim) %in% map$X.SampleID)

map <- map[order(map$subjectID)]
rownames(map) <- map$X.SampleID
order <- rownames(map)

all <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = FALSE), 
                tax_table(taxa.species), sample_data(map))

#Reorder ps for paired analysis
otu_table(all) <- otu_table(all)[order, ]
```

**Comment by LaserKate** [comment]
You can also try using the ordered function:
library("data.table")
newtab = data.table(p$data)
newtab$Sample <- ordered(newtab$Sample, 
                levels = c("1","2","3","4","5","15","16","17","6","7","8","10","11","12","13","14","18","19","20"))
p$data <- newtab
print(p)

**Comment by GeoMicroSoares** [comment]
Hello there,

How about if I have depths as x axis? How can I order plot_bar()?

I have the following as part of my medadata:
```
> sample_data(ps)$Depth
 [1] 112.9  114.7  109.5  109    405    296    261    145    1063   140    1044.9 327    585   
[14] 145    324    321.96 576.26 411.6  517.76 1047.1 140    261    327    1045.5 1064.4 1042.3
[27] 1064.4 544.5  314.6  1045.5 371.65 472.11 419.89 730    730    730    730    730    730   
[40] 94     362    2383   973    1264   884    884    973    4850   4850   800    4850   800   
[53] 1700   222.63 231.83 230.28 229.8  217.13 220.83 180    180    2260   1820   2300   500   
[66] 2260   645.5  393    809    1135   857.5  535   
54 Levels: 1042.3 1044.9 1045.5 1047.1 1063 1064.4 109 109.5 112.9 1135 114.7 1264 140 ... 973
```
However, when plotting the axis axis always comes up as follows:
![image](https://user-images.githubusercontent.com/14272488/33550811-2b86d650-d8e7-11e7-95e6-d4a81eb31b41.png)
i.e. ordered, but not as I want it to (smallest to largest numbers).

What I'm using:
```
biom <- import_biom(biom_file)
metadata <- import_qiime_sample_data(map_file)
tax_table(biom) <- tax_table(biom)[,1:7]
colnames(tax_table(biom)) = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")
ps <- phyloseq(otu_table(biom),
               sample_data(metadata),
               tax_table(biom))
ps.f = subset_samples(ps, Depth != "missing")
ps.f.alpha = subset_taxa(ps.f, Class=="Alphaproteobacteria")

ps.f.plot<-plot_bar(ps.f.alpha, 
                                      fill="Order", x="Depth") + 
  geom_bar(aes(color=Order, fill=Order), 
           stat="identity", position="stack")

ps.f.plot
```

Because this can't be factorised I'm not sure what to do as the usual strategies for reordering axes are directed discrete variables. Any solution you see here @colinbrislawn @joey711 @benjjneb @LaserKate ?

Thanks in advance!

**Comment by colinbrislawn** [comment]
Hello @GeoMicroSoares 

My first thought is that `$depth` should be treated as a number, not a factor. How does the graph look when you convert this factor to a number? Your code might looks like this:

```
# Pull output metadata
meta <- sample_data(ps)
# convert factor to numer
meta$Depth <- as.numeric(as.character(meta$Depth))
# Put new metadata back into ps object
sample_data(ps) <- meta

# Now graph ps like before:
...
```

**Comment by GeoMicroSoares** [comment]
Thanks @colinbrislawn that did work!

**Comment by Arrowessee** [comment]
I had the same problem with @GeoMicroSoares but my numbers are not consecutive and has varied value gaps. Is there any way I can still arrange this in increasing order without manually doing level_order?

Thank you!

**Comment by colinbrislawn** [comment]
This is a classic R question about how to code metadata values!

Because we are in the future, we can now use [the Tidyverse](https://www.tidyverse.org/) for this step.

If the column is a number: https://readr.tidyverse.org/reference/parse_number.html
If this column is a factor (ordered or not!): https://forcats.tidyverse.org/reference/as_factor.html

**Comment by Arrowessee** [comment]
Thanks @colinbrislawn! It did not work for my current samples but I learned a new technique.
