### ISSUE TITLE
Import biome file 

### ISSUE THREAD

**Issue by sungwoobae** [joey711/phyloseq#520]
I have used phyloseq for my data analysis. It is a great tool for analyzing metadata set from qiime. However, after i upgrade newer version of qiime, i encounter the error when i tried to import biom file.

 file<-import_biom("otu_table.biom")
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input

it was okay before. I am not sure whether new version of qiime would not be compatible with phyloseq. I test old biom file from qiime 1.8

**Comment by joey711** [comment]
This issue has been re-posted several times. Please see one of the originals:

https://github.com/joey711/phyloseq/issues/443

In short, QIIME and BIOM changed their underlying file format from JSON to HDF5. The HDF5 support is not included in my [biom package](https://cran.r-project.org/web/packages/biom/index.html) on which phyloseq depends. Joe Paulson and I are working on a new BioConductor package that will support both style formats, with some computational improvements to boot. The development version of phyloseq will depend on this soon, once it is available. In the short run, see the previous issue posts for several workarounds.

Thanks!
