### ISSUE TITLE
import_biom discards OTUs from QIIME generated biom

### ISSUE THREAD

**Issue by cw808** [joey711/phyloseq#521]
Hi Joey,

I am working on completing a data summary of my otu table and was comparing the results between QIIME and phyloseq and there are some concerning differences.  Using summarize biom-table in QIIME show 150 samples with 19399 OTUs and 651,764 total counts.  The same biom imported into phyloseq using:

qiimedata <- import_biom(otufile,trefile,rs_file,parseFunction = parse_taxonomy_greengenes)

results in 150 samples with 4900 OTUs and 520,526 total counts.  Noticing this difference I looked into what was happening and discovered that importing the biom with phyloseq doesn't import OTUs (and their counts) that do not have a numeric OTU ID.

The OTUs were picked in QIIME using open reference OTU picking and the clustering in the de novo step following closed reference picking assigns OTUs with IDs beginning with New.ReferenceOTU#### or New.CleanUp.ReferenceOTU####.  When looking at the biom file as a txt file the number of OTUs with strictly a numeric ID is 4900 and the New.Reference and New.CleanUp.Reference account for the 14,499 OTU difference between the QIIME summary and phyloseq.  I should also note that when looking at the taxonomy assignments these OTUs do have taxonomy assigned.

Based on this I have a couple questions: 1) Is there a reason these OTUs should not be included in the analysis and that is why phyloseq discards them?  2)  If they shouldn't be excluded is phyloseq discarding them because of non-numeric ID and is it reasonable to remove the New.ReferenceOTU and New.CleanUp.ReferenceOTU to have a numeric ID or will that create other problems?

I appreciate any help on this issue.

Thanks,
Chuck

**Comment by joey711** [comment]
Hi Chuck,

This problem has been re-posted several times now in previous issues. I will be sure to add it to the upcoming phyloseq-FAQ.

In short, one of the OTU-describing files you've imported has many fewer OTUs than the others. Sometimes this is the tree, sometimes the OTU table. One of the features of phyloseq is that it will automatically omit indices (samples or taxa) that are not present in all data components. 

To test this for yourself, you can simply import the biom file by itself. In that case, phyloseq would have no reason to omit any entries. Another thing to note, QIIME used to also include taxa that sum to zero counts across your experiment.

As a side note, many of the 19,000 OTUs are probably just noise resulting from PCR + sequencing errors, and further filtering is probably appropriate.

Hope that helps. I will close for now. Feel free to review previously-closed issues on this topic, and also to post back here with any followup and to let others know if this addressed your concern. 

Cheers

joey

**Comment by CarlyRae** [comment]
Hi Chuck,

I would bet that it is most likely coming from the tree file you generated in QIIME. But, is a result of the alignment process, that manifests itself when you bring the tree into Phyloseq. Those 150,000 sequences or ~15,000 OTUs are likely failing alignment because as Joey pointed out are most likely noise. See my comment on that here https://github.com/joey711/phyloseq/issues/512#issuecomment-131944988

Carly
