### ISSUE TITLE
colorramppalette function is lost after opening previous Rdata

### ISSUE THREAD

**Issue by ClaireA** [joey711/phyloseq#536]
Hello,

This has happened to me a few times before. If I am using phyloseq right after I start my R session I don't have problems with RColorBrewer, but if I open old Rdata into the same session I get the following error everytime I try to plot anything that requires more than 9 colors:

 In RColorBrewer::brewer.pal(n, pal) :
  n too large, allowed maximum for palette Set1 is 9
Returning the palette you asked for with that many colors

This can be fixed by using colorRamppalette but it can get a bit annoying. Does anyone have suggestions on how to stop from happening again?

Thanks,

Claire

**Comment by michberr** [comment]
Hi Claire,

The colorbrewer palette for Set1 has a maximum of 9 colors available see http://colorbrewer2.org/ . If you want more colors then you will have to choose a different palette. I don't understand how this issue relates to your R session, but if you post a reproducible example of your code then I can try to help. 

Best,
Michelle

**Comment by ClaireA** [comment]
Hi Michelle,
Automatically, phyloseq will plot a ramp of colors of Set1, if for example I use this:
 p = plot_bar(oswachildnobabiesfamily, fill="Family", facet_grid= ~Domain)
p + geom_bar(aes(color=Family, fill=Family), stat="identity", position="stack") 

the plot_bar function seems to have the function colorramppalette built in it.

However, it has happened several times that if I am working on a session and decide to add previous data from a past R session, it will stop ramping the colours and use only 9.

I also just found this posted 4 days ago:

https://github.com/joey711/phyloseq/issues/534

Could it be that they are already planning to fix this before the new release?

Thanks,

Claire

**Comment by michberr** [comment]
Hi Claire,

The plot_bar command makes no explicit reference to colorbrewer or colorramppalette. It is a simple wrapper for ggplot which also translates your phyloseq object into the long format. So it appears you problem is not really a phyloseq problem but more a ggplot or colorbrewer problem. 

Again, if you post a reproducible example of your code as well as your session info it will be easier to diagnose your problem.

**Comment by jeffkimbrel** [comment]
It is possible to get "unlimited" colors from colorbrewer set1 or any of the color palettes:

```
library("ggplot2")
library("RColorBrewer")
palette = colorRampPalette(brewer.pal(9, "Set1")) ## type the palette here ("Blues", "Reds", whatever)

# make some bogus data
data = data.frame(sample(1:200),sample(1:200),as.factor(sample(1:200)))
colnames(data) <- c("X","Y","Z")

# map the color values in palette, be sure to change the x in palette(x) to the number of colors needed
ggplot(data) + 
  geom_point(aes(x=X,y=Y,color=Z),size=10) + 
  scale_color_manual(values = palette(200)) +
  theme_bw() + 
  theme(legend.position = "none") 
```

![palette](https://cloud.githubusercontent.com/assets/10132972/11160588/97b76780-8a20-11e5-9a13-43a4ce414709.png)
