### ISSUE TITLE
Speedup Tax_Glom

### ISSUE THREAD

**Issue by zachcp** [joey711/phyloseq#537]
Hi @joey711,

In response to #517 I have a suggestion on how to handle the OTU merging when merging across something large like an entire Taxonomy class. If we add the taxonomy data to the OTUtable, we can do the split-apply-recombine strategy to calculate all of the merged OTUs. 

The code below shows a better-than 10x speedup over `merge_taxa` for merging the OTU table. it may not end up being quite as fast since the OTUs it returns are not correct. It does NOT output the correct OTU for each taxonomy group. i would expect this to be even faster as the OTU tables get bigger. Is the output simple the most abundant OTU in the group?

 I would appreciate any feedback and if it looks good can prepare a pull request.

thanks,
zach cp

```{r}
library(phyloseq)
data("GlobalPatterns")


#'  Helper Function that will take the OTU Table (as a data.frame()) 
#'  to which column representing taxa has been added.
#'  There is some munging to handle rownames and
#'  the tax column but the basic idea is there.
condenseOTUs <- function(otutable, splitcol) {
  
  #convert tax col to numeric
  # needed to allow colSums to work
  otutable[[splitcol]] <- as.numeric(factor(otutable[[splitcol]], labels=c(1:length(unique(otutable[[splitcol]])))))
  
  # split apply, combine
  splits   <- split(otutable, otutable[[splitcol]])  
  summed   <- Map(colSums, splits)
  summeddf <- Reduce(rbind, summed, init = NULL)

  #get rownames.
  # this needs to be changed to get most abundant OTU if thats what is used elsewhere
  # rightnow it returns the first OTU in the group
  newrownames <- Map(function(x){rownames(x)[[1]]}, splits)
  
  #add back rowname and remove tax column
  rownames(summeddf) <- newrownames
  summeddf[, !colnames(summeddf) %in% c(splitcol)]
}


# setup data. we are going to glob the OTU table based on the Class Taxonomy
GP  <- GlobalPatterns
# the following code directly from tax_glom
CN  <- which( rank_names(GP) %in% "Class" )
tax <- as(access(GP, "tax_table"), "matrix")[, 1:CN, drop=FALSE]
tax <- apply(tax, 1, function(i){paste(i, sep=";_;", collapse=";_;")})
spCliques <- tapply(names(tax), factor(tax), list)

# using merge_taxa: current Phyloseq
ptm <- proc.time()
otab1 <- otu_table(GP)
for( i in names(spCliques)){
  otab1 <- merge_taxa(otab1, spCliques[[i]])
}
proc.time() - ptm

# using Map-Reduce/vectorized
ptm <- proc.time()
otab2 <- data.frame(otu_table(GP))
taxdf <- data.frame(tax)
otab2 <- merge(otab2, taxdf, by = "row.names")
row.names(otab2) <- otab2$Row.names
otab2 <- otab2[ , 2:ncol(otab2)]
otab2 <- condenseOTUs(otab2,"tax")
proc.time() - ptm

#test equivalents
#good
sum(otab1) == sum(otab2)
dim(otab1) == dim(otab2)
sort(rowSums(otab1)) == sort(rowSums(otab2))
sort(colSums(otab1)) == sort(colSums(otab2))

#notgood: need to obtain the correct OTUs
sort(rownames(otab1)) == sort(rownames(otab2))
rownames(otab1) %in% rownames(otab2)


```

I setup two tests using the GP code. Using the current `merge_taxa` i get:
```{r}
# current
 proc.time() - ptm
   user  system elapsed 
  6.864   0.960   7.820 
#vectorized
> proc.time() - ptm
   user  system elapsed 
  0.445   0.101   0.543 
```

**Comment by joey711** [comment]
This does not add an additional dependency to phyloseq, is that correct? We could do a performance trial if you want to compare more carefully with #517 . 

My preference would be to use `data.table` for this and many other internal mechanics in phyloseq, but that will require a large infrastructure rewrite that I don't seem to have time for at the moment.

Happy to push in this or #517  so long as it doesn't break anything and is better in both speed and memory. Feel free to submit a pull and we'll see how it tests out.

Thanks!

**Comment by colinbrislawn** [comment]
Any progress on this? I'd love to see this implemented, as everything else in phyloseq is already so speedy! 
Thank you for building and improving this software.
Colin

**Comment by zachcp** [comment]
Hi @colinbrislawn ,

There is no additional progress on this. This implementation does not check for discrepancies in the taxonomy table and ambiguate up until the lowest common taxonomic group.While that could be done I believe you will lose the speedups I was trying to achieve.

As the issue has been raised before I agree with @joey711  and others that the most significant speedup gains will be switching to data.table. All of the joins and lookups can be made faster.  But I am not much of a data.table guy (at least not yet :) ) so I haven't made the move on that part.  Another caveat about the data.table switch (besides the totally different syntax) is that there are potential changes in behavior. For example I am pretty sure the issue in  https://github.com/joey711/phyloseq/issues/495 was due to a data.table join or data.table index issue but it was difficult to diagnose the source of the error. Maybe aggressive copying before transformations is the answer.   (@joey711, I'll try to test the new code soon.)

**Comment by colinbrislawn** [comment]
Thanks for updating me. It sounds like data.table is the right data structure moving forward.
Which issue tracks the implementation of data.table? Is it #538?

**Comment by zachcp** [comment]
@colinbrislawn As far as I know @joey711 is slowly data.table-ifying everything but there is no master issue that I am aware of. I suppose he would be the best one to answer this.  However, you might like to check out #517 where the major benefits of data.table are enumerated by Reino (@ProfFancyPants )

Reino, Joey, do you think you could agree on the high level data.table implementation - one table vs two or three tables, for example? Once that high level data structure is in place,  we could begin a pure data.table port. Theres got to be a few of us who could then help in porting and testing. For example, I could lend some "spare cycles" to the cause as this would seriously alleviate some of my problems with operations on large datasets.

@ProfFancyPants , in your entry you suggest using a single table. How would that fit the Phyloseq context? It seems to me that the Phyloseq data model does a nice job of separation of concerns :  

1. the OTU Table as the core with **Samples** as columns and **OTUs** as rows. 
2. **Sample** data contain info about the samples 
3. Taxonomy table contain info about the **OTU**s.  

Many of the methods act on one table and then join on the others (eg, subset the OTU table and then plot Species count (tax table) colored by Sample (sample table)). While having the tables merged all the time might save computation time, wouldn't it balloon the memory usage (see phyloseq::psmelt) ? Seems like three tables is the natural fit. If thats the case, is the best way forward to simply replace the three with data.tables,  and then go about fixing the failed tests until the test suite passes (focusing on core methods first?)

thanks,
zach cp

**Comment by colinbrislawn** [comment]
:joy: All this momentum! 

I find the data structure in the original phyloseq paper to be very intuitive, but I appreciate suggestions. 
http://www.plosone.org/article/info:doi/10.1371/journal.pone.0061217.g003/largerimage

**Comment by spholmes** [comment]
Hi there,

My five cents, we want to have several data.tables as we are currently
extending to incorporate
more types of data, but some data will only have a few of the types, so I
am not in favor of the
one table fits all strategy.
Thanks
Susan

On Thu, Mar 24, 2016 at 9:10 AM, zachcp <notifications@github.com> wrote:

> @colinbrislawn <https://github.com/colinbrislawn> As far as I know
> @joey711 <https://github.com/joey711> is slowly data.table-ifying
> everything but there is no master issue that I am aware of. I suppose he
> would be the best one to answer this. However, you might like to check out
> #517 <https://github.com/joey711/phyloseq/issues/517> where the major
> benefits of data.table are enumerated by Reino (@ProfFancyPants
> <https://github.com/ProfFancyPants> )
>
> Reino, Joey, do you think you could agree on the high level data.table
> implementation - one table vs two or three tables, for example? Once that
> high level data structure is in place, we could begin a pure data.table
> port. Theres got to be a few of us who could then help in porting and
> testing. For example, I could lend some "spare cycles" to the cause as this
> would seriously alleviate some of my problems with operations on large
> datasets.
>
> @ProfFancyPants <https://github.com/ProfFancyPants> , in your entry you
> suggest using a single table. How would that fit the Phyloseq context? It
> seems to me that the Phyloseq data model does a nice job of separation of
> concerns :
>
>    1. the OTU Table as the core with *Samples* as columns and *OTUs* as
>    rows.
>    2. *Sample* data contain info about the samples
>    3. Taxonomy table contain info about the *OTU*s.
>
> Many of the methods act on one table and then join on the others (eg,
> subset the OTU table and then plot Species count (tax table) colored by
> Sample (sample table)). While having the tables merged all the time might
> save computation time, wouldn't it balloon the memory usage (see
> phyloseq::psmelt) ? Seems like three tables is the natural fit. If thats
> the case, is the best way forward to simply replace the three with
> data.tables, and then go about fixing the failed tests until the test suite
> passes (focusing on core methods first?)
>
> thanks,
> zach cp
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/537#issuecomment-200905211>
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
I agree with @spholmes on where I'm leaning on this, and @zachcp is correct that a single-table model would balloon up the memory usage if there are a lot of sample variables. Unlikely there are a lot of taxonomic ranks, but imagine we want a data structure extension that also includes data on the taxa? That would have the same "ballooning" effect as with sample variables.

To be clear, aside from very fast and reliable joins, the advantage of switching the OTU table over to data.table would be to represented as a sparse / long-form table indexed by sample and OTU. This would be much more compact for most datasets because the zeroes would not need to be stored. Conversely, it might delay (slightly) any time a matrix is required because you'd have to first expand the long-form back into wide-form (`dcast.data.table`). For some scenarios this might be worth it, and I haven't ruled it out.

This is nice to discuss, and changes that don't completely upend the data structure but improve performance/reliability I favor. Unfortunately, the risk to backward compatibility and reliability here is huge. Thus, for the most part, if we're talking about a significantly different core data class, we're probably talking about a *phyloseq2* -- that is, a separate package. 

All that said, I've built up a lot of experience recently using *data.table* for this purpose, and I like what I see. Implementing it to work in phyloseq will be a lot of work. Happy to hear more.

**Comment by zachcp** [comment]
hey @spholmes, in regards to phyloseq I think your 5 cents approaches a dollar : )  

@joey711 sounds like phyloseq2 is in the works! I agree that its probably easier to start from scratch for big changes like this. If you do start a repo and want a hand/pair-of-eyeballs, please ping me. I am reluctant to hack on phyloseq without a good indicator that its going to be worthwhile/included so if a data.table version of phyloseq represents a new project thats fine - i'll be happy to help if/when.  

Also, I like the storage side of sparse matrices but can potentially see big overheads for distance calculations - especially during the exploratory phase.  These can already take long time and i'm doubtful even data.table can offset that conversion for big matrices.

**Comment by joey711** [comment]
@zachcp well let's not get ahead of ourselves. I don't want to give the impression that there is a phyloseq2 anywhere but a twinkle in my eye. I just meant to convey that such a drastic overhaul of the core data structure would be difficult to implement without sacrificing backward compatibility or alternatively, introducing a lot of unnecessary complexity (if both maintained simultaneously). 

Your original assessment -- that I'm slowly migrating things to *data.table* when it appears appropriate -- is pretty accurate, and in many cases resolves the performance issues. I think this is a better way to go for now than migrating to a single long-form table with a bunch of conventions... which is basically an R in-memory implementation of an unstructured database. 

In any case, I'm very open to hearing/reviewing proposals to improve phyloseq and related workflows, and also get feedback about priorities for future development/maintenance.

**Comment by zachcp** [comment]
@joey711 ok, perhaps that was a bit eager.  as for the original issue I can revisit the taxonomy disambiguation problem and take a look at Reino's data.table solution which I think was ~7-10x faster than mine.
