### ISSUE TITLE
Trouble plotting factor

### ISSUE THREAD

**Issue by beseekay** [joey711/phyloseq#542]
Hi,
I am having a similar problems to #541, but not the same. I was doing the distance tutorial, and just exchanging the enterotype data with my previously loaded phyloseq object, I had run it through the import data and heat map tutorials and was using a subset created there.

This is the script from the tutorial with data and variables changed.

plist <- vector("list", length(dist_methods))
names(plist) = dist_methods
for (i in dist_methods) {
  # Calculate distance matrix
  iDist <- distance(bdcmrp, method = i)
  # Calculate ordination
  iMDS <- ordinate(bdcmrp, "MDS", distance = iDist)
  ## Make plot Don't carry over previous plot (if error, p will be blank)
  p <- NULL
  # Create plot, store as temp variable, p
  p <- plot_ordination(bdcmrp, iMDS, color = "Site", shape = "Species")
  # Add title to each plot
  p <- p + ggtitle(paste("MDS using distance method ", i, sep = ""))
  # Save the graphic to file.
  plist[[i]] = p
}

followed by

df = ldply(plist, function(x) x$data)
names(df)[1] <- "distance"
p = ggplot(df, aes(Axis.1, Axis.2, color = "Site", shape = "Species"))
p = p + geom_point(size = 3, alpha = 0.5)
p = p + facet_wrap(~distance, scales = "free")
p = p + ggtitle("MDS with various distance metrics for soil sample 16s dataset")
p

The data set I am using has the same structure as the enterotype data for the variables I was using, except that site was listed as a integer after importation instead of a factor.

The plot legend, with the second part as shown above, listed Site and Species in quotes, and with single points and the plotted points were all the same. If I took the quotes off in the second function it listed the species, and showed the sites as a scale from 1-3. I then changed the site sample variable to a factor, and tried again, and it was unchanged. I tried renaming the variable levels "Site 1", "Site 2", etc. It then didn't show site in the legend, instead showing sample numbers with one colour each. I reverted the site levels to 1-3, but it is still printing only sample numbers.

When I tried to print out single dm plots, it listed listed sample numbers also, changing the quote status in the plist function, the variable was also not recognized.

 The tutorial data used a factor variable for the color also, so I don't understand what went wrong, any ideas how to fix this?

**Comment by zachcp** [comment]
HI @beseekay ,

I think you have at least two things going on here.

1) `aes` vs `aes_string` see the [ggplot docs](http://docs.ggplot2.org/current/)

```R
#in aes you are mixing column names and strings
p = ggplot(df, aes(Axis.1, Axis.2, color = "Site", shape = "Species"))
# try this instead
p = ggplot(df, aes_string(x="Axis.1", y="Axis.2", color = "Site", shape = "Species"))
# or this
p = ggplot(df, aes(x=Axis.1, y=Axis.2, color = Site, shape = Species))
```

2) numeric vs character. ggplot will interpret numerical columns as continuous and not as categorical.
```R
#convert your numbers to samplenames
df$Site <- as.character(df$Site)
```

There may be other suggestions as well but you would need to provide `df`

good luck,
zach cp

**Comment by joey711** [comment]
I will close as @zachcp seems to address the major issues and there was no follow up. Can re-open if there is further problem, but this looks like standard ggplot2 syntax comprehension.
