### ISSUE TITLE
Quick question - transforming sample counts on a sample by sample basis in PhyloSeq

### ISSUE THREAD

**Issue by dlennon** [joey711/phyloseq#544]
I am interested in filtering out taxa from samples, on a sample by sample basis. I would like to remove taxa with counts of less than 0.001% of the total reads in a sample. In other words, I would like to be able to remove an OTU that falls below this threshold in one sample but keep it in another sample if it is above this threshold. I have seen some options in PhyloSeq that remove taxa across all samples, but I don't think that's what I'm looking for.

Would this achieve my goal?
GPfiltered <- transform_sample_counts(GlobalPatterns, function(x) x>(.001)*(sum(x)), TRUE)

**Comment by zachcp** [comment]
Hi @dlennon,

You can't really do this. The phyloseq otutable is a table and therefore a row/OTU in the table is either there or not. It cannot be there for part of the row and not there for part of the row. 

An exception to this statement  (and not what I believe you are trying to do) is to subset by sample first.  In this case you could take only the OTUs for a sample of interest and then apply the threshold value.

good luck,
zach cp

**Comment by joey711** [comment]
@dlennon 

Yes this is possible. I'm not sure why @zachcp thinks otherwise. Since your criteria is only within-sample, the `transform_sample_counts` function will work just fine. However, your example syntax is a bit off.

Note that you said 0.001%, but then coded 0.001 (which is 0.1%). I assumed the former in the following code.

## Relative Abundance

Transform to proportions and set low proportion values to zero.

```
library("phyloseq"); packageVersion("phyloseq")
data("GlobalPatterns")
filterfun1 = function(x){
  xprop = (x / sum(x))
  xprop[xprop < (1e-5)] <- 0
  return(xprop)
}
GPfiltered <- transform_sample_counts(GlobalPatterns, fun = filterfun1)
```

## Keep the OTU table as counts...

but set low proportion values to zero.
Maybe counter-intuitive, this is a slightly more concise function to define.

```S
library("phyloseq"); packageVersion("phyloseq")
data("GlobalPatterns")
filterfun1 = function(x){
  x[(x / sum(x)) < (1e-5)] <- 0
  return(x)
}
GPfiltered <- transform_sample_counts(GlobalPatterns, fun = filterfun1)
```

**Comment by zachcp** [comment]
@joey711 looks like a misunderstanding. You are setting the values of low abundance OTUs to zero. If thats whats desired, than I happily stand corrected. For some reason I was thinking it was a trickier problem.

**Comment by joey711** [comment]
"filtering" from a sample and "setting to zero" are equivalent. If an OTU ends up being only trivially prevalent, or have a zero-sum across all samples, it can be "filtered" from the OTU table altogether in a following step, like `filter_taxa()`. I can see how it would seem trickier if you were attempting to do OTU filtering (index removal) during the middle of the low-abundance filtering.
