### ISSUE TITLE
Normalisation, negative abundances and distance metrics

### ISSUE THREAD

**Issue by ecologysarah** [joey711/phyloseq#545]
Hi Joey,

I have hit a problem in the 'Waste not, want not' workflow and noticed that the previous GitHub discussions on this particular point eg #470, #492, have gone cold.

Reading 'Waste not, want not' has convinced me against rarefying data, and I have been trying to get to grips with the DESeq normalisation based on your S1 script in the paper. My aim is to get a transformed OTU table that can be fed into NMDS/PERMANOVA. The problem I have hit is that the transformed data has negative values that then interfere with the distance metrics. Did you encounter this with your simulations, and if so, what did you do about it? I have tried reading around as much as I can, and have encountered suggestions to replace all negative values with 0 (which I'm not keen on, as it's throwing away data and effectively increasing some OTUs) or adding a scaling factor, which I don't know whether or not is statistically permissable. Any thoughts or suggestions would be much appreciated.

Many thanks,

Sarah

**Comment by spholmes** [comment]
Sarah,
What we usually do as commented on other issues is to add a constant to all the values so that all the values are positive, the statistics based on differences are unaffected and in particular NMDS and 
permanova.

Best
Susan

**Comment by ecologysarah** [comment]
Hi Susan,

Thank you for the clarification.

Best wishes,

Sarah

**Comment by joey711** [comment]
This has come up so many times I'm definitely going to include it early in the FAQ...
