### ISSUE TITLE
Pulling out OTUs from data set

### ISSUE THREAD

**Issue by ClaireA** [joey711/phyloseq#547]
Hi, 
I want to plot and run stats on a handful of OTUs only. I tried to use subset_taxa but this function only works for taxonomic levels, not OTU IDs. I checked the issue tracker and it seems that prune_taxa can be used for this, but I tried a few things that didn't work. How can I select specific OTUs to make an object?
Thanks!

**Comment by spholmes** [comment]
Claire,
The way I do it is that I use prune_taxa,
it would look something like:

where in my file the otus have names otu1 otu2 etc....
suppose I want to leave two out, I do:
noBP_otus=paste("otu",(1:484)[-c(48,64)],sep="")
yats_noBP_physeq=prune_taxa(noBP_otus,yats_physeq)

Hope this helps,
Susan

On Mon, Nov 2, 2015 at 3:14 PM, ClaireA <notifications@github.com> wrote:

> Hi,
> I want to plot and run stats on a handful of OTUs only. I tried to use
> subset_taxa but this function only works for taxonomic levels, not OTU IDs.
> I checked the issue tracker and it seems that prune_taxa can be used for
> this, but I tried a few things that didn't work. How can I select specific
> OTUs to make an object?
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/547>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by michberr** [comment]
Another option, if you wanted to use subset_taxa it would look something like this: 

```{}
physeq.subset <- subset_taxa(physeq, rownames(tax_table(physeq)) %in% c("Otu00001", "Otu00002"))
```

Alternatively, I always like to add my OTUs as their own column in the tax_table which i do this way:
```{}
tax_table(physeq) <- cbind(tax_table(physeq), 
	rownames(tax_table(physeq)))

colnames(tax_table(physeq)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "OTUID")

```

Then you can filter OTUs in your dataset the same way you would any other taxonomic level

**Comment by ClaireA** [comment]
thank you! I like the option of adding a column for OTUs, super handy!
