### ISSUE TITLE
Use plot_tree without biom file, want to use for culturable isolates

### ISSUE THREAD

**Issue by CarlyRae** [joey711/phyloseq#553]
Hello,

I have 119 bacterial isolates that I cultured and sequenced that have a trait I am interested in. I made a tree of the bacterial isolates' sequences and I have their trait values, along with other meta-data that I would like to put on the tree -- such as location isolate was found. 

I am playing around with picante and ape to make trees with this, but you all have spoiled me with some of the great graphics in phyloseq. I would love to use plot_tree in phyloseq, but I do not have a biom file to do along with this. 

> culture <- merge_phyloseq(isolates_map, tree)

Error in validObject(.Object) : invalid class “phyloseq” object: 
 An otu_table is required for most analysis / graphics in the phyloseq-package

Anyway around this?

Thanks,

Carly

**Comment by joey711** [comment]
Yes, this is possible. Map your experiment to a higher-throughput 16S amplicon sequencing project. The analogy would be one "sample" -- your strain isolations and the sequence you derived from each strain --  and within that one sample you have 119 "OTUs"

- (1) create a `otu_table`with a single column, and 119 rows. Name the rows according to the sequence names in the tree and trait table. Put a value of 1 in each entry
- (2) merge this OTU table with your other data

```S
# Initialize the dummy matrix
OTUmat = matrix(1L, 119, 1)
# Note these are dummy names. You should assign the real names
rownames(OTUmat) <- paste0("sp", 1:119)
OTU = otu_table(OTUmat, taxa_are_rows = TRUE)
culture <- merge_phyloseq(OTU, isolates_map, tree)
```

Hope that helps! Will close for now. Can re-open if further problems...
