### ISSUE TITLE
Feature: contour ordination plot?

### ISSUE THREAD

**Issue by gabuali** [joey711/phyloseq#554]
Hi Joey,

hope this does not sound inane but was wondering if you'd consider an ordination plot feature that would have contours around points?  Say each point is a individual or site that you sample repeatedly and generate an ordination with the point being the mean and contours the error bars.

thanks anyway!

galeb

**Comment by spholmes** [comment]
Hi there,
this can easily be done using geom_density2d
see the end of the file:
http://statweb.stanford.edu/~susan/papers/Pregnancy/PNAS_Stability.html
for an example,
good luck
Susan

On Mon, Nov 9, 2015 at 1:41 PM, gabuali <notifications@github.com> wrote:

> Hi Joey,
>
> hope this does not sound inane but was wondering if you'd consider an
> ordination plot feature that would have contours around points? Say each
> point is a individual or site that you sample repeatedly and generate an
> ordination with the point being the mean and contours the error bars.
>
> thanks anyway!
>
> galeb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/554>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by gabuali** [comment]
Many thanks Susan, precisely what I was looking for!
hope all is well,

galeb
