### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by laibinhuang** [joey711/phyloseq#556]
does anyone know how to figure out this problem 
plot_tree(mergedata)   

Error in as.data.table.matrix(xi, keep.rownames = keep.rownames)

thank you

**Comment by joey711** [comment]
This is not even close to a [MRE](http://robjhyndman.com/hyndsight/minimal-reproducible-examples/). Please see that guide, and re-post. I will close for now, but can re-open if you provide a MRE of your problem (and a better title).

cheers

joey
