### ISSUE TITLE
qiime datasets download?

### ISSUE THREAD

**Issue by diogocamacho** [joey711/phyloseq#557]
I wanted to test drive the phyloseq -> DESeq2 capability, and I was following the instructions you set.  However, with the changes in QIIME and their data repository of late, I can't seem to call: 

microbio_me_qiime(DATASET_BLAH)

Any idea of where these datasets are hosted now, if at all?  Thanks!

**Comment by spholmes** [comment]
I only know for one data set but the restroom data was available here:
ftp://ftp.microbio.me/pub/restroom-data/study_1335_split_library_seqs_and_mapping.zip

Best of luck (if you look at the restroom in the issues, a whole thread
discusses this)

Susan


On Mon, Nov 23, 2015 at 7:52 AM, Diogo Camacho <notifications@github.com>
wrote:

> I wanted to test drive the phyloseq -> DESeq2 capability, and I was
> following the instructions you set. However, with the changes in QIIME and
> their data repository of late, I can't seem to call:
>
> microbio_me_qiime(DATASET_BLAH)
>
> Any idea of where these datasets are hosted now, if at all? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/557>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by diogocamacho** [comment]
Hi Susan,

Many thanks.  I'll give that a try.  I'll let you guys know if I find
issues in there.

Best,
d.

**Comment by joey711** [comment]
Yes, this has already been discussed in a few places. In short, it's a QIIME-DB fail:

https://github.com/joey711/phyloseq/issues/491
