### ISSUE TITLE
Issue with taxon names 

### ISSUE THREAD

**Issue by cathi88** [joey711/phyloseq#560]
Dear Joey

I use the function import_biom for my otu_table.biom from qiime and import_qiime_sample_data for my mapping files. 
I am working with only 11 species but looking at the data, it says me that I have 5295 taxa (all this denovoxxxx, what should have been assigned to 1 of the 11 species). When doing the heatmap, all the 5295 OTUs get plotted. 
Did I make a mistake importing the files?

Thank you very much for your help, 

Catherine 
[Rplot.pdf](https://github.com/joey711/phyloseq/files/57108/Rplot.pdf)

**Comment by joey711** [comment]
@cathi88 it sounds much more like you need to reconsider how you did the OTU-clustering. You have mentioned de novo OTUs, but it sounds like you wanted a reference-only ("closed reference") result. 

I will close for now, as this is not a phyloseq issue. It sounds like phyloseq imported your data just fine, and you were surprised by what your data told you.

Best of luck!
