### ISSUE TITLE
Feature request - estimate_richness grouping variable

### ISSUE THREAD

**Issue by davidmartinad200** [joey711/phyloseq#561]
Hello,
In the plot_richness function you have added an x variable to group samples (i guess using the mean) by a specific variable.
plot_richness(GP, x = "SampleType", measures = c("Chao1", "Shannon"))

Would it be possible to have the same function in estimate_richness 
estimate_richness(GP,x="SampleType", measures = c("Chao1", "Shannon"))) 

thanks

**Comment by semorales** [comment]
I would second that request.

**Comment by joey711** [comment]
## Mapping to x-axis

Point of clarification. The `x` argument in `plot_richness` indicates which sample variable should be *mapped* to the horizontal axis (x-axis for shorthand). This is a grammar-of-graphics concept, and has nothing to do with variable aggregation, point estimation, or summarization. If you look closely in the example you provided, `mean` or similar point estimators were not used, and every point is shown. Their placement on the horizontal axis is by the `"SampleType"` categorical variable. 

See `plot_richness` and ggplot2 documentation for further details.

## Aggregating alpha diversity measures

This is already possible in R/phyloseq using the output of the `estimate_richness` and/or `plot_richness`. The following example shows this explicitly. 

```S
library("phyloseq")
```

```S
data("GlobalPatterns")
GP = GlobalPatterns
# Save output of `plot_richness` as a variable
pAlpha = plot_richness(GP, x = "SampleType", measures = c("Chao1", "Shannon"))
# "print" it to render the plot
pAlpha
```

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/841437/13907906/add1be5e-eeb5-11e5-9b7f-f37e9e52f82a.png)

The plot object already has the data embedded in it:

```S
head(pAlpha$data)
```

```
##   X.SampleID  Primer Final_Barcode Barcode_truncated_plus_T
## 1        CL3 ILBC_01        AACGCA                   TGCGTT
## 2        CC1 ILBC_02        AACTCG                   CGAGTT
## 3        SV1 ILBC_03        AACTGT                   ACAGTT
## 4    M31Fcsw ILBC_04        AAGAGA                   TCTCTT
## 5    M11Fcsw ILBC_05        AAGCTG                   CAGCTT
## 6    M31Plmr ILBC_07        AATCGT                   ACGATT
##   Barcode_full_length SampleType
## 1         CTAGCGTGCGT       Soil
## 2         CATCGACGAGT       Soil
## 3         GTACGCACAGT       Soil
## 4         TCGACATCTCT      Feces
## 5         CGACTGCAGCT      Feces
## 6         CGAGTCACGAT       Skin
##                                  Description samples variable    value
## 1   Calhoun South Carolina Pine soil, pH 4.9     CL3    Chao1 8588.071
## 2   Cedar Creek Minnesota, grassland, pH 6.1     CC1    Chao1 9236.465
## 3 Sevilleta new Mexico, desert scrub, pH 8.3     SV1    Chao1 7266.100
## 4    M3, Day 1, fecal swab, whole body study M31Fcsw    Chao1 4089.812
## 5   M1, Day 1, fecal swab, whole body study  M11Fcsw    Chao1 4178.124
## 6    M3, Day 1, right palm, whole body study M31Plmr    Chao1 4633.330
##         se
## 1 114.8130
## 2 106.8706
## 3 108.9271
## 4 123.0553
## 5 139.0962
## 6 121.9407
```

From here you are free to do standard data aggregation/summary techniques,
for which there are many, many fabulous tools in R. 

For starters, I recommend *data.table* and *dplyr* packages.
