### ISSUE TITLE
Perchance Two Bugs - One Critical in the Plot_tree()

### ISSUE THREAD

**Issue by Roli-Wilhelm** [joey711/phyloseq#563]
I've encountered a critical error in the Plot_tree() function, which led me to try installing the shiny package, which also produced a fatal error. The error with plot_tree occurs both with my phyloseq object (attached) and the included 'GlobalPatterns' phyloseq object. I've reported it in detail on the SeqAnswers forum so that your response could benefit the community (I can post your reply to me, if you do not have an account there). One piece of pertinent information is that I failed to include in that post is that my 'ape' is version 3.4.

Next, in trying to install shiny-phyloseq, I encountered an error. All the packages, including R itself (v. 3.2.3), is super up-to-date. Interestingly, when I open up a different R-session, I get slightly different error messages (though the root of the problem seems consistent - in italics).

Command:
shiny::runGitHub("shiny-phyloseq","joey711")

Error 1:
"Downloading https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘distance’ for signature ‘"character", "missing"’
In addition: Warning message:
In utils::download.file(url, ...) :
  downloaded length 2568342 != reported length 200"

Error 2:
"Downloading https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz
Loading required package: shiny
data.table 1.9.6  For help type ?data.table or https://github.com/Rdatatable/data.table/wiki
The fastest way to learn (by data.table authors): https://www.datacamp.com/courses/data-analysis-the-data-table-way
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘distance’ for signature ‘"character", "missing"’"

Thanks in advance for your assistance. I really enjoy using the phyloseq package. It is a great initiative and very useful for keeping my dataset consistent and my analysis coherent (and simplified by many of your functions). Many many thanks!

Roli Wilhelm

PhD Candidate @ UBC

**Comment by spholmes** [comment]
Roli,
Unfortunately you have conflated two errors:
one with phyloseq and plot_tree that we should deal with separately and
which is not documented in your email, the other errors come from
the conflicts between the ultra new phyloseq management of distances
and has been documented and a workaround provided in this issue:
https://github.com/joey711/shiny-phyloseq/issues/61

Let us know,
Susan


On Sat, Dec 12, 2015 at 9:50 AM, Roli Wilhelm <notifications@github.com>
wrote:

> I've encountered a critical error in the Plot_tree() function, which led
> me to try installing the shiny package, which also produced a fatal error.
> The error with plot_tree occurs both with my phyloseq object (attached) and
> the included 'GlobalPatterns' phyloseq object. I've reported it in detail
> on the SeqAnswers forum so that your response could benefit the community
> (I can post your reply to me, if you do not have an account there). One
> piece of pertinent information is that I failed to include in that post is
> that my 'ape' is version 3.4.
>
> Next, in trying to install shiny-phyloseq, I encountered an error. All the
> packages, including R itself (v. 3.2.3), is super up-to-date.
> Interestingly, when I open up a different R-session, I get slightly
> different error messages (though the root of the problem seems consistent -
> in italics).
>
> Command:
> shiny::runGitHub("shiny-phyloseq","joey711")
>
> Error 1:
> "Downloading
> https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz
> Error in (function (classes, fdef, mtable) :
> unable to find an inherited method for function ‘distance’ for signature
> ‘"character", "missing"’
> In addition: Warning message:
> In utils::download.file(url, ...) :
> downloaded length 2568342 != reported length 200"
>
> Error 2:
> "Downloading
> https://github.com/joey711/shiny-phyloseq/archive/master.tar.gz
> Loading required package: shiny
> data.table 1.9.6 For help type ?data.table or
> https://github.com/Rdatatable/data.table/wiki
> The fastest way to learn (by data.table authors):
> https://www.datacamp.com/courses/data-analysis-the-data-table-way
> Error in (function (classes, fdef, mtable) :
> unable to find an inherited method for function ‘distance’ for signature
> ‘"character", "missing"’"
>
> Thanks in advance for your assistance. I really enjoy using the phyloseq
> package. It is a great initiative and very useful for keeping my dataset
> consistent and my analysis coherent (and simplified by many of your
> functions). Many many thanks!
>
> Roli Wilhelm
>
> PhD Candidate @ UBC
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/563>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
I don't understand what the error is here. Recent tests with an updated version of shiny-phyloseq does not reproduce this issue on the included test datasets. 

As it may already by fixed, I will close for now, until a precise and persistent error can be shown.
