### ISSUE TITLE
Plot_tree function error

### ISSUE THREAD

**Issue by Roli-Wilhelm** [joey711/phyloseq#564]
The plot_tree function produces the following error for me with both the packaged dataset ("GlobalPatterns") and my own phyloseq object:

Error Message
"Error in as.data.table.matrix(xi, keep.rownames = keep.rownames) :
4 arguments passed to .Internal(nchar) which requires 3"

Version information:
R version 3.2.3
packageVersion("ggplot2") = ‘1.0.1’
packageVersion("phyloseq") = ‘1.14.0’
packageVersion("ape") = ‘3.4’

Steps to Reproduce Error:
library("phyloseq")
library("ggplot2")
data("GlobalPatterns")
phy_tree(GlobalPatterns)$node.label = substr(phy_tree(GlobalPatterns)$node.label, 1, 4)
physeq = prune_taxa(taxa_names(GlobalPatterns)[1:50], GlobalPatterns)
plot_tree(physeq)

Could someone please test that it works on their version and report what version that is? Or, otherwise, if you are developing the 'phyloseq' package, could you please work on a fix or offer me advice? I would love to use this function!

**Comment by spholmes** [comment]
Hi Roli,
Just checked this as you asked and with
R version 3.2.1 (2015-06-18)

> packageVersion("phyloseq")
[1] ‘1.12.2’
> packageVersion("ggplot2")
[1] ‘1.0.1’
there are no errors for me.

Susan

On Sat, Dec 12, 2015 at 1:10 PM, Roli Wilhelm <notifications@github.com>
wrote:

> The plot_tree function produces the following error for me with both the
> packaged dataset ("GlobalPatterns") and my own phyloseq object:
>
> Error Message
> "Error in as.data.table.matrix(xi, keep.rownames = keep.rownames) :
> 4 arguments passed to .Internal(nchar) which requires 3"
>
> Version information:
> R version 3.2.3
> packageVersion("ggplot2") = ‘1.0.1’
> packageVersion("phyloseq") = ‘1.14.0’
> packageVersion("ape") = ‘3.4’
>
> Steps to Reproduce Error:
> library("phyloseq")
> library("ggplot2")
> data("GlobalPatterns")
> phy_tree(GlobalPatterns)$node.label =
> substr(phy_tree(GlobalPatterns)$node.label, 1, 4)
> physeq = prune_taxa(taxa_names(GlobalPatterns)[1:50], GlobalPatterns)
> plot_tree(physeq)
>
> Could someone please test that it works on their version and report what
> version that is? Or, otherwise, if you are developing the 'phyloseq'
> package, could you please work on a fix or offer me advice? I would love to
> use this function!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/564>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by zbendiks** [comment]
I'm having the same issue as Roli-Wilhelm.  I'm using RStudio 3.2.0, Phyloseq version 1.14.0, and ggplot2 version 2.0.0.  Both the **plot_tree** and the **tree_layout** scripts give me this error:

*Error in as.data.table.matrix(xi, keep.rownames = keep.rownames) : 
  4 arguments passed to .Internal(nchar) which requires 3*

I'm receiving this error with both the phyloseq tutorial dataset and my own data. Any ideas or workarounds?

**Comment by zbendiks** [comment]
For any interested readers: I overcame this problem by updating to R version 3.2.3.  The plot_tree function now works without error.  For Roli, I imagine updating ggplot2 and phyloseq should get rid of the problem.

**Comment by joey711** [comment]
I will close for now, as I was never able to reproduce this error. Please advise / post if there is a lingering issue.
