### ISSUE TITLE
tax_glom issue

### ISSUE THREAD

**Issue by DSLUCB** [joey711/phyloseq#565]
Hello,

I am running the script below, in an attempt to plot my 10 most abundant families:

VphyseqT1 = transform_sample_counts(Vphyseq, function(x) 100 * x/sum(x))
VphyseqsF <- tax_glom(VphyseqT1, taxrank="Family")
Family10 = names(sort(taxa_sums(VphyseqsF), TRUE)[1:10])
VphyseqF10 = prune_taxa(Family10, VphyseqsF)
p = plot_bar(VphyseqF10, "Family", fill = "Family", facet_grid=Type~Location)

And instead of 10 families, I get 7. 
Could you please help me to figure out what I am doing wrong here? Thank you.

**Comment by joey711** [comment]
Are you sure you have a non-NA `Type` and `Location` entry for all of these? Do you actually have 10 families in `VphyseqsF`? What is returned by the following?

```S
ntaxa(VphyseqsF)
length(Family10)
```

It is very difficult to diagnose without a reproducible example.

Have you seen the following thread?

https://github.com/joey711/phyloseq/issues/418

My prototype code at the end might be helpful.

**Comment by DSLUCB** [comment]
Here's what I get:

> ntaxa(VphyseqsF)
[1] 2563
> length(Family10)
[1] 10

It seems that it does not sum up the families, because when I export the tax_table of VphyseqF10, I have 10 families but with duplicate entries for a couple of them, which would plot 7 at the end.

**Comment by joey711** [comment]
I will close for now. This seems to be an issue with your data, or your interpretation of it, and not an issue with phyloseq. If you can post an example to the contrary so that someone can reproduce your problem, then I will re-open. 

Hope you were able to solve this already and have been happily using phyloseq ever since!
