### ISSUE TITLE
Sequencing coverage calculation and Deseq2 automatic filtering

### ISSUE THREAD

**Issue by ademenez** [joey711/phyloseq#566]
Hi Joey,

I was wondering if there is a way in phyloseq to calculate microbiome sequencing coverage?

Also, would you have any suggestion for a way to find out what threshold that Deseq2 used when determining differential abundant OTUs. I know it is determined automatically as part of the results() function, but is there a way of finding out what was the threshold used? 

Many thanks,

Alexandre

**Comment by joey711** [comment]
## Sequencing Coverage?

- (1) Total reads per sample: `sample_sums()` function
- (2) Projections/predictions of coverage, usually through alpha-diversity and related theory: `estimate_richness()` / `plot_richness()`

## DESeq2 results default:

type the following into an R session and the DESeq2 documentation will explain further.

```S
?DESeq2::results
```

Good luck!
