### ISSUE TITLE
manual import of otu table

### ISSUE THREAD

**Issue by lebetimonas** [joey711/phyloseq#567]
[exampleoferror.txt](https://github.com/joey711/phyloseq/files/83228/exampleoferror.txt)

I'm trying to manually import an otu table, but it keeps failing the validation step. The error says that the data is non-numeric, presumably because of the first column with OTU names. If I remove the first column, the error message doesn't happen, but then there are no identifiers to tie the abundances to the taxonomy table. But this is the format of the example in the tutorial for manual imports.

The error message and the data I am trying to import are attached in the text file.

**Comment by CarlyRae** [comment]
My previous post may help? https://github.com/joey711/phyloseq/issues/543

**Comment by lebetimonas** [comment]
Excellent!

Using "row.names = 1" when importing the otu table fixed the problem.
Example:
otumat<-read.table("my_otu_table.txt",sep="\t",header=T,row.names=1)

Thank you!
