### ISSUE TITLE
Update vignettes to BioC common template

### ISSUE THREAD

**Issue by joey711** [joey711/phyloseq#569]
The template is distributed in [the *BiocStyle* package](https://www.bioconductor.org/packages/3.3/bioc/vignettes/BiocStyle/inst/doc/HtmlStyle.html)

Looks nicer than most other templates that I've tested to date.

I'm happy to consider other templates if people suggest them. This one has the added bonus at having some official support via BioC.

**Comment by spholmes** [comment]
Joey
I have been using that style for the Book I am writing,
and everything seems to be well thought through.
Definitely I recommend it,
Susan

On Tue, Jan 19, 2016 at 10:54 AM, Paul J. McMurdie <notifications@github.com
> wrote:

> The template is distributed in the *BiocStyle* package
> <https://www.bioconductor.org/packages/3.3/bioc/vignettes/BiocStyle/inst/doc/HtmlStyle.html>
>
> Looks nicer than most other templates that I've tested to date.
>
> I'm happy to consider other templates if people suggest them. This one has
> the added bonus at having some official support via BioC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/569>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
This is partly solved in a side branch. Will try to get the rest in shortly.
