### ISSUE TITLE
How does phyloseq treat unmatched reads when incorporating tree files?

### ISSUE THREAD

**Issue by lfaller** [joey711/phyloseq#571]
Hi all,

This is more of a question, rather than an issue, but I wasn't sure where else to post (please let me know if there is a better place for this).

I have an OTU table with OTUs as rows and samples in the columns. One of my OTUs is called "unmatched_reads" and I usually keep it there so I can normalize accurately.

I am trying to get started with phyloseq and noticed that my unmatched_reads OTU dropped out somewhere. 

My phyloseq object has an otu table, a taxonomy table (I have an extra row in there for this OTU [domain = undefined, phylum = undefined, etc]), some sample metadata, and a tree.

However, I have no tip labeled "umatched_reads" in my tree and I think when I do a call to `merge_phyloseq()` that's when it drops out (together with some other taxa).

```
> physeq
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 768 taxa and 258 samples ]
tax_table()   Taxonomy Table:    [ 768 taxa by 7 taxonomic ranks ]

> physeq1 = merge_phyloseq(physeq, sampledata, tree)

> physeq1
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 571 taxa and 258 samples ]
sample_data() Sample Data:       [ 258 samples by 5 sample variables ]
tax_table()   Taxonomy Table:    [ 571 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 571 tips and 558 internal nodes ]
```
So I was wondering, is there any thoughts on "best practices" regarding how to deal with unmatched reads? If I proceed with my physeq object, I'd like to know about the unmatched reads so that I can normalize accurately. Should I leave the tree analyses to the very end, given there are other taxa that also get removed?

Thanks for any advice (and again, if there is a better place for that kind of question, please point me to it!)

Best,
~Lina

**Comment by joey711** [comment]
There are lots of ways to do this. It depends on what you're hoping to get out of it. If "unmatched reads" are what I think they are, you don't necessarily need to "count" them as part of your sample in the first place. It might be helpful to note that value of the counts being assigned "unmatched" to tip you off to abnormalities or some problem in your workflow or sequencing artifacts. Other than that, it seems unlikely that you actually want to keep them around as part of a phyloseq object on which you're going to do analysis. If you really think the unmatched counts need to be considered part of each sample, you can save a named vector of sample count totals that includes the unmatched count, then merge and toss unmatched-reads in the process. When you encounter a step that requires the unmatched-inclusive relative abundance, you'll just refer to your sample totals vector. This is preferable to attempting to retain a "fake" OTU in your data object.

See `transform_sample_counts` for some examples. 

Make sense?

I'll close for now. Thanks for the feedback and interest in phyloseq :)

joey

**Comment by lfaller** [comment]
Thanks for the suggestions! I agree, keeping a "fake OTU" around is less than ideal... it's a remnant of old excel spreadsheets that our collaborators seem to prefer ;-) Incorporating a sample totals vector sounds like a good solution!
