### ISSUE TITLE
distance, jaccard ISSUE -- must specify binary = T in vegan to run true jaccard

### ISSUE THREAD

**Issue by CarlyRae** [joey711/phyloseq#572]
Hi,

I recently realized that if you run 

jacc_dist <- vegdist(x, method="jaccard")

in vegan, you are not really getting a true jaccard distance matrix. If you look at the vegdist help you will see: Jaccard index is computed as 2B/(1+B), where B is Bray–Curtis dissimilarity.

So, the distance matrix would be computed using abundance values.

You must specify 

jacc_dist <- vegdist(x, method="jaccard", binary = T)

to remove this problem.

I just tested it and realized that phyloseq is not specifying binary = T, and thus jaccard is not being computed correctly on a presence/absence matrix as one would think in phyloseq. It is using the abundance data.

jacc_dist_phyloseq <- distance(x, "jaccard") 

is not giving you what you actually want.

**Comment by joey711** [comment]
Thanks for the heads-up. I'll make sure this gets fixed. I may just encode the distance myself instead of calling to vegan.

**Comment by CarlyRae** [comment]
Thank you! I would be interested to see if you get the same numbers if you code it yourself. It's unclear to me how you can use Bray-Curtis to get to Jaccard, but the vegan folks do it that way so....

**Comment by CarlyRae** [comment]
I'm also curious about unifrac now. If I run: 

uni <- distance(x, method = "unifrac")

Am I running unweighted or weighted unifrac?

It looks like running unifrac is running it as unweighted through UniFrac, right?

 UniFrac(physeq, weighted=FALSE, normalized=TRUE,
  parallel=FALSE, fast=TRUE)

**Comment by joey711** [comment]
The documentation has been updated in the last release or two, explaining this. It is advisable to provide `"wUniFrac"` or `"uUniFrac"` to the method argument of the `distance()` function, rather than worry about invoking `UniFrac` as a separate method. I will most-likely deprecate this as a separate function in the next release. Arguments like `fast` have been deprecated for a while, as there is no reason to run the non-fast algorithm, and I've stripped the slow-method code from the package.

See the documentation of the `distance` function for further details.

**Comment by CarlyRae** [comment]
Thanks!

**Comment by joey711** [comment]
I'm going to leave this open until I've fixed the jaccard distance issue...

**Comment by joey711** [comment]
Here's a version that's decent. Needs vectorization or a low-level C call to really compete with vegan's version. Was a nice double-check though:

```S
library("phyloseq")
distance_jaccard_pair = function(x, y){
  return( 1 - sum((y > 0) & (x > 0), na.rm = TRUE) / sum((y > 0) | (x > 0), na.rm = TRUE) )
}
################################################################################
#' Calculate the Jaccard distance
#'
#' This is a phyloseq-specific implementation of the Jaccard Distance
#' for comparing pairs of microbial communities (samples) in an experiment. 
#' The expectation is that you have many samples (say. more than two) and you
#' want a distance matrix on which will perform further analysis. 
#' 
#' @param physeq (Required). \code{\link{phyloseq-class}}. 
#'  The phyloseq data on which to compute the 
#'  pairwise sample distance matrix.
#'
#' @return An object of class ``\code{\link{dist}}'' suitable for certain 
#'  ordination methods and other distance-based analyses.
#'  See \code{\link{distance}}.
#'  
#' @seealso
#'  \code{\link{distance}} 
#' 
#'  \code{\link{enterotype}}
#'
#' @references
#' # Need to add citation here.
#'
#' @author
#'  Susan Holmes \email{susan@@stat.stanford.edu}.
#'  Adapted for phyloseq by Paul J. McMurdie.
#'
#' @keywords internal
#' @examples
#' data(GlobalPatterns)
#' mydist1 <- distance_jaccard(GlobalPatterns)
#' gp.jacc.PCoA <- ordinate(enterotype, "PCoA", mydist1) 
#' plot_scree(gp.jacc.PCoA)
#' p <- plot_ordination(enterotype, gp.jacc.PCoA, color="Enterotype", shape="SeqTech") 
#' (p <- p + geom_point(size=5, alpha=0.5))
setGeneric("distance_jaccard", function(physeq){
  standardGeneric("distance_jaccard")
})
setMethod("distance_jaccard", "ANY", function(physeq){
  stop("distance_jaccard requires specific input classes. E.g. `phyloseq-class`.
       Check call and try again")
})
setMethod("distance_jaccard", "phyloseq", function(physeq){
  distance_jaccard(otu_table(physeq))
})
setMethod("distance_jaccard", "otu_table", function(physeq){
  # Coerce to species-as-columns
  if(taxa_are_rows(physeq)){ physeq <- t(physeq) }
  # Coerce physeq to matrix and pass on
  return(distance_jaccard(as(physeq, "matrix")))
})
# Assumes samples are rows
setMethod("distance_jaccard", "matrix", function(physeq){
  # create N x 2 matrix of all pairwise combinations of samples.
  spn <- combn(row.names(physeq), 2, simplify=FALSE)
  # initialize DistMat with NAs
  DistMat <- matrix(data = NA_real_,
                    nrow = nrow(physeq),
                    ncol = nrow(physeq))
  # name the indices
  rownames(DistMat) <- row.names(physeq)
  colnames(DistMat) <- row.names(physeq)
  # Loop through each sample-pair
  for(i in spn){
    # Indexed assignment to distance matrix
    DistMat[ i[2], i[1] ] <- distance_jaccard_pair(physeq[i[1], ], physeq[i[2], ])
  }
  return(as.dist(DistMat))
})

# test it out
data("GlobalPatterns")
system.time({
  djaccveg <- distance(GlobalPatterns, "jaccard", binary = TRUE)
})
system.time({
  djaccjoey <- distance_jaccard(GlobalPatterns)
})
all.equal(attributes(djaccjoey)$Labels, attributes(djaccveg)$Labels)
all.equal(djaccjoey, djaccveg, check.attributes = FALSE)
# See for your self
head(djaccjoey); head(djaccveg)
tail(djaccjoey); tail(djaccveg)
```

I'd add this as a pull request, but I see that mine is slower. It might be a reasonable resolution to just add something to the documentation of `phyloseq::distance` that makes plain this difference. I suspect that it is actually documented in `vegan::vegdist`, and as you can see in this example, the `binary` argument is still available to `phyloseq::distance()` via the `...`.

**Comment by CarlyRae** [comment]
Great, thanks for the work on this. I used to not be able to pass binary = T to the distance function, so that is great that works now. I think a note in phyloseq::distance would be good if you feel yours is slower and that the vegan::vegdist is the better way to go.

**Comment by joey711** [comment]
I agree. I'll re-open and tag this as a documentation issue...
