### ISSUE TITLE
Visualize within group variance of UniFrac scores

### ISSUE THREAD

**Issue by dylandahan** [joey711/phyloseq#576]
Hello Joey/Phyloseq community,

I am currently trying to visualize within group variance on the PCoA made from UniFrac scores using the ordinate and distance functions. To see, for example, if overall within group variance is different between treatments. Any ideas?

**Comment by CarlyRae** [comment]
You could do a few things. 

Easiest, but maybe not most informative is add stat_ellipse
jaccard_45 <- distance(ch3_45, "jaccard")

p2 <- plot_ordination(ch3_45, jaccard_45, color = "Temp", shape = "Trmt")

p2 + theme_bw() + theme(text = element_text(size = 16)) + geom_point(size = 4) + stat_ellipse(aes(group =Temp))

p2

This is drawing 95% confidence ellipses around your groups that you specify. It is sensitive to sample size. There may be differences in dispersion though that you would not see with the ellipses. But, can help visualize.

Other thing to do is take your distances you generated, then generate a mapping file dataframe to use to assign your groups of interest (sounds like treatments in your case), use betadisper (which is a PERMDISP) to examine group variances, and perform an anova on the output of betadisper. If significant, examine differences among groups. You can use help files from package 'vegan' to understand betadisper and plotting. You cannot label groups yet in plot.betadisper (but evidently in the works -- https://github.com/vegandevs/vegan/issues/128). You can use the plot from phyloseq to figure out which group is which though and label on your own.  

jaccard_45 <- distance(ch3_45, "jaccard")

df_45 <- as(sample_data(ch3_45_data), "data.frame")

groups <- df_45[["Temp"]]
groups
mod <- betadisper(jaccard_45, groups)

anova(mod)

## the dispersion is different between groups, then examine

plot(mod)
boxplot(mod)
mod.HSD <- TukeyHSD(mod )
plot(mod.HSD) 

#### This usually is accompanied with a PERMANOVA to examine centroid differences among groups, however if PERMDISP is significant it is similar to an ANOVA and the violation of variance inequality = you can't tell if it is dispersion or centroids driving the difference. I generally evaulate the plots to try to make inference if centroids are also different, if the betadisper (PERMDISP) gives a significant result.

temp_adonis_45 <- adonis(jaccard_45 ~ Bd*Temp, data = df_45)
temp_adonis_45

#### There is some cool stuff that geomorph package folks are developing to examine centroid and dispersion differences, but I don't have well tested code yet to share on that

Good luck!

**Comment by dylandahan** [comment]
Hi Carly,
Thanks a lot for your help. The betadisper function and plots are precisely what I was looking for. As you recommended, I used Phyloseq's plot_ordination to figure out which treatment is which and just labelled on my own. 
Cheers,
Dylan

**Comment by joey711** [comment]
https://github.com/joey711/phyloseq/issues/323
