### ISSUE TITLE
New version of ggplot2

### ISSUE THREAD

**Issue by spholmes** [joey711/phyloseq#577]
> library(phyloseq)
Warning messages:
1: replacing previous import by ‘ggplot2::Position’ when loading ‘phyloseq’ 
2: replacing previous import by ‘scales::alpha’ when loading ‘phyloseq’ 

This is the same error as noticed and responded to by Hadley here:
https://github.com/hadley/ggplot2/issues/1335

who says
``Package developers need to fix those warnings, by being more selective with imports (i.e. don't import all of scales, just import the functions that you need)''

**Comment by colinbrislawn** [comment]
Thanks for posting this! Looks like this is tripping up a PR of mine (#575)

**Comment by joey711** [comment]
Thanks, Susan @spholmes I'll try and get this squared away soon. I need to push a few other updates into the current devel branch so its in the next release (including the jump to biomformat, which will go out in the next release...)

**Comment by joey711** [comment]
`scales::alpha` is resolved. `ggplot2::Position` is not, but it is unclear what package dependency is causing the problem. The next BioC update may have this solved. I will close for now and re-open if I get feedback from BioC. The proactive alternative is to explicitly import every ggplot2 exported object that is used in phyloseq... This would be a rather large amount of effort, and seemingly in the use case for which full package import is intended.
