### ISSUE TITLE
Re-labeling axes in plot_heatmap

### ISSUE THREAD

**Issue by topato** [joey711/phyloseq#580]
Phyloseq version: 1.15.2
R version: 3.2.1

As per the [plot_heatmap tutorial](http://joey711.github.io/phyloseq/plot_heatmap-examples), I've tried to relabel the axes. However, I'm getting unexpected result:

```
biom_file <- "global_tax_json.biom"
biom <- import_biom(biom_file,parseFunction = parse_taxonomy_greengenes)
p <- plot_heatmap(biom, low="#000033", high="#CCFF66", method = "PCoA", distance="bray")

p$scales$scales[[1]]$name <- "My X-Axis"  # This actually re-labels the Y-axis
p$scales$scales[[2]]$name <- "My Y-Axis" # This re-labels the color scale legend (from the default "Abundance")
```

My question is, is this intended and if so, how do I relabel the X-axis?

**Comment by joey711** [comment]
All graphics objects generated by phyloseq `plot_*` family of functions are ggplot2 objects, and can therefore be further modified by ggplot2 functions. See [ggplot2 documentation](http://docs.ggplot2.org/current/) for further details about minor plot tweaks like these.

In your example, the code would actually be:

```S
biom_file <- "global_tax_json.biom"
biom <- import_biom(biom_file,parseFunction = parse_taxonomy_greengenes)
p <- plot_heatmap(biom, low="#000033", high="#CCFF66", method = "PCoA", distance="bray")
p + xlab("My X-Axis") + ylab("My Y-Axis")
```

**Comment by topato** [comment]
I did read that the functions are ggplot2 objects, but didn't realise it's that easy to interact with them that way. Thanks for taking your time to answer my question.
