### ISSUE TITLE
Running the plos one file: hcfun not found

### ISSUE THREAD

**Issue by spholmes** [joey711/phyloseq#582]
On line 155 of phyloseq_plos1_2012-source-doc
tggpsfb = tip_glom(gpsfb, NULL, 0.1)
now throws an error:
Error in as.hclust(hcfun(dd, ...)) : could not find function "hcfun"

Reported by Brian Williams and Susan Holmes

**Comment by joey711** [comment]
Well that doesn't sound good. Can we define a MRE? `hcfun` would be the placeholder variable that holds the function within a loop that tries multiple functions (if memory serves). A traceback might reveal what the missing clustering function is, and possibly other issues that might help in defining an MRE.

**Comment by spholmes** [comment]
I ran through the rnw file from the paper and found the line that
tripped,currently traveling,I'll try a mwe when I arrive.

**Comment by joey711** [comment]
Thanks!

**Comment by joey711** [comment]
Any update? I'll try and include before the next BioC release...

**Comment by spholmes** [comment]
`# Load required packages
```{r, message=FALSE, warning=FALSE}
library(knitr)
library("phyloseq"); library("ggplot2"); library("scales"); library("grid")
```
Should be using phyloseq version `1.3.20` or greater for reliable behavior. See 
[the phyloseq homepage](http://joey711.github.com/phyloseq/)
```{r}
packageVersion("phyloseq")
packageVersion("ggplot2")
packageVersion("scales")
packageVersion("grid")
packageVersion("knitr")
data("GlobalPatterns")
```


```{r}
sample_data(GlobalPatterns)$human = factor( sample_data(GlobalPatterns)$SampleType %in% c("Feces", "Mock", "Skin", "Tongue") )
GP = filter_taxa(GlobalPatterns, function(x) sum(x > 3) > (0.2*length(x)), TRUE)
total = median(sample_sums(GP))
standf = function(x, t=total) round(t * (x / sum(x)))
gps = transform_sample_counts(GP, standf)
gpsf = filter_taxa(gps, function(x) sd(x)/mean(x) > 3.0, TRUE)
gpsfb = subset_taxa(gpsf, Phylum=="Bacteroidetes")
#save(gpsf, gpsfb, file="gp-ex.RData")
head(phy_tree(gpsfb)$node.label)
phy_tree(gpsfb)$node.label = substr(phy_tree(gpsfb)$node.label, 1, 4)
head(phy_tree(gpsfb)$node.label)
```

This works
```{r}
plot_tree(gpsfb, "sampledodge", nodeplotboot(), "Order", "human", "abundance", title=title, ladderize="left")
```
This doesn't work
```{r}
tggpsfb = tip_glom(gpsfb, NULL, 0.1)
tggpsfb = merge_samples(tggpsfb, "SampleType")
```
`

**Comment by joey711** [comment]
Thanks, I'll see if I can fix it...

**Comment by joey711** [comment]
Also updated the HTML formatting with BiocStyle ;-)
