### ISSUE TITLE
better way to Hellinger transform otu_table data in phyloseq

### ISSUE THREAD

**Issue by Gian77** [joey711/phyloseq#585]
Hello Joey,
Is there a way to Hellinger transform otu_table data I have imported in a phyloseq object?
I got a custom import that looks like is working - below you can see my code - but I am wondering if there is an easier way to do it that I don't know.
Thanks a lot for helping :)
Gian

#import customizzed data in phyloseq
>metadata = read.table("mapping16s.csv", header=T, row.names=1, sep=",")
>sampledata = sample_data(metadata)

>biom = read.table(file="biom.csv", header=T, row.names=1, sep=",")
>biom.hel <- decostand(biom, method = "hellinger")
>my_biom = otu_table(biom.hel, taxa_are_rows=TRUE)

>taxonomy = read.table("taxonomy16s.csv", header=T, row.names=1, sep=",")
>taxonomy = as.matrix(taxonomy)
>my_tax = tax_table(taxonomy, errorIfNULL=TRUE)

>ps1 = phyloseq(my_biom, sampledata, my_tax)

**Comment by joey711** [comment]
that looks pretty easy to me... there are other ways to do it, but I'm not sure they would be fewer lines of code or better syntax. As it is, your hellinger transformation was one line. Not sure what you mean by better. Thoughts? Have your reviewed `transform_sample_counts()` documentation?

I'll close for now, but feel free to comment further.

**Comment by Gian77** [comment]
Hello Joey,
I probably wasn't able to explain myself very well. My question was, instead of doing all those 9 steps is there a way to get Hellinger transformation of the phyloseq data without one line of code. I will check transform_data_counts() better anyway. 
Thank you very much,
Gian

**Comment by gdanetzk** [comment]
Hi @joey711,

I'm also interested in using the Hellinger transformation. Would it be possible to add it as a flag to the transform_data_counts() command that would save the extra step that @Gian77 described above?

**Comment by Gian77** [comment]
Hi Kristi,
I think I get a better code for that, here below, just one line

otu_table(phyobject.hell) <-otu_table(decostand(otu_table(phyobject), method = "hellinger"), taxa_are_rows=TRUE)

:)

G.

**Comment by handibles** [comment]
@Gian77 thanks, that's a super helpful little duet. Used it to incorporate regularised log (rlog) transformation from DESeq2:
```
newobj_rlog <- phyobj
otu_table (newobj_rlog) <- otu_table ( **assay (rlog ( newobj_rlog ))**, taxa_are_rows = TRUE )
```
you can stick any suitable transformation in for the bit in bold.

**Comment by mikemc** [comment]
For future reference of anyone who googles this, I believe the easiest way to apply the Hellinger transform is simply by using `transform_sample_counts()` as Joey noted,
```r
ps2 <- transform_sample_counts(ps1, function(x) sqrt(x / sum(x)))
```
where I have used the definition of the Hellinger transform given by Equation (13) in Legendre and Gallagher (2001) DOI: 10.1007/s004420100716---convert the data to proportions and then take the square root.
