### ISSUE TITLE
reproducible research workflow, +1 to otu_table

### ISSUE THREAD

**Issue by vmaffei** [joey711/phyloseq#589]
Hello! I have a quick question regarding a step in the "reproducible research workflow," specifically within the variance stabilizing transform:
http://statweb.stanford.edu/~susan/papers/TeethRR.html#stabilize-the-variance

just prior to converting the phyloseq object to deseq2 object, 1 is added to the trimmed otu_table:

**#add 1 to each sample count**
**otu_table(core15_RLD) <- otu_table(core15) + 1**

What is the role of adding 1 to the table? Is it a pseudocount specifically added for rlog() transform (as follows in "RRW")? Is it intended to control 0s in the dataset? Should one also consider adding 1 for a varianceStabilizingTransformation() as well? Generally speaking, when should one consider adding 1 prior to rLog/VST transformation of 16S count data?

application: I am using phyloseq+deseq2 to produce a variance stabilizing transformation on 16S count data for downstream clustering/beta-diversity analysis.

Any comment would be much appreciated!

Vince

**Comment by spholmes** [comment]
Hi Vince
yes the regularization and variance stabilizations have problems
with 0 counts and adding a pseudocount avoids this, there are actually other
ways to treat the large numbers of zeros, but they are much more
complicated and this hack
has been working well for us,
Susan

On Thu, Mar 17, 2016 at 1:04 PM, vmaffei <notifications@github.com> wrote:

> Hello! I have a quick question regarding a step in the "reproducible
> research workflow," specifically within the variance stabilizing transform:
>
> http://statweb.stanford.edu/~susan/papers/TeethRR.html#stabilize-the-variance
>
> just prior to converting the phyloseq object to deseq2 object, 1 is added
> to the trimmed otu_table:
>
> *#add 1 to each sample count*
> *otu_table(core15_RLD) <- otu_table(core15) + 1*
>
> What is the role of adding 1 to the table? Is it a pseudocount
> specifically added for rlog() transform (as follows in "RRW")? Is it
> intended to control 0s in the dataset? Should one also consider adding 1
> for a varianceStabilizingTransformation() as well? Generally speaking, when
> should one consider adding 1 prior to rLog/VST transformation?
>
> application: I am using phyloseq+deseq2 to produce a variance stabilizing
> transformation on 16S count data for downstream clustering/beta-diversity
> analysis.
>
> Thanks so much!
>
> Vince
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/589>
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by vmaffei** [comment]
very helpful...thanks so much!
