### ISSUE TITLE
Use of wildcards in subset_taxa()

### ISSUE THREAD

**Issue by rmbowers2010** [joey711/phyloseq#590]
Hi all,

I have a question about using wildcards with the subset_taxa() function. I am an intermediate R user so have some ideas on how to achieve this but have been stumped to this point. What I would like to do would be to use grep or grepl within the subset_taxa() function. The subset_taxa() feature is very useful to isolate a specific region of the tree based on a specific phylum for example, however I have a tree that has a number of "New OTUs" (produced using Qiime's open_reference_otu.py workflow). Many of these OTUs are contained within specific phyla, but if I extract that region of the tree using  subset_taxa(pseq_object, phylum == " p__phylumX”), it returns just those taxa that have that name in the phyloseq object's tax_table. I realize that I can also use the pipe character "|" within the subset call to extract additional phyla for example like so: 

subset_taxa(pseq_object, class == " c__Alphaproteobacteria" | class == " c__Betaproteobacteria")

But, is there a way to do the same thing, but for all proteobacteria using a wildcard? subset_taxa(pseq_object, class == " *proteobacteria") ? Or my real example:

subset_taxa(pseq_object, class == " c__Alphaproteobacteria" | kingdom == " *New.OTU*"

I realize this syntax is wrong, but I've tried nesting grep and grepl to do this, however I am having some difficulty figuring this out as the phyloseq object is different than a typical dataframe when subsetting using grep as I probably need to call the actual tax_table somehow.

I will continue playing with this and post a solution if I find one, but would appreciate a nudge in the right direction if anyone has any ideas.

Best,

Bob

**Comment by rmbowers2010** [comment]
Hi, 
Never mind. I figured this one out. For example, if you want all proteobacteria and they're listed in the class column of the tax_table(), you could do: 
subset_taxa(phyloseq_object, grepl("proteobacteria", tax_table(pseq_object)[,3])
Just another way to get what I need out of this nice package. Thanks!

**Comment by joey711** [comment]
Glad that works for you! Thanks for posting -- and closing after you solved your issue.

Here's how I would have approached it:

```S
proteosOnly = subset_taxa(physeq, grepl("proteobacteria", Class))
```

The `subset_taxa()` function is already expecting to search the columns of the taxonomy table as variables in the search path, so if the taxonomic rank you were trying to wildcard-search was called `Class`, the above approach should do the trick, and saves from writing/executing the extra `tax_table` extraction.

Cheers!

**Comment by rmbowers2010** [comment]
Hi Paul,

Thanks for the tip. This is much cleaner!

Best,

Bob
