### ISSUE TITLE
Applying FDR-adjusted test on UniFrac Distances

### ISSUE THREAD

**Issue by AndreaQ7** [joey711/phyloseq#593]
Hi everyone,

I'm trying to apply FDR-adjusted test on UniFrac distances...does anyone know how to perform it?
I imagine that at first I should perfom _distance(data,"wunifrac") _  but then? Have a nice day you all

**Comment by joey711** [comment]
Hi @AndreaQ7 

Your question is a bit under-specified. To comment on multiple testing I would need to know what test you have in mind. For instance, if you were going to do an adonis test on a model with multiple sample-variables, multiple hypotheses are already accounted for in the F-test derived p-values. However, if you did multiple adonis tests, one at a time (not recommended), then you would need a correction.

Was this the test you had in mind with w-unifrac, or was it something else?

**Comment by AndreaQ7** [comment]
Hi Joey,
Thank you for your reply. Yes you right I've  been bit superficial in my description sorry. 
I'm performing metagenomic analysis of  sample from 5 different groups. I create a distance matrix with Weighted and Unweighted Unifrac, then I make the plot_ordination. But I would like to assign a statistical significance  to the distance among the groups like : Treated vs No_Treated; Treated vs Treated etc.... Do you know how can I perform a statistical analyis to assign a significance of distances between pairs of groups?
At the beginning I was thinking to performe a mt and than a correction for mt but I think that's not the right test to perform in this case.
Thank you

**Comment by michberr** [comment]
As Joey alluded to, it sounds like you are looking for a PERMANOVA test (which can be implemented in R with the vegan `adonis` command). There's lots of documentation for this function online. 

I would recommend reading this [page](http://mb3is.megx.net/gustame/hypothesis-tests/manova/npmanova), as well as many of the other pages on the gustame site for an introduction to multivariate statistics applied to microbiome datasets.

**Comment by joey711** [comment]
Thanks @michberr , 

it also sounds worth pointing out that there is a big difference between testing for difference between

(1) whole microbial communities, or some fingerprint thereof, and
(2) differences in relative abundance of individual taxa, or some transformation thereof

These are very different types of biological inference, and are computed with very different statistical methods.

I will close for now.

Make sure to also take a look at the new [phyloseq FAQ](http://bioconductor.org/packages/devel/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html).

**Comment by AndreaQ7** [comment]
Thank you a lot guys for your information and suggestions
