### ISSUE TITLE
Save phyloseq tree - newick format

### ISSUE THREAD

**Issue by maculatus** [joey711/phyloseq#599]
Hello,
Is it possible to save the tree produced by plot_tree (Phyloseq) to a newick format with only OTU or/and Taxonomic names?

**Comment by bioinfonm** [comment]
I was wondering the same thing! I am trying to find a work around right now.

**Comment by joey711** [comment]
Yes you can. The phyloseq tree is simply an ape-package tree (phylo-class) with tip names that are the OTU/taxa_names. 

This means that the [ape function write.tree()](http://www.inside-r.org/packages/cran/ape/docs/write.tree) will already allow you to do this.

If your phyloseq object was called `physeq1`...

```S
tree1 = phy_tree(physeq1)
ape::write.tree(tree1, "~/path/to/new/tree1.tree")
```

**Comment by maculatus** [comment]
Thanks

**Comment by dridk** [comment]
Ok. 
It seems there are other format where metadata can be embeded. Any idea ?
