### ISSUE TITLE
plot_heatmap taxonomic label not working

### ISSUE THREAD

**Issue by mpricketts** [joey711/phyloseq#600]
Hello,
I am writing because for some odd reason or other, when I try to use the simple plot_heatmap code as follows:
plot_heatmap(data, "NMDS", "bray", sample.label="Treatment", sample.order="Treatment", taxa.label="Order")
it still results in a heatmap with OTU's on the y-axis, not Order.

I made "data" with the following code:
biom <- import_biom("otu_table.biom", parseFunction = parse_taxonomy_greengenes)
map <- import_qiime_sample_data("MPR_map4.txt")
data <- merge_phyloseq(biom, map)

When I upload the GlobalPatterns data, it works fine, just like the example provided.
Both the "GlobalPatterns" and "data" phyloseq return the same summary:
Length    Class     Mode 
       1 phyloseq       S4

Are the files somehow different and not allowing me to group taxonomic groups??  
Please help!!
Thank you, 
Mike

**Comment by joey711** [comment]
It does sound like there's something fishy in your data.

Please post a MRE somehow, perhaps de-identified RDS binary of the phyloseq object. Otherwise it is very difficult to diagnose.

**Comment by mpricketts** [comment]
How would I go about creating that file?  I tried uploading the .biom and mapping files, but .biom is not a supported file type.

**Comment by husenzhang** [comment]
Mike -
Try:  taxa.label="Rank6".

**Comment by mpricketts** [comment]
Thanks for your response husenzhang!  But unfortunately I get the same result.

**Comment by michberr** [comment]
@mpricketts what is the output of colnames(tax_table(data)) ? These are the default column names of your taxonomy table. You will probably want to relabel these as kingdom, phylum, class etc . . . 
For example: 
```colnames(tax_table(data)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")```


I believe that all taxa.label does is change the label of the OTU. If you want to instead group your OTUs at the Order level and only show a heatmap of your Orders, you should first apply the `tax_glom` function.

**Comment by mpricketts** [comment]
Hey michberr!  Thank you for your reply.  tax_glom worked!  And now when I use "taxa.label="Order", it actually changes the y-axis label to "Order" and the individual rows to their Order names.  This did not happen before (it was always just "OTU")  Great!

One more question.  Is there a way to label the rows as Phylum_Class_Order instead of just Order and group them phylogenetically?

Thanks again!!

**Comment by michberr** [comment]
You can create a new column in your taxonomy table that pastes together the phylum, class, and order. 

`newrank <- paste(tax_table(data)[ ,"Phylum"], tax_table(data)[ ,"Class"], tax_table(data)[ ,"Order"], sep = "_") 
tax_table(data) <- cbind(tax_table(data), newrank) 

You can then pass in "newrank" instead of "order" into tax_glom

If you want to order them phylogenetically you will need to construct a phylogenetic tree. this isn't straightforward, as youve combined several OTUs into a group.

**Comment by mpricketts** [comment]
Great!  Thanks for the help!! You're awesome!

**Comment by mpricketts** [comment]
Ok. This just keeps getting weirder.
As worked out above, using tax_glom worked for Order.  It also works for Family, Class and Phylum.  However, it does NOT work for Genus.  Again, it defaults back to just OTU.
Here is the code I am using:

rm(list = ls())
setwd("~/Box Sync/Work/Professional/R/Phyloseq")

require(grid)
library(phyloseq)
require(ggplot2)
require(vegan)
require(RColorBrewer)
require(gridExtra)

biom <- import_biom("otu_table.biom", parseFunction = parse_taxonomy_greengenes)
map <- import_qiime_sample_data("MPR_map4.txt")
data <- merge_phyloseq(biom, map)

data_Gen <- tax_glom(data, taxrank="Genus")
plot_heatmap(data_Gen, "NMDS", "bray", sample.label="Treatment", sample.order="Treatment", taxa.label="Genus")

data_Fam <- tax_glom(data, taxrank="Family")
plot_heatmap(data_Fam, "NMDS", "bray", sample.label="Treatment", sample.order="Treatment", taxa.label="Family")

data_Ord <- tax_glom(data, taxrank="Order")
plot_heatmap(data_Ord, "NMDS", "bray", sample.label="Treatment", sample.order="Treatment", taxa.label="Order")

data_Class <- tax_glom(data, taxrank="Class")
plot_heatmap(data_Class, "NMDS", "bray", sample.label="Treatment", sample.order="Treatment", taxa.label="Class")

data_Phylum <- tax_glom(data, taxrank="Phylum")
plot_heatmap(data_Phylum, "NMDS", "bray", sample.label="Treatment", sample.order="Treatment", taxa.label="Phylum")

I have no idea why the Genus level doesn't act like the other levels.  Any help would be appreciated.

Thanks!
