### ISSUE TITLE
Error in asMethod(object) : Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

### ISSUE THREAD

**Issue by EOneita** [joey711/phyloseq#601]
Hello,

I'm trying to import a frankly massive biom file into R, and was wondering if this error is because the file is too large, or whether the command I'm applying to it is faulty.

Here is the code:
```
mybiomfile <- "~/Desktop/otu_table.biom"
read_biom(mybiomfile)
biom = import_biom(mybiomfile, parseFunction = parse_taxonomy_greengenes)
```
And then "Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105"

Any help would be greatly appreciated! Thank you.

PS The specs of the biom object are:
biom object. 
type: OTU table 
matrix_type: sparse 
3786522 rows and 3012 columns

**Comment by joey711** [comment]
That is pretty large.  The error statement appears to confirm that you have a memory issue. You'll most-likely need more memory to analyze that dataset as-is. Most likely you are not actually going to do much with all ~4-million taxa entries, and many of those probably should have been filtered out as noise before it got to this point. To this end, I recommend using [DADA2](http://benjjneb.github.io/dada2/). The paper is coming out very soon, but a draft is available and the package is released on Bioconductor today or tomorrow.

Minor point, your code also has an error. The second line is not doing anything except importing an extra time and printing the output to the std-out. The output of `import_biom` on the third line is really what you want. The updated code would look something like the following, with some extra summary commands added.

```S
mybiomfile <- "~/Desktop/otu_table.biom"
biom1 = import_biom(mybiomfile, parseFunction = parse_taxonomy_greengenes)
# Lets check some things
class(biom1)
print(biom1)
nsamples(biom1)
ntaxa(biom1)
rank_names(biom1)
sample_variables(biom1)
```

Hope that helps. I'll close for now, as this is not an issue with phyloseq directly. Thanks for your interest and feedback!

**Comment by EOneita** [comment]
Thank you very much for your help! I’ll take a look at DADA2 and run the dataset through it. That makes sense to me. I’m also not surprised that I had an error- I was a little confused and did think the code seemed strangely redundant.

Thank you again!
