### ISSUE TITLE
How are taxon abundances parsed when importing JSON formatted QIIME BIOM files into phyloseq?

### ISSUE THREAD

**Issue by jbjharvey** [joey711/phyloseq#602]
Hi Joey,

I've been importing BIOM files (MiSeq data processed in QIIME) into phyloseq, after first converting them to JSON, as described in the tutorial.

example: import_biom("NGSdata_json.biom", parseFunction = parse_taxonomy_default, parallel = TRUE)

When I look at the resulting otu table (in R, after importing with phyloseq), the sequence abundances are whole numbers, rather than the relative abundance percentages produced when I use 'summarize_taxa.py' in QIIME. Additionally, resulting phyloseq otu table numbers are not identical to (although they may be roughly proportional to) absolute numbers of sequences returned when I specify '-a' when running 'summarize_taxa.py' in QIIME.

So, my question is:
How are taxon abundances parsed when importing QIIME produced, JSON formatted BIOM files into phyloseq?

Thanks in advance for your guidance,

Julio

**Comment by joey711** [comment]
phyloseq importers do not modify the values present in the biom file. If you find that this has happened, it is a bug, and you should report it.

The philosophy of phyloseq is to let the user make decisions about appropriate transformations of the abundance values in tables based on their knowledge of the data and analysis goals, and to provide tools to help make that easy, transparent, and reproducible. 

I will close this for now, as there's no bug, issue, or feature request. If you do find that there is a mistake or missing data after import, please post again here a MRE, and I'll reopen.

cheers and good luck!

**Comment by jbjharvey** [comment]
Thanks Joey, I'll look into it further,

Julio
