### ISSUE TITLE
Question about tax_glom functionality

### ISSUE THREAD

**Issue by gabuali** [joey711/phyloseq#604]
Hi Joey,

can tax_glom collapse OTU counts to lowest _known_ taxonomic rank?  E.g. if tax_glom is set to 'species', then collapse to 'species' if 'species' taxonomy is known and if not then collapse to next lowest known rank, 'genus' through 'phylum'.  Thus creating a count table for terminal nodes.  

many thanks!

galeb

**Comment by joey711** [comment]
I don't think it does this, and I'm not sure I would recommend it for any purpose other than perhaps making a nice plot for a specific context. 

It certainly is possible to define a function that loops over lowest known taxomic ranks for each OTU, and then collapses any that have the same lowest-rank string. The function that does the internals of `tax_glom` is what you would use here, `merge_taxa`.

Cheers

joey
