### ISSUE TITLE
Stack the same bacteria in the bar graph. 

### ISSUE THREAD

**Issue by kelvinfrog** [joey711/phyloseq#605]
So I am following the example following this link http://joey711.github.io/phyloseq/import-data. But I have a question, is there a way that I can have all the samples showing the bacteria Family in the same order such as starting with "a" and end with "y" for all samples. 

![rplot01](https://cloud.githubusercontent.com/assets/11352733/14792006/5de4b7aa-0ae6-11e6-917f-d8c61cd4319c.png)
And here is the code I used to generate this graph and it is pretty much the same code in the tutorial. 

> otumat = matrix(sample(1:100, 100, replace = TRUE), nrow = 10, ncol = 10)
> otumat
> 
> rownames(otumat) <- paste0("OTU", 1:nrow(otumat))
> colnames(otumat) <- paste0("Sample", 1:ncol(otumat))
> otumat
> 
> taxmat = matrix(sample(letters, 70, replace = TRUE), nrow = nrow(otumat), ncol = 7)
> rownames(taxmat) <- rownames(otumat)
> colnames(taxmat) <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus", 
>                       "Species")
> taxmat
> 
> library("phyloseq")
> OTU = otu_table(otumat, taxa_are_rows = TRUE)
> TAX = tax_table(taxmat)
> OTU
> TAX
> 
> physeq = phyloseq(OTU, TAX)
> physeq
> 
> plot_bar(physeq, fill = "Family")

**Comment by joey711** [comment]
This question is the same as in another recent thread about [controlling color stacking in phyoseq `plot_bar`](https://github.com/joey711/phyloseq/issues/595).

Will close for now as redundant, unless something else comes up. Please check previous threads before posting something new. Thanks!
