### ISSUE TITLE
plot_heatmap renders blurry graph in Adobe Illustrator CC

### ISSUE THREAD

**Issue by analongo** [joey711/phyloseq#606]
Hi 

I'm having this problem with an Rplot produced using function plot_heatmap in phyloseq.
The pdf file looks 'ok' in Adobe Acrobat, looks 'ok' in Illustrator CS5 but colored boxes are not vectorized, then in Illustrator Creative Cloud the colored boxes are completely blurry. Resolution problem? any ideas on how to fix this? I've tried saving as eps, same results.
[Rplot.pdf](https://github.com/joey711/phyloseq/files/238625/Rplot.pdf)

**Comment by joey711** [comment]
the output of `plot_heatmap` is a ggplot2 object. This means you can use the `ggsave` function, which allows you to render the plot at any arbitrary size (speced in inches), and most standard formats, including eps and pdf, both of which are vectorized.

Your code would look something like this

```S
# upstream code defining phyloseq object here, call it `physeq1`
p1 = plot_heatmap(physeq`1, ...)
ggplot2::ggsave("~/path/to/myFigFileName.pdf", p1, width = 9, height = 6)
```

Hope that helps!
