### ISSUE TITLE
Creating a phylum proportion column

### ISSUE THREAD

**Issue by wurth13** [joey711/phyloseq#616]
Hi! 
So I've tried to figure this out using my Phyloseq data and my OTU tables I've created outside Phyloseq (but, they never had the ease of taxonomy level access) & cannot sort out how to actually calculate the proportions for something like Firmicutes in a sample. I can easily generate plots, but I'd like to be able to find the exact value &  even possible learn how to subset this as something like a column so that I can then create a scatterplot of Firmicutes and Bacteroidetes and see how the ratios compare between samples. 

Does anyone know how to do this? I see these values being reported all the time, but cannot find code for how to do this.

Thanks much in advance!

**Comment by jeffkimbrel** [comment]
The way I see it, there are two equally convenient ways. The first is to use `psmelt` and `aggregate` to combine everything together (which I won't show the code for).

But another way that is easier to conceptualize in the `phyloseq` framework is just to glom everything together into a new OTU table, and then change the name of the taxa to the phyla (or whatever level you used to glom (or higher)). 

For example, to create an "phylum" table (rather than an "OTU" table):

```
phyloGlom = tax_glom(phyloObject, "phylum")
glomTax = tax_table(phyloGlom)[,"phylum"]
glomOTU = otu_table(phyloGlom)
glomTable = merge(glomOTU,glomTax,by=0,all=TRUE)
rownames(glomTable) = glomTable[,"phylum"]
glomTable$Row.names = NULL
glomTable$phylum = NULL
```

This will make a table with total counts for samples in columns, and phyla in rows. 

If you would rather it be in percentages by column (sample), then:

```
glomTable = glomTable/colSums(glomTable)
```

Lastly, to plot a scatter plot of say Firmicutes vs Bacteroidetes, try this:

```
glomTable2 = as.data.frame(t(glomTable))
ggplot(glomTable2,aes(Bacteroidetes, Firmicutes)) + 
  theme_bw() +
  geom_point(size=2)
```

Let me know if that makes sense, or if you need to know what each line is actually doing.

Jeff

**Comment by jeffkimbrel** [comment]
FYI, there was an error above, but has been corrected now.

**Comment by wurth13** [comment]
Hi Jeff----this in immensely helpful & I follow most of the first part, but unfortunately I am getting the error:
> colSums(glomTable)
Error in base::colSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be numeric
following the command: glomTable2 = glomTable / rep(colSums(glomTable), each = nrow(glomTable))

I cannot sort out why this is given the table of glomTable is certainly containing numeric values in the columns.

If you happen to have R knowledge that understands why this might be, would appreciate the extra help.

Thanks again!
Renee

**Comment by jeffkimbrel** [comment]
If you don't have too many samples, would you mind posting the results of `head(glomTable)`? 

Also, what is the taxonomic name you are using... I used `phylum` in my example because that is how my original OTU table was labelled. If yours is at all different (like `Phylum` or `PHYLUM`), then don't forget to also change the `glomTable$phylum = NULL` line to your *exact* taxa name. Failing to do so will leave the phylum names in the new table, which are of course not numeric, and you will get the error that you posted.

Jeff

**Comment by wurth13** [comment]
Yep, I made those changes (was just capitalized the P).
This is what my table looks like::
                   S1   S10   S11   S12   S13   S14   S15   S16   S17   S18   S19
Actinobacteria   1318    56  1935  2505    62    39 13721  1272 10104   242   180
Firmicutes      18319 21588 10667 18386 21781 20014  6247 13284 11671 21460 21111
Verrucomicrobia   503     1  9141   712     1   231  2014  1103    34     2   159
Bacteroidetes    1624   218   186   274   173   560    14  4478    59   141    70
Proteobacteria     72   168    43    53     6   463    29  1690     6   143    19
unclassified       38    39    31    32    26   680    21   104   133     6   423

So in my mind these are numeric & I don't quite know what the issue would be.

Thank you!!
Renee

**Comment by jeffkimbrel** [comment]
Do you mind saving as an R object and putting somewhere I can download `save(glomTable,file="glom.Rda")`, and then send the `glom.Rda` file. I'm sure it is something simple.

Alternatively, you can try these two lines to replace the one line that is giving you troubles... it is just another way to convert to percentages by column sums, but it will convert to a matrix, which you need to convert back to a dataframe:

```
glomTable2 = scale(glomTable, center=FALSE, scale=colSums(glomTable))
glomTable2 = as.data.frame(glomTable2)
```

**Comment by wurth13** [comment]
Hi Jeff!
So I was about to send you the file, when my laptop crashed----& now suddenly the exact same code is working just fine!

Thank you so much for the help---saved me oodles of time & confusion :)

**Comment by jeffkimbrel** [comment]
Excellent... glad it worked out!

**Comment by GeoMicroSoares** [comment]
@benjjneb 
Sorry for reopening this issue. Am getting a weird error after using tax_glom() on my phyloseq as @jeffkimbrel suggested:
```
> phyloGlom = tax_glom(ps, "Phylum")
> glomTax = tax_table(phyloGlom)[,"Phylum"]
> glomOTU = otu_table(phyloGlom)
> glomTable = merge(glomOTU,glomTax,by=0,all=TRUE)
(...)
  TGGGGAATATTACACAATGGAGGAAACTCTGATGTAGCAACGCCGCGTGGAGGATGACACATTTCGGTGCGTAAACTCCTTTTATTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGCGTAAAGCGCATGTAGGCGGTCTTGTAAGTTGGGTGTGAAAGCCTATGGCTCAACCATAGAACT ...
1                                                                                                                                                                                                                                                              0
2                                                                                                                                                                                                                                                              0
3                                                                                                                                                                                                                                                              0
4                                                                                                                                                                                                                                                              0
5                                                                                                                                                                                                                                                              0
6                                                                                                                                                                                                                                                              0
  GCGCGAAACCTTCGCAATGCGCGAAAGCGTGACGAGGCTACCCGGAGTGCTTCTTGAAGAAAGAAGCTGTTGTCAGTGTTTAACTAGCCTGACGAGTAAGGAGAGGGCAAGGCTGGTGCCAGCCGCCGCGGTAAAACCAGCTCTTCAAGTTGTCGGGACGATTACTGGGCTTAAAGAGTCCGTAGCCGGTTTAGCAAGTCCTTGGTAAAATCTGGCAGCTTAACTGTCAGTACGCTAGGGAAACTACTTT ...
1                                                                                                                                                                                                                                                              0
2                                                                                                                                                                                                                                                              0
3                                                                                                                                                                                                                                                              0
4                                                                                                                                                                                                                                                              0
5                                                                                                                                                                                                                                                              0
6                                                                                                                                                                                                                                                              0
  Phylum
1   <NA>
2   <NA>
3   <NA>
4   <NA>
5   <NA>
6   <NA>
```
Phyloseq object build as described [here](https://github.com/joey711/phyloseq/issues/851).

What can I do about this?

Thanks!
