### ISSUE TITLE
phylogenetic tree without bubbles but with species names

### ISSUE THREAD

**Issue by lfaller** [joey711/phyloseq#617]
Hi all,

I would like to plot a phylogenetic tree with just the species names but no bubbles. It seems I can do either "species names + bubbles" or "no species names and no bubbles", but I can't figure out how to keep species names without keeping the bubbles.

```
data(esophagus)

# no labels no bubbles
plot_tree(esophagus,
          'treeonly',
          ladderize = 'left')

# labels and bubbles
plot_tree(esophagus, 
          ladderize = "left",
          label.tips = "taxa_names",
          text.size = 3)
```

Since I am not interested in colors, the last command just gives me a bunch of black circles which seem confusing in the figure and I'd like to remove them:

![screen shot 2016-05-25 at 4 19 59 pm](https://cloud.githubusercontent.com/assets/7854149/15554982/90c3efae-2294-11e6-8c71-1af1166b9036.png)

I appreciate any advice you might have!

Best,
~Lina

**Comment by joey711** [comment]
https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-want-a-phyloseq-graphic-that-looks-like
