### ISSUE TITLE
Error in `rownames<-`(`*tmp*`, value = c("sp1", "sp0")) : length of 'dimnames' [1] not equal to array extent

### ISSUE THREAD

**Issue by ngarud** [joey711/phyloseq#619]
Hello,

I'm trying to create a phyloseq object based on Metaphlan2 output so that I can use the inbuilt functions to create a heatmap. However I'm unable to use the 'subset' command. I'm pasting my code below as well as a link to the input data file. I really do appreciate your help! Also the version of Phyloseq I'm using is ‘1.14.0’. 

Data is here: https://www.dropbox.com/s/4w6zhspayoyt9wt/allSamples_merged_speciesOnly.txt?dl=0

Code is here:

library(phyloseq); packageVersion("phyloseq")
library(ggplot2); packageVersion("ggplot2")
library(stringr)

d=read.table("allSamples_merged_speciesOnly.txt")

######################
# Create phyloseq object  
######################

# make the taxonomy table                                                                                                                                     
classification=str_split_fixed(d$V1, "\\|",7)
colnames(classification)=c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus","Species")

labels=c()
for (i in 1:length(classification[,1])){
  labels=c(labels,(paste('OTU', i, sep='')))
}

rownames(classification)=labels
classification2=as.matrix(classification)

# make the OTU table                                                                                                                                          
OTU_tmp=d[,2:15]
sample_tmp=c('sample1','sample2','sample3','sample4','sample5','sample6','sample7','sample8','sample9','sample10','sample11','sample12','sample13','sample14'\
)
colnames(OTU_tmp)=sample_tmp
rownames(OTU_tmp)=labels
OTU_tmp2=t(OTU_tmp)
#OTU_tmp2=as.numeric(OTU_tmp2)                                                                                                                                
sampleNumber=c(1:14)
sample_tmp_df=data.frame(sampleNumber)
rownames(sample_tmp_df) = sample_tmp

ps=phyloseq(otu_table(OTU_tmp2, taxa_are_rows=FALSE), sample_data(sample_tmp_df), tax_table(classification2))

#################
# Create heatmap  
#################
gpt <- subset_taxa(ps, Kingdom=="k_Bacteria") # I AM STUCK HERE! 
#ERROR MESSAGE: Error in `rownames<-`(`*tmp*`, value = c("sp1", "sp0")) : length of 'dimnames' [1] not equal to array extent

gpt <- prune_taxa(names(sort(taxa_sums(gpt),TRUE)[1:300]), gpt)
plot_heatmap(gpt, sample.label="sampleNumber")

Thanks!
Nandita

**Comment by michberr** [comment]
Hey Nandita! 

R has terrible syntax for regular expressions :/ A backslash won't actually work as an escape for special characters. Instead you need to use brackets. For example:

```
d <- read.table("Downloads/allSamples_merged_speciesOnly.txt")
classification <- str_split_fixed(d$V1, pattern = "[|]", n = 7)
```

If you didn't already know about it, the `View` function is pretty useful for checking to see whether your data frame looks like you think it does. 

The only other bug in your code is that it looks like there are actually two dashes between the taxonomic level abbreviation and the taxonomy, so your subset_taxa line should look like this:

```
gpt <- subset_taxa(ps, Kingdom == "k__Bacteria")
```

The font here makes it look like one continuous underscore, but there are two there, i promise.

Let me know if this doesn't work for you.

Best,
Michelle

**Comment by michberr** [comment]
One last note, if you wanted to remove the prefixes for your taxonomy, this would work: 
```
apply(classification, MARGIN = 2, FUN = function(x) { str_split_fixed(x, "__", 2)[ ,2] } )
```

**Comment by ngarud** [comment]
Dear Michelle,

Thank you very much for your help! Sorry to take up your time with typos. I
now have some very beautiful plots from phyloseq!

Nandita
