### ISSUE TITLE
extracting newick from phyloseq

### ISSUE THREAD

**Issue by naarkhoo** [joey711/phyloseq#620]
Basically, I would like to extract the newick format from my object after trimming, For example

```
data(esophagus)
mytree = esophagus
mytree = prune_taxa(taxa_names(mytree)[1:4], mytree)
plot_tree(mytree,  label.tips = "taxa_names")

```
How can I extract the newick format of mytree

my ultimate goal is extracting the pairwise distance between each leaf,
so I looked into

```
bb = tree_layout(mytree)
bb
```
but I couldn't figure out what is `edge.length` and `xlef` and `xright`,

**Comment by naarkhoo** [comment]
the function `write.tree` from ape library is what I needed
`write.tree(phy = phy_tree(mytree))`

**Comment by joey711** [comment]
Yep!

And if you don't want to load the entire ape package just to write out the tree you just pruned with phyloseq, you can use:

```R
data(esophagus)
prunedEso = prune_taxa(taxa_names(esophagus)[1:4], esophagus)
ape::write.tree(phy = phy_tree(prunedEso), file = "treefileName.tre")
```
