### ISSUE TITLE
plot_ordination variation suggestion?

### ISSUE THREAD

**Issue by ishengtsai** [joey711/phyloseq#622]
Hi,

I have been playing around with plot_ordination and got the following:

p1 <- plot_ordination(GP1, ordu, color = "Patient", label="Patient") + geom_line(aes(fill = "Patient")) 
p2 <- plot_ordination(GP1, ordu, color = "TimePoint", label="Patient") 
multiplot(p1,p2)

The output is attached. Now, I was wondering if it's possible to do something like:

plot_ordination(GP1, ordu, color = "TimePoint", label="Patient")  + geom_line(aes(fill = "Patient")) 

to connect the points according to "Patient" category rather than "Timepoint" category in the figure below (unfortunately it will only connect by whichever vector is assigned in plot_ordination) ? That would be great!

So far it seems I can't combine the two plots into one. 

Best,
Jason

![image](https://cloud.githubusercontent.com/assets/5182142/15935073/a189a79c-2e98-11e6-8242-d9a2325d3252.png)

**Comment by joey711** [comment]
https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-want-a-phyloseq-graphic-that-looks-like
