### ISSUE TITLE
Taxonomy table from MED (minimum entropy decomposition) output

### ISSUE THREAD

**Issue by sfeds** [joey711/phyloseq#630]
Hi,
I'm working with sequencing data provided by a company that works with a mothur/MED pipeline.
This results in a series of sequence "nodes" (a list of numbers e.g. 115, 2330...), that can later be classified (in my case in RDP). So it returns the nodes with the number of total hits, a lineage line and a species line, such as:
- Lineage: Bacteria;Proteobacteria;Gammaproteobacteria;Pseudomonadales;Moraxellaceae;Moraxella;
- Species: Moraxella nonliquefaciens(15);Moraxella catarrhalis(10);Moraxella catarrhalis BBH18(4);Moraxella sp. OTG 46(1);

I can subdivide the lineage string to get the different levels (Domain.... to species), though not levels are available for all nodes. 
As for the species line, I'm not sure how realistic it is that it goes in that deep classification, so I could keep the first hit (some nodes have species lines of up to 90 items).
Furthermore, some nodes have similar taxonomy.

So now my questions are, in order to build a "phyloseq-friendly" tax_table:
1. How should I taxonomically annotate each sequence variant? The nodes are just a number, therefore not taxonomically informative. 
2. Should I make a short version of the string to use as rownames?
3. Should I aggregate those nodes with similar taxonomy for my whole-experiment analysis? Or keep the full list?

Any help will be highly appreciated!
PS: A short overview of the MED output

![picture1](https://cloud.githubusercontent.com/assets/20225551/16489433/d093d68c-3ed5-11e6-8709-c9d7fef08eac.png)

**Comment by joey711** [comment]
Is there an example set of output files, or a file format definition I could see for MED output? That screenshot is a little helpful, but not enough to build a new import_ function on.

I'll keep this open as a feature request for `import_med`.
