### ISSUE TITLE
Rank Abundance plot

### ISSUE THREAD

**Issue by ncpalmateer** [joey711/phyloseq#631]
I'm trying to make a rank abundance plot for a specific group of samples.  The only trouble I'm having is that the label on the x-axis is coming up as the OTU identifier, rather than the actual name of the taxon.  I'm sure there is a relatively simple fix to this, however I'm still very new to R/phyloseq and haven't figured it out yet.  Any help is appreciated.  

The code I used is:

N <- 20
barplot(sort(taxa_sums(Biopsy), TRUE)[1:N]/nsamples(Biopsy), las=2)

Biopsy is the dataset.  

Thanks
![screen shot 2016-06-30 at 12 10 48 pm](https://cloud.githubusercontent.com/assets/20228722/16495495/bc1f6c44-3ebb-11e6-8fb9-d470394b6dc9.png

**Comment by jeffkimbrel** [comment]
This isn't exactly what you asked for, but it's how I do my rank abundance curves using the mean of each, rather than the total reads.

```
# this converts taxa counts in each sample to a percentage
phyloTemp = transform_sample_counts(phyloObject, function(x) 1e+02 * x/sum(x))
  
clusterData = psmelt(phyloTemp)
clusterData = filter(clusterData,Abundance > 0)

# this is where the mean is calculated and the taxa to display is chosen
clusterAgg = aggregate(Abundance ~ OTU + phylum,data=clusterData,mean)

# filtering and picking the number to display
clusterAgg = clusterAgg[order(-clusterAgg$Abundance),][1:100,]

ggplot(clusterAgg,aes(x=reorder(OTU,-Abundance),y=Abundance)) +
    geom_point(aes(color=phylum),size=3) + 
    theme(axis.ticks = element_blank(), axis.text.x = element_blank()) +
    scale_y_log10()
 ```

![rplot](https://cloud.githubusercontent.com/assets/10132972/16541346/f7a832ee-4034-11e6-8025-cc2ff878e49a.png)

This is a bare-bones example. You can edit the axis and colors and everything with usual `ggplot` options.

**Comment by joey711** [comment]
https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-want-a-phyloseq-graphic-that-looks-like
