### ISSUE TITLE
merging phyloseq files

### ISSUE THREAD

**Issue by yugi1001** [joey711/phyloseq#632]
Hi,

I am processing my data in batches and hoping to merge them at the phyloseq file stage. But the merge_phyloseq did not seem to merge the PS file. Can someone point out what I am doing wrong or is there a better step where the batch files can be merged for final analysis in Phyloseq. I am using DADA2 for the 16s data processing.

thanks

**Comment by spholmes** [comment]
In order to find what you are doing wrong, you need to send us the code
that you are using.
Have you looked at the example of creating a phyloseq object in the
workflow paper?

http://f1000research.com/articles/5-1492/v1

Best
Susan

On Fri, Jul 1, 2016 at 7:09 AM, yugi1001 <notifications@github.com> wrote:

> Hi,
>
> I am processing my data in batches and hoping to merge them at the
> phyloseq file stage. But the merge_phyloseq did not seem to merge the PS
> file. Can someone point out what I am doing wrong or is there a better step
> where the batch files can be merged for final analysis in Phyloseq. I am
> using DADA2 for the 16s data processing.
>
> thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joey711/phyloseq/issues/632>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABJcvbKTy8T96anEmS648eeVAXsIOMexks5qRR-NgaJpZM4JDLUc>
> .
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Samter Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by jeffkimbrel** [comment]
Thanks for posting that article, Susan. It's a very helpful resource!

**Comment by yugi1001** [comment]
Hi Susan,

Thanks for the quick response. I am aware of the F1000 paper though I must admit have not read it.

I am following the DADA2 protocol that was available @ benjjneb.github.io/dada2/tutorial.html

I am able to create a phyloseq object and use for further analysis without any problems. Where I am facing issues is in merging two phyloseq objects. I have about 74 fastq files and I am doing the analysis on my laptop and therefore the program would crash if I tried to analyse all at the same time. So I am currently doing it in batches of 12 each and planned to merge them in the end. Hoping the merge_phyloseq would then give me one consolidated file. I am not sure if this is indeed the best way to do it. the code is below

> ps1
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 490 taxa and 12 samples ]
sample_data() Sample Data:       [ 12 samples by 19 sample variables ]
tax_table()   Taxonomy Table:    [ 490 taxa by 6 taxonomic ranks ]
> ps2
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 618 taxa and 12 samples ]
sample_data() Sample Data:       [ 12 samples by 19 sample variables ]
tax_table()   Taxonomy Table:    [ 618 taxa by 6 taxonomic ranks ]


> ps_x <- merge_phyloseq(ps1, ps2)
Warning messages:
1: In `[<-.factor`(`*tmp*`, ri, value = c(4L, 1L, 3L, 9L, 5L, 6L, 9L,  :
  invalid factor level, NA generated
2: In `[<-.factor`(`*tmp*`, ri, value = c(4L, 1L, 3L, 9L, 5L, 8L, 6L,  :
  invalid factor level, NA generated
3: In `[<-.factor`(`*tmp*`, iseq, value = c(10.1, 3.5, 3.4, 9.7, 5.1,  :
  invalid factor level, NA generated
> ps_x
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 871 taxa and 19 samples ]
sample_data() Sample Data:       [ 19 samples by 31 sample variables ]
tax_table()   Taxonomy Table:    [ 871 taxa by 12 taxonomic ranks ]


I am running R version
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair  

As you can see the number of samples reduced when I merged and so did the number of variables. The taxonomic ranks doubled. I would like to merge all the 6 ps files which are subsets of the larger data. How would you recommend people with limited compute power handle large data?

TIA

**Comment by spholmes** [comment]
TIA
If this has to do with the merge of the sample_data as I guess it is from
the error
messages, I think you need to create the factor levels to be inclusive of
all the
levels present in the data. You can try it out on only that the factor
variables of the sample
data (I'm calling them c1,c2) . Create a new factor with  the two existing
sample factors c1,c2 as
c1f = factor(c1, levels=c(levels(c1),levels(c2)))
c2f = factor(c2, levels=c(levels(c1),levels(c2)))

replace c1 and c2 with c1f and c2f in the sample data.

This is due to the fact that the two factors do not have the same levels
so you can't combine those data.

As you haven't provided the data I am afraid I can't provide more details,
let us know if this works,
Susan




On Sun, Jul 3, 2016 at 8:45 PM, yugi1001 <notifications@github.com> wrote:

> Hi Susan,
>
> Thanks for the quick response. I am aware of the F1000 paper though I must
> admit have not read it.
>
> I am following the DADA2 protocol that was available @
> benjjneb.github.io/dada2/tutorial.html
>
> I am able to create a phyloseq object and use for further analysis without
> any problems. Where I am facing issues is in merging two phyloseq objects.
> I have about 74 fastq files and I am doing the analysis on my laptop and
> therefore the program would crash if I tried to analyse all at the same
> time. So I am currently doing it in batches of 12 each and planned to merge
> them in the end. Hoping the merge_phyloseq would then give me one
> consolidated file. I am not sure if this is indeed the best way to do it.
> the code is below
>
> ps1
> phyloseq-class experiment-level object
> otu_table() OTU Table: [ 490 taxa and 12 samples ]
> sample_data() Sample Data: [ 12 samples by 19 sample variables ]
> tax_table() Taxonomy Table: [ 490 taxa by 6 taxonomic ranks ]
> ps2
> phyloseq-class experiment-level object
> otu_table() OTU Table: [ 618 taxa and 12 samples ]
> sample_data() Sample Data: [ 12 samples by 19 sample variables ]
> tax_table() Taxonomy Table: [ 618 taxa by 6 taxonomic ranks ]
>
> ps_x <- merge_phyloseq(ps1, ps2)
> Warning messages:
> 1: In [<-.factor(*tmp*, ri, value = c(4L, 1L, 3L, 9L, 5L, 6L, 9L, :
> invalid factor level, NA generated
> 2: In [<-.factor(*tmp*, ri, value = c(4L, 1L, 3L, 9L, 5L, 8L, 6L, :
> invalid factor level, NA generated
> 3: In [<-.factor(*tmp*, iseq, value = c(10.1, 3.5, 3.4, 9.7, 5.1, :
> invalid factor level, NA generated
> ps_x
> phyloseq-class experiment-level object
> otu_table() OTU Table: [ 871 taxa and 19 samples ]
> sample_data() Sample Data: [ 19 samples by 31 sample variables ]
> tax_table() Taxonomy Table: [ 871 taxa by 12 taxonomic ranks ]
>
> I am running R version
>
> R.version
> _
>
> platform x86_64-w64-mingw32
>
> arch x86_64
>
> os mingw32
>
> system x86_64, mingw32
>
> status
>
> major 3
>
> minor 3.1
>
> year 2016
>
> month 06
>
> day 21
>
> svn rev 70800
>
> language R
>
> version.string R version 3.3.1 (2016-06-21)
> nickname Bug in Your Hair
>
> As you can see the number of samples reduced when I merged and so did the
> number of variables. The taxonomic ranks doubled. I would like to merge all
> the 6 ps files which are subsets of the larger data. How would you
> recommend people with limited compute power handle large data?
>
> TIA
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joey711/phyloseq/issues/632#issuecomment-230199378>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABJcvaxGqg4S0wggcoeKHoKg24gMHIsrks5qSIH2gaJpZM4JDLUc>
> .
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Samter Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by benjjneb** [comment]
It would probably be easier for you to perform this merging before importing into the phyloseq object.

I'm not sure exactly how you split up your R code into these chunks, but what you want to do is just run `makeSequenceTable` on a list of all of the dada-class objects for every sample, or a list of the merged data.frames for each sample if you are merging paired-end reads.

That certainly won't be too large to hold in memory even on your laptop. One easy way to do that, while keeping memory requirements low, is too use the first block of samples to estimate your error rates, then loop over each sample individually, processing it with those error rates, and saving the output as a .rds, before reading those all back in to create a sequence table from.

A basic outline of this (pseudocode):

```
d0 <- dada(dereps[1:X, selfConsist=TRUE)
err <- d0[[1]]$err_out

for sam in samples:
  drpF <- derep(samF)
  drpR <- derep(samR)
  ddF <- dada(drp, err=err)
  ddR <- dada(drpR, err=err)
  merger <- mergePairs(ddF, drpF, ddR, drpR)
  saveRDS(merger, sam.rds)

mergers <- list()
for sam in samples:
  mergers <- c(mergers, readRDS(sam.rds))
names(mergers) <- samples

seqtab <- makeSequenceTable(mergers)
```

**Comment by yugi1001** [comment]
Hi Ben,

tried what you have suggested but run into the below problem. I am new to R and programming as well so it took me some time to get your pseudocode working.
The warning I get is that merger out put is not in the right format.

> seqtab <- makeSequenceTable(mergers)
Error in FUN(X[[i]], ...) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns. 

what I have run so far is as below
d0 <- dada(derepFs[1:2],err =inflateErr(tperr1, 3), selfConsist = TRUE)

err <- d0[[1]]$err_out

mergers = ''

for (i in seq_along(filtFs)) {
  drpF <- derepFastq(filtFs[i], verbose = TRUE)
  drpR <- derepFastq(filtRs[i], verbose = TRUE)
  ddF <- dada(drpF, err = err)
  ddR <- dada(drpR, err = err)
  merger <- mergePairs(ddF, drpF, ddR, drpR, verbose = TRUE)
  saveRDS(merger, file = paste(filtFs[i],'.rds')) 
}


mergers <- list()

filenames <- list.files(path, pattern="*.rds", full.names=TRUE)

for (file in filenames){
  mergers <- c(mergers, readRDS(file))
}


names(mergers) <- sample.names

### belowstep not working due to file format issues
seqtab <- makeSequenceTable(mergers)

**Comment by benjjneb** [comment]
That looks like it should work...

Can you report the output of the following commands, at the point where you are trying to run `makeSequenceTable`:

```
class(mergers)
length(mergers)
table(sapply(mergers, class))
```

**Comment by yugi1001** [comment]
Hi Ben,
see below

> class(mergers)
[1] "list"

> length(mergers)
[1] 54

> table(sapply(mergers, class))

character   integer   logical   numeric 
        6        36         6         6

**Comment by benjjneb** [comment]
The `mergers <- c(mergers, readRDS(file))` is messing up the structure of what should be a list of data.frames.

Replace the loop with this:

```
for (i in seq_along(filenames)){
  mergers[[i]] <- readRDS(filenames[[i]])
}
```

Does that fix the problem? You should get a list of 6 data.frames at the end.

**Comment by yugi1001** [comment]
Still a problem. Please see below:

> for (i in seq_along(filenames)){
+ mergers[[i]] <- readRDS(filenames[[i]])
+ }
> names(mergers) <- sample.names
> seqtab <- makeSequenceTable(mergers)
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Error in FUN(X[[i]], ...) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.
> dim(seqtab)
[1] 0 0

**Comment by yugi1001** [comment]
sorry, that messed up the format on pasting

> for (i in seq_along(filenames)){
+ mergers[[i]] <- readRDS(filenames[[i]])
+ }
> names(mergers) <- sample.names
> seqtab <- makeSequenceTable(mergers)
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Error in FUN(X[[i]], ...) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

> dim(seqtab)
[1] 0 0

**Comment by yugi1001** [comment]
posting again to make it more readable:

> names(mergers) <- sample.names

> seqtab <- makeSequenceTable(mergers)
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.

Error in FUN(X[[i]], ...) :   Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

> dim(seqtab)
[1] 0 0

**Comment by benjjneb** [comment]
Could you share the .rds files for the merger data.frames? That will make trouble-shooting a lot easier.

**Comment by yugi1001** [comment]
How do I share the files with you?

**Comment by benjjneb** [comment]
Sharing via dropbox or some file-sharing service.

You can also email them to me, I'm assuming they are not too big: benjamin.j.callahan AT gmail DOT com
