### ISSUE TITLE
Class Type Problems

### ISSUE THREAD

**Issue by heidi-ml** [joey711/phyloseq#635]
Hello,

I am having trouble figuring out how to join an otu table of samples (generated via iTagger and in a .txt format) and the metadata file (also in a .txt format) that includes a description of all samples. I uploaded the two .txt files into R and they appear under the Data area. When I try to run phyloseq, I get :

> OTU = otu_table(otu_table_fixed, taxa_are_rows, errorIfNULL = TRUE)
> Error in validObject(.Object) : 
>   invalid class “otu_table” object: invalid object for slot "taxa_are_rows" in class "otu_table": got class "standardGeneric", should be or extend class "logical"
> class(otu_table_fixed)
> [1] "data.frame"

How would I change the class so that I would be able to specify the otu table?

I also have the taxonomic description of each OTU within the otu table, as the last column, and am unsure of how to specific the tax_table as being the last column. Would I need to specify this or use a different command?

Any help or point towards more information would be very much appreciated.
Many thanks,
Heidi

**Comment by joey711** [comment]
http://joey711.github.io/phyloseq/import-data.html#phyloseq-ize_data_already_in_r
