### ISSUE TITLE
Simpson index

### ISSUE THREAD

**Issue by OUuctp** [joey711/phyloseq#637]
Hello,
I've been facing an issue with calculations of Simpson diversity index in Phyloseq. For a really diverse community (soil bacteria, see the attached file with counts) I am getting a value closer to 1 in Phyloseq, however when I am calculating Simpson using mothur with the same input data, I am getting values closer to 0. 
Can I get some explanation?
Thanks a lot
[final.database.summed.xlsx](https://github.com/joey711/phyloseq/files/354813/final.database.summed.xlsx)

**Comment by joey711** [comment]
Difficult to post this as a MRE, but you might at least provide the exact mothur commands you're using to get to your Simpson result. My first guess is that mothur is rarefying at some step. Until we see exactly the steps you're taking in both mothur and phyloseq, it is only a guess.

**Comment by joey711** [comment]
Also, it would be much better for you to share your data as a standard format (e.g. .csv, .biom, etc). Biom-format is preferred, as it is self-describing.

**Comment by OUuctp** [comment]
Mothur:
collect.single(shared=dada.shared, calc=chao-shannon-simpson-invsimpson, freq=10)
catchall()
summary.single(calc=nseqs-coverage-sobs-chao-shannon-simpson-invsimpson)

Phyloseq:
samdf <- data.frame(Samples = rep(c("soil"), each=3), Replica = rep(1:3))
samdf
#name change
rownames(samdf) <- colnames(final.seqtab.nochim.summed.norm)
ps <- phyloseq(otu_table(round(t(final.seqtab.nochim.summed.norm)), taxa_are_rows=FALSE),
               sample_data(samdf), tax_table(taxa))
ps
plot_richness(ps, x = "Samples") + geom_boxplot()

Shannon or Sobs correcpond, it is just Simpson which differs.

**Comment by benjjneb** [comment]
The term "Simpson index" is very confusingly sometimes used to refer to the numbers A and (1-A).

If you subtract the mothur numbers from 1 do they then equal the phyloseq numbers?

**Comment by OUuctp** [comment]
Looks like it is, actually. So that will be the explanation - Phyloseq displays 1-D whereas mothur displays D, right?
Thanks a lot for the clarification

**Comment by Gerlex89** [comment]
This is something that must be clarified as it's not intuitive at all. Something like changing the names of the measure from Simpson to Gini-Simpson would be enough.

The most direct reply to it, citing that it's like that in the Vegan package, is here: https://github.com/joey711/phyloseq/issues/940
