### ISSUE TITLE
Not show legend in Barplot

### ISSUE THREAD

**Issue by sfeds** [joey711/phyloseq#639]
Hi,
I'm trying to NOT show legend in barplot in the ggplot2 "geom_point" with "show.legend= FALSE", but it seems I don't manage to get it to work. I've also tried with the example data from phyloseq but also doesn't work:

data("GlobalPatterns")
gp.ch = subset_taxa(GlobalPatterns, Phylum == "Chlamydiae")

p = plot_bar(gp.ch, "Family", fill="Genus", facet_grid=~SampleType)
p + geom_point(aes(x=Family, y=Abundance), color="black", position="jitter", size=3, **show.legend = FALSE**)

Any tips? Thanks!

**Comment by jeffkimbrel** [comment]
Try 'theme(legend.position = "bottom")'.

**Comment by jeffkimbrel** [comment]
Sorry, this is why I shouldn't be in github before 7am, I meant:

theme(legend.position = "none")

**Comment by sfeds** [comment]
Brilliant, many thanks! (well, it is 15:30 here and I didn't know this, most probably, very simple issue...)
Have a good day!
