### ISSUE TITLE
alpha diversity plots

### ISSUE THREAD

**Issue by HSapers** [joey711/phyloseq#644]
Hi - I'd like to include additional alpha diversity metrics (shannoneven and simpsoneven) - is there an easy (I'm very new to R) to include calculations not present in the wrapper? Also, I noticed that in the output my samples are in a non-logical order - is there a way to specify the order of samples on the X-axis?

thanks!

**Comment by colinbrislawn** [comment]
Hello there,
I submitted a PR #568 that implements evenness metrics awhile ago. I'm still interested in adding these, so I'll touch base with @joey711 and see if we can get them into the next release.

**Comment by HSapers** [comment]
That's awesome @colinbrislawn. Would you mind sharing your code and a citation?

**Comment by colinbrislawn** [comment]
The code is over in #575, if you want to take a look.

These pages explain the metrics and offer citations:
http://www.tiem.utk.edu/~gross/bioed/bealsmodules/shannonDI.html 
http://www.tiem.utk.edu/~gross/bioed/bealsmodules/simpsonDI.html 

Ideally, this PR (pull request) would get merged and a minor release of phyloseq, but this is my first time developing R software, and I think I'm missing pieces... Any thoughts @joey711

**Comment by joey711** [comment]
Great, sorry @colinbrislawn for the delay. I'll try to take a look again and get it in soon.

Will close this issue for now, though.
