### ISSUE TITLE
PCoA with Euclidean distance fails with built-in "GlobalPatterns" dataset

### ISSUE THREAD

**Issue by amckinlay** [joey711/phyloseq#645]
```
> library("phyloseq")
> packageVersion("phyloseq")
[1] ‘1.16.2’
> data("GlobalPatterns")
> ordinate(GlobalPatterns, method = "MDS", distance = "euclidean")
Error in 1:(zero.eig[1] - 1) : NA/NaN argument
```

**Comment by joey711** [comment]
Please update to the latest package... also, it might be that MDS on euclidean distance is supposed to fail when applied to an OTU table like GlobalPatterns...

Will close for now...

**Comment by hk20013106** [comment]
Hi, 
I'm still receiving the same error message when running with v 1.25.3

> packageVersion("phyloseq")
[1] ‘1.25.3’
> data("GlobalPatterns")
> ordinate(GlobalPatterns, method = "MDS", distance = "euclidean")
Error in 1:(zero.eig[1] - 1) : NA/NaN argument

Any thought? Thanks!

**Comment by rachaelantwis** [comment]
Hi, did you manage to solve this? I'm having the same problem. Thanks.
