### ISSUE TITLE
plot_richness manual dataframe 

### ISSUE THREAD

**Issue by HSapers** [joey711/phyloseq#646]
Hi - I really like the output of the alpha diversity plots - but I would like to add a couple of statistics. I'm fairly new to R - but is there a way to have plot_richness work directly with an edited version of the dataframe output of estimate_richness? Specifically I'd like to add a plot of the number sequence reads for each sample as well as evenness estimators. 

Thanks

**Comment by joey711** [comment]
Yep, or rather, you can modify the data slot in the `plot_richness` output directly; for instance, adding columns or rows to the data.frame there.

```
p = plot_richness(physeq)
p$data
```

See also

https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-want-a-phyloseq-graphic-that-looks-like
