### ISSUE TITLE
Losing taxa upon addition of phy tree 

### ISSUE THREAD

**Issue by fjmob** [joey711/phyloseq#648]
Hi,

I am having trouble adding the phylogenetic tree to my phyloseq object.  When I add it, the phyloseq object loses a lot of taxa and I can't figure out why... Here's my script:

> biom = import_biom("otu_table_no_chloroplasts_or_mitochondria_rare198288.biom", parseFunction=parse_taxonomy_default)
> meta = import_qiime_sample_data("qiime.metadata_with_aphids_and_Bulk.txt")

before_tree=merge_phyloseq(biom, meta)

> before_tree
> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 79579 taxa and 40 samples ]
> sample_data() Sample Data:       [ 40 samples by 17 sample variables ]
> tax_table()   Taxonomy Table:    [ 79579 taxa by 7 taxonomic ranks ]
> 
> tree=read_tree("rep_set_aligned_pfiltered.midpoint.tree")
> after_tree = merge_phyloseq(biom, meta, tree)
> 
> after_tree
> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 399 taxa and 40 samples ]
> sample_data() Sample Data:       [ 40 samples by 17 sample variables ]
> tax_table()   Taxonomy Table:    [ 399 taxa by 7 taxonomic ranks ]
> phy_tree()    Phylogenetic Tree: [ 399 tips and 398 internal nodes ]

**Comment by joey711** [comment]
This means your tree is missing a lot of taxa that are present in the table. This is expected behavior.

https://rdrr.io/bioc/phyloseq/man/merge_phyloseq_pair-methods.html

```
A single component data object that matches x and y arguments. The returned object will contain the union of the species and/or samples of each. If there is redundant information between a pair of arguments of the same class, the values in x are used by default. Abundance values are summed for otu_table objects for those elements that describe the same species and sample in x and y.
```
