### ISSUE TITLE
ordinate sample in plot_bar

### ISSUE THREAD

**Issue by AndreaQ7** [joey711/phyloseq#650]
Dear all,

I'm learning how to use phyloseq step by step. At this moment I'm trying to use the function plot_bar and it works well BUT it plot my sample on the X axis not in the order that thay are in the sample_data.
How can i ask it to follow exactly the samples in the same order thay are in the sample_data?
thank you for your help

**Comment by grasshoppermouse** [comment]
Read up on ggplot2:

http://docs.ggplot2.org/current/

http://rstudio-pubs-static.s3.amazonaws.com/7433_4537ea5073dc4162950abb715f513469.html

**Comment by jeffkimbrel** [comment]
From what I remember, this isn't really a ggplot tweak, but rather a dataframe tweak.

Let's say you have a phyloseq object named `phyloObject`, and your samples are named as `SAMPLE` in your phyloseq object, you can `psmelt()` the object, and then order by your names:

```
df = psmelt(phyloObject)

samples = sample_names(phyloObject)
# or
samples = c("sample1","sample2","sample3",etc...)

# this orders your dataframe according the to "samples" list
df <- transform(df, SAMPLE = factor(SAMPLE, levels = samples))

ggplot(df,aes(x=SAMPLE,y=Abundance)) + 
  geom_bar(aes(fill=phylum),stat="identity")
```

**Comment by grasshoppermouse** [comment]
ggplot uses the order of the factor levels to order the bars (which is what your code does). A bit off topic, but Hadley is creating a new package that aims to make ordering factors and other factor operations a bit easier:

https://github.com/hadley/forcats

**Comment by AndreaQ7** [comment]
Thanks a lot for your help!!!!!
