### ISSUE TITLE
estimate_richness & split=TRUE

### ISSUE THREAD

**Issue by plebeau** [joey711/phyloseq#651]
Hi,

I am wondering if someone would be able to clarify for me when one would choose to set split=TRUE when estimating alpha diversity, versus leaving the default set to FALSE? 
From the documentation it looks like that the alpha diversity would be calculated per sample when split=TRUE but wouldn't that be what one wants all the time?

Thank you

**Comment by grasshoppermouse** [comment]
Looks like the default *is* TRUE:

https://github.com/joey711/phyloseq/blob/master/R/extend_vegan.R
