### ISSUE TITLE
Error in merge_samples by mean

### ISSUE THREAD

**Issue by bashma** [joey711/phyloseq#656]
Hi,
I'm using phyloseq on percentage data and I want to agglomerate samples by group means.
I tried:

```
>diagnosis.p14 <- merge_samples(ps.p14, "diagnosis", fun = mean)
>diagnosis.p14
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 26 taxa and 2 samples ]
sample_data() Sample Data:       [ 2 samples by 5 sample variables ]
>otu_table(diagnosis.p14)
OTU Table:          [26 taxa and 2 samples]
                     taxa are columns
           CD           p1         pos.p1 pos.1        Capo     gdTCR.p1    Cos.p1
fPAH     166.45          87.15      57.8  35.90375   16.1308     0.61460      14.20
IPAH     561.40         514.70     351.2 149.02473  130.7140    29.87613      23.35
```

Although I chose `mean` I think `sum` was chosen.

I did work around it using 

```
aggregate(otu_table(diagnosis.p14), list(otu_table(diagnosis.p14)$diagnosis, mean)
```

**Comment by michberr** [comment]
Hi @bashma,

I would consider whether your raw data format is actually in percentages, or more likely it is in counts. If you want to merge all of the samples in a group but some samples have 2x or maybe 10x the counts of other samples, averaging the counts as if each sample was sampled equally is not desirable. I believe this is why the `merge_samples` function defaults to summing.
