### ISSUE TITLE
Error converting file to DESeq format

### ISSUE THREAD

**Issue by Biancabrown** [joey711/phyloseq#658]
Hey Joey, 

First let me say great work! Following the tutorial has been teaching me a lot. 

I was woking on the dataset "study_1457_split_library_seqs_and_mapping.zip" using the DESeq2 with phyloseq tutorial. When I got to this function 

diagdds = DESeq(diagdds, test="Wald", fitType="parametric")

I got the error message below. 

"estimating size factors
Error in estimateSizeFactorsForMatrix(counts(object), locfunc = locfunc,  : 
  every gene contains at least one zero, cannot compute log geometric means"

I am not sure where I went wrong because when I checked the dataset after removing the None variable I got the same output as the tutorial.

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2505 taxa and 185 samples ]
sample_data() Sample Data:       [ 185 samples by 71 sample variables ]
tax_table()   Taxonomy Table:    [ 2505 taxa by 7 taxonomic ranks ]

Can you please advise?

-Best 
Bianca

**Comment by joey711** [comment]
See this answer on the FAQ page, and related links it posts:

https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-get-an-error-regarding-geometric-mean
