### ISSUE TITLE
Plot phyla and class in one stacked bar plot

### ISSUE THREAD

**Issue by hamahowa** [joey711/phyloseq#659]
Hello,

I would like to make a stacked bar plot that shows species by phylum, but I want to represent Proteobacteria by class to show Gammaproteobacteria, Alphaproteobacteria, etc. I cannot figure this out. Has anyone done this, and if so, would you mind sharing the code?

Thanks,
Doug

**Comment by joey711** [comment]
https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-want-a-phyloseq-graphic-that-looks-like
