### ISSUE TITLE
Plotting merged samples by sample variable

### ISSUE THREAD

**Issue by sreuter39** [joey711/phyloseq#660]
I have a phyloyseq object (physeq) with a sample variable called "Basin" where each sample is categorized as either A, B, or C. I merged samples according to another sample variable, "Type". After merging samples, I wanted to plot (plot_bar) the top 10 phyla of each "Type" with panels (facet_grid?) according to the "Basin" sample variable. However, I get an error message saying "object 'Basin' not found" with the below code. Any help would be much appreciated.

x1 <- merge_samples(physeq, "Type", fun=mean)
x2 <- transform_sample_counts(x1, function(x) x / sum(x) )
# glom to phyla level

x3 <- tax_glom(x2, taxrank="Phylum")
# Generate list of top 10 phyla

TopNOTUs <- names(sort(taxa_sums(x3), TRUE)[1:10])
x4 <- prune_taxa(TopNOTUs, x3)
plot_bar(x4,fill="Phylum", facet_grid("Basin"))

**Comment by joey711** [comment]
https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-want-a-phyloseq-graphic-that-looks-like
