### ISSUE TITLE
Problem merging samples - NAs introduced by coercion

### ISSUE THREAD

**Issue by davidmartinad200** [joey711/phyloseq#663]
Any idea how to debug this problem ??

```
>taxo
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 6310 taxa and 134 samples ]
sample_data() Sample Data:       [ 134 samples by 2 sample variables ]
tax_table()   Taxonomy Table:    [ 6310 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 6310 tips and 6308 internal nodes ]

```

I´m trying to merge based on column tech_replicates that contains three factors (A,B,C)

```
merge_samples(taxo, "tech_replicates", fun=mean)
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 6310 taxa and 3 samples ]
sample_data() Sample Data:       [ 132 samples by 2 sample variables ]
tax_table()   Taxonomy Table:    [ 6310 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 6310 tips and 6308 internal nodes ]
Warning messages:
1: In asMethod(object) : NAs introduced by coercion
2: In asMethod(object) : NAs introduced by coercion

```

I have now successfully merged the replicates but my merged  sample_data is NA ???? However sample_data(taxo) is perfect with all my variables. I don´t really understand how merge_samples works with the sample_data columns ?
thanks.

**Comment by davidmartinad200** [comment]
Hi,
I just understood how this works by looking at the phyloseq package. I realized that the phyloseq object sample_data need to be coerced to a numeric class before running the merge.
My input file is an MRexperiment object created with the function write_biom(MRobject). The problem is that phyloseq imports the data without transforming the sample_data to factors and that was causing problems with the merge_samples functions as it expects factors variables for the aggreagate function.

So what i did is just added a line that transforms all my columns imported in the sample_data object to factors and then to numeric class as follows:
```
#Import my MRexperiment as a phyloseq object
taxo = import_biom(otufile, parseFunction=parse_taxonomy_default)

# Transform all variables to factors just in case...
df <- as.data.frame(lapply(sample_data(taxo),function (y) if(class(y)!="factor" ) as.factor(y) else y),stringsAsFactors=T)
row.names(df) <- sample_names(taxo)
sample_data(taxo) <- sample_data(df)

# Finally run the merge function
merge_samples(taxo,group)
# Works well....
```

Maybe this can added directly into phyloseq merge_samples method as follows (not tested)

```
merge-methods.R
```
# Remove any non-coercable columns.
	# Philosophy is to keep as much as possible. If it is coercable at all, keep.
	# Coerce all columns to numeric matrix
	coercable    <- sapply(x1, canCoerce, "numeric")

**#Transform all columns to factors just in case we don´t have it yet (not tested)
x1 <- as.data.frame(lapply(x1,function (y) if(class(y)!="factor" ) as.factor(y) else y),stringsAsFactors=T)**

# Coerce to numeric....
	x2           <- sapply(x1[, coercable], as, "numeric")
	rownames(x2) <- rownames(x1)	
	

```
```

**Comment by joey711** [comment]
Thanks @davidmartinad200 

This is already discussed in the documentation for `merge_samples`, and the link to the underlying general method `merge` in R, for merging records in a data.frame. The behavior you're describing is expected according to this method, and also something you should always think about ahead of time. What is the meaning of merging two or more categorical values (1) when some are different? (2) when they're all the same? If they are factors/numeric the tendency might be to aggregate/average the factor integer values. Is this meaningful? When categorical values are all the same within a merge, I believe the single value is simply kept. 

As you can see, a naive/general `merge` is probably not appropriate in many cases, and you'll probably want to define a covariate table explicitly for your merged case. For some variables, it will simply be taking the most-often / only value in the set being merged, for others it might be `NA` or something more complicated; decisions that you'll need to make and understand based on what the data is. In many cases the default behavior in R is pretty good, but be careful/skeptical about what it is doing when the data is actually being transformed like this. 

Cheers (will close for now)

**Comment by rachaelantwis** [comment]
I am having a similar problem where I need to convert all my columns to factors otherwise it's causing me problems with merging. I can do this when I initially import the sample data, but the only remaining column causing me problems is the sampletype column that I specify after import to remove contaminants. I am trying to convert this to a factor or delete it but I keep getting the same error message:

>         
>     #Remove Negative 'Contamination' OTUs for phyloseq object using 'prune_taxa' (removes FALSE values)
>         ps2<-prune_taxa(otus.in.neg.false,ps)
>         sample_sums(ps2)
>     #Remove Control Samples and Negative
>         ps4 <- prune_samples(sample_names(ps3) != "BLANK2", ps2)
>     
>     #Check they have gone
>         sample_sums(ps4)
>         final.data<-ps4    
>     
>     # Removing OTUs with fewer than 100 reads
>         final.data.reduced<-prune_taxa(taxa_sums(final.data)>100,final.data)
>         
>     #How Many Taxa Did We Lose?    
>         ntaxa(final.data); ntaxa(final.data.reduced)
[1] 1994
[1] 598
>         ntaxa(final.data)- ntaxa(final.data.reduced)
[1] 1396
>     
> 
>         
>         ###############
>         # Post-QC Library Stats
>         ###############
>         
>         median(sample_sums(final.data))
[1] 7649.5
>         range(sample_sums(final.data))
[1]   646 20941
>         final.data
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1994 taxa and 102 samples ]
sample_data() Sample Data:       [ 102 samples by 8 sample variables ]
tax_table()   Taxonomy Table:    [ 1994 taxa by 6 taxonomic ranks ]
>         
>         median(sample_sums(final.data.reduced))
[1] 7380.5
>         range(sample_sums(final.data.reduced))
[1]   614 20033
>         final.data.reduced
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 598 taxa and 102 samples ]
sample_data() Sample Data:       [ 102 samples by 8 sample variables ]
tax_table()   Taxonomy Table:    [ 598 taxa by 6 taxonomic ranks ]
>         
> # Check the column names of the data and change if necessary
> colnames(tax_table(final.data.reduced))
[1] "ta1" "ta2" "ta3" "ta4" "ta5" "ta6"
> colnames(tax_table(final.data.reduced)) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")
> colnames(tax_table(final.data.reduced))
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"  
> 
> final.data.reduced$sampletype <- NULL
Error in `$<-`(`*tmp*`, sampletype, value = NULL) : 
  no method for assigning subsets of this S4 class


Please can you help me delete or convert this column? Many thanks

**Comment by rachaelantwis** [comment]
Just so you can see where the 'sampletype' column came from: 

Sample_data <- read_csv(".../XXX.csv")
      View(Sample_data)
      
        sample.info<-Sample_data
        head(sample.info)
        
      #Samples as factor
        sample.info$Sample<-as.factor(sample.info$Sample)
      
           # Others as factors
      sample.info$ID<-as.factor(sample.info$ID)
      sample.info$Band<-as.factor(sample.info$Band)
      sample.info$Band_gender_age<-as.factor(sample.info$Band_gender_age)
      sample.info$Gender_age<-as.factor(sample.info$Gender_age)
      sample.info$Offspring<-as.factor(sample.info$Offspring)
      sample.info$Gender<-as.factor(sample.info$Gender)
      
      #Merge the Sample ID data from dada2 with the metadata  
        sample.merge<-merge(sample.info,samples.out,by="Sample",all.y=TRUE)
        nrow(sample.merge)
        #tail(sample.merge)
        
      #Rownames of sample data are sample IDs
        rownames(sample.merge)<-sample.merge$Sample
        
      #Add an indicator variable for whether a sample is a sample or a negative
        sample.merge$sampletype<-"sample"
        sample.merge$sampletype[grep("Negative",sample.merge$Sample)]<-"negative"
      
      ## Trim Names of Taxa Table - label them as sequence variants (SVs)
          #note this strips out the sequence data whcih dada2 uses as a name element
          #so this is where to find the sequence if you need them
        taxa.slim<-unname(tt)
        rownames(taxa.slim)<- paste("SV",seq(nrow(tt)))  
        head(taxa.slim)
      
      # Trim Names of OTU Table
        seqtab.slim<-t(seqtab.nochim)
        rownames(seqtab.slim)<-paste("SV",seq(nrow(tt)))
          
      #Export to Phyloseq
        library(phyloseq)
        
        ps <- phyloseq(otu_table(seqtab.slim,taxa_are_rows = TRUE), 
                       sample_data(sample.merge), 
                       tax_table((taxa.slim)))

 #Identify the samples (columns) that are negative controls
        otuloc<-grep("negative",sample_data(ps)$sampletype)

    #Evaluate if any SVs (rows) are >0 for negatives (positive SV counts)
        otus.in.neg<-(otu_table(ps)[,otuloc]>0)
        sum(otus.in.neg)
    
    #There are two samples here, giving us a 2-column matrix
      #so we use 'apply' to evaluate rows and ask if any of the negs has a positive count
        otus.in.neg.true<-apply(otus.in.neg,1,function(x)any(x=="TRUE"))
        
    #Then convert all 'TRUE' (contaminant) OTUs to FALSE values (phyloseq will strip out these)
        otus.in.neg.false<-ifelse(otus.in.neg.true==TRUE,FALSE,TRUE)
    
    #How Many OTUs were contaminants (FALSE values)?    
        table(otus.in.neg.false)
        
    #Remove Negative 'Contamination' OTUs for phyloseq object using 'prune_taxa' (removes FALSE values)
        ps2<-prune_taxa(otus.in.neg.false,ps)
        sample_sums(ps2)
        
    #Remove Control Samples and Negative
        ps3 <- prune_samples(sample_names(ps2) != "Mock-comm", ps2)
        ps4 <- prune_samples(sample_names(ps3) != "Water", ps3)
