### ISSUE TITLE
Lost of OTU and taxonomic level labels using the tax_table function

### ISSUE THREAD

**Issue by olar785** [joey711/phyloseq#664]
Hi,

I'm importing my OTU, taxonomic and sample tables as .csv files using the commands below. It works fine with the otu_table and sample_ table functions but when it gets to the tax_table function, my labels are lost and renamed sp1, sp2 for OTUs and ta1, ta2 for my taxonomic levels. Is it me doing something wrong or there is a glitch?

N.B: I'm using R version 3.3.1 with the latest update for all packages

otu.rna<-read.csv(file.choose())
taxo.rna<-read.csv(file.choose())
sites.rna<-read.csv(file.choose())

rownames(sites.rna) <- sites.rna[,1]
sites.rna<-sites.rna[,-1]

rownames(otu.rna) <- otu.rna[,1]
otu.rna<-otu.rna[,-1]

rownames(taxo.rna) <- taxo.rna[,1]
taxo.rna<-taxo.rna[,-1]

otu.rna = otu_table(otu.rna, taxa_are_rows = TRUE)
taxo.rna = tax_table(taxo.rna)
sites.rna = sample_data(sites.rna)

**Comment by slvrshot** [comment]
How is your taxa_table formatted in the csv file?

**Comment by olar785** [comment]
Here is how it looks like once uploaded in R
<img width="1280" alt="screen shot 2016-10-07 at 9 02 34 am" src="https://cloud.githubusercontent.com/assets/20408813/19168547/0ebeaaf6-8c6d-11e6-84ab-f20b454aa771.png">

**Comment by olar785** [comment]
And here is what happens when I use the tax_table function.
<img width="1280" alt="screen shot 2016-10-07 at 10 49 29 am" src="https://cloud.githubusercontent.com/assets/20408813/19171947/e9082abc-8c7b-11e6-9b64-ec8643aa5f54.png">

Strangely when I use the same structure with the otu_table or the sample_data command I do not loose my labels...

**Comment by slvrshot** [comment]
I reproduced it and discovered the same issue.  Everything gets turned into sp...

**Comment by slvrshot** [comment]
Try this line to change the rownames

`rownames(tax2) <- rownames(biomfile)`

```
tax <- read.csv("metagenome_gut_taxonomy2.csv")
View(tax)
rownames(tax) <- tax[,1]
taxo.rna <- tax[,-1]
tax2 = matrix(taxo.rna)
tax2
rownames(tax2) <- rownames(biomfile)
colnames(tax2) <- c("KO")
tax2
class(tax2)
OTU = otu_table(biomfile, taxa_are_rows = TRUE)
TAX = tax_table(tax2)
OTU
TAX
```

**Comment by olar785** [comment]
Thanks slvrshot, I just ended up using the following command to have my labels of my OTU table matching the taxonomic matrix: 

otus<-read.csv(file.choose())
otus<-otus[,-1] 
otus = otu_table(otus, taxa_are_rows = TRUE)

and after merging everything into a phyloseq object I used this command to change the labels of my taxonomic levels

colnames(tax_table(name_of_phyloseq_object)) <- c("Domain", "kingdom", "Phylum", "Class", "Genus", "Specie")

**Comment by joey711** [comment]
Glad you found a workaround. I don't recommend over-writing your the taxa IDs (row names) that are already present in your taxonomy table. What if there was a different number, or they were in a different order than in the OTU table object? You would wind up with mis-annotated data, without knowing it. A pretty terrible error.

Instead, figure out why the rownames are lost. Note that `tax_table` expects a matrix, not a data.frame. The object you fed it was a data.frame, and it tried to coerce it to matrix for you, and warned you as much. 

You can try 

```R
taxo.rna = read.csv("path/to/your/file")
rownames(taxo.rna) <- taxo.rna[,1]
taxo.rna<-taxo.rna[,-1]
taxmat = as.matrix(taxo.rna)
taxtab = tax_table(taxmat)
# Verify that you created a taxonomy table with proper names
taxa_names(taxtab)[1:10]
```

If this worked, you should be able to compare the taxa names in `taxtab` with those in `otus`, etc.; and indeed, `phyloseq()` will do this for you when you merge them together into a phyloseq object.

Will close for now.
