### ISSUE TITLE
Confusion about taxonomy and phylogenetic tree

### ISSUE THREAD

**Issue by WandeRum** [joey711/phyloseq#665]
Phyloseq is really a great tool for R user dealing with microbiome data.
However, when I tried the example data of Global Pattern. I found same family could be assigned to different branches of the phylogenetic tree. I am wondering why it happened?
<img width="578" alt="2016-09-11 1 32 31" src="https://cloud.githubusercontent.com/assets/7929199/18421353/4bb91dea-7824-11e6-821f-fcadb3334ffc.png">
I always suppose that same taxa will locate in the same branch of the tree some how (such as the purple family: Ruminococcaceae). Maybe I have some misunderstandings. Can anyone explain it a little bit?
Thanks.

**Comment by joey711** [comment]
This is not a phyloseq question, but a question about the algorithms that you used to define taxonomy, and to define the phylogenetic tree. It is very likely that they were different. The phyloseq-generated plot you include here is simply revealing some of those differences that are present in your data/results. 

I'm also not sure I can tell the difference between the Rumino and Veillon families in this color palette. You may want to modify that.

Please dig more deeply into the documentation of the tools you used to define the tree and the taxonomy. You may want to choose a different method for one or both of those methods, and re-run. I've has some pretty stable, effective results using UTAX, for example. The tree-building process is also pretty tricky for data with this many sequence features, indels, etc.

Will close for now, but thanks for your interest in phyloseq! Glad it was able to bring to your attention some contradictions within your data.
