### ISSUE TITLE
Problem in plotting bar and richness

### ISSUE THREAD

**Issue by Eustacialee** [joey711/phyloseq#666]
Hi,

I am having problem when I tried to plot bar and richness chart. It showed :
 Error in theme_get()[newitem_names] : 
  object of type 'closure' is not subsettable

Currently I am using R version 3.2.4. It worked when I ran the similar script few months ago. Could you please advice?

The following is my script:

> library(phyloseq)
> library(ggplot2)
> library(plyr)
> setwd("~/Desktop/Phyloseq/")
> map_file = "~/Desktop/Phyloseq/Mapping_Tee1.txt"
> biom_file = "~/Desktop/Phyloseq/sorted_otu_table_json.biom" 
> tree_file  = "~/Desktop/Phyloseq/rep_phylo.tre"
> map <- import_qiime_sample_data(map_file)
> biom <- import_biom(biom_file)
> tree <- read_tree_greengenes(tree_file)
> run1 <- merge_phyloseq(biom, map, tree)
> run1
> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 7703 taxa and 32 samples ]
> sample_data() Sample Data:       [ 32 samples by 21 sample variables ]
> tax_table()   Taxonomy Table:    [ 7703 taxa by 7 taxonomic ranks ]
> phy_tree()    Phylogenetic Tree: [ 7703 tips and 7701 internal nodes ]
> plot_bar(run1)
> Error in theme_get()[newitem_names] : 
>   object of type 'closure' is not subsettable
> plot_richness(run1)
> Error in theme_get()[newitem_names] : 
>   object of type 'closure' is not subsettable

Thanks.

Regards,
Soo Ching

**Comment by Eustacialee** [comment]
Hi,

I have re-installed R and Phyloseq but still having the same problem. 

I tried to run the example data (global patterns) from tutorials but still same error pop up.

Thanks.

Regards,
Soo Ching

**Comment by joey711** [comment]
Can you please post the reproducible example of this error that uses the `GlobalPatterns` dataset?

Thanks

**Comment by joey711** [comment]
Will close for now. Can not reproduce this error.
