### ISSUE TITLE
Can I use Phyloseq to produce figures for .biom tables produced in PICRUSt or other software?

### ISSUE THREAD

**Issue by slvrshot** [joey711/phyloseq#668]
I have successfully done this in QIIME to create abundance plots with facets (stacked bar plots look awful) but I was unsure if I could create a phyloseq object from just a PICRUST OTU table and a mapping file, and run scripts like the barplot function without having a tree file. I suppose I could create a tree file but it may or may not be necessary. Could you please comment on this?

**Comment by joey711** [comment]
Yes, you can.

You do not need a tree file to use phyloseq. A proper biom file should be fine, regardless of what produced it. 

Glad you agree with me [that stacked bar plots are awful and should be avoided](https://github.com/joey711/phyloseq/issues/442)

See [the following from the FAQ on importing](https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#not-every-data-component-is-included-in-.biom-files), and follow the links and tutorials for importing/coercing non-standard files into phyloseq. If you can read the data into R, then you can use it in phyloseq.

Cheers

joey
