### ISSUE TITLE
Select phyla >2% relative abundance or select specific phyla with subset_taxa?

### ISSUE THREAD

**Issue by TokeB-A** [joey711/phyloseq#670]
Thank you for developing phyloseq! Highly appreciated!

I have two questions which most likely is very easily answered (I just cant find the solution online...)
1. Can I select specific phyla to keep using subset_taxa?

I can use e.g: p_Acido = subset_taxa(p, Phylum =="Acidobacteria") to keep only Acidobacteria, but what if I want to keep more, like Actinobacteria, Firmicutes, Planctomycetes etc?
1. How can I subset all phyla which have relative abundances above 2%
   I can transform OTU counts to relative abundance using: p_ra = transform_sample_counts(p, function(x) x/sum(x))
   And I can keep OTU's with a mean relative abundances above a specific value by: p_OTU_filtered = filter_taxa(p, function(x) mean(x) > 1e-5, TRUE)
   But how can I keep all OTUS belonging to Phyla which have relative abundances above 2%?

Hope you can help out - and sorry if this is very basic stuff :-/

Thank you very much in advance!

-Toke

**Comment by joey711** [comment]
1. Yes. 

```R
subset_taxa(p, Phylum  %in% c("Acidobacteria", "Actinobacteria", "Firmicutes", "Planctomycetes")) 
```

2. 

```R
# First agglomerate by phylum to define the phyla you want to keep.
physeqPhylum = tax_glom(p, "Phylum")
physeqPhylumRA = transform_sample_counts(physeqPhylum, function(x) x/sum(x))
physeqPhylumRAF = filter_taxa(physeqPhylumRA, function(x) mean(x) > 0.02, TRUE)
# Define the vector of phyla names that are still present after your filter
keepPhyla = get_taxa_unique(physeqPhylumRAF, "Phylum")
# Like in the first question, subset to just the phyla that you want, using the original phyloseq object
physeqF = subset_taxa(p, Phylum  %in% keepPhyla) 
```

These are indeed basic questions. I suggest you review the wide array of phyloseq supporting documentation, including vignettes, function docs, tutorials, and the other previous posts on this issue tracker before posting further questions. Most google searches will also turn these up.

Good luck!

**Comment by aff30** [comment]
Hi Joey, 

I am filtering my data for relative abundance and when after transform_samples_counts I try to remove taxa with total relative abundance less than 10e-5 but I get the following error:  Error in validObject(.Object) : invalid class “otu_table” object: 
 OTU abundance data must have non-zero dimensions.

I am using the following code:
# transform to relative abundance
pst <- transform_sample_counts(psf3, function(x) x / sum(x) )

# remove taxa with total relative abundance less than 10e-5
psr <- filter_taxa(pst, function(x) mean(x) > 1e-5, TRUE) 

Would you mind helping me out with that? 
Thank you so much! 
Ana
