### ISSUE TITLE
vegdist and distance not returning the same bray-curtis matrix

### ISSUE THREAD

**Issue by sformel** [joey711/phyloseq#675]
I'm pretty new to using phyloseq and vegan, so I'm guessing that I am misinterpreting how these commands work.  I was surprised to find the distance function in phyloseq does not return the same matrix as the vegdist function in vegan.  I thought they used the same calculations, so I assumed they would return the same values. Can anyone explain to me where I might be going wrong, or how they are different?

`data("GlobalPatterns")

p = prune_taxa(taxa_sums(GlobalPatterns) > 0, GlobalPatterns)
GP.chl = subset_taxa(GlobalPatterns, Phylum=="Chlamydiae")

vegdist <- head(vegdist(otu_table(GP.chl), method = "bray"))
distance <- head(distance(otu_table(GP.chl), method = "bray")) 

identical(vegdist,distance)`

Thanks,
Steve

**Comment by joey711** [comment]
@sformel `vegdist` expects a sample-by-taxa matrix, while `phyloseq::distance` understands the current orientation of the table and computes accordingly. Compare the dimensions of the two distance matrices, and you should see what I mean. 

I'll close for now. Please feel free to respond with any follow-up...

**Comment by sformel** [comment]
Makes sense, thanks for the explanation!
