### ISSUE TITLE
Issue in plot-bar in Phyloseq

### ISSUE THREAD

**Issue by Imee929** [joey711/phyloseq#676]
Hi Joey,

I have issue with plot_bar. I am using the current phyloseq package. My data are all in  the phyloseq object 'sbsp". I tried the suggestions in the forum but  I still am not successful in getting a good bar plot. Can you help me on this one? I have attach a pdf of my output. 
Thanks,
Imee

plot_bar(sbsp, fill= "Genus")
[Rplot02.pdf](https://github.com/joey711/phyloseq/files/525365/Rplot02.pdf)

**Comment by StackerEd** [comment]
I had the same issue, and had to filter out the top 20 OTU's and plot them... but I'd also like to know how to scale the plot so I can have ALL OTU's

**Comment by jeffkimbrel** [comment]
You simply have too many OTUs so the legend is obscuring the plot (or rather pushing it off the display). With that many OTUs, a legend is worthless anyway, so it is best to just remove it.

```
plot_bar(sbsp, fill= "Genus") + theme(legend.position="none")
```

**Comment by joey711** [comment]
https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html#i-want-a-phyloseq-graphic-that-looks-like
