### ISSUE TITLE
Return median abundance for OTUs when running merge_samples()

### ISSUE THREAD

**Issue by colinbrislawn** [joey711/phyloseq#678]
Good morning,

I'm trying to `merge_samples()` and return the median OTU abundance in a group. The documentation says 

> Note that this is (currently) ignored for the otu_table, where the equivalent function is `sum`, but evaluated via `rowsum` for efficiency.

I would like to calculate the **median OTU abundance** within my merged samples. Do you have any advice on how to do this?

If this is outside the current functionality of phyloseq, feel free to close this issue.

**Comment by joey711** [comment]
I'd have to think about how to tweak the current implementation. There are several ways to do it that would support what you're asking, and shouldn't cost too much extra on performance.

In the short run, if it were me prototyping a solution to do this, I'd use `psmelt` to get a long-form table, and then compute the median by group using standard data.table logic. plyr/dplyr would also get you there. Check if the zeroes are omitted in the `psmelt` table, as that obviously affects your `median` calculation.

Cheers

**Comment by jeffkimbrel** [comment]
I didn't test this much, but `aggregate()` will also do it on a `psmelt` object. You can run this on the non-merged phyloseq object.

```
melt = psmelt(phyloObject)
aggregate(Abundance ~ XXX,data=melt,median)

# OR

aggregate(Abundance ~ XXX + OTU,data=melt,median)
```

Just replace the XXX on the `sample_data` that you are using to merge. I'm not sure how other R functions treat an even number of values for getting the median, but `aggregate()` averages the two median values.

**Comment by colinbrislawn** [comment]
Thanks for the prompt feedback. Using `psmelt()` and `aggregate()` does work well; I've been processing my samples like that, and wanted to do a sanity check with 'official' phyloseq functions to make sure I was not messing something up along the way.

You can close this at your discretion.

**Comment by joey711** [comment]
LGTM. This is the kind of use case I had in mind when I migrated `psmelt` to an external function.

Glad it helped. Cheers.
