### ISSUE TITLE
Error in taxonomy level import

### ISSUE THREAD

**Issue by waleadebayo** [joey711/phyloseq#690]
Hi, all. While running phyloseq extension for edgeR, my taxa level are not labeled properly, I get Rank1,2....7 instead of Kingdom, Phylum,... I had to merge metadata with otu table previously, I don't know if that would be responsible

head(sigtab)
             Rank1             Rank2                  Rank3
697578 k__Bacteria     p__Firmicutes             c__Bacilli
322927 k__Bacteria p__Proteobacteria c__Gammaproteobacteria
381296 k__Bacteria p__Proteobacteria c__Gammaproteobacteria
362505 k__Bacteria p__Proteobacteria c__Gammaproteobacteria
922584 k__Bacteria p__Proteobacteria c__Gammaproteobacteria
284177 k__Bacteria p__Proteobacteria  c__Betaproteobacteria
                    Rank4               Rank5
697578      o__Bacillales                <NA>
322927 o__Pseudomonadales    f__Moraxellaceae
381296 o__Pseudomonadales    f__Moraxellaceae
362505 o__Pseudomonadales    f__Moraxellaceae
922584 o__Pseudomonadales    f__Moraxellaceae
284177 o__Burkholderiales f__Oxalobacteraceae
                      Rank6         Rank7    logFC   logCPM
697578                 <NA>          <NA> 5.905408 12.37833
322927     g__Acinetobacter           s__ 6.006386 13.90359
381296     g__Acinetobacter          <NA> 6.107291 14.25434
362505     g__Acinetobacter           s__ 4.948377 12.31145
922584     g__Acinetobacter s__schindleri 5.029264 12.40841
284177 g__Janthinobacterium    s__lividum 3.975926 10.66460
             PValue          FDR       Rank1
697578 1.084148e-20 1.637064e-18 k__Bacteria
322927 4.125225e-17 3.114545e-15 k__Bacteria
381296 1.917907e-16 9.653466e-15 k__Bacteria
362505 2.635492e-16 9.948984e-15 k__Bacteria
922584 1.114715e-15 3.366439e-14 k__Bacteria
284177 1.245164e-14 3.133662e-13 k__Bacteria
                   Rank2                  Rank3
697578     p__Firmicutes             c__Bacilli
322927 p__Proteobacteria c__Gammaproteobacteria
381296 p__Proteobacteria c__Gammaproteobacteria
362505 p__Proteobacteria c__Gammaproteobacteria
922584 p__Proteobacteria c__Gammaproteobacteria
284177 p__Proteobacteria  c__Betaproteobacteria
                    Rank4               Rank5
697578      o__Bacillales                <NA>
322927 o__Pseudomonadales    f__Moraxellaceae
381296 o__Pseudomonadales    f__Moraxellaceae
362505 o__Pseudomonadales    f__Moraxellaceae
922584 o__Pseudomonadales    f__Moraxellaceae
284177 o__Burkholderiales f__Oxalobacteraceae
                      Rank6         Rank7
697578                 <NA>          <NA>
322927     g__Acinetobacter           s__
381296     g__Acinetobacter          <NA>
362505     g__Acinetobacter           s__
922584     g__Acinetobacter s__schindleri
284177 g__Janthinobacterium    s__lividum
........................................
I merged metadata with otu table before proceeding.

final2 <- import_biom("final_otu_table.biom")
map1 <- sample_data(map)
exam1 <- phyloseq(final2, map1)
x <- exam1
x <- phyloseq(exam1)
finalmerg <- merge_phyloseq(final2, x)
finalmergep = transform_sample_counts(finalmerg, function(x){x/sum(x)})
hist(log10(apply(otu_table(finalmergep), 1, var)),
xlab="log10(variance)", breaks=50,
main="A large fraction of OTUs have very low variance")
varianceThreshold = 1e-5
keepOTUs = names(which(apply(otu_table(finalmergep), 1, var) > varianceThreshold))
finalmergB = prune_taxa(keepOTUs, finalmerg)
finalmergB
finalmerg
View(map1)
dge = phyloseq_to_edgeR(finalmergB, group="EGG_PRESENCE")
# Perform binary test
et = exactTest(dge)
# Extract values from test results
tt = topTags(et, n=nrow(dge$table), adjust.method="BH", sort.by="PValue")
res = tt@.Data[[1]]
alpha = 0.05
sigtab = res[(res$FDR < alpha), ]
sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(finalmergB)[rownames(sigtab), ], "matrix"))
dim(sigtab)
head(sigtab)
....................................
My sessionInfo

> sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                         
[5] LC_TIME=English_United States.1252   

attached base packages:
[1] stats     graphics  grDevices utils     datasets
[6] methods   base    

other attached packages:
[1] phyloseq_1.14.0 edgeR_3.12.1    limma_3.26.9  

loaded via a namespace (and not attached):
 [1] igraph_1.0.1        ggplot2_2.2.0     
 [3] zlibbioc_1.16.0     lattice_0.20-34   
 [5] stringr_1.1.0       IRanges_2.4.8     
 [7] S4Vectors_0.8.11    parallel_3.2.5    
 [9] ape_3.5             Biobase_2.30.0    
[11] Rcpp_0.12.8         plyr_1.8.4        
[13] tools_3.2.5         MASS_7.3-45       
[15] multtest_2.26.0     nlme_3.1-128      
[17] XVector_0.10.0      BiocGenerics_0.16.1
[19] scales_0.4.1        assertthat_0.1    
[21] permute_0.9-4       gtable_0.2.0      
[23] Matrix_1.2-7.1      foreach_1.4.3     
[25] stringi_1.1.2       cluster_2.0.5     
[27] reshape2_1.4.2      munsell_0.4.3     
[29] grid_3.2.5          colorspace_1.3-1  
[31] rhdf5_2.14.0        data.table_1.9.6  
[33] biom_0.4.0          vegan_2.4-1       
[35] magrittr_1.5        splines_3.2.5     
[37] Biostrings_2.38.4   lazyeval_0.2.0    
[39] stats4_3.2.5        ade4_1.7-4        
[41] survival_2.40-1     mgcv_1.8-16       
[43] iterators_1.0.8     codetools_0.2-15  
[45] tibble_1.2          chron_2.3-47      
[47] RJSONIO_1.3-0

Thanks

**Comment by waleadebayo** [comment]
Solved the issue by renaming immediately after merge_phyloseq
> colnames(tax_table(finalmerg)) <- c("kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

**Comment by joey711** [comment]
great!
