### ISSUE TITLE
plotting samlpe types next to eachoter

### ISSUE THREAD

**Issue by luddiks** [joey711/phyloseq#691]
how to order the samples so the same sample type is next to eachother? i have it like this in my tables but it changes when it it plotted
Jane

**Comment by dadahan** [comment]
You can order samples on the x-axis in ggplot by specifying order in `scale_x_discrete()` . [ggplot2 has good documentation](http://docs.ggplot2.org/current/scale_discrete.html) on this!

**Comment by luddiks** [comment]
Thanks! this was very helpful:)
