### ISSUE TITLE
is it possible to make a plot_ordination with taxa abundance?

### ISSUE THREAD

**Issue by AndreaQ7** [joey711/phyloseq#692]
Hi all,

I was trying to make a simple biplot of Weigthed UniFrac distance with plot_ordination, but i'm not really satisfied of the results. I used this command line

plot_ordination(biom.rar,weigh, color="Phylum",type="biplot",shape="Treatment") + theme(aspect.ratio=1)

but in this way I obtain thousands of point colored on the base of their phyla, I'm trying to understand if is there a way to plot, instead of thousands of points, just one point as big as the relative abundance of that taxa within the plot. 
I try to attach a picture that i found in an article to let u understand what i mean
![image](https://cloud.githubusercontent.com/assets/18282354/20623528/4005d6d6-b308-11e6-803c-b17a217ee7ec.PNG)

**Comment by joey711** [comment]
I'm going to close for now. This appears to be a feature request for a very special desired case that I'm not planning to support within the package.

What you are doing is possible with just a few lines of your own. Perhaps someone else wants to add an example for how to do this, hear?  The relevant additional function is `taxa_sums`. The ggplot2 documentation is very good and should get you the rest of the way.

Cheers

**Comment by Stabilo12** [comment]
@AndreaQ7 did you fix this problem? 
Because this dont work, but i dont no why.. 

Prev <- as.numeric(otu_table(pseq)["g__Bifidobacterium",])
#Error in as(x, "matrix")[i, j, drop = FALSE] : subscript out of bounds

meta$Bifidobacterium <- Prev
sample_data(pseq) <- meta
plot_ordination(pseq, ord_bray, color="Bifidobacterium")
