### ISSUE TITLE
filter OTU by relative abundance

### ISSUE THREAD

**Issue by jenlang** [joey711/phyloseq#694]
Hi there! I'm new to phyloseq and I'm trying to transition all my microbiome work into R for efficiency, and have come across some problems.

I cannot figure out how to write the function to subset the OTUs that have a total sum greater than 0.005%. More explicitly, the sum of an OTU across all samples is greater than 0.005% of all OTUs. 

If I read the manual correctly, the function is applied automatically across samples so does this code do the equivalent of this: (rowSums(x)/sum(x)*100) > 0.005? 
`FS_0.005 <- filter_taxa(fullset, function(x) x/sum(x)*100 > 0.005)
Error in filter_taxa(fullset, function(x) x/sum(x) * 100 > 0.005) : 
  Logic error in applying function(s). Logical result not same length as ntaxa(physeq)`

Just in case I tried these versions. I'm still new to writing functions. 
`FS_0.005 <- filter_taxa(fullset, function(x) (rowSums(x)/sum(x)*100) > 0.005)
 Error in rowSums(x) : 'x' must be an array of at least two dimensions `

`FS_0.005 <- filter_taxa(fullset, function(x) (apply(x, 1, sum)/sum(x)*100) > 0.005)
 Error in apply(x, 1, sum) : dim(X) must have a positive length `

This is my object
`> fullset
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 9312 taxa and 512 samples ]
sample_data() Sample Data:       [ 512 samples by 11 sample variables ]
tax_table()   Taxonomy Table:    [ 9312 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 9312 tips and 9309 internal nodes ]
refseq()      DNAStringSet:      [ 9312 reference sequences ]`

Also, if you set prune==TRUE does that mean the OTUs that are removed are also removed from the other portions of the phyloseq-class like the tree? And does that matter?
I want to know if I can just give up on this and do the filtering in QIIME and then use that biom file to skip all this.

Thanks for the help!

**Comment by dadahan** [comment]
Hi, 
This is outlined in the [preprocessing section of the manual](https://joey711.github.io/phyloseq/preprocess.html).

In your case, since you're trying to filter by relative abundance you'll want to use the `transform_sample_counts` function first. I think omitting this step is your hiccup since you  are trying to do this with the `x/sum(x)*100` part of your function and dividing by lengths that don't agree.

Should look like this:
```{r}
FSr  = transform_sample_counts(fullset, function(x) x / sum(x) )
FSfr = filter_taxa(FSr, function(x) sum(x) > .005, TRUE)
```

**Comment by dadahan** [comment]
Also, see bottom of #671 for prune explanation.

**Comment by jenlang** [comment]
Hi dadahan, thanks for the response. I've already read those examples and tried them but ran into problems. 

1. I didn't want to use the transformed RA dataset because it doesn't make sense for analyses. Relative Abundance should be from within the samples and not the entire dataset. But I can just use the filter_taxa to get a list and then pass that through prune_taxa. (haven't tried it yet but that's the plan)
2. One sample had no reads so it was calculating to NaN within the OTU table so I think that's why I kept getting errors on things I was trying. 

3. NEW PROBLEM: I tried to remove the low count samples. Anything less than 1000 reads but I get an error because some of the OTUs must only be present in those samples. 
-Error in validObject(.Object) : invalid class “otu_table” object: 
 OTU abundance data must have non-zero dimensions.

**Comment by dadahan** [comment]
Hi jenlang, Happy to help where I can, though other more experienced users may want to jump in. According to `?transform_sample_counts` documentation, each sample is transformed individually, so you shouldn't have an issue with relative abundance transformed from the entire dataset. Curious myself, I confirm this below:

## Does phyloseq already calc within sample relative abundance?
```{r}
#Make OTU table
otumat = matrix(sample(1:10, 100, replace = TRUE), nrow = 10, ncol = 10)

rownames(otumat) <- paste0("OTU", 1:nrow(otumat))
colnames(otumat) <- paste0("Sample", 1:ncol(otumat))
```
Within sample relative abundance of OTU1 in Sample1
```{r}
otumat[1]/sum(otumat[1:nrow(otumat),1])
```
[1] 0.05882353

Within dataset relative abundance of OTU1 in Sample1
```{r}
otumat[1]/sum(otumat[1:nrow(otumat),1:ncol(otumat)])
```
[1] 0.007117438

Make phyloseq object and inspect OTU table output after transforming sample counts
```{r}
OTU = otu_table(otumat, taxa_are_rows = TRUE)
physeq <- phyloseq(OTU)
physeqr = transform_sample_counts(physeq, function(x) x / sum(x))

as.data.frame(otu_table(physeqr))[1,1]
```
[1] 0.05882353
 
Same as within sample as seen above. 

As for the pruning taxa, I've run into something similar and once you have your list you can make a list of taxa without those found at your threshold then use prune_taxa to retain these. This way you can filter by relative abundance but then filter these taxa from your table with absolute abundance, 

For instance, only retain taxa in absolute abundance table with an abundance > .1%
```{r}
physeqrF = filter_taxa(physeqr, function(x) mean(x) < .1,TRUE)
rmtaxa = taxa_names(physeqrF)
alltaxa = taxa_names(physeq)

myTaxa = alltaxa[!alltaxa %in% rmtaxa]

physeqaF <- prune_taxa(myTaxa,physeq)
```

I hope this is helpful and not pedantic or redundant with what you're already doing.

If you can post the code from the final problem I can try and help.

**Comment by jenlang** [comment]
Hi dadahan! Thanks for all the help and the clarifying. I keep mixing approaches up and most of my issues seem to stem from not fully comprehending the manual and issues with my data/inputs. 

1.To determine OTUs with RA >0.005%, I needed a matrix where the OTU was relative abundance of the entire OTU table. Then I summed the OTUs up to get the total RA. If I used the phyloseq object and transform_sample_counts I got the RA by sample, which is what I want for the analyses, just not in this instance. I was trying to do it all at once using the phyloseq object, but that just seemed to get messy so I did it outside of the phyloseq object to get a list that I could then use through prune_taxa.

3. I didn't make my sample name character vector correctly because a column of sample reads was also included. I've fixed it and now it works. 

Whew! I think I'm all good with questions

**Comment by joey711** [comment]
"More explicitly, the sum of an OTU across all samples is greater than 0.005% of all OTUs."

```R
minTotRelAbun = 1e-5
x = taxa_sums(fullset)
keepTaxa = which((x / sum(x)) > minTotRelAbun)
prunedSet = prune_taxa(keepTaxa, fullset)
```

**Comment by jenlang** [comment]
Awesome thanks! Much more efficient than what I was doing.

**Comment by wanglu2014** [comment]
Thank you all for those kindly reply. However, the 0.05% is confusing from start. Might it be threshold 0.00005? Your explaination is helpful.
“For datasets where a mock community is not included for calibration, we recommend the conservative threshold of (c = 0.005%).（Nature method）”http://europepmc.org/articles/PMC3531572

**Comment by anniewest** [comment]
Hey @joey711, I tried running your code and I got this error message:
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘prune_taxa’ for signature ‘"phyloseq", "integer"’

I tried looking up how to fix it but couldn't find a straight answer. I want to filter out low abundance ASVs from my phyloseq object but keep the read counts instead of transforming them to relative abundance at this point in my pipeline.

**Comment by mikemc** [comment]
@anniewest Please post the exact code you used, so that we can try to identify the problem. It sounds like you may have switched the order of the arguments to `prune_taxa()`.

**Comment by anniewest** [comment]
minTotRelAbun = 1e-5
x = taxa_sums(my_data)
keepTaxa = which((x / sum(x)) > minTotRelAbun)
prunedSet = prune_taxa(keepTaxa, my_data)

I also tried switching the order of arguments in prune_taxa() several times but had no luck, could it be a version update problem? 

I've also tried using genefilter_sample() with prune_taxa(), which works but I'm struggling to understand quite what genefilter_sample() is doing to my data. I understand it works at the sample level, and that I can specify the number of samples that the ASV must be present in as the described function, but I feel like I can't quite 'click' with what its doing...

filter <- phyloseq::genefilter_sample(ps1, filterfun_sample(function(x) x / sum(x) > 1e-5), A=5) 
ps2 <- prune_taxa(filter, ps1)

**Comment by mikemc** [comment]
The problem is the line `keepTaxa = which((x / sum(x)) > minTotRelAbun)`. This is giving a list of indices, which is not what `prune_taxa()` wants. You can either do
```r
keepTaxa = (x / sum(x)) > minTotRelAbun
```
which is a logical vector with TRUE for the taxa to keep, or
```r
keepTaxa = taxa_names(my_data)[which((x / sum(x)) > minTotRelAbun)]
```
which is a list of the taxa to keep. If you look at `help(prune_taxa)`, you can see that these are the possible forms to give for the first argument. The line in Joey's reply above might be simply a mistake, or maybe `prune_taxa()` has changed since 2016.

**Comment by anniewest** [comment]
Thanks @mikemc, tried both and both codes worked great!

**Comment by MaristelaMorais** [comment]
I just would like to point that the notation of the number 0.005% would be `5e-5` instead of `1e-5` which is the same as 0.001%.

**Comment by devinjones18** [comment]
Is there a way to keep only those ASVs occurring at a minimum relative abundance of 0.25% in at least one sample? I've tried 
filtered_object <- filter_taxa(my_phyloseq_object, function(x) (x > 0.25) > 0, TRUE)
and variations of this with no luck.

**Comment by mikemc** [comment]
@devinjones18 You need to call a summarizing function on `x`, which turns the vector `x` into a single number. E.g. I think either of these should work: `function(x) max(x) >= 0.25` or `function(x) sum(x >= 0.25) > 0`

**Comment by devinjones18** [comment]
Great! That worked! Thank you so much!
