### ISSUE TITLE
variance stabilized data

### ISSUE THREAD

**Issue by Maya0801** [joey711/phyloseq#696]
Dear Joey,

I read in detail issue #283 were you discussed using variance stabilized data rather then rarefied data.

I have a few questions, but before I want to give background to my research: 

I am using phyloseq version ‘1.18.1’ to analysis 16s amplicon data from marine sponges. My main goal is to identify differential abundant OTUs in different treatments. I want to use DEseq2 for that, and to present the results as heat plot. 

My questions: 
1. I was wandering if I need to use the variance stabilized data? 
2. I also wanted to know if it important to keep OTUs will all zero counts when I make this transformation? in other words after I prune for the samples of interest, should I use this?  

>phyloseq = prune_taxa(taxa_sums(phyloseq ) > 0, phyloseq )

3. I did not use geometric means calculation, as when I had upload the data to DEseq I didn't get an error, is not OK? 

I ran the analysis once with and once without using variance stabilized data. when I used the variance stabilized data I get the error: 
here are the commands that I ran: 

without
```
> W_P_DNA = prune_samples(c("Maya41-389", "Maya42-390", "Maya43-391", "Maya44-393",	
+                           "Maya45-394", "Maya46-396", "Maya47-402", "Maya49-403",	
+                           "Maya50-404", "Maya51-405", "Maya52-406", "Maya53-412"),PF)
> W_P_DNA = prune_taxa(taxa_sums(W_P_DNA) > 0, W_P_DNA)
> W_P_DNA_dds = phyloseq_to_deseq2(W_P_DNA, ~ symbioticState)
converting counts to integer mode
Warning message:
In DESeqDataSet(se, design = design, ignoreRank) :
  some variables in design formula are characters, converting to factors
> diagdds = DESeq(W_P_DNA_dds)
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
> res = results(diagdds)
> res = res[order(res$pvalue, na.last = NA), ]
> alpha = 0.005
> sigtab = res[which(res$pvalue < alpha), ]
> sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(W_P_DNAt)[rownames(sigtab), ], "matrix"))
Error in tax_table(W_P_DNAt) : object 'W_P_DNAt' not found
> sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(W_P_DNA)[rownames(sigtab), ], "matrix"))
> keepOTUs = rownames(sigtab)
> sig_OTUs = prune_taxa(keepOTUs, W_P_DNA)
> plot_heatmap(sig_OTUs, taxa.order = "Phylum", taxa.label = "Class", sample.label = "symbiotic_State", 
+              sample.order = "symbiotic_State")
Warning message:
Transformation introduced infinite values in discrete y-axis 
```
with:

```
> #run deseq
> diagdds = DESeq(W_P_DNA_dds)  
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
> 
> 
> 
> diagdds = estimateSizeFactors(diagdds)
> diagdds = estimateDispersions(diagdds)
found already estimated dispersions, replacing these
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
> diagvst = getVarianceStabilizedData(diagdds)
> dim(diagvst)
[1] 2284   12
> 
> W_P_DNA0 = W_P_DNA
> otu_table(W_P_DNA) <- otu_table(diagvst, taxa_are_rows = TRUE)
> 
> diagdds = DESeq(W_P_DNA_dds)  
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
> 
> res = results(diagdds)
> res = res[order(res$pvalue, na.last = NA), ]
> alpha = 0.005
> sigtab = res[which(res$pvalue < alpha), ]
> sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(W_P_DNA)[rownames(sigtab), ], "matrix"))
> #head(sigtab)
> keepOTUs = rownames(sigtab)
> sig_OTUs = prune_taxa(keepOTUs, W_P_DNA)
> 
> 
> 
> plot_heatmap(sig_OTUs, taxa.order = "Phylum", taxa.label = "Class", sample.label = "symbiotic_State", 
+              sample.order = "symbiotic_State")
Error in 1:rankcol : argument of length 0
```
Thank you for your time!

**Comment by joey711** [comment]
Neither of the errors in your post are phyloseq errors. They are errors in your code after doing other stuff.

First error:

```
> sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(W_P_DNAt)[rownames(sigtab), ], "matrix"))
Error in tax_table(W_P_DNAt) : object 'W_P_DNAt' not found
```

The object `W_P_DNAt` is not present. You'll need to decide if this is what you mean, a typo, or if that object is supposed to have been created prior to running that line.

Second error:

```
> plot_heatmap(sig_OTUs, taxa.order = "Phylum", taxa.label = "Class", sample.label = "symbiotic_State", 
+              sample.order = "symbiotic_State")
Error in 1:rankcol : argument of length 0
```

`plot_heatmap` is a phyloseq function designed mainly to work with a phyloseq object as its first argument. In your code, `sig_OTUs` does not appear to have a taxonomy table. You need to go back and check the results of `tax_table(sig_OTUs)`, or any of the earlier objects.

Side note, some comments in your code explaining what you mean to do would be very helpful; especially for yourself when you look back at what you did. 

I will close for now, but feel free to post an update if you already discovered and fixed this problem, or if something else came up. 

Cheers
