### ISSUE TITLE
Prevalence filtering the dataset, F1000 workflow question

### ISSUE THREAD

**Issue by dadahan** [joey711/phyloseq#697]
Hi,
I am walking through the Bioconductor Workflow on F1000 and currently *prevalence* filtering the dataset. The article finds that Deinococcus-Thermus appeared in just over one percent of samples, but I am finding that it is found in  ~14%, which could make a downstream difference considering the supervised parameter for *prevalence* filtering and the unsupervised threshold. It is likely I miscalculated. Can someone provide the correct calculation?

Add *prevalence* proportion column
```{r}
prevdfMSP = plyr::ddply(prevdf, "Phylum", 
            function(df1){cbind(mean(df1$Prevalence),sum(df1$Prevalence),(mean(df1$Prevalence)/nsamples(ps0)))})
```

Check proportion column. Check Deinococcus-Thermus sample proportion. 

```{r}
prevdfMSP
```
![screen shot 2016-12-13 at 1 42 37 pm](https://cloud.githubusercontent.com/assets/13370432/21142433/07ce4d1c-c13a-11e6-9d8b-ba525b12c4d4.png)

It looks like Deinococcus-Thermus appeared in ~14% of samples. I could be mistaken. Correct calculation?

This difference might change Fig.3 as well?
```{r}
filterPhyla = subset(prevdfMSP$Phylum, prevdfMSP$`3` < 0.02)
ps1 = subset_taxa(ps0, !Phylum %in% filterPhyla)

prevdf1 = subset(prevdf, Phylum %in% get_taxa_unique(ps1, "Phylum"))

ggplot(prevdf1, aes(TotalAbundance, Prevalence/nsamples(ps0), color=Phylum)) +
  #prevalence threshold as 5%
  geom_hline(yintercept = 0.05, alpha = 0.5, linetype = 2) + geom_point(size = 2, alpha = 0.7) +
  scale_x_log10() + xlab("Total Abundance") + ylab("Prevalence [Frac. Samples]") + 
  facet_wrap(~Phylum) + theme(legend.position= "none")
```
  
![screen shot 2016-12-13 at 2 32 31 pm](https://cloud.githubusercontent.com/assets/13370432/21144033/02ca6722-c141-11e6-9976-ed768177aeaf.png)

**Comment by joey711** [comment]
In your `ddply` you're reporting the sum or mean of prevalences of taxa, by Phlum, neither of which is a meaningful measure. Prevalence can be calculated separately at the phylum level, but the average of taxa within a phylum does not have a biological meaning. 

If you simply agglomerate the taxa by phylum using tax_glom, you can re-run the prevalence calculation and should get to the same numbers that we found (unless we made a mistake elsewhere).
