### ISSUE TITLE
does not work when I try to subset a phyloseq object in a loop using an idex.

### ISSUE THREAD

**Issue by jvkuehl** [joey711/phyloseq#698]
I have a phyloseq object with lots of taxa that I want subset by each of the  phyla in the phyloseq object and  then use plot_tree.  Is it possible to use an index  in subset in a loop ?     This function is not working for me: 

treeplots = function(df) {
      
      x = as.data.frame(unique(tax_table(df)[,"Phylum"]))
      x  = as.character(x$Phylum)
      x = x[complete.cases(x)]  
     
     for (i in 1:length(x)) {
      print(x[i])
      sdf = subset_taxa(df, Phylum == x[i])
      print(sdf)
      pdf(paste("phylum",x[i],".pdf",sep=""))
      plot_tree(sdf, color="found", label.tips="taxa_names" )
      dev.off()
    }
     
     
 }

> ground_exper_prune
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3362 taxa and 303 samples ]
sample_data() Sample Data:       [ 303 samples by 11 sample variables ]
tax_table()   Taxonomy Table:    [ 3362 taxa by 10 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 3362 tips and 3360 internal nodes ]

>treeplots(ground_exper_prune)
[1] "Proteobacteria"  
Error in eval(expr, envir, enclos) : object 'x' not found
Called from: eval(expr, envir, enclos)

**Comment by StackerEd** [comment]
I had the same problem.  It has to do with R in general.  What you need to do is set something equal to plot_tree ( like p <- plot_tree(...) ) and print(p) after pdf

  pdf(paste("phylum",x[i],".pdf",sep=""))
  p <- plot_tree(sdf, color="found", label.tips="taxa_names" )
  print(p)
  dev.off()

**Comment by joey711** [comment]
good answer. This is a ggplot2 / R issue, and @StackerEd solution should work. Will close for now. Please post back if not, or with your alternative solution.
