### ISSUE TITLE
convert txt to biom for import to shiny-phyloseq

### ISSUE THREAD

**Issue by StefPN** [joey711/phyloseq#711]
Hi, 
My pipeline outputs the OTU table as a .txt and I need help converting it in order to used it in shiny-phyloseq. How do I do this?
I attach a small table as an example.
Thanks a lot for the help!
/Stef
[ALL.unoise.vsearch_short.txt](https://github.com/joey711/phyloseq/files/750392/ALL.unoise.vsearch_short.txt)

**Comment by joey711** [comment]
Most usearch/vsearch tools are going to be able to output a biom-format file. I would start by looking for how to do that, as it is a more effectively maintained solution. The biom-format companion tools in python (or R) can also probably get you there.

I'm going to close this for now, but feel free to post more details, especially if you feel that converting to biom-format in your current pipeline, or from those tools, is not possible for some reason.

Cheers
