### ISSUE TITLE
JSON file error despite conversion to JSON format

### ISSUE THREAD

**Issue by tarunaaggarwal** [joey711/phyloseq#715]
Hi,

I'm trying follow a [tutorial](https://web.stanford.edu/class/bios221/labs/phyloseq/lab_phyloseq.html) for your program but ran into otu table format issues. After researching the issues post, I ended up converting my otu table with BLAST taxonomy into JSON format, but I'm still getting the error below. I'm using `biom-format version 2.1.5`. Any suggestions why I'm still getting the error below. I posted my commands below as well so you know what I'm doing. Thanks for your help!

Cmds:

```
require("phyloseq")
require(ggplot2)
packageVersion("phyloseq")
```
```
[1] ‘1.6.1’
```
```  
myOTU  = system.file("extdata", "~/Downloads/test_otu_w_BLAST_tax_json.biom",  package="phyloseq")
import_biom(myOTU, parseFunction=parse_taxonomy_default)
```
Error:
```
Error in fromJSON (content, handler, default.size, depth, allowComments,  :    invalid JSON input
```

**Comment by joey711** [comment]
That's a very old version of phyloseq if I'm reading that version number correctly. Please update, and post back here if that doesn't already solve the problem.
