### ISSUE TITLE
black slices in plot_bar

### ISSUE THREAD

**Issue by ramiroricardo** [joey711/phyloseq#721]
Hi,

I am new to phyloseq and I was just trying to plot the abundance on my samples. When I do that, I get some of the slices as black, a colour that does not show up in the legend. This happens independent of whether I am using relative or absolude abundance data, if I use a command like:

`plot_bar(data_relativeAbundance, x="sample", fill ="Phylum")`

but not if I use 

`plot_bar(data_relativeAbundance, x="sample", fill ="Phylum")+geom_bar(stat="identity")`

The latter plot matches more my expectation from similar plots that I generated in qiime, so I would like to know if anyone can explain me what is going wrong with the first plot.

the plot for the first command looks like this:

![screen shot 2017-03-01 at 17 52 55](https://cloud.githubusercontent.com/assets/20688427/23474114/8a8732ca-feaa-11e6-97e9-a7dda8d0ed8e.png)

and for the second:

![screen shot 2017-03-01 at 18 01 19](https://cloud.githubusercontent.com/assets/20688427/23474129/97841a4c-feaa-11e6-9043-519a694a8a98.png)

Thanks for any help,

Ramiro

**Comment by jeffkimbrel** [comment]
If you look at the legend of your first plot, each fill is surrounded by a black box. That is what is showing on your first plot as black lines. In `ggplot`, the area inside the box is called the `fill`, and the border is called the `color`. If you look into the `plot_bar` function, you can see it calls `color = "black"` , making the borders have a black line.

When you call `geom_bar(stat="identity")`, it is overriding the `color` call in the `plot_bar` function, removing the border. But, you can see it makes the rectangles a bit jagged.

If you want to cleanest possible version 2 plot, it is the most simple probably to `tax_glom` at the phylum level. 

```
phylumGlommed = tax_glom(data_relativeAbundance, "Phylum")
plot_bar(phylumGlommed, x="sample", fill ="Phylum")
```

**Comment by joey711** [comment]
Thanks @jeffkimbrel nice rec.

@ramiroricardo the black lines are a feature, not a bug. Each box within a color group is a taxa that happen to have the same phylum, in your case. The annoying thing in that graphic is that the black borders have a fixed size, so as the fraction gets small, they overwhelm the color. Since it sounds like you're not interested in peering at the taxa-breakdown within each phyla, your mod or the one recommended above are both fine solutions.

My preferred solution for this, however, would be to use points instead of bars, and a log10 scale on the y-axis (and facets)

See the following post for the facets issue with bars:

https://github.com/joey711/phyloseq/issues/442

**Comment by ramiroricardo** [comment]
Thanks @joey711 and @jeffkimbrel for your quick replies and clarification.

**Comment by tjarbour** [comment]
Dear @joey711 and/or phyloseq team, I am having an issue somewhat related to this and would appreciate any help.

First of all, I have followed the methodology in the Restroom Biogeography example to create the 'NA' category that contains all OTUs less than N% abundance.

For the plotting, I have effectively removed the black borders separating taxa in the line `p + geom_bar…` with the `stat = "identity"` argument, see code below. However, I still get some graphical artifacts in the boundaries between taxa in the stacked bars – see screenshot. I have tried ggsave-ing as PNG, PDF, SVG and all give the same. Any ideas?

Mac OS Ventura running the latest software version 13.3 and R 4.2.3 / RStudio-2023.03.0-3.

Thanks a lot in advance!
Tyler

```
p <- plot_bar(subset_samples(psB.enr.rel.5percNA, grepl("^G0", sample_names(psB.enr.rel.5percNA))),
         "DepthMid_cm")
p + geom_bar(aes(fill = genus5perc), stat = "identity") + # Add 'color = "black"' here to add the black boundaries separating OTUs
  theme_classic() +
  coord_flip() + # switch ('flip') x and y axes to have depth on the vertical
  # Next *reverse* the vertical (now x) axis <==> sample depth, cm bsf
  scale_x_reverse(breaks = breaks_extended(n = 7), limits = c(NA, 0)) +
  scale_y_continuous(labels = function(x) x/3, # have to /3 to normalize for triplicates
                     breaks = 3*c(0, .25, 0.5, 0.75, 1)) + # manually define axis label positions
                                                           # (have to *3 to correct for above)
  labs(y = "Avg. relative abundance (triplicates, all OTUs)") +
  labs(x = "Inoculum sample depth (cm bsf)") +
  guides(fill = guide_legend(title = "Genus", ncol = 1)) +
  theme(legend.text = element_text(size = 8))

ggsave("plots/barplot/G0enrBactGenusRel5perc.png", width = 8, height = 5)
```

![G0enrBactGenusRel5perc](https://user-images.githubusercontent.com/5767144/229785575-c2ba707d-72ca-4c54-aea4-310d971f053d.png)

<img width="1139" alt="plot artifacts zoom" src="https://user-images.githubusercontent.com/5767144/229785905-acf4e1f8-9e5c-42d7-b57c-b04913a21d40.png">

**Comment by jeffkimbrel** [comment]
Although you have removed the border, ggplot is still drawing an individual rectangle for all OTUs, so that is what you are seeing. Try running a `tax_glom` at the genus level, which should collapse the counts to a single value per genus per sample, giving ggplot only a single rectangle to draw.

**Comment by tjarbour** [comment]
Many thanks @jeffkimbrel for your quick response! Your advice was spot-on and I can use this in other instances, but unfortunately for this plot it isn't the solution I need. The reason being that prior to this plotting step I have followed the '[Restroom Biogeography](http://joey711.github.io/phyloseq-demo/Restroom-Biogeography.html)' example to try and create this 'NA' or 'Others' category for all species less than 5% relative abundance (code below). So I have an additional artificial "taxonomic" column called 'genus5perc' that is filled with NAs for sub-5% abundance taxa. Taking the `tax-glom` approach effectively undoes this by throwing out the NAs.

I can't think of any obvious workaround. I think it will involve manual data-wrangling to make different tax_tables where I sum up the abundances of all the sub-N% OTUs and keep them in one artificial row. So maybe forget about phyloseq's plot_bar and just make it with pure ggplot?

```
top5perc = taxa_names(psB.enr.rel.5perc)
taxtab5perc = cbind(tax_table(psB.enr.rel), genus5perc = NA)
taxtab5perc[top5perc, "genus5perc"] <- as(tax_table(psB.enr.rel)[top5perc, "Genus"],
                                          "character")
psB.enr.rel.5percNA <- psB.enr.rel # Copy psB.enr.rel to avoid overwriting in next step
tax_table(psB.enr.rel.5percNA) <- tax_table(taxtab5perc) # Replace the tax_table of this
                                                         # phyloseq object with 'taxtab5perc'
```

Thanks again!
