### ISSUE TITLE
merging two phyloseq objects

### ISSUE THREAD

**Issue by Gian77** [joey711/phyloseq#740]
Hello everyone,
I am here simply to ask, is there a way to easily merge two phyloseq objects? Basically, I have filtered out the most abundant OTUs present in two different groups of samples and now I want to put those two groups of samples together again.
Thank you,
G.

**Comment by joey711** [comment]
See `?merge_phyloseq`

**Comment by Gian77** [comment]
Wow, I had missed it. Thank you! G.
