### ISSUE TITLE
Editing mapping file after generating phyloseq object

### ISSUE THREAD

**Issue by yilmazbah** [joey711/phyloseq#746]
Dear all,

Please allow me to ask a naive question. After generating mapping file and run some analysis, I have realised that there are some typing error in my mapping file. Would that be possible to edit/change this  typing mistakes without regenerating phyloseq object from scratch (I mean without using merge_phyloseq)? Can we do edits on merged phyloseq object?

Thank you very much for your time.

Best wishes,
Bahti

**Comment by campenr** [comment]
You can replace/modify the existing `sample_data` for a phyloseq object like so:

    sample_data(physeq) <- new_sample_data

Just make sure your `new_sample_data` is formatted correctly and is a `phyloseq::sample_data` table.

**Comment by yilmazbah** [comment]
Thanks a lot Richard. That's really helpful.
Best wishes,
Bahti
