### ISSUE TITLE
Quick question regarding Chao1/ACE error bars on Plot Richness Plots

### ISSUE THREAD

**Issue by Justinwright973** [joey711/phyloseq#747]
Hello,

I have a very quick question regarding the standard Plot Richness output from Phyloseq regarding the error bars that are displayed on Chao1/ACE richness plots. Are these error bars presenting the standard error after conducting the test through multiple permutations, or is this a confidence interval?

Thanks!
Justin

**Comment by joey711** [comment]
They are the standard errors as defined for the Chao1 model for estimating richness.

Your second question about confidence intervals is unclear. In principle, one can always estimate a confidence interval through resampling (e.g. bootstrap) or from an explicit formula for uncertainty when one exists. In the case of Chao-1, there is such an explicit formula derived from the assumptions in the Chao-1 model. From the associated help doc in vegan:

> Functions estimate the standard errors of the estimates. These only concern the number of added species, and assume that there is no variance in the observed richness. The equations of standard errors are too complicated to be reproduced in this help page, but they can be studied in the R source code of the function. The standard error are based on the following sources: Chao (1987) for the Chao estimate and...

The confidence interval shown by `plot_richness` is exactly these  Chao-1 standard errors.
