### ISSUE TITLE
export to BIOM format

### ISSUE THREAD

**Issue by joey711** [joey711/phyloseq#75]
Issue 71:

https://github.com/joey711/phyloseq/issues/71

already explains the details for BIOM format and importing is now supported in phyloseq. However, in the future, exporting to BIOM format might be a nice exchange format to handoff between different platforms. There are few standards specific to high-throughput phylogenetic sequencing data, and so this is a good format to support and encourage from within phyloseq.

**Comment by sirmicrobe** [comment]
Hi @joey711 and @nosson 

I would like to take my pre-processed phyloseq-class experiment-level object and export it as a classic otu table or biom format. I could not get the above suggestions to work (the output from make_biom(otu_table(myData), sample_data(myData),tax_table(myData)) did not return a valid biom file). Ideally I would take the biom (or classic otu table > biom) output and be able to use QIIME or other tools for analyses.

Thanks!

**Comment by ghanesh** [comment]
Hello @joey711 
I wanted to ask about the progress with the export into biom format function?
I would specifically need this to export subset trees and otu tables into other platforms to do memory intensive calculations, where R (on my machine) is too limited...

@sirmicrobe: to only export the otu-table you can do following:
otu.tab<-myData@otu_table
write.table(otu.tab, file = "otutab.csv", append = FALSE, quote = TRUE, sep = " ", eol = "\n", na = "NA", dec = ".", row.names = TRUE, col.names = TRUE, qmethod = c("escape", "double"), fileEncoding = "")

Cheers, Alexander

**Comment by joey711** [comment]
This is now supported in [the biomformat package](https://www.bioconductor.org/packages/release/bioc/html/biomformat.html)

**Comment by fitzfinon** [comment]
I'm still confused on how do this. I have biom file that I read into phyloseq and do some processing. I would like the save the  processed phyloseq object as a biom file. Is this possible? I'm having trouble following the discussion above as many of the links are dead. I have the biomformat package, but I can't seem to load a phyloseq object in it. any advice?

**Comment by grasshoppermouse** [comment]
I also would like example code for exporting a modified phyloseq object to a biom file. The following code successfully imports a biom file (with intact tax table), but the export and reimport doesn't work:

```
library(phyloseq)
library(biomformat)
b <- import_biom('data/CAR.biom')
sample_data(b) <- samples_df
b2 <- 
    make_biom(
        data = otu_table(b),
        sample_metadata = sample_data(b),
        observation_metadata = tax_table(b)
    )
write_biom(b2, 'data/CAR2.biom')
b3 <- import_biom('data/CAR2.biom') # Error occurs here

Error in `colnames<-`(`*tmp*`, value = c("ta1", "ta0")) : 
  length of 'dimnames' [2] not equal to array extent
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
1: In parseFunction(i$metadata$taxonomy) : Empty taxonomy vector encountered.
...
```

**Comment by itsmisterbrown** [comment]
It seems that the biomformat package still has quite a few bugs to work out, because it doesn't write a usable .biom file (eg, without needing significant manipulation) for downstream applications (not from a phyloseq object, at least). 

The best workaround that I found was to export the OTU table from the desired phyloseq object and add sample and observation metadata independently via the standalone biom application. It would be fantastic to be able to do this with a convenient wrapper script, however!

**Comment by adityabandla** [comment]
Can this be done in phyloseq now?

**Comment by itsmisterbrown** [comment]
@adityabandla I haven't checked the latest version of the biomformat package (v1.8) yet, but I've since written several processing, filtering, and exporting functions for microbial community data, some of which specifically address this issue. Of those, you might find the write.dataset and/or write.dataset.biom functions helpful. They're hosted at https://github.com/itsmisterbrown/marker_gene_processing_scripts, with a vignette that should hopefully detail their usage.

**Comment by cyklee** [comment]
Hi @itsmisterbrown. Thanks for microfiltR, `write.dataset` worked perfectly to help export data to biom format before converting for use with [FUNGuild](https://github.com/UMNFuN/FUNGuild/). Much appreciated.

**Comment by FilipeMatteoli** [comment]
@itsmisterbrown, I tried to use your code to write a biom file, when I try
write.dataset.biom(ps, filePATH="home/ps.biom", writeFASTA = FALSE)
I got: Error in paste0(filePATH, filePREFIX, "_ASV_table.biom") : 
  argument "filePREFIX" is missing, with no default 

I tried to supply a string or a file to filePREFIX to no avail, what am I missing?

**Comment by itsmisterbrown** [comment]
hi @FilipeMatteoli, here are a few things that might help:

**first, try something like:**

`write.dataset.biom(ps, filePATH="/path/to/home/ps.biom", writeFASTA = FALSE,  filePREFIX = "your_prefix")`

where "your_prefix" is the character string (read:title) that you'd like labeled on your exported biom file, eg. your_prefix.biom. I'd also recommend either using absolute file paths or inserting a variable that lists an absolute file path, such as:

`fp <- paste(getwd(), "/", sep = "")`

and then

`write.dataset(ps = ps, filePATH = fp, filePREFIX = "your_prefix")`

**some other notes:**

I'm not sure how the functionality of the R biom package is these days, so I'd still recommend exporting with `write.dataset()` and then manually creating a biom file with the [biom-format python package](http://biom-format.org/). 

an example workflow using that package would be:

_convert the count table (output of write.dataset in R) to biom format_
`biom convert -i ASV_table.txt -o ASV_table.biom --table-type="OTU table" --to-json`

_add sample metadata and taxonomy_
`biom add-metadata -i ASV_table.biom -o ASV_table_w_tax_and_md.biom --observation-metadata-fp ASV_taxonomy.txt --sample-metadata-fp sample_data.txt `

_check to make sure the the conversion and metadata addition worked properly_
`biom summarize-table -i ASV_table_w_tax_and_md.biom -o table_summary.txt`

where ASV_table.txt, ASV_taxonomy.txt, and sample_data.txt are the raw files outputted by `write.dataset()`

**Comment by DrMaestre** [comment]
Is there a new way to convert from phyloseq object to biom format? I am trying all the ways commented above, but the packages no longer exist, or they have not been updated.... in summary, I can not use those ways to save my phyloseq object into a biom file that I need for a tool called phinch. Any help will be welcome! Appreciate it.

**Comment by jtclaypool** [comment]
@DrMaestre  (and any future people looking to make biom-phyloseq-biom roundtrips) - Here's a workaround I've created as it seems there's not a great way to structure the data to make this easier

```
biom_test <- biomformat::make_biom(data = otu_table(phy_obj),
                                   sample_metadata = sample_data(phy_ob)
                                   ) #create a biom format leaving metadata NULL

test_list <- lapply(seq(biom_test$rows),FUN = function(x){
  list("id"= biom_test$rows[[x]]$id,"metadata"=list("taxonomy"=as.vector(tax_table(phy_obj)[biom_test$rows[[x]]$id,])))
}) #create a correctly formatted list to be exported when written to json

biom_test$rows <- test_list #overwrite the previous list

biomformat::write_biom(biom_test,biom_file = "./test.biom")

test_phy <- phyloseq::import_biom("./test.biom")
```

works for biomformat version 1
