### ISSUE TITLE
Why there is the Component taxa/OTU names do not match error?

### ISSUE THREAD

**Issue by wanglu2014** [joey711/phyloseq#750]
Excuse me.
My code is:
sample_data<-read.csv('sam_table.csv',row.names = 1)
tax_table<-read.csv('tax_table.csv',row.names = 1)
otu_table<-read.csv('otu_table.csv',row.names = 1,check.names=FALSE)

ps <- phyloseq(tax_table(tax_table),sample_data(sample_data),otu_table(otu_table,taxa_are_rows=T))

And, the error massage:
Error in names(frame)[names(frame) == "x"] <- name : 
  names() applied to a non-vector
Error in names(frame)[names(frame) == "x"] <- name : 
  names() applied to a non-vector
Error in names(frame)[names(frame) == "x"] <- name : 
  names() applied to a non-vector
Error in names(frame)[names(frame) == "x"] <- name : 
  names() applied to a non-vector
Coercing from data.frame class to character matrix 
prior to building taxonomyTable. 
This could introduce artifacts. 
Check your taxonomyTable, or coerce to matrix manually.
 Show Traceback
Error in validObject(.Object) : invalid class “phyloseq” object: Component taxa/OTU names do not match. Taxa indices are critical to analysis. Try taxa_names()

Example files is in zip. Might my post does not suit for the rule in github, thank for your advice to improve.

**Comment by wanglu2014** [comment]
Thanks. I have find the method. It all about column row transpose.

**Comment by yfchanmicro** [comment]
Could you tell me how did you resolve this? Thanks.

**Comment by maymystery** [comment]
Could you tell me which table should be transposed?

**Comment by maymystery** [comment]
Could you tell me which table should be transposed?
