### ISSUE TITLE
subset_samples doesn't work in a for loop???

### ISSUE THREAD

**Issue by nextgenusfs** [joey711/phyloseq#752]
I'm trying to filter a phyloseq object to drop samples that have a "no_data" for a given treatment (sample_variables).  Here's an example:
```
> physeq
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 456 taxa and 130 samples ]
sample_data() Sample Data:       [ 130 samples by 15 sample variables ]
tax_table()   Taxonomy Table:    [ 456 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 456 tips and 455 internal nodes ]
```
Now I can look at sample_variables:
```
> sample_variables(physeq)
 [1] "CT_result"            "phinchID"             "CT_mean"             
 [4] "age_class"            "DNA_quant_result"     "BarcodeSequence"     
 [7] "site"                 "sex"                  "site_date"           
[10] "LinkerPrimerSequence" "WNS_status"           "date"                
[13] "DNA_quant_mean"       "ReversePrimer"        "location"            
```
I am able to subset in interactive mode, where I can drop samples where "CT_result" equal "no_data" i.e. via:
```
> subset_samples(physeq, CT_result != "no_data")
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 456 taxa and 128 samples ]
sample_data() Sample Data:       [ 128 samples by 15 sample variables ]
tax_table()   Taxonomy Table:    [ 456 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 456 tips and 455 internal nodes ]
```
However, I"m trying to loop this where I iterate through all the sample_variables.  For example, the following doesn't work:
```
for (y in sample_variables(physeq)) {
    subset_samples(physeq, y != "no_data")
}
```
Can somebody tell me why this doesn't work in the for loop???  And how might I accomplish this, perhaps with a different method?  Would pulling out the sample names into a list work and passing that to prune_samples?

**Comment by nextgenusfs** [comment]
Looks like I found a workaround here https://github.com/joey711/phyloseq/issues/482

Reasoning seems to be that the subset function doesn't work well in this way (I don't really understand why), but the workaround is to use `prune_samples` like this:
```
remove_idx = as.character(get_variable(physeq, treatments[y])) != "no_data"
NewPhySeq = prune_samples(remove_idx, physeq)
```

**Comment by joey711** [comment]
Yep, you beat me to the correct answer. The reason has to do with how R evaluates the expression that is the second argument. The basic R function `subset` has the same limitation, and the core developers at CRAN have suggested that I avoid using `subset()` within low-level functions. 

Basically, a highlevel function like this is fine to use during an interactive session, but don't build on top of it for non-interactive API devel. prune_* family is provided for that purpose instead, or even lower-level functions.

Thanks for closing this :-)

**Comment by AKerley** [comment]
Hi again,

I've managed to work out how to do this. Typical after 3 days of playing around with code I finally write a question on here and I work it out a few hours later. I thought I would add the code I have used for anyone else in my position in the future.

\#Create an empty list for loop output to be recorded in
`pruned_data <- list()`

\#Loop that will iterate through each variable and create list containing each phyloseq class with just one group from the variable
<pre><code>for(i in 1:length(sample_data(myphyloseqclass)$Variable)){
    remove_pops <- as.character(get_variable(myphyloseqclass, "Variable")) == sample_data(myphyloseqclass)$Variable[i]
    pruned_data[[i]] <- prune_samples(remove_pops, myphyloseqclass)
}</code></pre>

\# To call out specific variable subsetted phyloseq classes, the loop saves each variable subset to a number but a new object with variable name can be assigned later on. 
`pruned_data[[1]]`
`pruned_data[[2]]`
`pruned_data[[3]]` ... etc

Cheers!
