### ISSUE TITLE
manual colours assigned in Plot_tree?

### ISSUE THREAD

**Issue by Pete-github** [joey711/phyloseq#770]
Is it possible to customise the colours used in Plot_tree? 

Being able to specify a colour per variable in a specified category would be perfect, like can be done in the ggplots for the DeSeq2 outputs. If this isn't possible, is there a way to change the default pallet? 

One of my variables is being plotted as yellow but it's not very visible. So i guess another solution would be if i could add outlines to each point/base?

Thank you!

**Comment by gcuster1991** [comment]
I'm struggling with the same question.  Did you ever figure out how to change the colors manually?

**Comment by Pete-github** [comment]
Im afraid i couldn't work it out. I spent a few days trying but in the end, unfortunately, i had to resort to photoshop. 
If anyone has any insight i would be very interested though! i have no problem assigning colours or colour pallets to the bar_plots ect. The trees seem to play by different rules.

**Comment by gcuster1991** [comment]
I was able to figure it out last night. The following worked for me:


colorspalette <- c("forestgreen", "red", "gray")
> tree<- plot_tree(ps_Bulk_Class, label.tips="catglab", color="Infestation_Stage", ladderize="left", plot.margin=2.15)
> tree <- tree + scale_color_manual(values=c(colorspalette))
> tree

![image](https://user-images.githubusercontent.com/24256789/36936730-3f3531ea-1ec6-11e8-85d1-b36e9c91cee7.png)

**Comment by Pete-github** [comment]
Excellent, thank you for following up! i tried it out and works good on mine too.
