### ISSUE TITLE
taxa_names<-: You are attempting to assign duplicated taxa_names

### ISSUE THREAD

**Issue by mghanbari** [joey711/phyloseq#785]
Hi

I want to import an otu-like table in Phyloseq for doing some diversity analysis but I keep getting this error: 
```
Error in `taxa_names<-`(`*tmp*`, value = gsub("\"", "", taxa_names(x),  : 
  taxa_names<-: You are attempting to assign duplicated taxa_names 
```
In table each column is a sample, each row is a gene and the intersections have the relative abundance information (calculated as RPKM). I checked the row names of the table and I am sure there is not any duplicate. I guess the problem is due to the type of the names; some example of the names: 
aac(3)-IIa
aac(3)-Ia
aac(6')-Im
aac(6')-aph(2'')
aadA1
aadA11
aadA2
aadA24
aadA3
aadA6
aadA9
 Any idea how to solve this?

**Comment by mghanbari** [comment]
Actually, Phyloseq was right, there were some duplicates :).

**Comment by rachaelantwis** [comment]
Hi - how did you fix these duplicates? And do you know why duplicates occur in the agglomeration, if the agglomeration is based on the name?
Many thanks

**Comment by ankit4035** [comment]
> And do you know why duplicates occur in the agglomeration, if the agglomeration is based on the name?

The duplicates could be caused by `NA`. I was agglomerating at Family and Genus level by keeping `NA` taxonomy and then similar error was encountered. The solution is how you consider these `NA` taxa as their hierarchy is different (unless considering Phylum level). 

The probable solution is remove `NA` and see if error persists.

Hope this helps.

Ankit

**Comment by rachaelantwis** [comment]
Thanks Ankit, I think it was caused by differences further up the taxonomy, i.e. the genus name was the same but the family etc were different so they didn’t agglomerate properly. I edited by hand and reimported.
Many thanks
