### ISSUE TITLE
Create a "Others" category in a stacked bar chart with multiple phyla

### ISSUE THREAD

**Issue by JSkar** [joey711/phyloseq#797]
Hi!

I have been making stacked bar charts using plot_bar() to show the composition of each sample based on the relative abundance of the top 8 Phyla present. However, when I subset out the top 8 phyla, the bars don't go all the way to 1.00 because it has taken out some of the sequences, as expected.

Is there a way to use merge_taxa() to combine all but the 8 most abundant taxa, and then when I plot it, call it "Other"? That way, the bars go all the way to 1.00 and looks more complete.

Thanks!

**Comment by shandley** [comment]
Hi JSkar,

I have accomplished something like this using advice from this #494.

Although I agree with @joey711 in #442 that this isn't always a great way to display your data. Faceting can be more revelatory.

Scott
