### ISSUE TITLE
Create Sample data

### ISSUE THREAD

**Issue by Emskie92** [joey711/phyloseq#799]
Hi I'm trying to execute this command Below but am getting the following error:

>sampledata = sample_data(sampledata2)

Error in validObject(.Object) : 
  invalid class “sample_data” object: Sample Data must have non-zero dimensions.

Help?

**Comment by yoannperrin** [comment]
hi,

What do you want to do? create sample data? Or assign sample data to a phyloseq object?

**Comment by Emskie92** [comment]
I want to add sample data to a phyloseq object

Thanks for getting back to me 🙂

**Comment by yoannperrin** [comment]
Ok,
to create your sample data, go in the good directory and :

> sampledata<-import_qiime_sample_data("Fasting_map.txt")

And next :

> sample_data(GP)<-sampledata

Or, you can add your sample data when you create your phyloseq object with merge_phyloseq
