### ISSUE TITLE
NMDS plot analysis

### ISSUE THREAD

**Issue by lemetrec** [joey711/phyloseq#803]
Hi Joey,

Many thanks for the great tool!
I have a quick question. I have an NMDS plot with an overlay of pH metadata for each sample. The lower pH values seem to group together, where the rest of the distribution is more intermingled. I am trying to ascertain this with a statistical test that could give me a p-value of the statistical difference of the NMDS grouping for the lower pH samples compared to the rest of the pH.
Is there a way in phyloseq to get this out of the ordination object?

Many thanks!
Christophe

**Comment by joey711** [comment]
try `vegan::adonis` on your distance matrix directly.
