### ISSUE TITLE
Is there a good way to analyze Forward and Reverse reads from the same 16S data set?

### ISSUE THREAD

**Issue by ezandi** [joey711/phyloseq#805]
I have 24 pair-end 16S reads that do not merge after filtering.  I have generated separate phyloseq objects for Forward and Reverse reads of each sample.  Is there a good way to combine the F and R phyloseqs for downstream analysis? 

OR: 
 I have manually checked  that many pair reads map to the same 16S gene.  Is it a way to map F and R reads to their corresponding 16S gene and then generate a sequence table from those genes?  This would merge the F and R reads without any overlap.

**Comment by benjjneb** [comment]
This is a dada2 answer rather than a phyloseq answer, but you can combine non-overlapping reads in dada2 with `mergePairs(..., justConcatenate=TRUE)`. This just pastes the F/R reads together with 10Ns in the middle. Downstream stuff like chimera removal and taxonomy assignment should still work, and then it can be imported into phyloseq.

We definitely recommend using overlapping primer sets, but this is an option to consider if needed.

**Comment by ezandi** [comment]
I am worry that the 10Ns at the concatenation point would cause alignment issues!  I agree with you and I like to have overlapping reads. ButI just want to get some data from these reads.

Thanks,

Ebi
On Aug 8, 2017, at 1:28 PM, Benjamin Callahan <notifications@github.com<mailto:notifications@github.com>> wrote:


This is a dada2 answer rather than a phyloseq answer, but you can combine non-overlapping reads in dada2 with mergePairs(..., justConcatenate=TRUE). This just pastes the F/R reads together with 10Ns in the middle. Downstream stuff like chimera removal and taxonomy assignment should still work, and then it can be imported into phyloseq.

We definitely recommend using overlapping primer sets, but this is an option to consider if needed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_joey711_phyloseq_issues_805-23issuecomment-2D321072162&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=l_VYsnUCr4SyPI40sec7Rw&m=qw3eLEpj7gw-Iwq0n9aYf98YpuJK-aZ9KXcQ9A7okpM&s=dNlr1WK2ANV7EMdtT9NeksS2DPIeXtG33ZJ-Gf_oo6M&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQORU8ZKUZ97qvG7CAM3cIqP3-2DH7Acqrks5sWMTVgaJpZM4OxLMU&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=l_VYsnUCr4SyPI40sec7Rw&m=qw3eLEpj7gw-Iwq0n9aYf98YpuJK-aZ9KXcQ9A7okpM&s=audasQoJ9FMq5S92Jt1DZrCs-hA5BlynVeJOmqJbhcw&e=>.

Ebrahim Zandi, Ph.D.
Associate Professor of Molecular Microbiology and Immunology
Faculty Director of Proteomics Core at USC
University of Southern California
Norris Cancer Comprehensive Cancer Center, Keck School of Medicine
NOR 6429, Mail Stop # 9176
1441 Eastlake Ave.
Los Angeles, CA 90089-0112
Phone: 323 865 0644
Email: zandi@usc.edu<mailto:zandi@usc.edu>
