### ISSUE TITLE
How does phylogenetic tree topology change after prune_taxa?

### ISSUE THREAD

**Issue by m-ocejo** [joey711/phyloseq#811]
How does phyloseq treat those taxa removed from the otu_table after filtering in the phylogenetic tree topology? 
In my case I got 2381 ASVs after DADA2. After filtering taxa with kOverA(2,10), only 1501 ASV were left (880 were filtered).
In cases where there is an important number of taxa removed, is there any need to perform new alignment to create a new phylogenetic tree? 

Thanks!

**Comment by joey711** [comment]
exactly according to the `drop.tip` function in ape. See the following in your R session for details:

`?ape::drop.tip`
