### ISSUE TITLE
Integrating metagenomeSeq output in phyloseq object

### ISSUE THREAD

**Issue by Jinx169** [joey711/phyloseq#814]
Hello Joey,

I am doing some 16S-V3-V4-Amplicon analyses of ~300 samples and before doing the statistics I would like to normalize my sequence data, as there are different sequence counts in different samples depending on the sample origin. 
After some reading I found, that probably (am no statician, so it's mainly an educated guess) the CSS approach within the metagenomeSeq package is most suitable for my data. In the R code accompanying your "Waste Not, Want Not" paper I found the R code to transform a phyloseq object into an metagenomeSeq object to use for the calculation of either the normalization factors or the normalized values within the package.
Once a matrix with the normalized values is obtained, how does one integrate it back into the phyloseq object to replace the old values within the OTU table with the normalized once?

Many thanks in advance for your help!
Best regards,
Jenny

PS:
I was trying to figure something out, but since I'm still quite the R rookie I basically have no clue. So I'm sorry to bother you with something potentially trivial. Thanks again!

**Comment by joey711** [comment]
Suppose you have two phyloseq objects, `ps_original` and `obj_trans`, where the latter is a taxa-by-sample matrix with its count values transformed in some way, e.g. via metagenomeSeq.

What you're asking to do then looks like

```R
# copy
ps_trans <- ps_original
otu_table(ps_trans) <- otu_table(obj_trans, taxa_are_rows = TRUE)
```

Make sense?

**Comment by Jinx169** [comment]
Yes, thank you!!!
Was seriously stuck on such a basic thing...^^

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-06 20:48 GMT+01:00 Paul J. McMurdie <notifications@github.com>:

**Comment by hkr01** [comment]
Hello Jenny,
I was wondering whether you could help me with a similar issue? I've used the code 
``obj_trans<-phyloseq_to_metagenomeSeq(ps_filt)`` to convert phyloseq object (ps_filt) to metagenomeSeq - I think this is right?
I then want to scale my data by cumulative sum scaling, using this code `obj_trans<-cumNorm(obj_trans)` 
I then want to convert it back to a phyloseq object using the code 
`otu_table(ps_trans) <- otu_table(obj_trans, taxa_are_rows = TRUE)`
However, I'm getting an error message: `Error in access(object, "otu_table", errorIfNULL) : 
  otu_table slot is empty.`

If you have any suggestions, please let me know. I'd really appreciate it!
Many thanks,
Harriet
