### ISSUE TITLE
prune_taxa, subset_taxa et al. Error

### ISSUE THREAD

**Issue by yumingzhongsheng** [joey711/phyloseq#815]
I want to remove  the OTUs that included all unassigned sequences from my phyloseq dataset, but when I used the functions such as, prune_taxa, subset_taxa, but it shows "Error in phy$edge[, 1] <- newNb[phy$edge[, 1]] : 
  number of items to replace is not a multiple of replacement length"
  Someone can help me ?

**Comment by joey711** [comment]
can you show a reproducible example of what you're attempting to do? Also more explicit about what your filtering criteria are?

**Comment by joey711** [comment]
Please post a [MRE](https://stackoverflow.com/a/5963610/935950). Will close for now.
