### ISSUE TITLE
Ordination failed when doing constrained analysis using data containing missing values

### ISSUE THREAD

**Issue by seashore001x** [joey711/phyloseq#819]
Analysis will be failed when doing RDA or CCA analysis using environmental constrain data containing missing values . 
The ordination in phyloseq was based on vegan package. The default setting (`na.fail`) in vegan is to call stop with missing value. 
I highly recommend to add an optional setting to deal with missing values in `ordination` function or switch default setting to `na.exclude` and give an extra warning .

**Comment by joey711** [comment]
Please post a [MRE](https://stackoverflow.com/a/5963610/935950). Will close for now.

**Comment by DeniRibicic** [comment]
Any update/improvement on this?
