### ISSUE TITLE
PCoA Axis Explanation

### ISSUE THREAD

**Issue by yilmazbah** [joey711/phyloseq#822]
Dear all,

Please forgive me for my naive question. Generally I come across in papers with such a statement about the axis of beta diversity analysis: "Axis1 can be explained with disease variable, Axis2 is related disease location and etc." Can you explain me how we can determine which axis associated with which variable? Can we do this analysis in phyloseq?

Thank you very much.

Bahti

**Comment by joey711** [comment]
there are lots of competing ways to attempt this. Most are somewhat fuzzy, as the axes themselves are necessarily naive to your experimental variables. Most of the statements to which you are referring should be taken with at least a few grains of salt, and an expectation to see supporting evidence.
