### ISSUE TITLE
Combining taxa in stacked barplots

### ISSUE THREAD

**Issue by pvaelli** [joey711/phyloseq#823]
Hi all,

When making stacked barplots, is there anyway to combine the same phyla so that I do not get these lines in my plot? I assume the lines are different OTUs that share the same phylum. Can I somehow merge phyla when they're the same before plotting? Here is the code I'm using and the result; regardless of which format I use (pdf, png, jpg, eps), I end up with these lines. I would prefer to export as an EPS file so I can edit in illustrator. 

Thank you,
Patric

```
data.phylum <- data.merge %>%
  tax_glom(taxrank = "Phylum") %>% 
  transform_sample_counts(function(x){x/sum(x)}) %>%
  psmelt() %>% 
  filter(Abundance > 0.02) %>%
  arrange(Phylum) 

# Stacked Barplot at Phylum level
ggplot(data.phylum, aes(x = Body_Site, y = Abundance, fill = Phylum)) +
  facet_grid(.~Location) +
  geom_bar(stat = "identity",position="fill") + # to equal 1
  theme_classic() +
  # scale_fill_manual(values = phylum_colors) +
  theme(text = element_text(size=15),axis.text.y = element_text(hjust=1)) +
  scale_x_discrete(drop=TRUE) +
  theme(axis.title.x = element_blank()) + # Remove x axis title
  guides(fill = guide_legend( keywidth = 1, keyheight = 1)) +
  ylab("Relative Abundance (Phyla > 2%) \n") +
  ggtitle("Phylum Composition of Newt Bacterial Communities by Location and Body Site")
ggsave("~/Github/16S_community_analysis/mothur/figures/Phylum_abundance.jpg")

```
![phylum_abundance](https://user-images.githubusercontent.com/8581767/30667680-5a99babc-9e26-11e7-8b40-ba1608d218cb.jpg)

**Comment by pvaelli** [comment]
it doesn't look so bad when uploaded to this webpage, but the lines are very clearly visible in my figure. thanks in advance for any suggestions

**Comment by jeffkimbrel** [comment]
Look into `tax_glom()`... it should have what you need.

**Comment by joey711** [comment]
This has been asked and demo-ed before. My [restroom biogeography tutorial](http://joey711.github.io/phyloseq-demo/Restroom-Biogeography) was one of the first to show this.

Detail: 

The default `color` aesthetic is set to "black" in order to get that boundary effect. This is intended and useful if you want to see the number and distribution of features within the taxonomic group mapped to `fill`. 

If you want to get rid of them without agglomerating with `tax_glom` (which is a fine solution @jeffkimbrel !), then you can replace the `color` mapping to be the same as `fill`. If they're both the same, then there's no boundary between features, and all you have left is the color groups (e.g. Phylum in your example).

Also, note that **I strongly recommend not using stacked barplots**, in favor of faceting your groups. Here is the thread that discusses this and shows other bar plot examples:

https://github.com/joey711/phyloseq/issues/291

**Comment by joey711** [comment]
Also see the canonical tutorial where this is already demonstrated:

https://joey711.github.io/phyloseq/plot_bar-examples.html

**Comment by pvaelli** [comment]
Thank you very much for your quick response!

**Comment by MahUIC** [comment]
Hello,

I am new to using R for visualizing the phloseq data. So forgive me if the question is simple.
I don't know why the final plot doesn't stack the same phylum together, and they are all over the place!
One graph has been attached as an example. And I am using script below;

I highly appreciate your help in advance.

![phylum- 2016 and 2017- all depth](https://user-images.githubusercontent.com/45364957/49044929-eee15a00-f194-11e8-9bd0-2e50f16251b2.png)


otubiom="/Users/mahsa/Desktop/pear_assembly/qiime/otu_table_json.biom"
otu_table_temp2 <- import_biom(otubiom, parseFunction = parse_taxonomy_greengenes)
mapping_file="/Users/mahsa/Desktop/pear_assembly/MappingFile_corrected5.txt"
map <- import_qiime_sample_data(mapping_file)
Thacker_data <- merge_phyloseq(otu_table_temp2,map)
print(Thacker_data)
colnames(tax_table(Thacker_data)) <- c("kingdom", "Phylum", "Class", "Order","Family", "Genus", "Species", "Rank1")
Thacker_chloropast= merge_phyloseq(otu_table_temp2,mapping_file,map)
Thacker_NC= Thacker_chloropast %>%
  subset_taxa(Family != "Mitochondria" & Class != "Chloroplast")

# Phylum
Thacker_all= sort(tapply(taxa_sums(Thacker_NC), tax_table(Thacker_NC)[,"Phylum"], sum),TRUE)[1:10]
dim(Thacker_all)
Thacker_all_AllPhylum= subset_taxa(Thacker_NC, Phylum%in%names(Thacker_all))

# Phylum
pPhylum= plot_bar(Thacker_all_AllPhylum, x="Location", fill = "Phylum", facet_grid = ~Year)+theme(text = element_text(size = 20, face = "bold"), axis.text = element_text(size = 14))
pPhylum + geom_bar(aes(color=Phylum, fill=Phylum), stat = "identity", position = "stack")

**Comment by Thermoraptor** [comment]
Hi lads

I'm having the same issue, i simply want to merge the same genus with the same colour as above but it doesn't work. 

p1<-plot_bar(cd, "Contaminant",fill="Genus", facet_grid=~Section)
p1 + geom_bar(aes(color=Genus, fill=Genus),width=1, stat="identity", position="stack")+scale_fill_hue(l=50)+scale_colour_hue(l=70)

[Rplot.pdf](https://github.com/joey711/phyloseq/files/3360950/Rplot.pdf)

Regards C
