### ISSUE TITLE
out_table(phyloseq) column/table differs by input

### ISSUE THREAD

**Issue by gilsharon** [joey711/phyloseq#824]
Hi All, 

I'm fairly new to Phyloseq. I've ran analyses starting from either Qiime imported files, or data handed off from DADA2. It appears as though the topography of the OTU tables is transposed (with the DADA2 one being correct; see below). 
```
> dim(otu_table(qd)) # imported from Qiime files
[1] 603 114
> dim(otu_table(ps_noGF)) # handed off from DADA2
[1] 114 804

```
It is important to mention the the phyloseq data structure is fully functional in both cases (see below), but extracting information is problematic. 
```
> qd
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 603 taxa and 114 samples ]
sample_data() Sample Data:       [ 114 samples by 42 sample variables ]
tax_table()   Taxonomy Table:    [ 603 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 603 tips and 599 internal nodes ]
refseq()      DNAStringSet:      [ 603 reference sequences ]
> ps_noGF
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 804 taxa and 114 samples ]
sample_data() Sample Data:       [ 114 samples by 41 sample variables ]
tax_table()   Taxonomy Table:    [ 804 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 804 tips and 803 internal nodes ]
```
I supposed there's an easy workaround, but this feels like a bug.. ?

**Comment by gilsharon** [comment]
Today I learned of t() to transpose otu-tables and phyloseq classes.

**Comment by joey711** [comment]
Please post a [MRE](https://stackoverflow.com/a/5963610/935950). Will close for now.

also, note that I can't imagine why you would expect QIIME output to have the same number of taxa features as for DADA2...
