### ISSUE TITLE
Merge and split 2 phyloseq objects

### ISSUE THREAD

**Issue by NinaKons** [joey711/phyloseq#825]
Hi Joey,

I have just started looking at the phyloseq code and was wandering how can I merge and split 2 phyloseq objects based on the sampel_IDs in the metadata table?

**Merge**  
- To make sure that the shared RSVs between the 2 datasets (16S DNA and cDNA) are removed given that the same RSVs are assigned the same taxonomy, but how can I check this?
- 2 datasets (16S DNA and cDNA) are comparable ie. have undergone the same phyloseq processing steps
- Same colours for the tax_rank, groups etc are used in the plots

**Split or subset this common phyloseq object** 
- Analyze and visualize the 2 datasets separately in terms of **all** their samples and a subset of **shared** samples (based on 2 separate metadata tables)

# Merge
### Load 3 input files generated via DADA2 pipeline
seqtab.nochim <- readRDS("/home/ubuntu/work/cDNA/trimmed/seqtab.rds") # Chimer-removed RSV table
tax <- readRDS("/home/ubuntu/work/cDNA/trimmed/tax.rds") # Taxonomy table
mt <- read.csv(file="metadata.csv", header=TRUE) # Metadata

### Phyloseq object
ps_DNA <- phyloseq(otu_table(seqtab.nochim_sp, taxa_are_rows = FALSE), 
                   tax_table(tax),
                   sample_data(mt))

### Remove unclassified taxa and reduce sparsity
physeq_DNA <- subset_taxa(ps_DNA, Kingdom != "k__unclassified")
physeq_DNA <- prune_taxa(taxa_sums(ps_DNA) > 0 , ps_DNA)

### Merge
Can apply the same code to cDNA dataset and try to merge the 2 phyloseq objects:

ps_merge <- **merge_phyloseq**(physeq_DNA, physeq_cDNA)

But, have not tested whether **merge_phyloseq** can merge 2 phyloseq objects or found this case in the tutorial (https://joey711.github.io/phyloseq/merge.html#merge_phyloseq). 
- Can you please, confirm that **merge_phyloseq** indeed can merge 2 phyloseq objects?
- As you see my phyloseq object(s) were **created without a tree**, do you think it is going to cause problems during object merging, plotting bars and ordinations, and ADONIS analyses?  

# Subset
### Subset DNA and cDNA with the same samples
sub_ps_same_samples = subset_samples(ps_merged, mt_DNA$Short_name = mt_cDNA$Short_name) 

# Split the subsetted phyloseq object
sub_ps_DNA = subset_samples(sub_ps_same_samples, Short_name = mt_DNA$Short_name) 
sub_ps_cDNA = subset_samples(sub_ps_same_samples, Short_name = mt_cDNA$Short_name) 

Many thanks in advance!

**Comment by joey711** [comment]
@benjjneb do you have a suggestion here?

**Comment by joey711** [comment]
Yes, this is the intended use of `merge_phyloseq`. The sample names from the two phyloseq objects should not overlap. The `taxa_names` for the same RSV must be the same. Your `sample_data` should have a variable that indicates which assay type generated each sample (for your sanity).

The fact of not including a tree (yet) is fine, as there is no good way to merge two trees that I'm aware. If someone shows me one I'd love to support it, though. Once you have the final set of RSV sequences, you can then compute a tree and add to the combined phyloseq object.

**Comment by AngelicaMiraples** [comment]
Hi @joey711, 

I have a phyloseq object that I had to subset into two, psl and pse, for separate analyses. I would now like to merge back together, but am running into errors regarding the tree, as you mentioned above:

> pse
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 156 taxa and 40 samples ]
sample_data() Sample Data:       [ 40 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 156 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 156 tips and 155 internal nodes ]
refseq()      DNAStringSet:      [ 156 reference sequences ]

> psl
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 306 taxa and 40 samples ]
sample_data() Sample Data:       [ 40 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 306 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 306 tips and 305 internal nodes ]
refseq()      DNAStringSet:      [ 306 reference sequences ]

> mps <- merge_phyloseq(pse, psl)
Error in FUN(X[[i]], ...) : one tree has a different number of tips

Any help would be greatly appreciated!

Thanks!

Angelica
