### ISSUE TITLE
Merge 2 ordination plots

### ISSUE THREAD

**Issue by NinaKons** [joey711/phyloseq#826]
Hi Joey,

I have the following code and I need to merge the 2 ordinations on a single plot with the arrows indicating mapping samples from each dataset

ord_DNA <- ordinate(physeq_subset_DNA, method="PCoA", weighted=TRUE)
p_DNA <- plot_ordination(physeq_subset_DNA, ord_DNA, color="Group", title="Phyloseq's Weighted")
p_DNA + geom_point(size=5) + theme_bw()

ord_cDNA <- ordinate(physeq_subset_cDNA, method="PCoA", weighted=TRUE)
p_cDNA <- plot_ordination(physeq_subset_cDNA, ord_cDNA, color="Group", title="Phyloseq's Weighted")
p_cDNA + geom_point(size=5) + theme_bw()

Can you please, suggest how to merge these plot with the p_cDNA having different shape when plotted with p_DNA. Then I need to add arrows between the samples (starting from DNA samples) that are the same between these datasets.

Many thanks in advance!

**Comment by joey711** [comment]
Not sure what you're trying to do here. It is hard to compare more than one pair of axes at a time by eyeball in a chart. There are formal methods for this like procruste, mantel-test, to compare the two sample-wise distances derived from different sources.

To the extent that you want to attempt this at all simply as a graphical comparison, which might be a nice quick peek at the data, you might consider just making a vanilla ggplot2 scatter plot where x is axis-1 of your DNA and y is axis-1 from your cDNA.

To be clear, there is no meaningful relationship between the series of axes from the two separately-derived ordinations, other than the shared samples. Hence, "merging" them in a single table of coordinates for the purposes of plotting is as simple as ordering by sample and pasting the columns from the two ordinations together (e.g. column-binding via `cbind`). Whether you can learn something from this table is another matter, will depend a lot on the data.
