### ISSUE TITLE
Species ordinations and weighted unifrac: what do they mean and are they ok to use?

### ISSUE THREAD

**Issue by ohnoplus** [joey711/phyloseq#827]
In Callihan et al.'s 2016 manuscript  ["Bioconductor workflow for microbiome data analysis"](https://f1000research.com/articles/5-1492/v2)  the there comes a point in the "Different ordintion projections" section where the authors generate both a PCoA plot of sample positions using weighted Unifrac (Figure 13), and another of species coordinates corresponding to that same weighted unifrac (Figure 14). I am puzzled about this later figure, since in the documentation for  [plot_ordination-examples tutorial](http://joey711.github.io/phyloseq/plot_ordination-examples) under section 3, biplot graphic, it states that you can't make a biplot UniFrac, because 

>  this requires methods that are not intrinsically samples-only ordinations. For example, this doesn’t work with UniFrac/PCoA.

I'm trying to figure out then what these species scores that describe the unifrac sample positions end up actually meaning. Is the analysis performed by Calihan et al. ok to do? If so I'll totally use it, but figured I should confirm and hopefully learn why it is ok.

**Comment by joey711** [comment]
Yes you can use it. Note, however, that its meaning is limited for the reasons described in the tutorial. If exploratory analysis that carries forward contributions of individual taxa is important, there are other ordination methods you might consider trying, like DPCoA.
