### ISSUE TITLE
need help with spearman correlation command

### ISSUE THREAD

**Issue by hanhnguyen84** [joey711/phyloseq#831]
Hi guys,
I have a problem with R coding. I am new with R. So basically I have an excel file which has a list of all the bug is all of my sample and one column of a chemical concentration. I need to find the Spearman correlation of all the bugs from all sample to my chemical. A then I want a report of all which has a positive correlation. I am wondering how can do that in R. I am wondering if someone could help.
Thank you so much!
Hanh

**Comment by joey711** [comment]
Please post a [MRE](https://stackoverflow.com/a/5963610/935950). Will close for now.
