### ISSUE TITLE
prune_taxa gaps in trees

### ISSUE THREAD

**Issue by jgoodlife** [joey711/phyloseq#832]
Hi Joey,

when i use `prune_taxa` on  a phyloseq object, it also trims the tips of the phylogenetic tree right?
when i plot the tree using `plot_tree` , i get gaps in the tree.

Is there a way to fix this?

thanks for your help!

**Comment by joey711** [comment]
What do you mean by gaps?
Can you show a reproducible example, emphasizing what it is about the tree that you want to be different?

**Comment by joey711** [comment]
Please post a [MRE](https://stackoverflow.com/a/5963610/935950). Will close for now.
