### ISSUE TITLE
phyloseq_to_edgeR otu counts  

### ISSUE THREAD

**Issue by ninaxhua** [joey711/phyloseq#834]
Hello,
I tried converting a phyloseq object to a DGElist, but I noticed that the count matrix for the DGE list has different counts. All of the samples in the DGE list have 1 greater count value than the original count matrix. Is this a large issue to look into?

**Comment by ninaxhua** [comment]
I guess I could replace the matrix with the corrected count matrix, but that would not change the pseudo.count matrix calculated right?

**Comment by joey711** [comment]
This is up to you. The choice for pseudocount can get even more complicated than you're describing. There is not a universally optimal answer.
