### ISSUE TITLE
mt() with Mann-Whitney Wilcoxon Test 

### ISSUE THREAD

**Issue by ericjcgalvez** [joey711/phyloseq#835]
Hello guys thanks for the great tool and support,
Is there any way to add a non-parametric test such as Wilcoxon in the mt() function?

Best,

Eric

**Comment by joey711** [comment]
I don't recall. However, you can always define a row-(taxa-)wise test, and then use `p.adjust` on the results for multiple testing correction. The trick, as usual, is making sure you're using an appropriate transformation prior to the wilcoxon test. row-wise ranks might not be meaningful for certain transformations.

**Comment by ericjcgalvez** [comment]
Dear Joey,
Thanks a lot for your answer,
I found this way using the library 'EMA::runWilcox' on a relative abundance phyloseq object.

 Do you think that is a good strategy? 

```
library("EMA")
mydata.psq  #phyloseq object in relative abundance 
genus_glom.psq <-tax_glom(mydata.psq, "Genus") #For Genus level

myotu_table<-as(otu_table(genus_glom.psq), "matrix")
mymeta_data <- as(sample_data(genus_glom.psq), "data.frame")
myclass =mymeta_data$CLASS #Class of the pairwise comparison ("Control VS treatment")
myclass.num <- ifelse(myclass=="Control", 0,1) #Define a class i.e Control 

myWilcox_test=EMA::runWilcox(myotu_table, myclass.num, typeFDR = "FDR-BH", q = 0.05, plot = TRUE)

#add the tax_table
row.names(myWilcox_test) = myWilcox_test$probeID
wilcox_testFDR =  merge(as.data.frame(tax_table(genus_glom.psq)), as.data.frame(myWilcox_test), by='row.names', sort=F)
```

Best,

Eric
