### ISSUE TITLE
removing dots from box plots

### ISSUE THREAD

**Issue by StackerEd** [joey711/phyloseq#836]
I've tried a few methods but have been unable to remove dots from box plots... any ideas?

so far I've tried adding geom_boxplot(outlier.color=NA) and geom_point(size=NA, alpha=0, color=NA) to my plot_richness() produced plot....

**Comment by joey711** [comment]
I will close this as a general ggplot2 question. You did not post a reproducible example, but it sounds like you added a boxplot layer to a `plot_richness` ggplot2 object produced using phyloseq. This means you have multiple layers, and you want to remove one or more of them. 

Doing this usually this has the form

```R
p$layers <- p$layers[-1]
p
```

Where `1` was the index of the layer you wanted to remove. The second line `p` just emphasizes that you'll still need to initiate a new render to see the updated version of the plot.
