### ISSUE TITLE
calculating distance erorrs

### ISSUE THREAD

**Issue by Georgie-ru** [joey711/phyloseq#839]
Hi Joey

I am not sure if this is a phyloseq error, but I am trying to Calculate Distances using the distance() function, and I keep getting the error:
"Error in .C(ape:::node_depth_edgelength, PACKAGE = "ape", as.integer(Ntip),  : 
  Incorrect number of arguments (7), expecting 5 for 'node_depth_edgelength'"

Any assistance will be greatly appreciated. Thanks

Georgina

**Comment by Georgie-ru** [comment]
I thried these 2 commands but got the same error:
 > FNA_wUniF.dist = distance(FNA_otu.relative.table, "wunifrac")
Error in .C(ape:::node_depth_edgelength, PACKAGE = "ape", as.integer(Ntip),  : 
  Incorrect number of arguments (7), expecting 5 for 'node_depth_edgelength'
> FNA_wUniF.dist <- phyloseq::distance(FNA_otu.relative.table,"wunifrac")

**Comment by joey711** [comment]
This is due to a bug introduced when ape-package recently updated to version 5. It has been fixed. 

Please update phyloseq to the latest version.

**Comment by Georgie-ru** [comment]
Thank you

Kind Regards,


Georgina Nyawo
