### ISSUE TITLE
distance function: Unweighted and weighted UniFrac

### ISSUE THREAD

**Issue by wasimbt** [joey711/phyloseq#841]
Hi, 
For performing beta diversity analysis for my microbiome samples, i calculated unweighted and weighted UniFrac metrics. After running, when I see the summary for both metrics they differ, for unweighted its shows Euclidean matrix (Gower 1966): TRUE, whereas for weighted it shows Euclidean matrix (Gower 1966): FALSE. Is this normal or i am doing something wrong. Below is the script i used. 

>MLSite_u <- distance(MLSite, method = "uunifrac") #unweighted unifrac

>summary(MLSite_u)
......
call: as.dist.default(m = UniFracMat)
method: 
Euclidean matrix (Gower 1966): TRUE
 
>MLSite_w <- distance(MLSite, method = "wunifrac") #weighted unifrac

>summary(MLSite_w)
.......
call: as.dist.default(m = UniFracMat)
method: 
Euclidean matrix (Gower 1966): FALSE

Please let me know,
Best!
Wasim

**Comment by joey711** [comment]
Please post a [MRE](https://stackoverflow.com/a/5963610/935950). Will close for now.

**Comment by wasimbt** [comment]
Hi, 

Here is the phyloseq class object i used for the analysis (with reduced number of samples). 

[MLtestdata.zip](https://github.com/joey711/phyloseq/files/1457005/MLtestdata.zip)

Again, i used script as, 

    >MLtest_u <- distance(MLtestdata, method = "uunifrac") #unweighted unifrac

    >summary(MLtest_u)
    ......
    call: as.dist.default(m = UniFracMat)
    method:
    Euclidean matrix (Gower 1966): TRUE

    >MLtest_w <- distance(MLtestdata, method = "wunifrac") #weighted unifrac

    >summary(MLtest_w)
    .......
    call: as.dist.default(m = UniFracMat)
    method:
    Euclidean matrix (Gower 1966): FALSE

Let me know why for unweighted it made Euclidean matrix (Gower 1966): TRUE and not for weighted UniFrac. 

Thanks!
