### ISSUE TITLE
Error in the ordinate function for UNIFRAC distance measures (Dimension?)

### ISSUE THREAD

**Issue by waughsh** [joey711/phyloseq#842]
Good Monring, 
I am trying to preform a simple PcoA of about 522 samples using a UNIFRAC distance measurment.
I have followed the advice of updating ape and Phyloseq to the newest version, however, I have obtained the following error. 
```

Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0
In addition: Warning messages:
1: In UniFrac(physeq, ...) :
  Randomly assigning root as -- OTU410377177 -- in the phylogenetic tree in the data you provided.
2: In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE,  :
  data length [7951] is not a sub-multiple or multiple of the number of rows [3976]
```

I have not encountered this error in the past and other distance measures not based on phylogentic trees work fine, so I'm guessing the new package might be interacting weirdly with my tree.

Please advise!

Thanks,
Sheldon W.

**Comment by joey711** [comment]
Please post a [MRE](https://stackoverflow.com/a/5963610/935950). Will close for now.
