### ISSUE TITLE
Box plot outlier question

### ISSUE THREAD

**Issue by ademenez** [joey711/phyloseq#846]
Hi Joey,

I have plotted alpha diversity measures (OTUs observed and Chao1) using geom_boxplot within phyloseq, and I noticed that in many cases there are "dots" (which I believe are there to represent outliers) which are within and not beyond the whiskers. Shouldn't the outliers be plotted only when located beyond the whiskers?

This is the code I have used:

physeq_alpha <- prune_taxa(taxa_sums(physeq3) > 0, physeq3)
sample_data(physeq_alpha)$site_treatments <- factor(sample_data(physeq_alpha)$site_treatments, levels = c("G_pre-exp", "G_Control", "G_L", "G_EW_L","G_cast","T_pre-exp", "T_Control", "T_L", "T_EW_L","T_cast"))

dd <- plot_richness(physeq_alpha, x = "site_treatments", measures=c("Chao1", "Observed")) + geom_boxplot()

![image](https://user-images.githubusercontent.com/11306985/32798777-a5d175f2-c96d-11e7-8454-c97d65d1cce9.png)

I'd appreciate any feedback.

Cheers,
Alex

**Comment by joey711** [comment]
see the `ggplot2::geom_boxplot` documentation for details, options.
