### ISSUE TITLE
ordinate() error with DADA2-derived phyloseq object

### ISSUE THREAD

**Issue by GeoMicroSoares** [joey711/phyloseq#851]
Hello there,

I've followed your [big data](https://benjjneb.github.io/dada2/bigdata.html) and [standard DADA2](https://benjjneb.github.io/dada2/tutorial.html) tutorials to obtain a working phyloseq object from my Illumina MiSeq reads.

The phyloseq object was thus built as such:
```
ps <- phyloseq(otu_table(seqtab_bimR, taxa_are_rows=FALSE),
               sample_data(metadata_ord), 
               tax_table(taxa))
> ps
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 70937 taxa and 128 samples ]
sample_data() Sample Data:       [ 128 samples by 79 sample variables ]
tax_table()   Taxonomy Table:    [ 70937 taxa by 7 taxonomic ranks ]
```

Been playing around with my data quite successfully to get the basic info I need as well as some nice barplots. However, whilst trying to produce an nMDS from the 1000 most abundant SVs my data I run into the following:
```
> ps.1000 = prune_taxa(names(sort(taxa_sums(ps), TRUE))[1:1000], ps)
> ps.r = transform_sample_counts(ps.1000, function(x) x/sum(x))
> ps.ord <- ordinate(ps.r, method="NMDS", distance="bray")

Error in if (autotransform && xam > 50) { : 
  missing value where TRUE/FALSE needed
```
This could be something to do with the relative abundance transformation, but there you go:
```
> ps.ord.c.r.nmds <- ordinate(ps, method="NMDS", distance="bray")
Square root transformation
Wisconsin double standardization
Error in cmdscale(dist, k = k) : NA values not allowed in 'd'
In addition: Warning messages:
1: In distfun(comm, method = distance, ...) :
  you have empty rows: their dissimilarities may be meaningless in method “bray”
2: In distfun(comm, method = distance, ...) : missing values in results
```

Also tried changing taxa names to SV** with ```taxa_names(ps.ord) <- paste0("SV", seq(ntaxa(ps.ord)))``` with and without relative abundance transformation but got the same error as above.

This led me to believe the problem could lie in the phyloseq object, not the ordinate() function, but still tested that with the GP dataset and it worked as it should:
```
> data(GlobalPatterns)
> GP<-GlobalPatterns
> GP
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 19216 taxa and 26 samples ]
sample_data() Sample Data:       [ 26 samples by 7 sample variables ]
tax_table()   Taxonomy Table:    [ 19216 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 19216 tips and 19215 internal nodes ]
> ordinate(GP, method="NMDS", distance="bray")
(...)
Dimensions: 2 
Stress:     0.1612348 
Stress type 1, weak ties
Two convergent solutions found after 20 tries
Scaling: centring, PC rotation, halfchange scaling 
Species: expanded scores based on ‘wisconsin(sqrt(veganifyOTU(physeq)))’
```

What should I check to find/fix the issue? @benjjneb @joey711 
Could this be something to do with the fact that this is a DADA2 output?

Thanks in advance and congratulations for all this work!

**Comment by GeoMicroSoares** [comment]
So sorry - was getting NAs from empty control samples. Worked perfectly as soon as those were out.

Thanks again!

**Comment by Marielis24** [comment]
Hello,

Could you share the code to remove zeros or NAs from the data set?

**Comment by Tr1sh** [comment]
# Transform data to proportions as appropriate for Bray-Curtis distances
> ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))
> ord.nmds.bray <- ordinate(ps.prop, method="NMDS", distance="bray")
Error in if (autotransform && xam > 50) { : 
  missing value where TRUE/FALSE needed
