### ISSUE TITLE
trans_new 

### ISSUE THREAD

**Issue by raw937** [joey711/phyloseq#857]
Hello, 

I can't figure out how to scale by log value or z-score using the trans_new function for heat maps.

Cheers
Rick

**Comment by raw937** [comment]
Hello? Is there a way to fix heatmaps in phyloseq?

**Comment by drcarrot** [comment]
This might help... have you tried decostand from package vegan?

**Comment by raw937** [comment]
How?

**Comment by joey711** [comment]
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
