### ISSUE TITLE
PCoA Plot Inverts when reducing Data set

### ISSUE THREAD

**Issue by Emskie92** [joey711/phyloseq#861]
Hi 

I have been doing some Beta diversity analysis using PCoA plots and have some nice clustering, but I want to track a small proportion of my samples within the larger data set.

However when I reduce my data set it inverts the original cluster diagram, is there any way for me to avoid this?
[Cluster 20 Babies.pdf](https://github.com/joey711/phyloseq/files/1568228/Cluster.20.Babies.pdf)
![pcoa rel ord figure baby labels](https://user-images.githubusercontent.com/30501798/34110654-3a073f94-e3ff-11e7-9f8e-76df4ad32f24.png)

**Comment by joey711** [comment]
PCoA are equivalent on reflection about the origin. You can multiply the coordinates of the "flipped" PCoA axes by `-1`.
