### ISSUE TITLE
Component taxa/OTU names do not match

### ISSUE THREAD

**Issue by ysh1962** [joey711/phyloseq#863]
I am having this problem and would really, really appreciate a help in fixing it.
It is rather my inexperience than any program bug.
So, I imported a biom(with a metadata) and a tre file, separately.
But cannot merge them into a phyloseq.
I can see the discrepancy in taxa_names in biom file and tree file, but have no clue how to fix it.
biom and tre files were generated following mothur SOP.

![image](https://user-images.githubusercontent.com/27475513/34465126-f907c70e-eee2-11e7-9f13-426e14af9ac5.png)

**Comment by joey711** [comment]
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
