### ISSUE TITLE
change color scale for plot_bar

### ISSUE THREAD

**Issue by ohnoplus** [joey711/phyloseq#864]
I'd like to customize the color scale for plot_bar so that I have colors for the different taxa beyond the default ones. Two challenges I have with the default color scheme is that (1) when there are many taxa, ones near eachother are similar in color so its hard to tell where one group ends and the next begins and (2) I (and maybe some of my readers) am partially red-green color blind and have trouble telling several regions of the plot apart.
In ggplot, I can customize my color scale for any plot. Indeed one thing that I like to do is use scale_colour_manual(values = myPalette) with some color-blind friendly palette in which colors that are adjacent to each other look different from each other. At the very least I'd like to use scale_colour_gradient() to change the color gradient to something that works a little better for me. Currently, these functions seem to have no effect on plot_bar. Is there some clever work-around, or can I at least put this in as a feature request? Thanks!

**Comment by jeffkimbrel** [comment]
Try 'fill' instead of 'colour'.

**Comment by joey711** [comment]
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by ohnoplus** [comment]
Thanks @jeffkimbrel, that was exactly what I am looking for.

**Comment by ohnoplus** [comment]
@joey711 Dully chastised. Thanks for keeping me humble.

**Comment by Stabilo12** [comment]
Hi Cramjaco, 

I have the same problem, I want to change the "rainbow" color in the plot_bar function, but this work:

P1= merge_samples(pseq, "Feed")
sample_data(P1)$Feed <- levels(sample_data(pseq)$Feed)
P2 = transform_sample_counts(P1, function(x) 100 * x/sum(x))
P3<- aggregate_taxa(P2, "Family")

p <- plot_bar(P3, "Feed", fill = "Family", title = "relative abundance" )
plot(p) 

But the scale_fill_manual doesn't work:  

P1= merge_samples(pseq, "Feed")
sample_data(P1)$Feed <- levels(sample_data(pseq)$Feed)
P2 = transform_sample_counts(P1, function(x) 100 * x/sum(x))
P3<- aggregate_taxa(P2, "Family")

MyPalette <- c("#5DD0B9", "#E1E7E9", "#1f78b4", "#a6cee3", 
                         "#de77ae", "#c51b7d", "#8e0152", "#6a3d9a", 
                          "#fbdf6f", "#ff7f00", "#fff99")

p <- plot_bar(P3, "Feed", fill = "Family", title = "relative abundance" ) + scale_fill_manual(values=MyPalette)
plot(p) 

Error in +scale_fill_manual(values = myPalette) :  invalid argument to unary operator 

Does somebody know what I'm doing wrong?

**Comment by cresil** [comment]
Your last hex is only 5 characters.

**Comment by Stabilo12** [comment]
Sorry for that typo, but even then, I doesn't work..

**Comment by cpavloud** [comment]
I have the same issue as @cramjaco but I can't seem to make anything work. 
My bar plot is created just fine with 
barchart <- plot_bar(physeq, "Location", fill="Phylum") + facet_wrap(~Biome, scales="free_x")

So, I want to use another colour palette and not the default one for the different Phyla.

First, I count how many Phyla I have in my taxonomy
HowManyPhyla <- length(unique(unlist(taxonomy[,c("Phylum")])))
And I create a relevant colour palette
coloursHowManyPhyla <- c(terrain.colors(HowManyPhyla))
And I run the previous command, where I have added the scale_colour_gradientn function
barchart <- plot_bar(physeq, "Location", fill="Phylum") + facet_wrap(~Biome, scales="free_x") + scale_colour_gradientn(colours=coloursHowManyPhyla)

But the bar plot that is created is just the same as the previous one. Nothing changes. 
So, how can I change the colours of the plot?

**Comment by mikemc** [comment]
In ggplot2, when you use the `fill` aesthetic as you are doing here (`fill = "Phylum"`), rather than the `color` aesthetic, you need to use `scale_fill_*()` instead of `scale_color_*()` or `scale_colour_*()`. See the ggplot2 documentation and tutorials for more information.

**Comment by cpavloud** [comment]
I tried it but again it doesn't work...

barchart4 <- plot_bar(physeq, "Location", fill="Phylum") + facet_wrap(~Biome, scales="free_x") + 
  scale_fill_gradientn(colours=coloursHowManyPhyla)

Error: Discrete value supplied to continuous scale

The only thing I found that kind of works (although I don't really understand how or why) is this

barchart2 <- plot_bar(physeq, "Location", fill="Phylum") + facet_wrap(~Biome, scales="free_x") + 
  geom_bar(aes(color=Phylum, fill=Phylum), stat="identity", position="stack")

but again, I just changed the colours.
I didn't succeded in specifying which colours I want.

**Comment by mikemc** [comment]
In these situations, where you are struggling to figure out how to do ggplot customization to a plot created by a phyloseq function, I suggest just getting the data frame and building up the ggplot from scratch. This makes it easier to know exactly what is going on and get help from all the various online resources for ggplot2 (such as stackoverflow, the ggplot docs, and google more generally). You can do this by
```r
p <- plot_bar(physeq, "Location", fill="Phylum")
pd <- p$data
```
or
```r
pd <- psmelt(physeq)
```
Now you just have a data frame with everything you need to make the plot.
```r
head(pd)
```
Then start building up the bar plot yourself
```r
ggplot(pd, aes(x = Sample, y = Abundance, fill = Phylum)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Biome, scales = "free_x")
```
At this point, you are now in the world of having `ggplot2` problems, rather than `phyloseq` problems,

**Comment by cpavloud** [comment]
So, I have a solution. 
I am posting here in case it helps others. 
You will need to load the RColorBrewer library

First of all, I count how many phyla I have in my taxonomy file (which is a data.frame)
`HowManyPhyla <- length(levels(as.factor(taxonomy$Phylum)))`

Then I build a colour palette with number of colours as many as the Phyla in my samples, by interpolating the palette "Set2". "Set2" is one of the colorblind friendly palettes. 
`getPalette = colorRampPalette(brewer.pal(9, "Set2"))
PhylaPalette = getPalette(HowManyPhyla)`

I get the data frame from the phyloseq object
`pd <- psmelt(physeq)`

And then I do the actual plotting and print my plot as a pdf file
`barchart_palette <- ggplot(pd, aes(x = Location, y = Abundance, factor(Phylum), fill = factor(Phylum))) +
  geom_bar(stat = "identity") +
  facet_wrap(~Biome, scales = "free_x") +
  scale_fill_manual(values = PhylaPalette) +
  guides(fill=guide_legend(ncol=2))
pdf("barchart_palette.pdf", width = 12)
print(barchart_palette)
dev.off()`

Thank you for your help!

**Comment by mikemc** [comment]
@cpavloud Glad you got it working and thanks for sharing your solution. For a potentially easier way to save `ggplot` figures, you might also look into the `ggsave()` function.

**Comment by Hermandez** [comment]
Thank you @mikemc and @cpavloud for our solution... It worked for me. However when I add the function facet_wrap(~Biom, ...) I get the following error

> ggplot(pd, aes(x = Sample, y = Abundance, fill = Family)) +
+   geom_bar(stat = "identity") 
> ggplot(pd, aes(x = Sample, y = Abundance, fill = Phylum)) +
+   geom_bar(stat = "identity") +
+   facet_wrap(~Biome, scales = "free_x")
Error: At least one layer must contain all faceting variables: `Biome`.
* Plot is missing `Biome`
* Layer 1 is missing `Biome`
Run `rlang::last_error()` to see where the error occurred. 


How to sort this out?
Thank you for your assistance.

**Comment by cpavloud** [comment]
Looks like you don't have a Biome parameter column in your original metadata (and subsequently in your phyloseq object), so the ggplot cannot understand how to split the plots.
If you use another one of your parameters instead of Biome, it should probably work just fine.

**Comment by Hermandez** [comment]
Completely right !!!
Thank you @cpavloud, I saw **_Biome_** here like a file type/extension, that is what confuses me.

**Comment by Masoleno** [comment]
As long as you know how many phyla you have, you can simply use get_palette() from ggpubr to make a custom palette. I did 
phylaPalette = get_palette("Dark2", 45) 
to use the Dark2 palette from RColourBrewer for my 45 phyla.
Then you can simply add 
 + scale_fill_manual(values =  phylaPalette)
to the plot_composition() function within phyloseq, like this:

plot_composition(ps,
         average_by = "variable") +
  labs(x = "", y = "", fill = "Phyla")  +
  scale_fill_manual(values =  phylaPalette)
