### ISSUE TITLE
Weighted Unifrac Problem

### ISSUE THREAD

**Issue by ZarulSaurus** [joey711/phyloseq#865]
Hello Phyloseq developers,

I love using phyloseq to visualize my PCoA plots. However, only recently I encountered an error message regarding number of arguments of ape:::node_depth_length. The line that I used here was:

ORD_W = ordinate(PHYSEQ, "PCoA", "unifrac", weighted = T)

The error message is:

Error in .C(ape:::node_depth_edgelength, PACKAGE = "ape", as.integer(Ntip),  : 
  Incorrect number of arguments (7), expecting 5 for 'node_depth_edgelength'
In addition: Warning message:
In UniFrac(physeq, ...) :
  Randomly assigning root as -- Otu1928 -- in the phylogenetic tree in the data you provided.

The warning message of randomly assigning root is common. This problem did not arise when I did unweighted Unifrac ordination.

I attached here the entirety of the script that I used.

Please help me. Thank you.
[phyloseq_script.txt](https://github.com/joey711/phyloseq/files/1606225/phyloseq_script.txt)

**Comment by joey711** [comment]
phyloseq was recently updated to fix an issue when the ape-package changed some of its internal methods, including the one listed in your error message.

You should be able to resolve this error by simply updating to the latest version of phyloseq.

I'll close this for now. Please report back if updating did in fact solve your problem.

**Comment by ZarulSaurus** [comment]
Yes, that definitely solved the problem. Thank you so much for your wonderful software!

**Comment by Bisasara** [comment]
I updated phyloseq and used the codes for PCoA of unweighted unifrac distances. 
I am getting the same error as ZarulSaurus got before updating phyloseq. ZarulSaurus resolved the issue by updating. However, I still have the issue.

**Comment by moderndryad** [comment]
I am having the same problem, and just updated phyloseq. Did you try something else?

**Comment by BS2018** [comment]
No. I just updated phyloseq. I had to do it two to three times.
