### ISSUE TITLE
Identifying which higher level taxa fall within a tip_glom agglomerated taxa

### ISSUE THREAD

**Issue by ohnoplus** [joey711/phyloseq#866]
`tip_glom` seems like a really useful tool for simplifying phyloseq objects into photogenically course bins. However, I can't seem to figure out which higher level taxa (from the non-agglomerated object) fall within the less agglomerated one.

For example, if we follow the example given in the tip_glom documentation
```
library('phyloseq')
library('dplyr')
esophagus1 = prune_taxa(taxa_names(esophagus)[1:25], esophagus)
esophagus2 <- tip_glom(esophagus1, h=0.2)
plot_tree(esophagus1, label.tips="taxa_names", size="abundance", title="Before tip_glom()")
plot_tree(esophagus2, label.tips="taxa_names", size="abundance", title="After tip_glom()"
```

Comparing the two trees visually, it seems like taxa 65_8_7, 65_7_18 and 9_4_3 all end up in a new group called 65_8_7.
I'd like a way to ask, systematically with code, which taxa from esophagus1 fall within each taxon of esophagus2. Is such an operation reasonable?

For instance, I'd really like to add a new column to the tax_table(esophagus2) [if esophagus had a tax_table] called something like "subtaxa" which would be a delimited list of taxa from esophagus1 that fall in that bin.
So one line of tax_table would have something that looks like

> tip;     subtaxa
> 65_8_7;  65_8_7, 65_7_18, 9_4_3

Or something similar.

Thanks for any suggestions.

**Comment by ohnoplus** [comment]
I re-wrote tip_glom to do this as follows. This version requires a data-set with a tax table already existing, so I'll provide an example below.
```
tip_glom_saveid <- function(physeq, h = 0.2, hcfun = agnes, ...){

## Necessary libraries
require(phyloseq)
require(ape)
require(cluster)
require(dplyr)
require(tibble)

## Original phyloseq object
physeq0 <- physeq

## From phyloseq::tip_glom
dd = as.dist(cophenetic.phylo(phy_tree(physeq)))
psclust = cutree(as.hclust(hcfun(dd, ...)), h = h)
## Key showing which OTUs are in which groups
taxGlomKey <- data.frame(key = psclust) %>% rownames_to_column

## Key comparing new otus to old otus
nGrp = max(taxGlomKey$key) 

grps = vector("list", nGrp)
for (loc_key in 1:nGrp){
      grps[[loc_key]] = taxGlomKey %>% filter(key == loc_key) %>% pull(rowname)
}

## Turn list of lists into list of concatenated strings.
oldGroups <- sapply(grps,
                    function(x){
                    unlist(
                        paste(x, collapse = ', ')
                    )
}
)

## From phyloseq::tip_glom - do the actual merging
cliques = levels(factor(psclust))[tapply(psclust, factor(psclust), 
                                         function(x) {
                                         length(x) > 1
})]
for (i in cliques) {
physeq = merge_taxa(physeq, eqtaxa = names(psclust)[psclust == 
                                                    i])
}
```

Example of how this would work.

```
library(phyloseq)
data("GlobalPatterns")
#Smaller test data-set
myTaxa = names(sort(taxa_sums(GlobalPatterns), decreasing = TRUE)[1:10])
ex1 = prune_taxa(myTaxa, GlobalPatterns)

tip_glom_saveid(ex1)
```

**Comment by gcagle1** [comment]
Hi @cramjaco ,
Thanks for sharing your code! I ended up here with the same question you had- I want to be able to see which taxa were merged in a tip glom. I tried out your function but I don't see where the original IDs are returned. From what I can tell it is saved in "oldGroups" but that object isn't returned or incorporated into physeq. Am I missing something?

Thanks

**Comment by O-tempora** [comment]
Probably not relevant to @gcagle1 anymore, but here's the simple way to find what ASV's got agglomerated into each class. Essentially, you can just execute the code of the tax_glom function itself step-by-step.

The "spCliques" object that is generated via "spCliques <- tapply(names(tax), factor(tax), list)" is what you are looking for; it contains each group and corresponding ASVs.

```
CN <- which(rank_names(my_physeq) %in% "level_of_interest_ex_Genus")
tax <- as(access(my_physeq, "tax_table"), "matrix")[, CN]

tax <- as(access(my_physeq, "tax_table"), "matrix")[, 1:CN, drop = FALSE]
tax <- apply(tax, 1, function(i) {paste(i, sep = ";_;", collapse = ";_;")})

bad_empty <- c(NA, "", " ", "\t")
tax <- tax[!(tax %in% bad_empty)]

spCliques <- tapply(names(tax), factor(tax), list)
```
Example "spCliques":
$`Bacteria;_;Verrucomicrobia;_;Verrucomicrobiae;_;Verrucomicrobiales;_;DEV007;_;NA`
 [1] "ASV3597"  "ASV2067"  "ASV2689"  "ASV12609" "ASV3336"  "ASV1027"  "ASV4331"  "ASV3001"  "ASV5145"  "ASV930"  
[11] "ASV1951"  "ASV2298"  "ASV2175"  "ASV3037"  "ASV8562"  "ASV937"   "ASV1504"  "ASV10840" "ASV3570"  "ASV2321"
