### ISSUE TITLE
reorder sample names

### ISSUE THREAD

**Issue by CarlyRae** [joey711/phyloseq#871]
Hi,

I've looked through this issue (https://github.com/joey711/phyloseq/issues/518) and tried several things myself and can't figure out how to keep the sample order in the order that I need.

I am trying to get the rows of a phyloseq object into a specific order to match another dataset that I have. I will be comparing dendrograms between the two datasets. 

Example of the problem:

data("GlobalPatterns")

sample_data(GlobalPatterns)$SampleType

### try to first reorder the factor levels, but that doesn't change the row positions
sample_data(GlobalPatterns)$SampleType <- factor(sample_data(GlobalPatterns)$SampleType, 
                      levels = c("Soil", "Feces", "Freshwater", "Freshwater (creek)", 
                      "Mock", "Ocean", "Tongue", "Skin", "Sediment (estuary)"))

sample_data(GlobalPatterns)$SampleType

### Here is the order I want the rows to be in
desiredOrder <- c("Soil", "Soil", "Soil", "Feces", "Feces", "Feces", "Feces", "Freshwater", "Freshwater",
                  "Freshwater (creek)", "Freshwater (creek)", "Freshwater (creek)","Mock", "Mock", "Mock",
                  "Ocean", "Ocean", "Ocean", "Tongue", "Tongue", "Skin", "Skin", "Skin","Sediment (estuary)",
                  "Sediment (estuary)", "Sediment (estuary)")

### make this into a dataframe as this is what the data I have is in
values <- c(1:26)
select <- as.data.frame(cbind(desiredOrder, values))

### I can get the sample_data in the right order
sample_data(GlobalPatterns)[ order(match(sample_data(GlobalPatterns)$SampleType, select$desiredOrder)), ]

### But it will not assign back to the sample_data object
sample_data(GlobalPatterns) <- sample_data(GlobalPatterns)[ order(match(sample_data(GlobalPatterns)$SampleType, select$desiredOrder)), ]

### Still in the original order
sample_data(GlobalPatterns)

### Can try this too, doesn't work either as in #518 
desiredOrder2 <- c("AQC1cm"  , "AQC4cm" ,  "AQC7cm" ,  "CC1"   ,   "CL3"    ,  "Even1"  ,  "Even2"   , "Even3" ,
                   "F21Plmr" , "LMEpi24M" ,"M11Fcsw"  ,"M11Plmr",  "M11Tong" , "M31Fcsw" ,
                    "M31Plmr",  "M31Tong" , "NP2"   ,   "NP3"   ,   "NP5"  ,    "SLEpi20M", "SV1"   ,  
                    "TRRsed1",  "TRRsed2" , "TRRsed3" , "TS28"   ,  "TS29")

select2 <- as.data.frame(cbind(desiredOrder2, values))
rownames(select2) <- select2$desiredOrder2

order <- rownames(select2)

### Looks great
sample_data(GlobalPatterns)[order, ]

### Won't re-assign...
sample_data(GlobalPatterns) <- sample_data(GlobalPatterns)[order, ]
sample_data(GlobalPatterns)

What I am missing here? And I'm not even sure if this will then translate to the phyloseq object to then be in that order...

Thanks!

**Comment by CarlyRae** [comment]
You can close this. While it is not initiative you have to reorder the otu_table and it will work. This was pointed out in #518, but I thought it was specific to their problem and not what you have to do in all instances to re-order the sample_data

data("GlobalPatterns")
values <- c(1:26)

levels(sample_data(GlobalPatterns)$X.SampleID)
desiredOrder2 <- c("AQC1cm"  , "AQC4cm" ,  "AQC7cm" ,  "CC1"   ,   "CL3"    ,  "Even1"  ,  "Even2"   , "Even3" ,
                   "F21Plmr" , "LMEpi24M" ,"M11Fcsw"  ,"M11Plmr",  "M11Tong" , "M31Fcsw" ,
                    "M31Plmr",  "M31Tong" , "NP2"   ,   "NP3"   ,   "NP5"  ,    "SLEpi20M", "SV1"   ,  
                    "TRRsed1",  "TRRsed2" , "TRRsed3" , "TS28"   ,  "TS29")

select2 <- as.data.frame(cbind(desiredOrder2, values))
rownames(select2) <- select2$desiredOrder2

rownames(sample_data(GlobalPatterns)) <- sample_data(GlobalPatterns)$X.SampleID
order <- rownames(select2)

## does not work
sample_data(GlobalPatterns) <- sample_data(GlobalPatterns)[order, ]
sample_data(GlobalPatterns)

## does work
otu_table(GlobalPatterns) <- otu_table(GlobalPatterns)[,order]
sample_data(GlobalPatterns)

**Comment by splaisan** [comment]
is there any progress on the sample re-ordering using phyloseq, I agree that this is a needed feature and going through splitting and rebuilding the object seems complicated to me.

**Comment by eaholdsworth** [comment]
For anyone still using this for reference, Carly's approach above does work with one small edit:

The second to last reads: otu_table(GlobalPatterns) <- otu_table(GlobalPatterns)[,order]
It should be: otu_table(GlobalPatterns) <- otu_table(GlobalPatterns)**[order,]**
