### ISSUE TITLE
jaccard distance is not jaccard similarity index

### ISSUE THREAD

**Issue by nate-d-olson** [joey711/phyloseq#895]
`phyloseq::diversity(ps_obj, method = "jaccard")` is a weighted distance metric and not the expected unweighted Jaccard similarity index. 
When `method="jaccard"`, the `vegan::vegdist` function is used, and calculates the distance as; 
"Jaccard index is computed as 2B/(1 + B), where B is Bray–Curtis dissimilarity" (from vegan documentation, https://cran.r-project.org/web/packages/vegan/vegan.pdf). 

To get the unweighted Jaccard Index you need to use, `phyloseq::diversity(ps_obj, method = "j")` or `phyloseq::diversity(ps_obj, method = "jaccard, binary = TRUE)`.

**Comment by joey711** [comment]
thanks, @jarioksa
