### ISSUE TITLE
error in loadind phyloseq

### ISSUE THREAD

**Issue by anatiburcia** [joey711/phyloseq#900]
I try to load phyloseq and this message appears:
why this would occur?

> library(phyloseq)
Error: package or namespace load failed for ‘phyloseq’ in namespaceExport(ns, exports):
 undefined exports: %s!=%, %s!==%, %s+%, %s<%, %s<=%, %s==%, %s===%, %s>%, %s>=%, %stri!=%, %stri!==%, %stri+%, %stri<%, %stri<=%, %stri==%, %stri===%, %stri>%, %stri>=%, stri_datetime_add<-, stri_sub<-, stri_subset<-, stri_subset_charclass<-, stri_subset_coll<-, stri_subset_fixed<-, stri_subset_regex<-, stri_c, stri_c_list, stri_cmp, stri_cmp_eq, stri_cmp_equiv, stri_cmp_ge, stri_cmp_gt, stri_cmp_le, stri_cmp_lt, stri_cmp_neq, stri_cmp_nequiv, stri_compare, stri_conv, stri_count, stri_count_boundaries, stri_count_charclass, stri_count_coll, stri_count_fixed, stri_count_regex, stri_count_words, stri_datetime_add, stri_datetime_create, stri_datetime_fields, stri_datetime_format, stri_datetime_fstr, stri_datetime_now, stri_datetime_parse, stri_datetime_symbols, stri_detect, stri_detect_charclass, stri_detect_coll, stri_detect_fixed, stri_detect_regex, stri_dup, stri_duplicated, stri_duplicated_any,

**Comment by erictleung** [comment]
@anatiburcia those function names are from the `stringi` package so there might be something wrong with your installation of that package. So maybe do something along the lines of

```r
remove.packages("stringi")
install.packages("stringi", dependencies = TRUE)
```

Got this suggestion from https://stackoverflow.com/questions/31717850/error-package-or-namespace-load-failed-for-ggplot2-and-for-data-table

**Comment by anatiburcia** [comment]
I removed stringi and it worked

thanks
