### ISSUE TITLE
Creating 100% stacked bar plots with less abundant taxa in a sub-category  

### ISSUE THREAD

**Issue by brookeweigel** [joey711/phyloseq#901]
Hello! I tried to follow the logic from the following issue (https://github.com/joey711/phyloseq/issues/494)... using tips from @audy and @Nick243. But for some reason, when I try creating a new data frame with the phyla condensed into low abundance (< 1%) taxa, I end up with some samples that do not reach 100% on the bar graph... and I cannot figure out how some of the values went "missing" so that relative abundance does not total 100%. See the two plots compared below, 1) for the condensed phyla bar plot, and 2) for the normal relative abundance bar plot (which reaches 100% on the y axis for all samples). Any help would be very useful! Thanks!!

# merge into one phyloseq object
physeq = phyloseq(OTU, TAX, META, phy_tree)
physeq

# Transform into relative abundances + filter to a mean threshold 
physeq2  = filter_taxa(physeq, function(x) mean(x) > 0.1, TRUE)
physeq2
physeq3 = transform_sample_counts(physeq2, function(x) x / sum(x) )
physeq3

# choose samples (only stomach)
stomach <- subset_samples(physeq3, Sample_type=="Stomach")
stomach

# create dataframe from phyloseq object for stomach samples... to graph samples without condensed phyla
stom <- psmelt(stomach) 

# Condense low abundance taxa into an "Other" category for the barplot

# Turn all OTUs into phylum counts
glom <- tax_glom(stomach, taxrank = 'phylum') 
glom # should list # taxa as # phyla
data <- psmelt(glom) # create dataframe from phyloseq object
data$phylum <- as.character(data$phylum) #convert to character

#simple way to rename phyla with < 1% abundance
data$phylum[data$Abundance < 0.01] <- "< 1% abund."

# I also tried using this method, based on median abundance threshold... either way, I still end up with sample that do not reach 100% on the bar graph
# group dataframe by Phylum, calculate median rel. abundance
medians <- ddply(data, ~phylum, function(x) c(median=median(x$Abundance)))
# find Phyla whose rel. abund. is less than 1%
remainder <- medians[medians$median <= 0.01,]$phylum
# list of low abundance phyla
remainder
# change their name to "Phyla < 1% abund."
data[data$phylum %in% remainder,]$Phylum <- "Phyla < 1% abund."
#rename phyla with < 1% relative abundance
data$phylum[data$Abundance < 0.01] <- "Phyla < 1% abund."

#plot with condensed phyla into "< 1% abund" category 
p <- ggplot(data=data, aes(x=Sample, y=Abundance, fill=phylum))
p + geom_bar(aes(), stat="identity", position="stack") + 
  scale_fill_manual(values =  c("darkblue", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "lightskyblue", "darkgreen", "deeppink", "khaki2", "firebrick", "brown1", "darkorange1", "cyan1", "royalblue4", "darksalmon", "darkblue",
                                "royalblue4", "dodgerblue3", "steelblue1", "lightskyblue", "darkseagreen", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "brown1", "darkorange1", "cyan1", "darkgrey")) +
  theme(legend.position="bottom") + guides(fill=guide_legend(nrow=5))

![stomach_grouped_low_abund](https://user-images.githubusercontent.com/26445274/37539040-8dd0d016-2920-11e8-91bc-bb64e62bc38b.png)

# compare to plot of same data, without condensed phyla
p <- ggplot(data=stom, aes(x=Sample, y=Abundance, fill=phylum))
p + geom_bar(aes(), stat="identity", position="stack") + 
  scale_fill_manual(values =  c("darkblue", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "lightskyblue", "darkgreen", "deeppink", "khaki2", "firebrick", "brown1", "darkorange1", "cyan1", "royalblue4", "darksalmon", "darkblue", "royalblue4", "dodgerblue3", "steelblue1", "lightskyblue", "darkseagreen", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "brown1", "darkorange1", "cyan1", "darkgrey", "darkblue", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "lightskyblue", "darkgreen", "deeppink", "khaki2", "firebrick", "brown1", "darkorange1", "cyan1", "royalblue4", "darksalmon", "darkblue", "royalblue4", "dodgerblue3", "steelblue1", "lightskyblue", "darkseagreen", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "brown1", "darkorange1", "cyan1", "darkgrey")) +
  theme(legend.position="bottom") + guides(fill=guide_legend(nrow=5))

![stomach_no_groups](https://user-images.githubusercontent.com/26445274/37539060-a3d75376-2920-11e8-9e57-0325621309bb.png)

**Comment by brookeweigel** [comment]
Nevermind... I figured it out! I had some unassigned (blank) taxonomy cells... once I renamed those to "unknown", the gaps went away! Maybe this will be useful to somebody as well...

**Comment by KMKemp** [comment]
## I solved this problem in a slightly different way using:

```
# Transform to relative abundance
AID_norm <- transform_sample_counts(AID_R, function(x) 100 * x/sum(x))

# Compile taxa by Order (filtering out low abundance taxa)
AID_Orders <- AID_norm  %>%
  tax_glom(taxrank = "Order") %>%                     # agglomerate taxa at order level
  psmelt() %>%                                        # Melt phyloseq object to long format for producing graphics with ggplot2
  filter(Abundance > 1.0)  %>%                        # Filter out orders below 1% in each sample
  arrange(desc(Phylum),desc(Class),desc(Order))

# Sum remaining taxa with a relative abundance < 1% and make a new dataframe
Remainders <- (AID_Orders) %>%
  group_by(SampleID,Mouse,Sex,Diet,Week,Description) %>% 
  summarise(Abundance = (100-sum(Abundance))) %>% 
  as.data.frame()
Remainders$Order<-"Orders < 1%"
Remainders$Phylum<-"_Orders < 1%"
Remainders$Class<-"_Orders < 1%"
Remainders$Kingdom<-"Bacteria"

# Join dataframes
AID_barchart <- full_join(AID_Orders,Remainders)

# reorder based on phylogeny
AID_barchart <- AID_barchart[with(AID_barchart, order(Phylum,Class,Order)),]

# lock in Order level
AID_barchart$Order <- factor(AID_barchart$Order, levels = AID_barchart$Order)
```
## Then I plotted the stacked bar chart with ggplot2

**Comment by saifsikdar** [comment]
Hi @joey711 @KMKemp 
I ran the following code:

top20 <- names(sort(taxa_sums(ps_hi_abundant), decreasing=TRUE))[1:20]
ps.top20 <- transform_sample_counts(ps, function(OTU) 100 * OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.top20)

plot_bar(ps.top20, x="tumour.growth", fill="Phylum") + theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + geom_bar(aes(color=Phylum, fill=Phylum), stat="identity", position="stack")

This code generated an abundance plot.  But,  the stacked bars are not in 100% bars.  Could you please let me know how can I represent those bars in 100% 

Thank you

**Comment by saifsikdar** [comment]
I figured it out.  Just in case anybody needs to know. You just need to transform the phyloseq object using the **psmelt()** function and then you can generate the graph using **ggplot()** and command **position = "fill"** argument inside **geom_bar()** function. 
For example: 
ggplot(data = **psmelt(phyloseq_object)**, mapping = aes_string(x = "variable of your data frame",y = "Abundance")) + **geom_bar**(aes(color=taxon name, fill=taxon name), stat="identity", **position="fill"**)

**Comment by Nat211** [comment]
@brookeweigel  I would also like to know which code you used to remove the unassigned taxa, I am having the same issue. Thanks for sharing!

**Comment by brookeweigel** [comment]
Hello @rahulnccs and @Nat211! It has been a little while since I looked at this, but here is my recent code that worked! It starts with a phyloseq object and ends with a nice looking stacked bar graph, using ggplots in R with the phyloseq package.

# load libraries 
library(ggplot2)
library(phyloseq)
library(tidyverse)

# transform sample counts
physeq3 = transform_sample_counts(physeq2, function(x) x / sum(x) )
physeq3

# Turn all OTUs into class (or phylum or order level) counts
glom <- tax_glom(physeq3, taxrank = 'class') 
glom # should list # taxa as # phyla
data_glom<- psmelt(glom) # create dataframe from phyloseq object
data_glom$class <- as.character(data_glom$class) #convert to character

#simple way to rename phyla with < 1% abundance
data_glom$class[data_glom$Abundance < 0.01] <- "< 1% abund."

#Count # phyla to set color palette
Count = length(unique(data_glom$class))
Count

# To change order of bacterial classes, use factor() to change order of levels (for example, maybe you want to put the most abundant taxa first)... Use unique(data_glom$class) to see exact spelling of each class
unique(data_glom$class)

data_glom$class <- factor(data_glom$class, levels = c("Alphaproteobacteria", "Betaproteobacteria", "Deltaproteobacteria", "Gammaproteobacteria", "Flavobacteriia", "Verrucomicrobiae", "Planctomycetia", "Saprospirae", "Sphingobacteriia", "BD1-5", "Cytophagia", "Acidobacteriia", "OM190", "TA18", "Unknown", "< 1% abund."))

#plot with condensed phyla into "unknown" category 
spatial_plot <- ggplot(data=data_glom, aes(x=Sample, y=Abundance, fill=class)) + facet_grid(~Location, scales = "free")
spatial_plot + geom_bar(aes(), stat="identity", position="stack") + 
  scale_fill_manual(values =  c("royalblue4", "deepskyblue", "blue", "cyan2", "darkorchid", 
                                "gold1", "forestgreen", "firebrick", "mediumspringgreen", "darkorange1",
                                "saddlebrown", "deeppink", "slategray2", "seagreen", "snow4", "black")) +
  theme(legend.position="bottom") + guides(fill=guide_legend(nrow=5))

## I hope this helps everyone!! :)

**Comment by Slamazon4** [comment]
Hi @brookeweigel, 

This code is great thank you! It was exactly what I'm looking for.

However, I'm still having the issue of the bar graph not reaching 100%.

**Comment by brookeweigel** [comment]
Hi @Slamazon4, it looks like your abundance values are not between 0-1, (they range from 0-20+), so the transform_sample_counts must not have worked properly. I can't find the exact reason for your error, but sometimes with phyloseq I have to clear my workspace environment in R and start over, because maybe you re-ran a previous code that wrote over the transformed sample count data. I'm sorry that I can't offer any better advice, but I think that the transform sample count step is the source of your problem (why the bar graph doesn't reach 100%). I hope you get it to work!

**Comment by Slamazon4** [comment]
Thanks for getting back to me so quick @brookeweigel ! 

I did start fresh and run the code again, but the same thing happened. I checked the abundance values and they are all between 0 and 1 so I don't think that's it unfortunately :(

**Comment by PatoUru** [comment]
Hi @brookeweigel!
I followed you script step by step but... I'm still having the issue of the bar graph not reaching 100%.
I didn't found where I have to  change the unassigned (blank) taxonomy cells.
It's a nice barplot but with some problem!
![image](https://user-images.githubusercontent.com/47186701/87715656-116a2180-c784-11ea-9f42-9936c8ade1e5.png)

The script that I used was:
`> #Turn all OTUs into class (or phylum or order level) counts
> glom <- tax_glom(tot2.ra, taxrank = 'Class')
> glom # should list # taxa as # phyla
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 132 taxa and 14 samples ]
sample_data() Sample Data:       [ 14 samples by 12 sample variables ]
tax_table()   Taxonomy Table:    [ 132 taxa by 8 taxonomic ranks ]
> data_glom<- psmelt(glom) # create dataframe from phyloseq object
> data_glom$Class <- as.character(data_glom$Class) #convert to character
> #simple way to rename phyla with < 1% abundance
> data_glom$Class[data_glom$Abundance < 1] <- "< 1% abund."
> #Count # phyla to set color palette
> Count = length(unique(data_glom$Class))
> Count
[1] 41
> #To change order of bacterial classes, use factor() to change order of levels (for example, 
> #maybe you want to put the most abundant taxa first)... Use unique(data_glom$class) to see exact spelling of each class
> unique(data_glom$Class)
 [1] "c__Clostridia"           "c__Gammaproteobacteria"  "c__Alphaproteobacteria"  "c__Desulfotomaculia"     "c__Synergistia"         
 [6] "c__Negativicutes"        "c__Bacilli"              "c__Anaerolineae"         "c__Parcubacteria"        "c__Planctomycetes"      
[11] "c__Verrucomicrobiae"     "c__Thermoanaerobacteria" "c__Syntrophomonadia"     "c__Vicinamibacteria"     "c__Thermotogae"         
[16] "c__Syntrophia"           "c__Spirochaetia"         "c__Leptospirae"          "c__Kiritimatiellae"      "c__Syntrophorhabdia"    
[21] "c__Fermentibacteria"     "c__Actinobacteria"       "c__Aminicenantia"        "c__Phycisphaerae"        "c__Bacteroidia"         
[26] "c__Subgroup_18"          "c__Chlamydiae"           "c__BRH-c20a"             "c__Saccharimonadia"      "c__Lentisphaeria"       
[31] "c__Incertae_Sedis"       "c__Dadabacteriia"        "c__ABY1"                 "c__Dehalococcoidia"      "c__Chloroflexia"        
[36] "c__Moorellia"            "c__uncultured"           "c__Hydrogenedentia"      "c__Polyangia"            "c__MVP-15"              
[41] "< 1% abund."            
> #plot with condensed phyla into "unknown" category
> spatial_plot <- ggplot(data=data_glom, aes(x=Exp, y=Abundance, fill=Class)) + #facet_grid(~otros, scales = "free")
+ #spatial_plot + 
+   geom_bar(aes(), stat="identity", position="stack") +
+ #  scale_fill_manual(values = c("royalblue4", "deepskyblue", "blue", "cyan2", "darkorchid",
+ #                               "gold1", "forestgreen", "firebrick", "mediumspringgreen", "darkorange1",
+ #                               "saddlebrown", "deeppink", "slategray2", "seagreen", "snow4", "black")) +
+   scale_fill_manual(values = c("#70dc85", "#78ac83", "#006602", "#7e5b00", "#5d7fff", "#cb88a6", "#a152da", "#0079b9", "#81d33d",.......................")) +
+   theme(legend.position="bottom") + guides(fill=guide_legend(nrow=5))
> spatial_plot2 <- spatial_plot + scale_x_discrete(limits = newSTorder)
> spatial_plot2`

**Comment by Slamazon4** [comment]
@brookeweigel @PatoUru 

I figured out what my issue was. I needed to plot 'samples' on the x axis for the script to work. I was trying to plot one of my categorical variables instead.

So instead of this:

spatial_plot <- ggplot(data=data_glom, aes(**x=Scores**, y=Abundance, fill=Phylum)) + facet_grid(~Season, scales = "free")
spatial_plot + geom_bar(aes(), stat="identity", position="stack") +
theme(legend.position="bottom") + guides(fill=guide_legend(nrow=5))

I did this:

spatial_plot <- ggplot(data=data_glom, aes(**x=samples**, y=Abundance, fill=Phylum)) + face_grid(~Season, scales = "free")
spatial_plot + geom_bar(aes(), stat="identity", position="stack") +
theme(legend.position="bottom") + guides(fill=guide_legend(nrow=5))

If I wanted to plot my variables along the x axis I had to transform my data x2. For example, if I wanted to plot by season:

**Transform sample counts**
phy.squeeze = transform_sample_counts(phy.squeeze, function(x) x / sum(x))

**Turn all OTUs into class (or phylum or order level) counts**
glom.phylum <- tax_glom(phy.squeeze, taxrank = "Phylum")

**And then merge samples for whatever variable I want to plot along the x axis**
glom.season <- merge_samples(glom.phylum, "Season"

** Transform counts again **
glom.season.phylum = transform_sample_counts(glom.season function(x) x / sum(x))
data_glom <- psmelt(glom.season.phylum) # create dataframe from phyloseq object


** Now I can plot my desired variable along the x axis **
season <- ggplot(data=data_glom, aes(x=Season, y=Abundance, fill=Phylum)) +
  geom_bar(aes(),stat="identity", position="stack") +
  scale_fill_manual(values = c("royalblue3","darkgoldenrod1", "cyan2", "darkorchid4",
                               "black")) +
  theme(legend.position="bottom")

**Comment by gagecoon** [comment]
@PatoUru 

I ran the tax_glom line with my raw counts phyloseq object and then converted that output to relative abundance rather than using relative abundance to select for one division of taxonomy. This resolved my issue with having the plot come up short of 1.0, hope this helps.

**Comment by Hina1112** [comment]
Hi, i need help. When i plot my otu, my graph plot showed the same group sample apart. How can I arrange them, so that they come next to each other? e.g I have LF1, LF2, LF3 AND HF1,HF2,HF3.. the bar graph comes out like HF1, LF2,LF3,HF2,HF3.

**Comment by sethyyyyy** [comment]
Thanks for the help! I had a similar problem
