### ISSUE TITLE
Subset both taxa and samples using a sample variable: phyloseq object 

### ISSUE THREAD

**Issue by nelly87** [joey711/phyloseq#904]
Hi,
My aim is to end up with a phyloseq object that has taxa that only occur at least once in a particular group and only samples from that group.

As a toy example, I would like to subset the enterotype dataset that has 553 taxa, using the sample variable “ClinicalStatus == healthy” and only retain taxa that occur at least once in the subsetted object such that the subset has less than 553 taxa and only has samples from those who are “healthy” .

How can I achieve this?

I tried:

data("enterotype") 

enterotype # 553 taxa and 280 samples

healthy <- enterotype %>% subset_samples(ClinicalStatus == "healthy")

healthy # 553 taxa and 23 samples

Many thanks,
nelly

**Comment by joey711** [comment]
Hi Nelly,

There are actually a lot of examples of doing this kind of operation. Also official doc like this:
https://joey711.github.io/phyloseq/preprocess.html

For the special case of your question, the following works, keeping only taxa that have been observed at least once:

```r
healthy <- prune_taxa(taxa_sums(healthy) > 0, healthy)
```

A more general solution to provenance filter (filtering based on the minimum number of samples in which a taxa appeared):

```r
# Remove taxa that are not present in at least two samples
nSamples = 2
healthy <- prune_taxa(
  taxa = apply(otu_table(healthy), 1, function(x){sum(x>0) >= nSamples}), 
  x = healthy)
```

Hope that helps.
