### ISSUE TITLE
variation proportions in CAP analysis

### ISSUE THREAD

**Issue by kuenz7** [joey711/phyloseq#919]
Hi Paul

I have a question related to the implementation of CAP analysis in phyloseq…

In the old days I coded the CAP analysis myself using the vegan function capscale() and I extracted the variation data for plotting. Today I use your functions ordinate(.., method=“CAP”) and plot_ordination(). I noticed that using your functions, the variation proportions in a CAP are consistently lower than if I do this myself. I also noticed that using phyloseq, the variation proportions in CAP were ofter lower than in a PCoA (Shouldn't a constrained ordination explain more variation than an unconstrained?). Then I tried to find why this is. 

At the level of calculating the ordinations (capscale() vs. ordinate(.., method=“CAP”)), everything is identical as it should be. I then found that you calculate the variation proportions differently. See the screenshot from my R session below. While I calculate the variation proportions only among the Eigenvalues of the constrained axes (I label the CAP axes 1&2 with 69% and 23%), you calculated them among the Eigenvalues of the constrained _and_ unconstrained axes (you label the CAP axes 1&2 with 34% and 11%). Combining the Eigenvalues of the constrained and unconstrained axes occurs at the step of extract_eigenvalues.cca (underlined in red). I was wondering, if I missed something during my stats courses or if this could be improved in the phyloseq code?

Thanks for your help,
Klaus

![screen shot 2018-04-17 at 09 01 07](https://user-images.githubusercontent.com/38457945/38859890-3e48c724-422f-11e8-9ef8-2099c43e4a1e.png)

**Comment by jarioksa** [comment]
This is actually similar as in **vegan** (which is used here). The logic is that the total variation is independent on the set of explanatory variables. The total variation is actually just the same total variation as without any explanatory variables (like it is in, say, analysis of variance and linear regression where you can calculate the total variance before analysis). The proportions tell how much axes based on those explanatory variables explain from that total variation. 

Your way gives something different: it tells you how much your axes explain of the variation that the explanatory axes explain. People do that, too, but that is something else than the proportion of variation explained. If it tells you something, it tells how much of the explained variation can be concentrated on the first axes, but it does tell you what is the proportion of total variation that these axes explain. The **vegan** function `summary(eigenvals())` gives you both statistics.

Finally a comment about your question "Shouldn't a constrained ordination explain more variation than an unconstrained?". The answer naturally depends on what you mean with "explaining", but the eigenvalues of unconstrained ordination are guaranteed to be the largest possible ones. The eigenvalues of any constrained axes can be at maximum as large as the unconstrained eigenvalues, and in that case they don't constrain anything. In general, the eigenvalues of constrained ordination are lower than eigenvalues of unconstrained ordination. If that is what you mean with "explaining".

**Comment by kuenz7** [comment]
Dear Jari
Many thanks for clarification. I see the distinction. 
Great help!, Klaus
