### ISSUE TITLE
Vegan and Phyloseq

### ISSUE THREAD

**Issue by sfeds** [joey711/phyloseq#921]
Hi,

I just wrote this in another thread but then realized that the topic was closed, so I'll open a new one just in case, my apologies if it wasn't necessary.

I'm having issues with vegan and phyloseq when calling the function "distance".
I have been reading in the issues tracker for vegan, and also here, but I'm still unsure of the solution. 
I have updated both packages (phyloseq also from source code).

As a recap, I have:

>library("vegan") ; packageVersion("vegan")
[1] ‘2.5.1’
>library("phyloseq") ; packageVersion("phyloseq")
[1] ‘1.22.3’

>GPdist <- phyloseq::distance(pseq_ra, "bray")
Error in .C("veg_distance", x = as.double(x), nr = N, nc = ncol(x), d = double(N * :
"veg_distance" not available for .C() for package "vegan"

Any tips?
Thanks!

**Comment by vinksn** [comment]
I have the same problem. The distance function works for "wunifrac" but not "bray". 

It seems there is a mismatch between the compiled library and phyloseq copies of vegan functions (see the following for a more complete discussion: [https://stackoverflow.com/questions/49882886/make-network-error-in-r-error-veg-distance-not-available-for-c-for-packag]

**Comment by cjfields** [comment]
My guess is the upcoming Bioconductor release will address this, installing the Github development version works for me.  Using `devtools`:

```
library("devtools")
install_github("joey711/phyloseq")
```
