### ISSUE TITLE
how to plot different taxonomic ranks using tax_glom

### ISSUE THREAD

**Issue by cathi88** [joey711/phyloseq#929]
Hi there, I use phyloseq to analyze 16S data generated from samples of gnotobiotic animals, meaning that I know exactly which species are there. As some are very closely related, I do not get to the species and taxonomy stops at the order. Using tax_glom at Species level, I lose all the informations about these taxa. Is there any way to merge the Order with the Species level if this is empty?Thank you for your help, 
Catherine

**Comment by colinbrislawn** [comment]
Hello Catherine,

One option is to make a new taxonomy level that contains multiple taxonomy ranks at once. Like this:

```R
# my demo phyloseq object:
phyloseqobject

# pull out tax table
tax <- data.frame(tax_table(phyloseqobject))

# make new category with Ranks 4, 5, and 6
tax$Taxonomy <- paste(substring(tax$Rank4, 4), substring(tax$Rank5, 4), substring(tax$Rank6, 4))

# write that additional taxonomy back into the phyloseq object
tax_table(phyloseqobject) <- as.matrix(tax)

# graph combined taxonomy
plot_bar(phyloseqobject, fill = "Taxonomy")
```

Let me know if that works for you!
Colin

**Comment by colinbrislawn** [comment]
I'm glad that worked for you, Cat! 

If this issue is solved, feel free to close this issue.

Colin
