### ISSUE TITLE
phyloseq installation issue

### ISSUE THREAD

**Issue by jp2018ucla** [joey711/phyloseq#933]
Hi, there,
 I was trying to install the phyloseq following the instruction in "https://joey711.github.io/phyloseq/install.html#quick_install".
 However, always get this error message"  **package ‘phyloseq’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\xxxx\AppData\Local\Temp\RtmpyuXNse\downloaded_packages
> library (phyloseq)
Error: package or namespace load failed for ‘phyloseq’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringr’**.  Could anyone help?
 Thank you very much!

**Comment by mmclaren42** [comment]
This might be an issue with your R version and bioconductor version. You might try backing up your personal R library, starting with an empty library, and doing a fresh install of Bioconductor and 
phyloseq (which should install stringr along with other dependencies) using the standard instructions
```{r}
source("http://bioconductor.org/biocLite.R")
biocLite("phyloseq")
```

**Comment by jp2018ucla** [comment]
I deleted the R3.4. and installed R 3.5, and thenrun "phyloseq" using
source("http://bioconductor.org/biocLite.R")
biocLite("phyloseq").

 Still showing 

**package ‘ade4’ successfully unpacked and MD5 sums checked
package ‘ape’ successfully unpacked and MD5 sums checked
package ‘phyloseq’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\xxxx\AppData\Local\Temp\RtmpukVHKM\downloaded_packages
installation path not writeable, unable to update packages: MASS, survival**

      Thank you!

**Comment by jp2018ucla** [comment]
The problem is solved! I need administration permission for the installation. Thanks!

**Comment by cjfields** [comment]
@jp2018ucla it's probably best to go ahead and close the ticket if the issue is resolved.

**Comment by jp2018ucla** [comment]
Will do. Thank you!
