### ISSUE TITLE
Unifrac warning message

### ISSUE THREAD

**Issue by cwatt** [joey711/phyloseq#936]
I'm running into trouble calculating unifrac distances in phyloseq. I keep getting the following message whenever I run the distance function with weighted or unweighted unifrac:

`Warning message: In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE, : data length [86515] is not a sub-multiple or multiple of the number of rows [43258]`

I've checked to make sure that my tree is rooted, that there are no 0 count OTUs in my count table, or any NA values in the OTU count table or tree. After seeing this thread I updated phyloseq (v1.23.1), but the problem is still ongoing. A solution will be reached when I run the distance function, but I'm not sure if it can be trusted. Does anyone have any ideas about what this warning means, how much of a problem it is, and how it might be solved? I'd really appreciate the help.

Thanks in advance! 

Update: I've updated R to version 3.5 and all packages to the latest versions (vegan v2.5-2, ape v5.1, and phyloseq v1.24.0) but no luck getting rid of the warning.

Edit: Removed data and code 7/3/18

**Comment by mstagliamonte** [comment]
This happens to me when the data frame containing the sample names is incomplete.

Hope it helps
Max

**Comment by cwatt** [comment]
Thanks for the suggestion, Max. I double checked and unfortunately my sample names is complete, so that's not causing whatever this issue is.

**Comment by MSMortensen** [comment]
Hi,
I get the same error message every time I try to calculate UniFrac distances for a data set which have had OTUs removed after the tree was created. If this is the case you might want to recalculate your phylogenetic tree.

**Comment by cwatt** [comment]
Hi MSMortsensen, I went back and pruned samples after incorporating them into the phyloseq object and that fixed the issue! Thank you for your insight!

**Comment by gkphylo** [comment]
> Hi MSMortsensen, I went back and pruned samples after incorporating them into the phyloseq object and that fixed the issue! Thank you for your insight!

can you please clarify how you pruned samples to solve this? thanks

**Comment by cwatt** [comment]
@gkphylo My specific problem was caused because I removed some unneeded samples from my OTU table before putting everything together in a phyloseq object, which meant that my tree was inconsistent with my table. When I pruned those samples after making the phyloseq object instead, the problem was solved because phyloseq removed the offending OTUs from the tree at the same time.

If you've already put everything into a phyloseq object before removing things, it sounds like you have a slightly different problem than I did.

**Comment by gkphylo** [comment]
It is interesting that my tree seems to be rooted after pruning and I still get the problem. 

""" is.rooted(phy_tree(set))
[1] TRUE """"

I will try @MSMortensen 's approach and report back to all. I bet this question will become very important for users of the decontam package

**Comment by Nat211** [comment]
Hi all,

I have the same problem! I created my phyloseq object with the tree, used the decontam package as well and then pruned unwanted samples and taxa. I checked and my tree is still "rooted = TRUE". But I get the same error message when trying to use PCoA and unifrac either weighted or unweighted in the ordinate function.

> ps.ord<- ordinate(ps, method="PCoA", distance="unifrac", weighted=TRUE)

Warning message:
In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE,  :
  data length [2237] is not a sub-multiple or multiple of the number of rows [1119]
> 

Looking forward to someone figuring this out!

**Comment by gkphylo** [comment]
> Hi all,
> 
> I have the same problem! I created my phyloseq object with the tree, used the decontam package as well and then pruned unwanted samples and taxa. I checked and my tree is still "rooted = TRUE". But I get the same error message when trying to use PCoA and unifrac either weighted or unweighted in the ordinate function.
> 
> > ps.ord<- ordinate(ps, method="PCoA", distance="unifrac", weighted=TRUE)
> 
> Warning message:
> In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE, :
> data length [2237] is not a sub-multiple or multiple of the number of rows [1119]
> 
> > 
> 
> Looking forward to someone figuring this out!

I don't have a good solution yet, but I have a patch for this. I traced the problem back to removing "family" level taxa using the pruning function and fixed it by removing "genus" level contaminants. Curious to know how you are removing the contaminants identified by decontam

**Comment by Nat211** [comment]
@gkphylo 

First I identified contaminants based on prevalence:

sample_data(ps)$is.neg <- sample_data(ps)$Sample_or_Control == "Control"
contamdf.prev05 <- isContaminant(ps, method="prevalence", neg="is.neg", threshold=0.5)

Then I removed them from my ps object:

ps.decontam_Skin <- prune_taxa(!contamdf.prev05$contaminant, ps)

I am not sure I understand what you are saying about removing "family" or "genus" level?

**Comment by gkphylo** [comment]
> @gkphylo
> 
> First I identified contaminants based on prevalence:
> 
> sample_data(ps)$is.neg <- sample_data(ps)$Sample_or_Control == "Control"
> contamdf.prev05 <- isContaminant(ps, method="prevalence", neg="is.neg", threshold=0.5)
> 
> Then I removed them from my ps object:
> 
> ps.decontam_Skin <- prune_taxa(!contamdf.prev05$contaminant, ps)
> 
> I am not sure I understand what you are saying about removing "family" or "genus" level?

I traced my problem to the genus Klebsiella by removing all contaminants manually. 
e.g. 
""" ex6 = subset_taxa(ex5, !Genus %in% c("g__Delftia","g__Yersinia","g__Ralstonia","g__Microbacterium","g__Schlegelella",
                                        "g__Escherichia","g__Klebsiella"))  """

So when I sequentially add taxa to find what is causing the glitch Klebsiella is the culprit. 
I have tried to see if this is a problem with the tree not being rooted and it does not seem to be the case. 

I get these responses:
"""
> any(is.na(phy_tree(ex6)))
[1] FALSE
> is.rooted(phy_tree(ex6))
[1] TRUE 
"""

**Comment by Nat211** [comment]
@joey711 or anyone else. I still haven't been able to figure this out. Do you guys have any input? Highly appreciate it, Nat

**Comment by Nat211** [comment]
Thank you @MSMortensen - I managed to get it to work!

**Comment by andrebolerbarros** [comment]
Hello everyone,

I'm having the same issue; however, I am not performing any kind of filtering whatsoever. Nevertheless, I get the same error:

`data length [3983] is not a sub-multiple or multiple of the number of rows [1992]`

This happens with rooted & unrooted.

**Comment by Jia9** [comment]
> > I am experiencing the exact same issue but can't recalculate the tree as suggested.
> > I am using the new decontam package for filtering contaminants using a phyloseq object (i.e. "set").
> > After filtering out the contaminants using subset commands, e.g.
> > '''ex5 <- subset_taxa(set, !Genus=="g__Pseudomonas")'''
> > I am pruning to remove taxa_sums<1 and then trying to plot an ordination and keep getting this tree edge problem.
> > How can you recalculate the phylogenetic tree as suggested above to resolve this problem?
> > ''' uuf = UniFrac(ex89, weighted = FALSE)
> > Warning message:
> > In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE, :
> > data length [3635] is not a sub-multiple or multiple of the number of rows [1818]'''
> 
> Hi,
> The problem seems to be that one of the taxa you have removed were the root of your phylogenetic tree. If you reroot your tree it should solve the problem.
> For me the solution was to export the repseq from the pruned phyloseq object, import that into Qiime2, calculate and root a new tree with just those OTUs and then use that new tree with the pruned phyloseq object.

Hi, 
Just wondering how did you export the repseq from the pruned phyloseq object. I exported otu.biom and regenerated the tree in qiime2, but still got warning messages. 

library(biomformat);packageVersion("biomformat")
otu<-as(otu_table(Toad5),"matrix")
otu_biom<-make_biom(data=otu)
write_biom(otu_biom,"otu_biom_Toad5.biom")
##RUN CODE IN QIIME2: desktop_qiime2_2.txt
Toad6<-qza_to_phyloseq(features="feature-table_Toad5.qza", tree="rooted-tree-Toad5.qza", taxonomy="taxonomy_gg.qza", metadata="MetaData_CaneToadData1_2.txt")
Toad6

**Comment by MSMortensen** [comment]
Hi,
For me it was easier just to export the representative sequences from R, import them into a new qiime2 object, build tree, export tree file, and import the new tree file into R (you might have to move some files, but the names are consistent):

**Export repseq and redo tree with seq in clean.2k**
Biostrings::writeXStringSet(refseq(ps.clean),"data/ps.clean.fasta")

**Import into Qiime2**
qiime tools import –input-path ps.clean.fasta –output-path sequences.qza –type ‘FeatureData[Sequence]’

**Build midpoint rooted tree in Qiime2**
qiime alignment mafft --i-sequences sequences.qza --o-alignment aligned-sequences.qza
qiime alignment mask --i-alignment aligned-sequences.qza --o-masked-alignment masked-aligned-sequences.qza
qiime phylogeny fasttree --i-alignment masked-aligned-sequences.qza --o-tree unrooted-tree.qza
qiime phylogeny midpoint-root --i-tree unrooted-tree.qza --o-rooted-tree rooted-tree.qza

**Export tree**
qiime tools export rooted-tree.qza --output-dir exported-feature-table/

**Create the tree in qiime2 and import it here**
tree.new <- read_tree("data/tree.nwk")
phy_tree(ps.clean) <- tree.clean

**Comment by mvanhaute** [comment]
Hello,

I'm having the same issue. I am not performing any filtering and directly using an OTU table with taxonomy and rooted tree from QIIME2. 

Warning message:
In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE,  :
  data length [7655] is not a sub-multiple or multiple of the number of rows [3828]

Any help is appreciated!

**Comment by cadl0590** [comment]
Hi,

I am also having the same issue with DADA2 classified OTUs from qiime2. I have tried the tree re-rooting, which doesn't seem to be helping.

Seems to be a problem a few are having, anybody found a solution that is not to do with rooting the tree?

Thanks!

Christina

**Comment by wallacelab** [comment]
Resurrecting this because I ran smack into it and think I found the root (no pun intended) of the problem.

This error seems to occur when a phylogenetic tree ends up with an `edge` matrix with an odd number of rows, so that this line (distance-methods.r, line 604)

`node.desc <- matrix(tree$edge[order(tree$edge[,1]),][,2],byrow=TRUE,ncol=2)`

fails because an odd number of elements can't go into a 2-column matrix evenly.

The odd number of rows, in turn, seems to happen when the phylogenetic tree is built so that some nodes have more than two children. This is output from my own tree (freshly imported from QIIME2):

```mytree = read.tree(treefile)
edges=phy_tree(mytree)$edge
mycounts = table(edges[,1]) # Source nodes; 1st column of edge matrix
length(mycounts[mycounts ==2]) # Number of nodes with exactly 2 children
[1] 27366
length(mycounts[mycounts !=2]) # Number of nodes with more or fewer children
[1] 47
mycounts[mycounts !=2] # How many nodes each of the above has

28065 29006 29113 29372 29728 30091 30849 31021 31469 32032 33032 33069 33306 33400 33665 33948 34071 
    5     3     4     7     6     3     6     3     5     3     3     3     3     5     5     5     4 
34338 34507 34614 35250 35491 35932 36706 37447 43084 43309 44003 44120 44390 45018 45597 45791 45871 
    4     5     3     3     4     3     3     3     3     8     3     5     3     5    11     5     4 
46802 47317 48616 49981 51266 51740 52245 52277 53381 53626 53855 54298 54949 
    3     3     3     6     3     4     3     3    10     4     6    13     9
```

Most nodes have only 2 children, but some have more (up to 13!). The thing is, I don't know enough about phylogenetics to know if this is an error in phyloseq for making a faulty assumption, or an error in QIIME (or its wrapped software) for making a faulty tree. Can someone tell me where the error lies?

I've made a trimmed version of my tree where I trimmed it to 1000 taxa but still have some nodes with 4-5 children and an odd number of rows in the edge matrix. I'm new to Github; is there a way to upload/attach that file for reproducibility?

**Comment by mstagliamonte** [comment]
Hi, @wallacelab , 

Thank you for your input. If you want to attach a file, just drag and drop it into the message box.

Best,
Max

**Comment by tiffmnelson** [comment]
Hi Jia,
Yes I do remember that error.... interesting but wouldn’t you be able to check this by selecting an even number of rows and the making a tree based on his conclusion?

My understanding is that nodes are the recent common ancestors, the branches between them point to relationships and the ‘children’ I think he is referring to are what we/I call the tips. These are the species/OTUs that represent genetic similarity and in microbe land this can be many. Might be wrong in my understanding though...

**Comment by tiffmnelson** [comment]
It will be good to see what the response is

**Comment by wallacelab** [comment]
Here's the example:
[example.newick.txt](https://github.com/joey711/phyloseq/files/3557103/example.newick.txt)

Code:
```
> library(phyloseq)
> tree = read_tree('example.newick.txt')
> str(tree)
List of 5
 $ edge       : int [1:1795, 1:2] 902 903 904 905 906 907 908 908 907 909 ...
 $ edge.length: num [1:1795] 3.46e-02 1.17e-02 1.94e-02 1.89e-02 1.20e-08 ...
 $ Nnode      : int 895
 $ node.label : chr [1:895] "0.963" "0.806" "0.870" "0.714" ...
 $ tip.label  : chr [1:901] "EU202849.1.1443" "KP398529.1.1417" "LN572572.1.1372" "KR559961.1.1464" ...
 - attr(*, "class")= chr "phylo"
 - attr(*, "order")= chr "cladewise"
> node.desc <- matrix(tree$edge[order(tree$edge[,1]),][,2],byrow=TRUE,ncol=2) # copied from distance-methods.r
Warning message:
In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE,  :
  data length [1795] is not a sub-multiple or multiple of the number of rows [898]
```

Again, I'm not a phylogenetics expert, so I don't know if it's internal nodes or tips or whatever that is the issue, but it seems likely to mess up the resulting calculation.

**Comment by PandengWang** [comment]
Hi all,
I have encountered the same issue.
@wallacelab is right!
When your tree is not **dichotomy tree**, which means that one internal node owns "two and only two" children, you will have this issue.
One way to solve this problen is transforming all multichotomies into a series of dichotomies with one (or several) branch(es) of length zero.
`new_tre <- ape::multi2di(tre)`
After i did this, this issue was gone and I got the same unifrac values comparing with that were calculated by function `picante::unifrac`.

**Comment by andrewjmc** [comment]
Wow, am I glad someone had already gotten to the bottom of this. Note that for me though, the problem came down to having singleton lineages, and I had to add `collapse.singles=TRUE` to my `drop.tip` command as `multi2di` can't fix non-branching lineages.

**Comment by jonathanth** [comment]
For me, seems the solution from @PandengWang with `ape::multi2di(tree)` works! My tree was already rooted, but re-rooting with `ape::root(tree, newroot)` also worked @MSMortensen. Maybe they consolidate the tree stucture in the same way?

**Comment by wasade** [comment]
I just became aware of this issue.

If encountering problems with UniFrac, I advise checking for expected results with the [reference implementation](https://github.com/biocore/unifrac-binaries/). It has been validated against the original test suite in [PyCogent](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2007-8-8-r171) developed by Cathy Lozupone and Rob Knight who originally [defined UniFrac](https://journals.asm.org/doi/10.1128/aem.71.12.8228-8235.2005), as well as validated against the [test suite](https://github.com/scikit-bio/scikit-bio/blob/e3a27f56970fded68ba7561767cec41e47ba3c78/skbio/diversity/beta/tests/test_unifrac.py#L22) in [scikit-bio](https://github.com/scikit-bio/scikit-bio). The reference implementation is BSD-licensed, developed and maintained by Rob Knight's lab, has been extensively optimized ([ref.1](https://www.nature.com/articles/s41592-018-0187-8); [ref.2](https://journals.asm.org/doi/10.1128/msystems.00028-22)), and is actively maintained.
