### ISSUE TITLE
plot_bar() by abundance rather than alphabetically

### ISSUE THREAD

**Issue by MayaGans** [joey711/phyloseq#938]
Hi - I'm sorry if this has been addressed elsewhere but I'm struggling to figure out how to reorder a stacked bar plot from plot_bar() by Order abundance rather than Orders given alphabetically. I tried playing around within my phyloseq object to reorder the Order levels, but I'm struggling to extract the abundance data. Please advise. 

data from: https://joey711.github.io/phyloseq/plot_bar-examples.html
```{r}
data("GlobalPatterns")
gp.ch = subset_taxa(GlobalPatterns, Phylum == "Chlamydiae")
plot_bar(gp.ch, fill="Genus")
```
Output is given in alphabetical order starting with **Candidatus Protochlamydia** when **Parachlamydia** or **Wadlia** should be on top of the bars. 

Thank you!

**Comment by mmclaren42** [comment]
To customize in this way, you should/need to use `ggplot` directly. Essentially, you want to extract the dataframe from the plot returned by `plot_bar`, and re-level the fill variable to whatever order you want. How I would do this in this case (for genus, since it seems there is only one order in this example subsetted dataset):
```{r}
library(phyloseq)
library(tidyverse)

data("GlobalPatterns")
gp.ch = subset_taxa(GlobalPatterns, Phylum == "Chlamydiae")
p <- plot_bar(gp.ch, fill="Genus")
pd <- p$data %>% 
    as_tibble %>%
    mutate(Genus = as.character(Genus)) %>%
    replace_na(list(Genus = "unknown"))
genus_abun <- pd %>%
    group_by(Genus) %>%
    summarize(Abundance = sum(Abundance)) %>%
    arrange(Abundance)
genus_levels <- genus_abun$Genus
pd0 <- pd %>%
    mutate(Genus = factor(Genus, genus_levels))
ggplot(pd0, aes(x = Sample, y = Abundance, fill = Genus)) + 
    geom_bar(stat = "identity")
```

**Comment by douglas-hoen** [comment]
Thanks. But I must say, this is a lot of code to perform a common operation. Also, it fails to perform the sort on my data and it changes the color scheme. Lots of wasted time.
