### ISSUE TITLE
How to plot evenness metric in phyloseq

### ISSUE THREAD

**Issue by emankhalaf** [joey711/phyloseq#945]
Hello,
I already calculated evenness in phyloseq as follow:
alpha_diversity <- estimate_richness(silk_working_control, measure = c("Shannon", "Observed"))
alpha_diversity
H <- alpha_diversity$Shannon
S1 <- alpha_diversity$Observed
S <- log(S1)
evenness <- H/S
evenness
alpha_diversity$Evenness = evenness
alpha_diversity

#So now alpha diversity dataframe has three indices; oberved, shannon and evenness.
But when plot_richness, it is applied only on observed and shannon. 
Any help please?
Eman

**Comment by ianartmor** [comment]
Hi Eman,

I believe the input to `plot_richness()` is a phyloseq object, not a data frame, so I think you'll need to use ggplot2 to do what you're trying to do. Here's how I would do it (with the disclaimer that I'm not an expert in R):

`df <- data.frame(alpha_diversity, sample_data(physeq))`
`df2 <- tidyr::gather(df, key =  "Measure", value = "Value", Observed, Shannon, Evenness)`
`ggplot(data = df2, aes(x = insert_var_here, y = Value)) + `
    `facet_wrap(~Measure, scale = "free") +`
    `geom_point() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +`
  `ylab("Alpha Diversity Measure")`

Ian

**Comment by emankhalaf** [comment]
Hello Ian,
Great, the code works. Much thanks Ian, but it plots the values of total samples without categorization as in plot_richness. I want to display the points grouped by a specific variable like year, or replicates.
Have any suggestion.
Eman

**Comment by emankhalaf** [comment]
I tried 
facet_wrap(Measure~Year, scale = "free", nrow = 3). It did grouped the results, but not same quality of plot_richness . I mean I have two separate strips to show samples in two years. Whereas in plot richness, It is one strip with the measure name (Shannon), that includes two boxplots; each for a group (2016 and 2017).
Any help?

**Comment by emankhalaf** [comment]
Also, I want to unify the scale for each measure, for example, I have two plots for shannon metric (2017, 2016), same scale but not unified (two different levels) which is non-sense.
Thanks

**Comment by emankhalaf** [comment]
I tried scales="fixed"  which figured it out. But, now I have stacked strip (evenness/year). I want to remove the upper one which denotes the metric. The available option theme(strip.text.x = element_text()
remove the entire strip??
Also, to calculate p value, I added
+ geom_signif(comparisons = list(c("2016", "2017")), 
              map_signif_level=TRUE)
But I got 
Warning message:
"Computation failed in `stat_signif()`:
missing value where TRUE/FALSE needed"Warning message:
"Computation failed in `stat_signif()`:
missing value where TRUE/FALSE needed"

but same code is working well in plot_richness which deals with physeq
My problem is how to do the same job with evenness (dataframe)

Also, is there any option to display pvalue and test name on the graph

**Comment by ianartmor** [comment]
Hi Eman, 

In my code, did you replace `insert_var_here` with `Year`? That should get you a plot that looks like `plot_richness` produces.

I'm not familiar with `geom_signif`; that may be a more general ggplot2 question for stackexchange. Either way, it might work if you wrap only by measure and use your own variable for X as suggested (worth a try at least).

Ian

**Comment by yogeshgupt** [comment]
> Hi Eman,
> 
> I believe the input to `plot_richness()` is a phyloseq object, not a data frame, so I think you'll need to use ggplot2 to do what you're trying to do. Here's how I would do it (with the disclaimer that I'm not an expert in R):
> 
> `df <- data.frame(alpha_diversity, sample_data(physeq))`
> `df2 <- tidyr::gather(df, key = "Measure", value = "Value", Observed, Shannon, Evenness)`
> `ggplot(data = df2, aes(x = insert_var_here, y = Value)) + `
> `facet_wrap(~Measure, scale = "free") +`
> `geom_point() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +`
> `ylab("Alpha Diversity Measure")`
> 
> Ian

could you please suggest what is x = insert_var_here?

**Comment by yogeshgupt** [comment]
> Hi Ian,
> 
> I did something different which was really simple and to the point:
> 
> ##Add the diversity table to metadata
> data1$Shannon <- alpha_diversity$Shannon
> head(data1)
> 
> ##compare differences in Shannon index between two years.
> 
> # create a list of pairwise comaprisons
> PY <- levels(data1$Year) # get the variables
> 
> # make a pairwise list that we want to compare.
> PY.pairs <- combn(seq_along(PY), 2, simplify = FALSE, FUN = function(i)PY[i])
> 
> print(PY.pairs)
> 
> results in "2016", "2017"
> 
> ## boxplot:
> ##Statistics: pairwise comparision using non-parametric test (Wilcoxon test).
> p1 <- ggplot(data=data1, aes_string(x='Year',y='Shannon')) + geom_boxplot() + theme(legend.position = "right") + theme(legend.title = element_text(face = "bold", size = 9)) + theme(axis.title.y = element_text(face="bold", size = 10)) +
> theme(axis.text = element_text(size = 6)) + theme(axis.title.x = element_text(face="bold", size = 10)) +
> theme(panel.background = element_blank()) + theme( axis.line = element_line(size = 0.25, linetype = "solid")) + stat_compare_means(comparisons = PY.pairs, label = "p.signif") + stat_compare_means(label.y = 1.0, size = 3)
> 
> print(p1 + ggtitle("Shannon diversity index (Year)"))
> 
> ##that results in a boxplot graph with p-value and the name of the stat test showed as well.
> 
> ## to get the detailed calculations
> ps1 <- ggplot_build(p1)
> print(ps1)
> 
> Thanks
> Eman

what is data1 is here? is it a phyloseq object? how we can get data1?
