### ISSUE TITLE
Reordering x-axis in a Heatmap

### ISSUE THREAD

**Issue by astoriadetuncq** [joey711/phyloseq#948]
Hello,

I was able to produce a heatmap from my data, but I don't know how to reorder the x-axis i.e. [1,2,3,4...] instead of [4,2,1,3...]. Originally, I tried using levels(), but that did not work. 

Here is a pdf of the heatmap: [Basic R plot 1.pdf](https://github.com/joey711/phyloseq/files/2049757/Basic.R.plot.1.pdf)

Here is my code so far:

`library("phyloseq"); packageVersion("phyloseq")
[1] ‘1.22.3’
> library("ggplot2"); packageVersion("ggplot2")
[1] ‘2.2.1’
> theme_set(theme_bw())
> colnames(tax_table(biom_otu_tax)) <- c("kingdom", "phylum", "class", "order", "family",  "genus", "species")
> bot <- biom_otu_tax
> get_taxa_unique(biom_otu_tax, "phylum")
 [1] "p__Firmicutes"      "p__Actinobacteria" 
 [3] "p__Proteobacteria"  "p__Bacteroidetes"  
 [5] "p__Cyanobacteria"   "p__Fusobacteria"   
 [7] "p__Synergistetes"   "p__Verrucomicrobia"
 [9] "p__Chlamydiae"      "p__TM7"            
[11] "p__Tenericutes"     "p__Deferribacteres"
[13] "p__Spirochaetes"    "p__Lentisphaerae"  
[15] "p__Fibrobacteres"   "p__Planctomycetes" 
[17] "p__SR1"             "p__Euryarchaeota"  
[19] "p__Elusimicrobia"   "p__WPS-2"          
[21] "p__[Thermi]"        NA                  
[23] "p__Acidobacteria"  
> bot <- subset_taxa(biom_otu_tax, phylum=="p__Firmicutes")
> bot <- prune_taxa(names(sort(taxa_sums(bot),TRUE)[1:10]), bot)
> plot_heatmap(bot)`

Thanks and sorry if this is a really obtuse question.

**Comment by ianartmor** [comment]
Would the `sample.order` option in `plot_heatmap` work?

**Comment by astoriadetuncq** [comment]
@ianartmor Yes, that worked. Thanks for your help (again)! 

Do you know if you can also change axis titles using the `plot_heatmap` command? I read the documentation, and it does not look like I can change it there. 

`plot_heatmap(bot, method = "NMDS", distance = "bray", sample.label = NULL, taxa.label = NULL, low = "#000033", high = "#66CCFF", na.value = "black", max.label = 250, title = NULL, sample.order = (1:18), taxa.order = NULL, first.sample = NULL, first.taxa = NULL)`

**Comment by ianartmor** [comment]
You're welcome! Yeah, you can follow the `plot_heatmap()` command with `+ xlab("Insert_axis_title_here")`. More info here: http://ggplot2.tidyverse.org/reference/labs.html

**Comment by astoriadetuncq** [comment]
@ianartmor You're literally a life saver. Thanks!
