### ISSUE TITLE
Error with adonis !! Error in (function (classes, fdef, mtable) 

### ISSUE THREAD

**Issue by raw937** [joey711/phyloseq#950]
df = as(sample_data(filtered16s), "data.frame")
d = distance(filtered16s, "unifrac", weighted = F)
adonis(d ~ SoilType, df)

Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘distance’ for signature ‘"phyloseq", "character"’

WTH??

**Comment by MSMortensen** [comment]
You might have another package which also includes a function called distance (SummarizedExperiment for me).
If you are running RStudio the autocomplete box mentions which package the function is from and if this is not phyloseq you will have to call the function using:
phyloseq::distance(...)

**Comment by raw937** [comment]
Yup. The phyloseq:distance works, the d = distance doesn't any more.

**Comment by spholmes** [comment]
It's phyloseq::distance and is due to packages hiding the phyloseq version.

**Comment by raw937** [comment]
thanks.
