### ISSUE TITLE
Custom colors to plot_ordination

### ISSUE THREAD

**Issue by mstagliamonte** [joey711/phyloseq#952]
Hi,

I am trying to add custom colors to the plot_ordination results. My code is:

```
My_WPCoA<- ordinate(
  mydata, method= "PCoA", mydataDistances)

#Define ggplot2 custom colors:
allGroupsColors<- c(
  "grey0", "grey50", "dodgerblu", "deepskyblue",
  "red", "darkred", "green", "green4")
#
# get pcoa and plot:
p <- plot_ordination(mydata, My_WPCoA,  color = "Group_Treatment")
p + geom_point(size=3) +
  labs(title="Weighted Unifrac\n Grouping by Treatment")+
  theme_classic()+geom_vline(xintercept = 0, alpha=.25)+
  geom_hline(yintercept = 0, alpha=.25)

```
I looked at this tutorial: https://joey711.github.io/phyloseq/plot_ordination-examples.html
but it gives examples with predefined palettes, I am not sure how to add my custom colors.

Best,
Max

**Comment by ianartmor** [comment]
Hi Max,

You can try adding:

`+  scale_color_manual(values = allGroupsColors)`

Ian

**Comment by mstagliamonte** [comment]
Well, what do you know, it works!

Thank you, Ian, issue solved.

Have a nice day,
Max

**Comment by ianartmor** [comment]
Glad I could help!

Ian

**Comment by cjfields** [comment]
@mstagliamonte it would be great to close the ticket if the issue has been resolved; I believe only the developers and the ticket submitter have this privilege.
