### ISSUE TITLE
Struggling with re-ordering samples using plot_bar

### ISSUE THREAD

**Issue by seaverwa** [joey711/phyloseq#953]
I have been having substantial difficulty trying to override the default order in which my samples are displayed using plot_bar. I am attempting to order my samples based on another variable--increasing net community production (NCPvol)--but the default order appears to be alphabetic by sample ID no matter what I try...

I'm aware that several other issues have covered this problem, but in my case none of the suggested solutions appear to be working for me.

Following the suggestion by Richard Campen in this thread (https://github.com/joey711/phyloseq/issues/748), I tried changing the bar order by changing the order of rows in my sample_data object as well as the order of columns in my otu_table:

>#order by increasing NCP
>mapping18S<-mapping18S[order(as.numeric(as.character(mapping18S$NCPvol)), na.last = FALSE), ]
>order18S<-rownames(mapping18S)
>
>biom18Sfull <- merge_phyloseq(biom18Stax,mapping18S)# imported 18S data with re-ordered mapping file)
>
>Matchidx_order18S=as.data.frame(match(order18S,row.names(sample_data(biom18Sfull))))
>Matchidx_order18S=Matchidx_order18S[complete.cases(Matchidx_order18S),]
>
>order18S2=rep("1",dim(sample_data(biom18Sfull))[1])
>for(i in 1:dim(sample_data(biom18Sfull))[1]){
>  order18S2[i]=rownames(sample_data(biom18Sfull))[Matchidx_order18S[i]]
>}
>
>otu_table(biom18Sfull)<-otu_table(biom18Sfull)[,order18S2]#rearrange OTU columns based on increasing NCP
>sample_data(biom18Sfull)<-sample_data(biom18Sfull)[order18S2,]#rearrange rows of sample_data based on increasing NCP

This does not work--the resulting bar plot is still in alphabetical order. I also tried to adjust the factor levels as described [here](https://github.com/joey711/phyloseq/issues/291#issuecomment-40230243) and [here](https://rstudio-pubs-static.s3.amazonaws.com/7433_4537ea5073dc4162950abb715f513469.html), 

>sample_data(biom18Sfullabs)$X.SampleID<-factor(sample_data(biom18Sfullabs)$X.SampleID, levels = sample_data(biom18Sfullabs)$X.SampleID[order(sample_data(biom18Sfullabs)$NCPvol)])
>#etc

I suspect this is the issue, but changing all of the factor levels for the most likely culprits had no effect.

I have also attempted to change the order after making the plot, following another suggestion I found [here:](https://github.com/joey711/phyloseq/issues/518)

>B1617_bar18S=plot_bar(B1617_biom18Sabs_pruned,fill="R5")+labs(y="rRNA gene counts")
>B1617_bar18S+scale_fill_manual(values=distinctcolors2)
>library("data.table")
>newtable=data.table(B1617_bar18S$data)
>setorder(newtable, NCPvol)
>B1617_bar18S$data<-newtable
>print(B1617_bar18S)`

This does re-order the data table, but doesn't alter the order of samples in the resulting revised plot.

I'm aware from Paul McMurdie's comments elsewhere on similar issues that the problem I'm dealing with is on ggplot's end, but I think my current confusion is that **I don't know what factor level plot_bar is using by default to arrange the samples!** My guess would have been the alphabetical order of the first column in sample_data, but re-ordering that factor level and other factor levels within sample_data did not work. The otu_table structure contains no factors.

Here is the structure of my phyloseq object:

>Formal class 'phyloseq' [package "phyloseq"] with 5 slots
 > ..@ otu_table:Formal class 'otu_table' [package "phyloseq"] with 2 slots
  >.. .. ..@ .Data        : num [1:14344, 1:80] 0 0 0 1 0 0 50 62 0 108 ...
 > .. .. .. ..- attr(*, "dimnames")=List of 2
 > .. .. .. .. ..$ : chr [1:14344] "KF130112.1.1763" "KJ757396.1.1792" "KJ763066.1.1797" "FJ914461.1.1513" ...
 > .. .. .. .. ..$ : chr [1:80] "B17.S05" "B15.S12" "B17.S11" "B17.S01" ...
 > .. .. ..@ taxa_are_rows: logi TRUE
  >..@ tax_table:Formal class 'taxonomyTable' [package "phyloseq"] with 1 slot
  >.. .. ..@ .Data: chr [1:14344, 1:7] "Eukaryota" "Eukaryota" "Eukaryota" "Eukaryota" ...
 > .. .. .. ..- attr(*, "dimnames")=List of 2
 > .. .. .. .. ..$ : chr [1:14344] "KF130112.1.1763" "KJ757396.1.1792" "KJ763066.1.1797" "FJ914461.1.1513" ...
 > .. .. .. .. ..$ : chr [1:7] "Rank1" "Rank2" "Rank3" "Rank4" ...
 > ..@ sam_data :'data.frame':	80 obs. of  41 variables:
>Formal class 'sample_data' [package "phyloseq"] with 4 slots
>  .. .. ..@ .Data    :List of 41
>  .. .. .. ..$ : Factor w/ 80 levels "B15.S04.18S",..: 56 9 57 55 26 77 23 47 16 60 ...
>  .. .. .. ..$ : Factor w/ 62 levels "AATCCTAAGCTA",..: 1 19 15 17 7 10 40 2 55 22 ...
>  .. .. .. ..$ : Factor w/ 6 levels "CCAGCASCYGCGGTAATTCC",..: 1 3 3 3 1 3 2 1 6 3 ...
>  .. .. .. ..$ : Factor w/ 6 levels "ACTTTCGTTCTTGAT",..: 2 2 2 4 5 1 4 5 2 6 ...
>  .. .. .. ..$ : int [1:80] 2017 2015 2017 2017 2016 2017 2016 2016 2015 2017 ...
>  .. .. .. ..$ : Factor w/ 58 levels "1","10","11",..: 42 4 3 1 5 53 49 39 13 13 ...
>  .. .. .. ..$ : Factor w/ 10 levels "F1","F10","F11",..: 4 5 5 5 4 9 6 4 7 5 ...
>  .. .. .. ..$ : Factor w/ 10 levels "AATCCT","ACATCG",..: 1 3 3 3 1 2 6 1 9 3 ...
>  .. .. .. ..$ : Factor w/ 6 levels "CCAGCASCYGCGGTAATTCC",..: 1 3 3 3 1 3 2 1 6 3 ...
>  .. .. .. ..$ : Factor w/ 10 levels "R10","R11","R2",..: 1 5 1 4 9 2 10 3 5 7 ...
>  .. .. .. ..$ : Factor w/ 10 levels "AAGCTA","ATAGGT",..: 1 7 1 4 8 3 5 2 7 10 ...
>  .. .. .. ..$ : Factor w/ 6 levels "ACTTTCGTTCTTGAT",..: 2 2 2 4 5 1 4 5 2 6 ...
>  .. .. .. ..$ : Factor w/ 80 levels "B15.S04","B15.S05",..: 56 9 57 55 26 77 23 47 16 60 ...
>  .. .. .. ..$ : Factor w/ 80 levels "01 Aug 2017 06:19",..: 75 45 76 74 21 34 12 61 64 79 ...
>  .. .. .. ..$ : num [1:80] 34.2 36.2 35.3 31.8 28.6 ...
>  .. .. .. ..$ : num [1:80] 64.5 -75 -64.3 -64.5 -70 ...
>  .. .. .. ..$ : num [1:80] 1.5 1 1.5 2 2 1.5 1 2 1 1.5 ...
>  .. .. .. ..$ : Factor w/ 1 level "Surf": 1 1 1 1 1 1 1 1 1 1 ...
>  .. .. .. ..$ : Factor w/ 80 levels "7/29/17 16:02",..: 4 69 2 1 45 58 35 13 17 5 ...
>  .. .. .. ..$ : num [1:80] 27.9 26.8 28.2 28.9 29.9 ...
>  .. .. .. ..$ : num [1:80] 36.7 33.7 36.3 36.7 36.8 ...
>  .. .. .. ..$ : num [1:80] 22.9 11.2 25.7 14.7 16.6 ...
>  .. .. .. ..$ : num [1:80] -0.494 -0.357 -0.351 -0.283 -0.247 ...
>  .. .. .. ..$ : num [1:80] -11.3 -4 -9.02 -4.16 -4.1 ...
>  .. .. .. ..$ : num [1:80] 1.00e+04 3.27e-01 5.66e-02 2.24e-02 2.60e-02 ...
>  .. .. .. ..$ : num [1:80] 3.63 3.48 3.6 1.08 33.2 ...
>  .. .. .. ..$ : int [1:80] 9999 9999 9999 9999 9999 9999 9999 9999 9999 9999 ...
>  .. .. .. ..$ : int [1:80] 9999 9999 9999 9999 9999 9999 9999 9999 9999 9999 ...
>  .. .. .. ..$ : int [1:80] 9999 9999 9999 9999 9999 9999 9999 9999 9999 9999 ...
>  .. .. .. ..$ : num [1:80] 9999 9999 9999 9999 9999 ...
 > .. .. .. ..$ : num [1:80] 9999 9999 9999 9999 9999 ...
 > .. .. .. ..$ : num [1:80] 9999 9999 9999 9999 9999 ...
>  .. .. .. ..$ : num [1:80] 0.64 9999 0.39 9999 0.16 ...
>  .. .. .. ..$ : num [1:80] 0.63 9999 0.86 9999 0.7 ...
>  .. .. .. ..$ : Factor w/ 1 level "18S": 1 1 1 1 1 1 1 1 1 1 ...
>  .. .. .. ..$ : Factor w/ 6 levels "Bermuda","MAB",..: 3 3 3 1 3 5 3 4 5 3 ...
>  .. .. .. ..$ : Factor w/ 12 levels "B16.S21","B16.S28",..: 12 12 12 12 12 12 12 12 12 12 ...
>  .. .. .. ..$ : Factor w/ 1 level "Yes": 1 1 1 1 1 1 1 1 1 1 ...
>  .. .. .. ..$ : Factor w/ 2 levels "Coastal","Open": 2 1 2 2 2 2 2 2 2 2 ...
>  .. .. .. ..$ : Factor w/ 2 levels "Coastal","Open": 2 1 2 2 2 2 2 2 2 2 ...
>  .. .. .. ..$ : Factor w/ 1 level "18S": 1 1 1 1 1 1 1 1 1 1 ...
>  .. .. ..@ names    : chr [1:41] "X.SampleID" "BarcodeSequence" "LinkerPrimerSequence" "ReversePrimer" ...
>  .. .. ..@ row.names: chr [1:80] "B17.S05" "B15.S12" "B17.S11" "B17.S01" ...
>  .. .. ..@ .S3Class : chr "data.frame"
>  ..@ phy_tree : NULL
>  ..@ refseq   : NULL

Any help would be much appreciated! Been burning far more time trying to solve this simple issue than I'd like... many thanks!

**Comment by joey711** [comment]
If you look at the `plot_bar` documentation, the horizontal axis is mapped to `"Sample"` by default (the `x` parameter), not the `"X.SampleID"` variable that you've been modifying in the various attempts you posted above. Also, the doc for `plot_bar` recommends that you peek at `psmelt`, which is another way to understand the table that is being generated in order to generate the plot in `plot_bar`.

Any one of those solutions for re-ordering should probably work. Since this manipulation is solely for this visualization, I find it good practice to modify the data table that is in the plot,

```r
p = plot_bar(B1617_biom18Sabs_pruned, fill="R5") + labs(y="rRNA gene counts")
p$data$Sample <- factor(p$data$Sample, levels = uniqueVectorOfLevelsInOrder)
p
```

That ought to do it.
I'll close for now. Please post back confirmation that this worked. Thanks for summarizing all those other solutions. I think that will be helpful for others.

**Comment by seaverwa** [comment]
Thanks for the quick reply!

The specific solution you recommended (modifying the data table produced by psmelt for that plot) returned various errors for me:

> #Using an ordered vector of a length corresponding to the number of samples 
> B1617_bar18S=plot_bar(B1617_biom18Sabs_pruned,fill="R5")+labs(y="rRNA gene counts")
> B1617_bar18S$data$Sample<-factor(B1617_bar18S$data$Sample, levels = B1617_bar18S$data$Sample[order(sample_data(B1617_biom18Sabs_pruned)$NCPvol)])
>
>**Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [6] is duplicated**
>
> #Using an ordered vector of a length equal to that of the B1617_bar18S$data$Sample factor
> B1617_bar18S=plot_bar(B1617_biom18Sabs_pruned,fill="R5")+labs(y="rRNA gene counts")
> B1617_bar18S$data$Sample<-factor(B1617_bar18S$data$Sample, levels = B1617_bar18S$data$Sample[order(B1617_bar18S$data$NCPvol)])
>
>**Error in `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  : 
  factor level [2] is duplicated**

However, now that I understand that plot_bar is mapping the x-axis to "Sample" by default, I was able to produce a bar plot ordered the way I want by simply specifying a different x-axis variable, e.g.:

>sample_data(B1617_biom18Sabs_pruned)$Station<-factor(sample_data(B1617_biom18Sabs_pruned)$Station, levels = sample_data(B1617_biom18Sabs_pruned)$Station[order(sample_data(B1617_biom18Sabs_pruned)$NCPvol)])
>
>B1617_bar18S=plot_bar(B1617_biom18Sabs_pruned,x="Station",fill="R5")+labs(y="rRNA gene counts")

Not as convenient as being able to manipulate the data table for that particular plot directly, but this does work!

**Comment by joey711** [comment]
The error message shows that you were not providing factor levels to `level`, but instead the complete re-ordered vector. Hence the error about duplicates. Note that "your" solution and the one I proposed (and the others) are all the same solution. In some cases you've got the code wrong causing it to throw an error or not change the plot.

In general, you'll save yourself a lot of time in the future by reading the documentation associated with functions that throw an error. Most software authors will not be as quick to answer as this, myself included most of the time.
