### ISSUE TITLE
Add sample data 

### ISSUE THREAD

**Issue by ghost** [joey711/phyloseq#968]
Hi, I have just started phyloseq. And as other beginners do, I am struggling too : ) 

I have biom file which contain OTU table and taxonomy table. And I would like to add mapfile but it's csv format. As I couldn't find tutorial how to merge biom and csv format, I thought it's better to convert biom to data table and read them in phyloseq as objective. 

So what I tried is

```
library(biomformat)
mydata<-read_biom("Bora_16S_OTU.biom")
otutable<-as.data.frame(as.matrix(biom_data(mydata))) 
taxonomy <- observation_metadata(mydata) 

library(phyloseq)
OTU = otu_table(as.matrix(otutable), taxa_are_rows = TRUE)
TAX = tax_table(as.matrix(taxonomy))
```

Until here, everything was fine. And I tried to read mapfile using `sample_data`. 

```
sample <- read.csv("map_file_16s2.csv")
SP = sample_data(sample, errorIfNULL = T)
```

and I checked sample name to see if is is matched to OTU sample name. 
However, I got these sample name:

`sample_names(SP)`
> [1] "sa1"   "sa2"   "sa3"   "sa4"   "sa5"   "sa6"   "sa7"   "sa8"   "sa9"   "sa10"  "sa11"  "sa12"  "sa13"  "sa14"  "sa15" 
 [16] "sa16"  "sa17"  "sa18"  "sa19"  "sa20"  "sa21"  "sa22"  "sa23"  "sa24"  "sa25"  "sa26"  "sa27"  "sa28"  "sa29"  "sa30" 
 [31] "sa31"  "sa32"  "sa33"  "sa34"  "sa35"  "sa36"  "sa37"  "sa38"  "sa39"  "sa40"  "sa41"  "sa42"  "sa43"  "sa44"  "sa45" 
 [46] "sa46"  "sa47"  "sa48"  "sa49"  "sa50"  "sa51"  "sa52"  "sa53"  "sa54"  "sa55"  "sa56"  "sa57"  "sa58"  "sa59"  "sa60" ......

Then of course, because the sample names are not same as OTU sample names, I couldn't use `phyloseq` function. 
Would you kindly give me some advice please? Thanks.

**Comment by BoraKimUvA** [comment]
I fixed it! for your information, when I read sample data, I did 
```
sample <- read.csv("map_file_16s2.csv", row.names=1)
SAM = sample_data(sample, errorIfNULL = T)
```

and then, 

```
phylob <- phyloseq(OTU,TAX, SAM)
phylob
```

> otu_table()   OTU Table:         [ 2635 taxa and 198 samples ]
> sample_data() Sample Data:       [ 198 samples by 5 sample variables ]
> tax_table()   Taxonomy Table:    [ 2635 taxa by 7 taxonomic ranks ]

It seems fine! right? X )

**Comment by WisamR** [comment]
Hi!
Could you write down how to fix it, I stuck with the sample data!

**Comment by BoraKimUvA** [comment]
Hi! 
Yes just only by putting "row.names=1" and so R could read my sample name because rows of my data were sample names. Matching sample names and OTU names between phyloseq objects (OTU table, map file, and taxonomy) is necessary to make one object. Hope it's helping you : )

**Comment by WisamR** [comment]
Thanks, my concern is,,, how to choose the dataset that we need to find out the sample_data for it... I have "metadata" which has to be fit to my otu table,,,, I did the otu table and tax table successfully as phyloseq object, but stuck with sample_data!!

**Comment by marsfro** [comment]
Hello!
I've done everything according to your instruction:

`library(biomformat)
mydata<-read_biom("combine.biom")
otutable<-as.data.frame(as.matrix(biom_data(mydata))) 
taxonomy <- observation_metadata(mydata) 
  
library(phyloseq)
OTU = otu_table(as.matrix(otutable), taxa_are_rows = TRUE)
TAX = tax_table(as.matrix(taxonomy))
samples <- read_excel("Samples.xlsx")
SP = sample_names(samples) 
phylob <- phyloseq(OTU,TAX, SP)`

but 
phylob@sam_data
NULL
What to do?
