### ISSUE TITLE
Issue with plot_bar function after importing QIIME2 data

### ISSUE THREAD

**Issue by djbradshaw2** [joey711/phyloseq#972]
Dear Whom It May Concern,

I have been working with QIIME2 and just suceeding, I think, in uploading it to phyloseq. When I try to do the basic script plot_bar(RA, fill="Rank2") + geom_bar(stat="identify) I get the following plot (Rplot) and then I tried adding in the ggplot layers (Rplot01) and got a weird graph. I honestly do not know how to interpret what is going on. Shouldn't the bars plot each of the Phylums combined using this script? Thank you for your time and help. 

Sincerely, 

David Bradshaw

![rplot](https://user-images.githubusercontent.com/24995597/43203317-e3b1ea92-8feb-11e8-99ab-fda831d51d07.png)
![rplot01](https://user-images.githubusercontent.com/24995597/43203323-e8f22c2e-8feb-11e8-9055-661e9c8fe779.png)

**Comment by djbradshaw2** [comment]
Sorry second graph made using this script

plot_bar(RA, fill="Rank2") + geom_bar(aes(color=Rank2, fill=Rank2), stat="identity", position ="stack")

**Comment by ianartmor** [comment]
Hi,

Maybe you could try 
`plot_bar(RA, fill="Rank2") + geom_bar(stat="identity", position ="stack")`

Ian

**Comment by djbradshaw2** [comment]
Thanks that works great!
