### ISSUE TITLE
How to extract/export data used to generate krona graph in phyloseq

### ISSUE THREAD

**Issue by emankhalaf** [joey711/phyloseq#973]
Hello,
I am using cpauvert/psadd with phyloseq to generate krona graphs. I did used plot_krona on different samples subsets and I would like to apply statistics on taxa percentages in each subset to find a relationship between groups of samples.
It is overwhelming to extract the numbers visually from each krona circle and enter them to an excel sheet, I wonder if there is a function to export the underlying percentages used to build up krona graph?
Thanks for any help
Eman

**Comment by stan-iakhno** [comment]
Hi Eman, is that correct that you were able to convert your phyloseq object to krona visualization? In case you did, how did you do that? Regards Stan

**Comment by emankhalaf** [comment]
Hello Stan,

Just follow this link
https://rdrr.io/github/cpauvert/psadd/man/plot_krona.html
install the package, then run the posted code in the package documentation:
plot_krona(GlobalPatterns,"GP-krona", "SampleType",trim=T)

Good luck

**Comment by stan-iakhno** [comment]
Sounds easy, thanks a lot! I Will give it a shot=)  Regards Stan
