### ISSUE TITLE
unable to find an inherited method for function ‘prune_taxa'

### ISSUE THREAD

**Issue by TaylerChicoine** [joey711/phyloseq#977]
Hello, 

I'm trying to prune the top 50% most abundant genera in my phyloseq otu table. 
otu_rhizo_phylo is my phyloseq object. Everything works except when I get to prune_taxa I get an error. 
Below is the code I'm using and my error message: 

# Code: 
 tax glom - combine anything with the same Genus
otu_rhizo_genra <- tax_glom(otu_rhizo_phylo, "Genus")
ntaxa(otu_rhizo_genra) #538
50% most abundant genera would be 269 total genera 
rhizo_genus50perc <- names(sort(taxa_sums(otu_rhizo_genra),decreasing = TRUE)[1:269])
length(rhizo_genus50perc) # confirm that you pruned the top 269 genra
rhizo_top50perc <- prune_taxa(otu_rhizo_genra, rhizo_genus50perc)

# Error with prune_taxa: 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘prune_taxa’ for signature ‘"phyloseq", "character"’

Do any of you know what might be causing this problem? I haven't been able to find anything that helps...

Thank you!!!! 
Tayler

**Comment by ianartmor** [comment]
Hi Tayler,

This might not be the exact solution you're looking for, but for simplicity I use the `top_taxa()` function from the `microbiome` package to accomplish something similar.

If you don't have `microbiome`:
`source("http://www.bioconductor.org/biocLite.R")`
`biocLite("microbiome")`

To prune top n taxa:
`top_genera_physeq <- prune_taxa(top_taxa(physeq_genera, n = 269), physeq_genera)`

This is unsolicited advice, but in general, the top 50% genera might not be useful to look at. Chances are, most of those genera are pretty low abundance, so your bar plots will likely be over-plotted. I might look at your Inverse Simpson index using `plot_richness()` first; that value is a good estimate of the number of "dominant" OTUs/taxa you have.

Ian

**Comment by MSMortensen** [comment]
Hi,
If you prefer I have written two small functions to handle this.
Regards,
Martin

# Anything not with top x (return relative abundances)
merge_less_than_top <- function(pobject, top=10){
  transformed <- transform_sample_counts(pobject, function(x) x/sum(x))
  otu.table <- as.data.frame(otu_table(transformed))
  otu.sort <- otu.table[order(rowMeans(otu.table), decreasing = TRUE),]
  otu.list <- row.names(otu.sort[(top+1):nrow(otu.sort),])
  merged <- merge_taxa(transformed, otu.list, 1)
  for (i in 1:dim(tax_table(merged))[1]){
    if (is.na(tax_table(merged)[i,2])){
      taxa_names(merged)[i] <- "Other"
      tax_table(merged)[i,1:7] <- "Other"}
  }
  return(merged)
}

# Like above, but keeps counts
merge_less_than_top_count <- function(pobject, top=10){
  transformed <- transform_sample_counts(pobject, function(x) x/sum(x))
  otu.table <- as.data.frame(otu_table(transformed))
  otu.sort <- otu.table[order(rowMeans(otu.table), decreasing = TRUE),]
  otu.list <- row.names(otu.sort[(top+1):nrow(otu.sort),])
  merged <- merge_taxa(pobject, otu.list, 1)
  for (i in 1:dim(tax_table(merged))[1]){
    if (is.na(tax_table(merged)[i,2])){
      taxa_names(merged)[i] <- "Other"
      tax_table(merged)[i,1:7] <- "Other"}
  }
  return(merged)
}

**Comment by joey711** [comment]
Umm, the problem was that you had the two arguments flipped. The character-vector of the taxa you want to keep goes first. See `prune_taxa` doc. The error says that you had the phyloseq object first.
