### ISSUE TITLE
estimate richness - median and mean value of OTUs per sample?

### ISSUE THREAD

**Issue by raw937** [joey711/phyloseq#979]
#max and min work great
filter_max <- max(estimate_richness(filtered16s, measures=c("Observed")))
print(filter_max)
#[1] 382
filter_min <- min(estimate_richness(filtered16s, measures=c("Observed")))
print(filter_min)
#[1] 53

filter_mean <- mean(estimate_richness(filtered16s, measures=c("Observed")))
But, when I calculate a mean or median it barks at me:
Warning message:
In mean.default(estimate_richness(filtered16s, measures = c("Observed"))) :
  argument is not numeric or logical: returning NA

filter_med <- median(estimate_richness(filtered16s, measures=c("Observed")))
Error in median.default(estimate_richness(filtered16s, measures = c("Observed"))) : 
  need numeric data

**Comment by ianartmor** [comment]
Looks like that function returns a data frame, so you need to specify the column. Try:

`mean(estimate_richness(filtered16s, measures=c("Observed"))[,1])`
`median(estimate_richness(filtered16s, measures=c("Observed"))[,1])`

Ian

**Comment by raw937** [comment]
Perfect! Thank you!
