### ISSUE TITLE
Version 1.24.0 specific issue: Cannot coerce tax_table object into data frame after aggregating with tax_glom

### ISSUE THREAD

**Issue by cwatt** [joey711/phyloseq#983]
I'm having a new issue in phyloseq version 1.24.0 that doesn't occur in earlier versions such as 1.20.0 and 1.22.3 (all that I've tested so far). I'm unable to convert the tax_table component of my phyloseq object after aggregating using tax_glom into a data frame. I've tried:

`tax = as.data.frame(tax_table(MyPhyseqObject))`
`tax = as(tax_table(MyPhyseqObject), "data.frame")`
The error:
`Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent`

This code works just fine in all phyloseq versions if the phyloseq object has not been aggregated using tax_glom.

What might be going on here and how can it be fixed?

Thanks for your help!

**Comment by kflanna** [comment]
I'm having the same issue. Not sure about why it's actually happening, but as a workaround I was able to save the dataframe by calling the data of the tax table specifically:

df=as.data.frame(MyPhyseqObject@tax_table@.Data)

**Comment by cwatt** [comment]
@kflanna 

Thanks! This worked for me. Still have no idea what broke the other method though!

**Comment by joey711** [comment]
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

Note that error of the type you posted is almost always a result of `taxa_names()` no longer matching after some manipulation.
