### ISSUE TITLE
Alpha diversity on DADA2 output

### ISSUE THREAD

**Issue by FloraVincent** [joey711/phyloseq#984]
Hi,
I processed 16S data using DADA2 (incredibly well documented), and moved to phyloseq for the analysis. The data is normalised by flow cytometry using the QMP procedure, which gives absolute counts (this paper:https://www.nature.com/articles/nature24460) for a pretty small number of OTUs, 119.
Two questions: 
1) I read on phyloseq website that "many richness estimates are modeled on singletons and doubletons in the abundance data" . Where does this come from ? I don't understand why deleted singletons biases richness measures ? Especially when most of the singletons of other amplicon assemblies are deleted before analysis?
Does this mean none of the classic alpha descriptors can be applied to dada2 output ?

2) I also read that we can ignore the warning for metrics like Shannon, but could not find the option to do so.
"Error in estimateR.default(newX[, i], ...) : 
  function accepts only integers (counts)
In addition: Warning message:
In estimate_richness(physeq, split = TRUE, measures = measures) :
  The data you have provided does not have
any singletons. This is highly suspicious. Results of richness
estimates (for example) are probably unreliable, or wrong, if you have already
trimmed low-abundance taxa from the data.
We recommended that you find the un-trimmed data and retry."

Thanks !
Flora

**Comment by FloraVincent** [comment]
Just noticed this message in the error "Error in estimateR.default(newX[, i], ...) :
function accepts only integers (counts)" so will fix this for 2.. My question on alpha measurements in 1. still holds though !

**Comment by MSMortensen** [comment]
As fx Chao-1 is calculated based on the singleton/doubleton ratio in each sample this index cannot reliably be used if you have no singletons.

The bias introduced by removing singletons are dependent on how it is done. As DADA2 removes reads which are unique in an analysis, any analysis that includes multiple samples will still be likely to contain reads that appear only once in any given sample. This is expected and will not be a problem.
If you, on the other hand, choose the aggressive approach and define your singletons per sample, then removal of singletons will have a significant impact on your results.

Regards,
Martin
