### ISSUE TITLE
NA and g__

### ISSUE THREAD

**Issue by Biancabrown** [joey711/phyloseq#987]
Hello, 

I used greengenes to assign sequences, and I am trying to figure out why some assignments have g__ and others have NA for the same level? For example, if I make a bar plot with abundances at the Phylum level all the Phyla reported are assigned; there are no p__ or NAs. However, if I make a barplot at the genus level, I get unassigned  ASVs as "g__" and "NA." I'm confused as to why I get g__ and NA instead of one or the other. Any thoughts?

**Comment by MSMortensen** [comment]
Hi, 

This bit of code should do the basic clean-up of your tax table:

tax <- data.frame(tax_table(ps))

tax.clean <- data.frame(row.names = row.names(tax),
                        Kingdom = str_replace(tax[,1], "D_0__",""), 
                        Phylum = str_replace(tax[,2], "D_1__",""),
                        Class = str_replace(tax[,3], "D_2__",""),
                        Order = str_replace(tax[,4], "D_3__",""),
                        Family = str_replace(tax[,5], "D_4__",""),
                        Genus = str_replace(tax[,6], "D_5__",""),
                        Species = str_replace(tax[,7], "D_6__",""), 
                        stringsAsFactors = FALSE)
tax.clean[is.na(tax.clean)] <- ""

for (i in 1:7){ tax.clean[,i] <- as.character(tax.clean[,i])}
####### Fille holes in the tax table
tax.clean[is.na(tax.clean)] <- ""
for (i in 1:nrow(tax.clean)){
  #  Fill in missing taxonomy
  if (tax.clean[i,2] == ""){
    kingdom <- paste("Kingdom_", tax.clean[i,1], sep = "")
    tax.clean[i, 2:7] <- kingdom
  } else if (tax.clean[i,3] == ""){
    phylum <- paste("Phylum_", tax.clean[i,2], sep = "")
    tax.clean[i, 3:7] <- phylum
  } else if (tax.clean[i,4] == ""){
    class <- paste("Class_", tax.clean[i,3], sep = "")
    tax.clean[i, 4:7] <- class
  } else if (tax.clean[i,5] == ""){
    order <- paste("Order_", tax.clean[i,4], sep = "")
    tax.clean[i, 5:7] <- order
  } else if (tax.clean[i,6] == ""){
    family <- paste("Family_", tax.clean[i,5], sep = "")
    tax.clean[i, 6:7] <- family
  } else if (tax.clean[i,7] == ""){
    tax.clean$Species[i] <- paste("Genus",tax.clean$Genus[i], sep = "_")
  }
}

tax_table(ps) <- as.matrix(tax.clean)

**Comment by joey711** [comment]
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
