### ISSUE TITLE
Change NA taxa_names to higher level names

### ISSUE THREAD

**Issue by rachaelantwis** [joey711/phyloseq#990]
Hi all,

apologies if this has been covered elsewhere. I'm using tax_glom to agglomerate my data to genus level but this is stripping out NAs. Is there a way to replace genus names labelled as "NA" with a higher order name so these are not lost from further analyses, e.g. convert "NA" to "Bacillus_genus" etc.

Many thanks in advance

**Comment by alexthibodeau** [comment]
You always can take the long road and do it manually in Excell, using the table you want to import into Phyloseq! 

Or you can search the issue trackers, there is already 1-2 post about it .

**Comment by MSMortensen** [comment]
Hi, 
I use the following bit of code and you should be able to use at least a variation of this:
tax <- data.frame(tax_table(ps))

tax.clean <- data.frame(row.names = row.names(tax),
                        Kingdom = str_replace(tax[,1], "D_0__",""), 
                        Phylum = str_replace(tax[,2], "D_1__",""),
                        Class = str_replace(tax[,3], "D_2__",""),
                        Order = str_replace(tax[,4], "D_3__",""),
                        Family = str_replace(tax[,5], "D_4__",""),
                        Genus = str_replace(tax[,6], "D_5__",""),
                        Species = str_replace(tax[,7], "D_6__",""), 
                        stringsAsFactors = FALSE)
tax.clean[is.na(tax.clean)] <- ""

for (i in 1:7){ tax.clean[,i] <- as.character(tax.clean[,i])}
####### Fille holes in the tax table
tax.clean[is.na(tax.clean)] <- ""
for (i in 1:nrow(tax.clean)){
  #  Fill in missing taxonomy
  if (tax.clean[i,2] == ""){
    kingdom <- paste("Kingdom_", tax.clean[i,1], sep = "")
    tax.clean[i, 2:7] <- kingdom
  } else if (tax.clean[i,3] == ""){
    phylum <- paste("Phylum_", tax.clean[i,2], sep = "")
    tax.clean[i, 3:7] <- phylum
  } else if (tax.clean[i,4] == ""){
    class <- paste("Class_", tax.clean[i,3], sep = "")
    tax.clean[i, 4:7] <- class
  } else if (tax.clean[i,5] == ""){
    order <- paste("Order_", tax.clean[i,4], sep = "")
    tax.clean[i, 5:7] <- order
  } else if (tax.clean[i,6] == ""){
    family <- paste("Family_", tax.clean[i,5], sep = "")
    tax.clean[i, 6:7] <- family
  } else if (tax.clean[i,7] == ""){
    tax.clean$Species[i] <- paste("Genus",tax.clean$Genus[i], sep = "_")
  }
}

tax_table(ps) <- as.matrix(tax.clean)

**Comment by rachaelantwis** [comment]
Thank you very much for this. I tried manually but came unstuck at the reimporting stage - I couldn't seem to coerce my tax table back into the phyloseq object. This code looks great though - I will give it a go! Many thanks to you both.

**Comment by rachaelantwis** [comment]
This worked beautifully! Thank you very much for this code. The only addition (for the next user) is to load the stringr package for the function to work. Many thanks again.

**Comment by MSMortensen** [comment]
Thanks, and yes I forgot to include the part about which libraries to load.
stringr is a requirement for this to work.
