### ISSUE TITLE
Phyloseq Facet wraps

### ISSUE THREAD

**Issue by canaanwc** [joey711/phyloseq#991]
Hi,
I am new to R but am using phyloseq to make facet wraps at various taxonomic levels with some fungal ITS data. I have been through the tutorials and everything is working well. The problem is that many of these reads are not assigned taxonomy (which expected given this data set), especially at lower levels like genus. Thus when I make the facet wraps of the 10 most abundant genra (plot_bar(mydata, "Description", fill="Genus10", facet_grid=~Genus10) the "NA" genus abundance bars are much taller than the others which makes it very difficult to see the data ragarding the known fungal organisms because the y-axis is very tall to account for the height of the "NA" genus. My question is, can I generate a custom list of genera I'd like to include in the facet wrap? or is there a way to suppress the "NA" genus so that when I select for the 10 most abundant genera, NA is not included? Thanks so much!
Canaan

**Comment by joey711** [comment]
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
