### ISSUE TITLE
Phyloseq

### ISSUE THREAD

**Issue by Fatemah1989** [joey711/phyloseq#992]
Dear Joey711 
I hope you are fine,
I just started learning phyloseq, I have exported data from qiime2 (16s rRNA),using R version 3.5.0 (2018-04-23)/ phyloseq 1.24.2
I have used attached script to export my data into phyloseq, I have checked metadata and taxonomy file: everything sees ok , I have 51 samples and just one variable called diseaseCategory just wondering what is the best start point for my samples which do not have too many variables ,and how should I start to use phyloseq effectively on these samples? 
 As a first try when I do plot_bar(physeq,fill="Genus) the plot just shows abundance of one sample. I don't know what is wrong ?
I have attache the metadata file and screenshot, 
Thank you for your help ,

[metadata.txt](https://github.com/joey711/phyloseq/files/2338424/metadata.txt)
<img width="1440" alt="screen shot 2018-08-30 at 5 41 48 pm" src="https://user-images.githubusercontent.com/42830500/44887210-64609a00-ad0e-11e8-8ef1-86d790e524ab.png">
<img width="1440" alt="screen shot 2018-08-31 at 11 00 57 am" src="https://user-images.githubusercontent.com/42830500/44887211-64609a00-ad0e-11e8-89c9-88e98a926120.png">
<img width="1440" alt="screen shot 2018-08-31 at 11 02 03 am" src="https://user-images.githubusercontent.com/42830500/44887212-64609a00-ad0e-11e8-9b72-c06e0a1525af.png">
<img width="1440" alt="screen shot 2018-08-31 at 11 02 19 am" src="https://user-images.githubusercontent.com/42830500/44887213-64609a00-ad0e-11e8-99f8-177a08496bc4.png">

**Comment by joey711** [comment]
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example
