### ISSUE TITLE
Fatal error with read_tree()

### ISSUE THREAD

**Issue by FFoQS90** [joey711/phyloseq#994]
Hi,

R encounters a fatal error and my session is terminated whenever I try to import a tree file that I created using FastTree on full-length 16S rRNA gene sequences (Pacbio data). The sequences were denoised with dada2 and aligned with decipher. 
I have always been working with trees generated from shorter reads (Illumina data) and it worked fine. 

Is it possible that read_tree cannot handle the longer tip labels? Or does anyone have an idea what the problem might be?

**Comment by joey711** [comment]
I'll close for now, because not possible to reproduce. Can re-open if you can provide more detail, especially MRE

**Comment by FFoQS90** [comment]
Hello,

I still don´t know what exactly caused the issue but I found a workaround that I wanted to share in case anyone else runs into that problem.
I think the problem was that the headers in the alignment file that I used to create the tree were the actual sequences (as default in DADA2), which were about 1500 characters long. I guess read_tree can´t handle tip labels that long so I replaced them with a sequence ID (seq1, seq2, etc). After the tree was imported you can then use the original headers as tip labels with the help of a mapping file.  

library(seqinr)
library(ape)
infile <- "path to your alignment"
outfile <- "path to output file"

#read in alignment
alignment = read.alignment(infile, "fasta", forceToLower = TRUE)

#make mapping file with new names
mapping_file <- as.data.frame(alignment$nam)
colnames(mapping_file) <- "full_id"
mapping_file$new_id <- paste("seq", seq(1, nrow(mapping_file), 1), sep ="")

#write renamed alignment and use this as input for tree generation
write.fasta(alignment$seq, mapping_file$new_id, file.out = outfile)

#Import the tree and rename tip labels to original headers
tree <- read_tree("path to tree_file")
tree$tip.label <- mapping_file[[1]][match(tree$tip.label, mapping_file[[2]])]
