### ISSUE TITLE
subsetting specific samples

### ISSUE THREAD

**Issue by Bhamal** [joey711/phyloseq#995]
Hi,

I have total of 10 samples as follows in my phyloseq object 'ps',

> sample_names(ps)

[1] "control_L001"      "S13_114A_L001"          "S25_114B_L001"         
[4] "S37_114C_L001"          "S49_302_L001"      "S23_364_L001"     
[7] "S61_364A_L001"          "S73_364B_L001"          "S85_364C_L001"         
[10] "S2_383_L001" 

I would like to analyze abundance of different level taxa in only control sample 'control_LOO1'. So I did,

control <- subset_samples(ps,sampleID="control_L001") # subsetting only control sample

But, it looks like I am not getting only control sample,

> control
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 13227 taxa and 10 samples ]
sample_data() Sample Data:       [ 10 samples by 3 sample variables ]
tax_table()   Taxonomy Table:    [ 13227 taxa by 7 taxonomic ranks ]

> sample_names(control)
[1] "control_L001"      "S13_114A_L001"          "S25_114B_L001"         
[4] "S37_114C_L001"          "S49_302_L001"      "S23_364_L001"     
[7] "S61_364A_L001"          "S73_364B_L001"          "S85_364C_L001"         
[10] "S2_383_L001" 

My goal is to get subset ps object with only the control sample so that I could get abundance of, for example, phyla level as follows,

phyla_control <- table(tax_table(control)[, "Phylum"], exclude = NULL)
phyla_control <- data.frame(Phyla=names(phyla_control),Abundance=as.numeric(phyla_vcontrol))

I would appreciate for any help!

br,

**Comment by MSMortensen** [comment]
Hi,

First of all your command require your sample_data(ps) to have a column named "sampleID" which matches the sample_names(ps).
If this is not the case I suggest you use this command instead:
control <- prune_samples(sample_names(ps) == "control_L001", ps)

Second, your suggested second step would not provide the required output.
There should be no reason to subset your data in the first place, but you should definitely agglomerate your data to the taxonomical level you are investigating like this (for phylum level)
ps.phylum <- tax_glom(ps, taxrank = "Phylum)
taxa_names(ps.phylum) <- tax_table(ps.phylum)[,2] # you cannot subset a column in the tax_table using the name of the column.

Lastly as you "only" have 10 samples this table should be easily readable using:
View(otu_table(ps.phylum))

Lastly, remember that you will be looking at count data and if you want to compare between samples remember to transform your otu_table to relative abundances using
transform_sample_counts(ps.phylum, function(x) x/sum(x))

Good luck,
Martin

**Comment by Bhamal** [comment]
Hi Martin,

Thank you so much! That solves my problem.

I would appreciate if you could also help me understand the following,
"There should be no reason to subset your data in the first place.."

The reason I want to subset is as follows,
We have four different controls, one positive and three negative. The negative controls are based on three different extraction and the plan is to see if there is kit specific contamination. The results will be used to decide what kit to use in later projects. So, my interest is to subset control samples and analyze them separately. For example, analyze only 3 negative controls and see which kit has got more contamination. We have duplicates/triplicates for these controls.

I am doing this for the first time. So, it is possible that I am overthinking something here. Do you have any suggestions?

best wishes,

**Comment by MSMortensen** [comment]
Hi,
The reason for not subsetting into unique phyloseq objects is that such objects cannot be plotted together afterwards. 
In addition, if you keep all in one phyloseq object you would be able to look at things like distances or dissimilarity between your samples and the controls.

It all depends on your analysis, but if you want to compare samples they should be in the same phyloseq object.

Good luck
