### ISSUE TITLE
Plot_order_bar(physeq)

### ISSUE THREAD

**Issue by Fatemah1989** [joey711/phyloseq#996]
Hello 

I am using:
p1 <- plot_ordered_bar(physeq, fill="Family", leg_size = 0.6) 
p1 + ggtitle("plot_ordered_bar() Example")  to order the taxa in legends but it gives me this error after running p1 <- plot_ordered_bar(physeq, fill="Family", leg_size = 0.6)  ---->Error: C stack usage 7970032 is too close to the limit , May I know what does it mean and how I can fix it ?

Many Tnx for your help

**Comment by joey711** [comment]
`plot_ordered_bar` is not a phyloseq function...
