### ISSUE TITLE
Dealing with Negative (and Positive) Controls

### ISSUE THREAD

**Issue by brandondurant** [joey711/phyloseq#997]
Hi, I'm currently working on a project in which we sequenced Extraction Blanks and a Mock Community as our negative and positive controls, respectively, for our data set. I have been trying to determine how to utilize these controls in my data analysis.

NEGATIVE CONTROL
I recently came across the paper "Parsing ecological signal from noise in next generation amplicon sequencing" (Nguyen et. al., 2015) which discussed how to deal with negative controls. One method discussed in the paper is to completely remove the ASVs found within the negative control. Doing so however would remove some of the most abundant ASVs in many of my samples. Another method discussed in the paper was to just remove the abundance of ASVs found within the Extraction Blank across all samples. I figured this would be worth trying however I am unsure as  to how to subtract phyloseq objects from each other. I did see the thread on how to remove the ASV completely but Im specifically interested in subtracting out the abundance of the ASVs seen in the Extraction Blank, not removing the entire ASV itself.

POSITIVE CONTROL
I am still thinking about how to utilize our positive control within our data however the most pressing issue at the moment is subtracting out the abundance of the extraction blank ASVs across the board. I have heard about using the positive control to determine a cutoff under which ASVs should not be considered however I need to do more digging and understanding to attempt it. Any help would be appreciated! Thanks!

**Comment by joey711** [comment]
I think you should reflect more carefully on your statement:

> One method discussed in the paper is to completely remove the ASVs found within the negative control. Doing so however would remove some of the most abundant ASVs in many of my samples...

Often the goal of your negative controls is to detect signals in your data that are contamination/background. This is no exception. If you're seeing ASVs in high abundance that also appear in your NC, it is a reasonable interpretation that these *might* be contamination. Simply "I saw them a lot in my samples" does not mean your process was free from contamination or that you do not need a good explanation for why these ASVs should remain in your natural-data...

As for positive controls, we are experimenting with Spike-Ins. I'm not sure how other forms of positive control would help much in your data interpretation. Their utility might be limited to "the protocol worked as expected when the samples were of known composition".

Hope that helps.
